### ISSUE TITLE
paddleslim官方文档版本配置与实际不符

### ISSUE THREAD

**Issue by llt-Nancy** [PaddlePaddle/PaddleSlim#1002]
官方文档是paddleslim=2.1.0与paddlex=2.1.0,但实际却有冲突
![image](https://user-images.githubusercontent.com/80373122/155956195-9e5fc803-e23f-4408-8c01-add3a96b2659.png)

**Comment by LLiuzui** [comment]
请问这个问题解决了吗，我安装2.1.1也有这个问题
