### ISSUE TITLE
默认batch_size是16不太好吧

### ISSUE THREAD

**Issue by vicwer** [PaddlePaddle/PaddleSlim#1003]
https://github.com/PaddlePaddle/PaddleSlim/blob/66168f6b957146fe46fd6d45dff7f4d1985e59ab/paddleslim/quant/quanter.py#L315

默认batch_size的话，很多模型转换过来调用`slim.quant.quant_post_static()`会报错`InvalidArgumentError: The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape`，感觉默认是1比较好。

**Comment by yghstill** [comment]
@vicwer 感谢反馈，这个我们修正下。
