### ISSUE TITLE
关于使用slim做paddle模型的conv+bn合并

### ISSUE THREAD

**Issue by vicwer** [PaddlePaddle/PaddleSlim#1007]
如果对于一个paddle模型，只想做conv+BN合并，不想做量化，该调用什么接口呢，现在看合并是在quant_opst_static调用的

**Comment by yghstill** [comment]
@vicwer 目前没有发布此功能，可以参考下这个实现：https://github.com/PaddlePaddle/PaddleSlim/pull/692/commits/b93bce9174468209ee9c65f729910c9575d0756e
