### ISSUE TITLE
请教一下 nas 有关模型 fc层输出的问题

### ISSUE THREAD

**Issue by zhiyuan1i** [PaddlePaddle/PaddleSlim#1016]
您好， 我想使用paddleslim的nas功能为自己的研究搜索一个轻量级的深度哈希网络，希望模型可以输出指定长度的哈希编码，即需要用到模型最后一个fc层的输出，并且我想通过程序设置指定输出向量的长度。

我认真研读了 https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/nas/sanas_darts_space.py 的代码，包括https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/nas 还有 https://paddleslim.readthedocs.io/zh_CN/latest/api_cn/static/nas/search_space.html?highlight=output_size#id3 ，https://github.com/PaddlePaddle/PaddleSlim/blob/4d75cb9cecf5a02e789576b0c02ce7376615dafd/docs/zh_cn/api_cn/static/nas/nas_api.rst文档。  output_size 可以用来设置输出的feature map的大小。

这是我找到的最接近的config选项，请问倘若我要生成128位的二进制编码，我是需要将 传入SANAS的configs可以指定为[(’MobileNetV2BlockSpace’, {’input_size’: 224, ‘output_size’: 128, ‘block_num’: 10})]吗？ 

预期结果： 此时网络运算结果为 128位的二进制编码 即一个128位的二进制分布，每一位为一个浮点数。 
请问我理解的对吗？

![截屏2022-03-14 20 28 24](https://user-images.githubusercontent.com/31544054/158172124-86135183-fabb-45b1-9b67-c69089e01d6d.png)

**Comment by zhiyuan1i** [comment]
```python
output = static.nn.fc(x=output, size=args.class_dim)
```
样例代码中还有在这里设置fc层的，与上面output_size 造成了迷惑，可以麻烦帮忙解答吗。感谢！

**Comment by RachelXu7** [comment]
output_size是输出feature map的大小，跟fc无关。如果你想生成128位的二进制编码，可以将fc层输出设置为128。可以联想一下classification任务，args.class_dim=128即可。

**Comment by zhiyuan1i** [comment]
谢谢！
