### ISSUE TITLE
在线量化得到模型如何转换为paddle-trt支持的模型呢

### ISSUE THREAD

**Issue by marsbzp** [PaddlePaddle/PaddleSlim#1027]
![image](https://user-images.githubusercontent.com/20138766/160821128-9f178c8c-3633-4b01-9d35-afd911b4b849.png)
直接使用这个模型进行推理结果异常

**Comment by yghstill** [comment]
@marsbzp 执行的是trt_int8模式吗？量化后的精度eval正常吗？

**Comment by marsbzp** [comment]
> @marsbzp 执行的是trt_int8模式吗？量化后的精度eval正常吗？
这个模型在推理的时候conv和bn会进行合并
