### ISSUE TITLE
如何对已训练好的静态模型进行剪枝？

### ISSUE THREAD

**Issue by dhbhf** [PaddlePaddle/PaddleSlim#1030]
我现在有一个已经训练好的静态模型，其是使用PaddlePaddle2.1.2训练的，现在想对这个训练好的模型进行剪裁，看相关文档都是从模型训练开始的，但我模型已经训练好了。所以目前不知道使用什么API将模型导入进去以及是否还需要设置model.prepare参数？请帮忙解答下，如何操作可以将已经训练导出的静态模型进行剪枝

**Comment by smallhaozigithub** [comment]
同问。
