### ISSUE TITLE
Yolofastest模型怎么利用paddleslim做模型压缩呢？

### ISSUE THREAD

**Issue by Dora1483** [PaddlePaddle/PaddleSlim#1050]
我是一个新手。 我想请教一下前辈们， 必须是基于paddle框架训练的模型才能用paddleslim吗？
  
像yolofastest的模型能利用paddleslim做模型压缩吗？

如果可以的话， 应该怎么做呢？

**Comment by yghstill** [comment]
统一在 #1052 里交流~
