### ISSUE TITLE
paddle slim快速开始 » 静态图 » 量化训练教程报错

### ISSUE THREAD

**Issue by fash120** [PaddlePaddle/PaddleSlim#1059]
跑 paddle slim官方给出的例程的时候，在保存量化后的模型的时候报错，错误如下
![QQ截图20220420150421](https://user-images.githubusercontent.com/97490092/164170232-f66e15d5-d758-4474-a7d9-aec4177472d6.jpg)
：

**Comment by yghstill** [comment]
@fash120 感谢反馈，我们看下

**Comment by yghstill** [comment]
@fash120 你使用的PaddleSlim版本是多少，你的报错问题无法复现，请参考最新教程再试下呢？https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/quant_aware_tutorial.md
