### ISSUE TITLE
模型导出以及Paddlelite部署

### ISSUE THREAD

**Issue by WeizXy** [PaddlePaddle/PaddleSlim#1075]
### PaddleSlim开发者你好，请问如何将经过PRUNE-QAT的模型进行保存并通过Paddlelite进行部署？
因为PRUNE是动态图转为静态图(dygraphy to static)再进行保存，而QAT是直接从动态图(dygraphy)保存，因此请问经过PRUNE-QAT后的模型如何保存以及通过Paddlelite部署？
五一快乐~。~   
谢谢！

**Comment by yghstill** [comment]
@WeizXy 首先需要模型动转静，然后可以使用paddle_lite_opt工具将模型转换成nb格式即可使用paddlelite部署。

**Comment by WeizXy** [comment]
@yghstill 你好！
经过尝试，将经过PRUNE-QAT的模型转为静态后使用paddle_lite_opt工具转换成nb格式时会报错：
`This model is not supported, because 1 ops are not supported on 'arm',These unsupported ops are: 'moving_average_abs_max_scale'.`
对比发现，使用QAT的save_quantized_model函数导出模型后没有上面这个op，可以正常生成nb文件，但是动转静后这个op将会保留导致无法生成nb文件。
**问题在于：**
经过PRUNE-QAT的模型需要转为静态保存通道数，而转为静态后又无法使用QAT的save_quantized_model函数去掉上述op@.@。。。
请问这种问题如何解决?谢谢！

**Comment by yghstill** [comment]
@WeizXy QAT动转静就使用save_quantized_model接口即可直接在paddle Lite上部署，不能使用paddle.jit.save。

**Comment by WeizXy** [comment]
@yghstill 原来如此，是我想多了hahh。谢谢！

**Comment by Jiashuhao518** [comment]
> @yghstill 原来如此，是我想多了hahh。谢谢！

你好，我也是prune后QAT 但是无法导出模型 报错是str object has no attribute save quantized model
请问是什么样的原因呢
