### ISSUE TITLE
analysis中的model_size计算

### ISSUE THREAD

**Issue by zhizunbao-y** [PaddlePaddle/PaddleSlim#108]
该计算中对于模型中bn层，除了scale和offset外，将mean和variance也统计为了参数量，后两者没有经过优化算法优化过，不是学习到的 ，是否应该算作参数量？

**Comment by wanghaoshuang** [comment]
直观上理解，在保存模型用作线上预测时，计算`model_size`需要包含所有需要保存在文件系统的变量。

mean和variance其实也是学习到的，只不过学习的方法是简单的统计。
