### ISSUE TITLE
用途是在Paddle-Inference上使用，是否可以使用在线量化训练来压缩模型大小？

### ISSUE THREAD

**Issue by sun222** [PaddlePaddle/PaddleSlim#1091]
如同很多教程所说，在线量化训练导出的模型不会降低模型大小，使用paddle-lite opt后才能降低模型大小。
我的用途是在Paddle-Inference上使用的压缩模型，是不是不能使用在线量化策略来完成？

**Comment by yghstill** [comment]
@sun222 目前默认量化后的Inference model存储的weight是float32类型的int8数值，所以存储空间不变，Paddle Inference上模型大小不变，但是可以验证下量化后模型加速效果。

**Comment by sun222** [comment]
感谢解答
