### ISSUE TITLE
paddleslim在线量化demo train.py中引用的from utility import add_arguments, print_arguments报错

### ISSUE THREAD

**Issue by LLiuzui** [PaddlePaddle/PaddleSlim#1094]
Traceback (most recent call last):
  File "train_ssd.py", line 24, in <module>
    from utility import add_arguments, print_arguments
ImportError: cannot import name 'add_arguments' from 'utility' (unknown location)

请问这个utility包是什么，我直接pip安装了还是报错，且site-packages中只出现了utility-1.0.dist-info文件夹

**Comment by yghstill** [comment]
你是将demo拿出了吗？请把这个文件拷贝至你的目录下：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/utility.py

**Comment by LLiuzui** [comment]
好的，谢谢谢谢
