### ISSUE TITLE
paddleslim目前最新的版本是2.2.2吗

### ISSUE THREAD

**Issue by susan-812** [PaddlePaddle/PaddleSlim#1118]
在说明文档里面看到有自动压缩的示例，但是要求的paddleslim版本是2.3.0，产品动态里面写的5.23发布2.3.0，想确认一下是不是这样的

**Comment by yghstill** [comment]
@susan-812 使用PaddleSlim develop版本即可，2.3版本即将发布。
安装方式：
```shell
git clone https://github.com/PaddlePaddle/PaddleSlim.git
cd PaddleSlim
python setup.py install
```

**Comment by 983913761** [comment]
安装develop版本报错，提示找不到paddleslim-opt-tool组件怎么处理

**Comment by YiZhi-W813** [comment]
> @susan-812 使用PaddleSlim develop版本即可，2.3版本即将发布。 安装方式：
> 
> ```shell
> git clone https://github.com/PaddlePaddle/PaddleSlim.git
> cd PaddleSlim
> python setup.py install
> ```

你好，请问安装develop版本报错，提示找不到paddleslim-opt-tool组件怎么处理
