### ISSUE TITLE
自动压缩可用于压缩经过微调的ERNIE 1.0模型吗？

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleSlim#1126]
[https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/auto_compression/nlp#%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E5%A4%84%E7%90%86%E6%A8%A1%E5%9E%8B%E8%87%AA%E5%8A%A8%E5%8E%8B%E7%BC%A9%E7%A4%BA%E4%BE%8B](自然语言处理模型自动压缩示例)里面的例子是PP-MiniLM模型，可以套用在ERNIE 1.0模型上吗？

**Comment by ceci3** [comment]
可以的，只要是部署模型都可以~
