### ISSUE TITLE
自动压缩后，用paddlelite 导出报错

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/PaddleSlim#1132]
测试自动压缩[demo](https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/auto_compression)后，用paddlelite导出后报错

[F  5/21 18: 1: 6.617 ...optimizer/mir/static_kernel_pick_pass.cc:71 Apply] Check failed: !instruct.kernels().empty(): No kernels found for fake_quantize_abs_max

**Comment by yghstill** [comment]
@renmada 请问是哪个模型？我们排查下问题~

**Comment by renmada** [comment]
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/auto_compression
就readme的demo
