### ISSUE TITLE
cannot import name 'AbsmaxQuantizer' from 'paddle.fluid.contrib.slim.quantization' 

### ISSUE THREAD

**Issue by ljl86092297** [PaddlePaddle/PaddleSlim#1133]
![image](https://user-images.githubusercontent.com/59467994/169727333-27411560-e3e3-4307-b78d-8de5e11dd9dd.png)

只是使用了这个命令， paddlepaddle =2.0 paddleslim=2.2.2 
![image](https://user-images.githubusercontent.com/59467994/169727412-6f621205-c6ee-47fc-bbae-bbc7a7c42b17.png)
请问怎么解决

**Comment by ceci3** [comment]
可以安装paddlepaddle2.3试下
