### ISSUE TITLE
tinypose and lite hrne QAT 训练失败！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleSlim#1135]
Hi，
1 参考https://github.com/PaddlePaddle/Paddle/issues/42341 这个picodet的在线训练量化，完全搭建不出来一套tinypose或者litehrnet的qat在线训练版本啊，什么时候可以发布一套类似picodet的 tinypose的正式在线量化版本，多谢！
可以看到下面例子完全不能作为tinypos或者litehrnet的参考，必须paddle自己来做，这样失去了相当大的paddleslim这个框架研发的初衷
![image](https://user-images.githubusercontent.com/8407513/169745437-ba1f2c11-b3c2-49c4-937c-0f3af74649fc.png)

2 举个例子，pretrain_weights: https://paddledet.bj.bcebos.com/models/picodet_s_416_coco_lcnet.pdparams 
这个对于litehrnet 我的pretrain_weights 从哪里拿呢？不用也行？

![image](https://user-images.githubusercontent.com/8407513/169747365-57c0aa29-6cba-477b-8a49-3c346d3647a2.png)

3  #####data
TrainDataset:
  !KeypointTopDownCocoDataset
    image_dir: ""
    anno_path: aic_coco_train_cocoformat.json
    dataset_dir: dataset

这里的 dataset 数据集是哪个，具体子目录应该是啥样？aic_coco_train_cocoformat.json这个从哪里下载啊？
BR

**Comment by 2050airobert** [comment]
hello，anyone here？

**Comment by yghstill** [comment]
在 https://github.com/PaddlePaddle/PaddleDetection/issues/6037 统一回复
