### ISSUE TITLE
可不可以出一个fairmot里的模型的自动化压缩demo

### ISSUE THREAD

**Issue by susan-812** [PaddlePaddle/PaddleSlim#1144]
跟着目标检测的demo试了一下fairmot里的fairmot_hrnetv2_w18_dlafpn_30e_576x320模型的自动化压缩，没弄出来，官方大大能不能出一个呀

**Comment by ceci3** [comment]
是遇到什么问题了嘛？可以把您的代码提出来我们一起看下~
