### ISSUE TITLE
可不可以出一个动态图的bert量化例子

### ISSUE THREAD

**Issue by kismit** [PaddlePaddle/PaddleSlim#1148]

**Comment by yghstill** [comment]
@kismit 目前没有动态图量化训练的demo。可以模型动转静后直接量化训练和离线量化：
自动化压缩（量化训练）：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/auto_compression/nlp
离线量化：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/model_compression/pp-minilm/quantization

**Comment by kismit** [comment]
pp-minilm这里面提供的是离线量化的方式吧？nlp动态图没有qat的方式？
