### ISSUE TITLE
模型量化以后 精度直接没了

### ISSUE THREAD

**Issue by ljl86092297** [PaddlePaddle/PaddleSlim#1152]
谷歌关键点模型经过离线量化后
![image](https://user-images.githubusercontent.com/59467994/172144562-400c2852-3c6e-414a-9f77-ac0ed7c77665.png)
经过上图函数量化以后精度直接消失了
![image](https://user-images.githubusercontent.com/59467994/172144710-99fd231d-78a8-4f59-b80a-2951615aa07c.png)
上图是未量化前的模型效果
![image](https://user-images.githubusercontent.com/59467994/172144789-05c252d1-8558-44b3-939d-053efdcfe2bd.png)
这是量化后的效果，-1代表骨骼点未检测到

**Comment by wanghaoshuang** [comment]
这里有一个tinypose的PR：https://github.com/PaddlePaddle/PaddleSlim/pull/1179
还在review中。
之前我们对tinypose做全量化，精度损失较大，但可视化效果还可以接受。
