### ISSUE TITLE
paddle slim可以对leakyRelu做量化处理吗？

### ISSUE THREAD

**Issue by StrugglingForBetter** [PaddlePaddle/PaddleSlim#1154]
请问下paddle slim可以对leakyRelu做量化处理吗？我看有些框架没法对leakyRelu量化，导致即使量化了，还是相当于跑float一样，不知道paddle在这方面做得怎么样？如果好的话，可以考虑入坑

**Comment by ceci3** [comment]
这个应该是得看具体的硬件推理实现，slim产出的量化模型是支持对leakyRelu量化的
