### ISSUE TITLE
PaddleSlim 可以对BasicVSR++ 压缩吗？

### ISSUE THREAD

**Issue by eepeter** [PaddlePaddle/PaddleSlim#1156]
请问一下PaddleSlim 可以对BasicVSR++ 压缩吗？有相关经验可以分享吗？

**Comment by yghstill** [comment]
@eepeter BasicVSR++的模型暂时没有现成的压缩方案，
动态图可以根据 demo：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/dygraph
静态图：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant 、https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/prune 等案例
