### ISSUE TITLE
paddleslim运行报错没有AdaptorBase

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/PaddleSlim#1171]
求助，运行paddleslim提供的蒸馏训练时出现

错误，paddlepaddle-gpu版本2.2.1，paddleslim版本2.2.0
![image](https://user-images.githubusercontent.com/101849755/173539158-dcbf9357-a3f2-4574-8dbc-50b550f24bd1.png)

**Comment by wanghaoshuang** [comment]
PaddleSlim动态图的蒸馏是一个非正式的功能，不建议直接使用。
可以参考这里对推理模型直接蒸馏压缩：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/auto_compression/semantic_segmentation
