### ISSUE TITLE
How quant is called!

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleSlim#1172]

**Comment by wanghaoshuang** [comment]
这里是静态图量化教程：https://paddleslim.readthedocs.io/zh_CN/latest/tutorials/quant/static/index.html
这里是动态图量化教程：https://paddleslim.readthedocs.io/zh_CN/latest/tutorials/quant/dygraph/index.html

**Comment by 2050airobert** [comment]
so cool tks
