### ISSUE TITLE
PicoDet 量化训练模型发布问题！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleSlim#1177]
hi，
    1 请问下，picoDet 目前的量化训练精度调优ok了吗？ 下周是否有发布计划，多谢~
    2 关于量化压缩，以下两个链接 有啥区别，还是完全可以合并为一个？
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/auto_compression/detection

BR

**Comment by 2050airobert** [comment]
hello，anyone here？

**Comment by wanghaoshuang** [comment]
很抱歉，这么久才回复您。

>picoDet 目前的量化训练精度调优ok了吗？

暂时效果还不符合预期

>关于量化压缩，以下两个链接 有啥区别，还是完全可以合并为一个？

https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim
这个链接是用有监督数据（带label的数据），使用单个压缩策略。

https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/auto_compression/detection
这个链接是用无监督数据（无label），借助蒸馏策略，直接对推理模型（无训练逻辑）进行压缩。

目前发现，使用无监督数据，在图像目标检测任务上的效果很难达到预期。我们正在尝试解决该问题。

多谢您的关注。
