### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by yeliang2258** [PaddlePaddle/PaddleSlim#118]
安装不成功，使用pip安装成功后，出现以下问题：
![image](https://user-images.githubusercontent.com/30516196/74702482-20848c00-5245-11ea-8502-e1f27151ad08.png)
使用源码安装，出现以下问题：
![image](https://user-images.githubusercontent.com/30516196/74702526-3d20c400-5245-11ea-9bb5-07bd22648647.png)
另外，给的demo中，尝试运行了多个，结果都无法正常运行，主要是：
sensitive：无法运行，merge_sensitive()报错；
auto_prune：无法运行，报错信息如下
![image](https://user-images.githubusercontent.com/30516196/74734600-d70a6000-5289-11ea-9c11-6007250a124a.png)
sensitive_prune：无法正常运行完。报错信息如下
![image](https://user-images.githubusercontent.com/30516196/74734733-1d5fbf00-528a-11ea-9c69-0e7a73b52a69.png)
几乎给的demo都无法正常运行

**Comment by wanghaoshuang** [comment]
您好，PaddleSlim还没有正式发布，pip源上的安装包是比较老的版本。
用源码安装依赖Paddle1.7, Paddle1.7安装包会在近几天发布，之后我们才会正式发布PaddleSlim.

**Comment by wanghaoshuang** [comment]
今天我们会拉个分支，以便用户在Paddle1.6环境下也能用PaddleSlim. 搞定后再回复您。多谢支持理解。

**Comment by Cristhine** [comment]
> 今天我们会拉个分支，以便用户在Paddle1.6环境下也能用PaddleSlim. 搞定后再回复您。多谢支持理解。

我在paddle1.6使用遇到同样问题 麻烦搞定也回复我一下

**Comment by wanghaoshuang** [comment]
您好，我们[revert](https://github.com/PaddlePaddle/PaddleSlim/pull/121)了依赖paddle1.7分支的代码(一些量化功能)，新建了个[release/0.1.0](https://github.com/PaddlePaddle/PaddleSlim/tree/release/0.1.0)分支，请clone该分支，并重新从源码进行安装。
@yeliang2258  @Cristhine

**Comment by yeliang2258** [comment]
> 今天我们会拉个分支，以便用户在Paddle1.6环境下也能用PaddleSlim. 搞定后再回复您。多谢支持理解。

谢谢回复！期待哦

**Comment by Cristhine** [comment]
> 您好，我们[revert](https://github.com/PaddlePaddle/PaddleSlim/pull/121)了依赖paddle1.7分支的代码(一些量化功能)，新建了个[release/0.1.0](https://github.com/PaddlePaddle/PaddleSlim/tree/release/0.1.0)分支，请clone该分支，并重新从源码进行安装。
> @yeliang2258 @Cristhine

按照relase源码安装提示安装成功 依然报错 >>> import paddleslim
>>> paddleslim.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'paddleslim' has no attribute '__version__'
>>> from paddleslim.quant import quant_aware, quant_post, convert
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'quant_post' from 'paddleslim.quant' (/home/vis/duyuting/anaconda3_1.6/lib/python3.7/site-packages/paddleslim-1.0.0-py3.7.egg/paddleslim/quant/__init__.py)
请问原因是？

**Comment by wanghaoshuang** [comment]
@Cristhine  请问您确定更新代码到release/0.1.0分支了么？
我这边并没有文件 paddleslim/quant/init.py， 而且在paddleslim/quant/__init__.py中也没有你log中的提示。

![image](https://user-images.githubusercontent.com/7534971/74828998-0a60f380-534b-11ea-80ae-ba7e06a5e770.png)

release/0.1.0分支下是没有quant_post方法的，用不了离线量化。

**Comment by Cristhine** [comment]
> @Cristhine 请问您确定更新代码到release/0.1.0分支了么？
> 我这边并没有文件 paddleslim/quant/init.py， 而且在paddleslim/quant/**init**.py中也没有你log中的提示。
> 
> ![image](https://user-images.githubusercontent.com/7534971/74828998-0a60f380-534b-11ea-80ae-ba7e06a5e770.png)
> 
> release/0.1.0分支下是没有quant_post方法的，用不了离线量化。

好的 那我等paddle1.7吧 感谢回复
