### ISSUE TITLE
PaddleSlim量化训练

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/PaddleSlim#1195]
您好，我使用PaddleSlim对PaddleSeg的模型进行量化训练
![image](https://user-images.githubusercontent.com/101849755/175762682-fad57ff1-48e5-4555-80ab-a5a1f040c699.png)
这是我的量化模型，我使用测试脚本测试效果很好，请问一下，我怎样可以输出量化之后模型的参数量Params和量化模型进行一次模型推理所需要的计算量Flops呢?

**Comment by wanghaoshuang** [comment]
## 计算FLOPs的方法
第一步：使用load_inference_model加载推理模型为program, 参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/load_inference_model_cn.html#load-inference-model

第二步：使用paddle.flops接口计算FLOPs: https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/flops_cn.html#flops

## 关于量化模型的说明
1. PaddleSlim产出的量化模型文件，还是以float32的数值类型存储的权重，所以模型大小不会改遍。在用Paddle-Lite和Paddle Inference推理时，会按Int8进行计算。
2. 相比Float32模型，Int8量化模型的参数数量不会减少，只是数值类型的变化
3. FLOPs不能表示量化模型的计算量，理论上量化模型的计算量和Float32模型是一样的，只是计算精度不一样
4. Slim保存的量化模型中，会插入一些量化、反量化OP，这些OP反而会使量化模型的FLOPs变大；。在部署推理时，这些量化、反量化OP会被删掉
