### ISSUE TITLE
Missing Paddle slim tinypose 量化训练 quant8！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleSlim#1197]
Hi，
请问下，
paddle slim tinypose 量化训练版本何时能够release啊？
或者已经在主干了吗？多谢
BR

**Comment by wanghaoshuang** [comment]
@RachelXu7 你之前实现的tinypose 量化训练是不是可以先提交一版？

**Comment by 2050airobert** [comment]
@RachelXu7 最新的调优效果有更新吗？ 这两天能否先提交一版目前最优效果版本呢？

**Comment by 2050airobert** [comment]
hello，anyone could help？
