### ISSUE TITLE
paddleslim=2.2.2无法兼容paddlepaddle=2.3

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/PaddleSlim#1209]
以下为 @levinzhangyd 提出的问题，辛苦 @yghstill 帮忙看下？

https://github.com/PaddlePaddle/PaddleSlim/pull/338#issuecomment-1169773627
---------------------------------------------------
最新的2.2版本的paddleslim，写代码都能自动关联到函数，结果运行找不到，这是有什么机关吗？
Traceback (most recent call last): 
  File "E:\pythonProject\testLaneDetect\pytotch_2_pp_module.py", line 94, in <module> 
    quant.quant_post_dynamic(
AttributeError: module 'paddleslim.quant' has no attribute 'quant_post_dynamic'

调用代码
from paddleslim import quant
from paddleslim.quant import quant_post_dynamic

# 动态量化
quant_post_dynamic(

尝试1：重装。Not work
尝试2：重装，并且换到2.0版本.Not work
尝试3：部分帖子说quant_post_dynamic换成quant_post_only_weight，还是不行

环境描述：
paddle=2.3
python=3.9
paddlelite=2.10rc
paddleslim=2.2.2

**Comment by levinzhangyd** [comment]
感谢回复，把paddle从最新的2.3降低到2.2就好了，可以正常用了。应该又是兼容的问题，非常感谢你们的及时关注



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月29日 22:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | [PaddlePaddle/PaddleSlim] paddleslim=2.2.2无法兼容paddlepaddle=2.3 (Issue #1209) |

以下为 @levinzhangyd 提出的问题，辛苦 @yghstill 帮忙看下？
#338 (comment)

最新的2.2版本的paddleslim，写代码都能自动关联到函数，结果运行找不到，这是有什么机关吗？
Traceback (most recent call last):
File "E:\pythonProject\testLaneDetect\pytotch_2_pp_module.py", line 94, in
quant.quant_post_dynamic(
AttributeError: module 'paddleslim.quant' has no attribute 'quant_post_dynamic'

调用代码
from paddleslim import quant
from paddleslim.quant import quant_post_dynamic

动态量化

quant_post_dynamic(

尝试1：重装。Not work
尝试2：重装，并且换到2.0版本.Not work
尝试3：部分帖子说quant_post_dynamic换成quant_post_only_weight，还是不行

环境描述：
paddle=2.3
python=3.9
paddlelite=2.10rc
paddleslim=2.2.2

**Comment by wanghaoshuang** [comment]
感谢反馈，我们下周会发布PaddleSlim2.3.0版本, 与PaddlePaddle2.3.0对应。
PaddleSlim2.3.0会发布自动压缩功能：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/auto_compression

当前持续测试优化中，感谢并期待您的继续关注。
