### ISSUE TITLE
ernie+crf模型自动压缩问题

### ISSUE THREAD

**Issue by Macxy2018** [PaddlePaddle/PaddleSlim#1215]
环境:AIStudio GPU
模型结构：使用PaddleNLP/examples/information_extraction/waybill_ie模型，模型结构是ernie+crf。
当前使用AutoCompression。
问题：目前模型为静态图，最后一层为crf层，模型预测时走维特比算法，无法输入标签，无法计算loss，请问这个需要怎么处理呢？

**Comment by ceci3** [comment]
AutoCompression中的量化训练为量化训练+蒸馏，不用传入标签，可以参考 https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/detection/configs/ppyoloe_l_qat_dis.yaml 这个配置文件中的量化配置，或者使用离线量化超参搜索的功能，也不需要配置标签信息，只需要传入  config={'Quantization': {}, "HyperParameterOptimization": {}}, 即可
