### ISSUE TITLE
I need paddleslim-opt-tools for arm64

### ISSUE THREAD

**Issue by wayneck** [PaddlePaddle/PaddleSlim#1255]
I work on arm64  centos， use paddle suit develop. I install or build PaddleSlim  but cannt find a paddleslim-opt-tools for arm64?
Where or how to do it?

**Comment by ceci3** [comment]
最新的paddleslim不需要依赖 paddleslim-opt-tools 工具了，可以重新安装最新的试下，没有paddleslim-opt-tools这个工具会影响硬件延时表的使用，和自动压缩工具里设置了 deploy_hardware 参数之后的自动化策略选择，可以通过设置压缩策略来直接进行压缩~

**Comment by wayneck** [comment]
ok
