### ISSUE TITLE
FirstRunCrashedException,这个什么啥原因，已经如何破解啊

### ISSUE THREAD

**Issue by tianv** [PaddlePaddle/PaddleSlim#1263]
FirstRunCrashedException: First run crashed, abort. Please check your setup -- we assume that your default configuration does not crashes. (To deactivate this exception, use the SMAC scenario option 'abort_on_first_run_crash'). Additional run info: {}

**Comment by ceci3** [comment]
你好，可以截图多点报错信息嘛？这些看不出来具体的报错原因是什么
