### ISSUE TITLE
Exception: 'feed_targets' does not have x variable

### ISSUE THREAD

**Issue by Dora1483** [PaddlePaddle/PaddleSlim#1269]
在运行demo_yolofastest.py时， 将eval参数中的False改为True, 报上述错误。

**Comment by wanghaoshuang** [comment]
@Dora1483 请问“demo_yolofastest.py”所在路径是？

**Comment by Dora1483** [comment]
> @Dora1483 请问“demo_yolofastest.py”所在路径是？

https://github.com/yghstill/PaddleSlim/tree/add_yolofastest_auto_compress

**Comment by Dora1483** [comment]
> @Dora1483 请问“demo_yolofastest.py”所在路径是？
@wanghaoshuang  https://github.com/yghstill/PaddleSlim/tree/add_yolofastest_auto_compress

**Comment by ceci3** [comment]
> > @Dora1483 请问“demo_yolofastest.py”所在路径是？
> > @wanghaoshuang  https://github.com/yghstill/PaddleSlim/tree/add_yolofastest_auto_compress

可以用netron可视化看下模型的输入是不是叫 `x` ，不是的话需要修改下这里的key：https://github.com/yghstill/PaddleSlim/blob/add_yolofastest_auto_compress/demo/auto-compression/demo_yolofastest.py#L38
