### ISSUE TITLE
Do not reply, just some pics

### ISSUE THREAD

**Issue by D-DanielYang** [PaddlePaddle/PaddleSlim#1282]
![image](https://user-images.githubusercontent.com/23690325/178102488-9f09e991-bfd6-4827-8641-849d9c3fa83c.png)

**Comment by D-DanielYang** [comment]
![image](https://user-images.githubusercontent.com/23690325/178102623-6de25af1-eec8-4825-bb15-4dad5bee7c9c.png)

**Comment by leiqing1** [comment]
![github-slim全自动压缩](https://user-images.githubusercontent.com/54695910/178181077-57a3a631-f495-4821-878d-ef5e74981718.jpg)
