### ISSUE TITLE
 经过静态量化后性能却由150ms变为250m

### ISSUE THREAD

**Issue by yangguangda-hub** [PaddlePaddle/PaddleSlim#1292]
使用Android nnapi方式，硬件为mtk设备。经过将自己的yolov3模型，经过x2paddle转换后，在经过静态离线量化，最后经过动态量化后，性能对比不经过静态量化有150ms变为了250ms。具体见文件：
[apu_question.zip](https://github.com/PaddlePaddle/PaddleSlim/files/9098525/apu_question.zip)
![2022-07-13 10-45-21 的屏幕截图](https://user-images.githubusercontent.com/82625719/178639877-9a563e7e-45c7-495e-acd2-4b2d0626c91c.png)

**Comment by wanghaoshuang** [comment]
收到，我们安排相关同学看下这个问题。

**Comment by yingshengBD** [comment]
请提供 paddlepaddle和paddleslim的版本。
如果是较早版本，离线量化并不是全部算子都会量化，导致数据类型和计算IP来回切换从而性能下降

**Comment by yangguangda-hub** [comment]
paddlepaddle       2.2.0
paddleslim         2.0.0

**Comment by SunYF-0729** [comment]
@wanghaoshuang @yingshengBD 你好，我这里有个问题跟他差不多，可以麻烦帮我解答下吗，谢谢！！！
https://github.com/PaddlePaddle/PaddleSlim/issues/1305#issue-1308604097
