### ISSUE TITLE
qat failed！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleSlim#1304]
TinyPose qat全量化版本bug！ #1288
问题和log描述非常详细，请帮忙检查下为啥 无法export出paddledet提供的模型呢？(具体在1288这个issue最开始的帖子里)
建议您仔细看下
[tinypose_128x96-lcl.zip](https://github.com/PaddlePaddle/PaddleSlim/files/9108898/tinypose_128x96-lcl.zip)
[tinypose_128x96-yml-lcl.zip](https://github.com/PaddlePaddle/PaddleSlim/files/9108922/tinypose_128x96-yml-lcl.zip)
这是两个包，你要的都在，对吗？
BR

**Comment by 2050airobert** [comment]
hello, anyone here, could anyone help me with this problem of  slim or ppdet?

**Comment by leiqing1** [comment]
两个压缩包都提供完整的模型结构，包括model.pdiparams和model.pdmodel。
