### ISSUE TITLE
paddleslim对ssd_mobilenet_v1进行剪裁出现的推理速度等相关问题

### ISSUE THREAD

**Issue by SunYF-0729** [PaddlePaddle/PaddleSlim#1305]
版本：
![image](https://user-images.githubusercontent.com/109390344/179612740-420eba0b-4375-4faf-b733-887f6d0455ea.png)
问题：
剪裁0.3%后，flops减少，在验证集上预测速度变快，但量化后部署到arm和intel fpga上推理速度反而变慢
剪裁前：
![R_WVA%XZC3NDRTVXQ4P9H D](https://user-images.githubusercontent.com/109390344/179614192-e3bd9e85-4bb6-40a7-b8b6-b07773c5b9ba.png)
![7YY8_C (KVDCBFS DWECHWG](https://user-images.githubusercontent.com/109390344/179614209-4426b589-f1e2-4c0c-bf40-95f792814977.png)
剪裁后：
![{A_HX5YEMZ{CW6X}_F7QTYJ](https://user-images.githubusercontent.com/109390344/179614241-f99a2bf9-6ad4-470f-9a7f-1c919908e6b6.png)
![5_6DQ}QV06@A@X)V1`({BGQ](https://user-images.githubusercontent.com/109390344/179614261-644a7b0b-1207-41df-8d13-e71c6eec8017.png)
以下是我的训练过程：
![image](https://user-images.githubusercontent.com/109390344/179612808-25b4e690-a3d0-4b1d-9ca0-becac42be2bf.png)
我参照量化的congfig的设置方式加了个prune的congfig，在train中加入slim_config_prune,config如下：
![image](https://user-images.githubusercontent.com/109390344/179613085-b03bda03-e408-469f-a21e-b8a86ea8f865.png)
这里训练的时候我其实设的全为0.3。这里的参数名称我不清楚该裁剪哪个，不让剪裁的系统会自己跳过，所以都写上去。
剪裁后导出的静态模型从23.4M变为14.7M，但是部署到板子上推理照片的速度从350ms变为了610ms，求大佬解答！！！

**Comment by yghstill** [comment]
@SunYF-0729 剪裁完部署到arm和intel fpga上速度变慢的问题我们找相关同学看下，你使用paddle Inference在GPU上部署预测速度怎么样？

**Comment by SunYF-0729** [comment]
> @SunYF-0729 剪裁完部署到arm和intel fpga上速度变慢的问题我们找相关同学看下，你使用paddle Inference在GPU上部署预测速度怎么样？

还没有在gpu上试过，我搜查文献，在硬件上推理变慢是因为对权重的非结构化剪裁会产生一定的编码问题，所以部署到硬件反而会让速度变慢，但是我看我的这个应该是直接对卷积核进行剪裁去除，应该没这个问题，所以很费解

**Comment by SunYF-0729** [comment]
> @SunYF-0729 剪裁完部署到arm和intel fpga上速度变慢的问题我们找相关同学看下，你使用paddle Inference在GPU上部署预测速度怎么样？

我这个网络结构的pruned-params也是根据prune_config的print_params来设置的，这个是我调用不了static/slim/sensitive/sensitive.py对我自己模型的config进行敏感度检测才采用的无奈之举。

**Comment by SunYF-0729** [comment]
> @SunYF-0729 剪裁完部署到arm和intel fpga上速度变慢的问题我们找相关同学看下，你使用paddle Inference在GPU上部署预测速度怎么样？

我这个网络结构的pruned-params也是根据prune_config的print_params来设置的，这个是我调用不了static/slim/sensitive/sensitive.py对我自己模型的结构进行print_params才采用的无奈之举。全设为0.3也是因为调用不了sensitive.py没办法进行敏感度分析。

**Comment by SunYF-0729** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/6453#issue-1306564809 @yghstill 前辈，还有这个问题我也很困扰，麻烦您找人看下，万分感谢您的回复，期待您指导！

**Comment by zzjjay** [comment]
麻烦提供下剪枝后的模型文件（*.pdmodel） @SunYF-0729

**Comment by SunYF-0729** [comment]
> 麻烦提供下剪枝后的模型文件（*.pdmodel） @SunYF-0729

这里怎么提供

**Comment by SunYF-0729** [comment]
> 麻烦提供下剪枝后的模型文件（*.pdmodel） @SunYF-0729

这里不支持传输文件，请您给个其他方式吧

**Comment by zzjjay** [comment]
直接将文件拽入输入框即可～

> > 麻烦提供下剪枝后的模型文件（*.pdmodel） @SunYF-0729
> 
> 这里怎么提供

**Comment by SunYF-0729** [comment]
> 直接将文件拽入输入框即可～
> 
> > > 麻烦提供下剪枝后的模型文件（*.pdmodel） @SunYF-0729
> > 
> > 
> > 这里怎么提供
![image](https://user-images.githubusercontent.com/109390344/179650582-942919c7-17e7-4d64-ba68-9986f3f994dd.png)

**Comment by zzjjay** [comment]
那发我邮箱吧，zhouzhaojing@baidu.com

**Comment by yu0802chao** [comment]
请问你们现在能做到多少ms，这个裁剪率已经很高了

**Comment by SunYF-0729** [comment]
> 请问你们现在能做到多少ms，这个裁剪率已经很高了

只有量化的能到350，裁剪加量化没做出来呢

**Comment by yu0802chao** [comment]
> > 请问你们现在能做到多少ms，这个裁剪率已经很高了
> 
> 只有量化的能到350，裁剪加量化没做出来呢

纯量化就能到300多，是模型导出时把卷积连续映射到加速器了吗？

**Comment by SunYF-0729** [comment]
没有，我只做了量化。其他的硬件部分我不清楚，你也在做这个模型的剪裁吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSlim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSlim] paddleslim对ssd_mobilenet_v1进行剪裁出现的推理速度等相关问题 (Issue #1305)





   
请问你们现在能做到多少ms，这个裁剪率已经很高了
  
只有量化的能到350，裁剪加量化没做出来呢
  
纯量化就能到300多，是模型导出时把卷积连续映射到加速器了吗？

**Comment by yu0802chao** [comment]
> 没有，我只做了量化。其他的硬件部分我不清楚，你也在做这个模型的剪裁吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleSlim" ***@***.***&gt;; 发送时间:&nbsp;2022年7月19日(星期二) 下午3:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleSlim] paddleslim对ssd_mobilenet_v1进行剪裁出现的推理速度等相关问题 (Issue #1305) 请问你们现在能做到多少ms，这个裁剪率已经很高了 只有量化的能到350，裁剪加量化没做出来呢 纯量化就能到300多，是模型导出时把卷积连续映射到加速器了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

是的，可能是你直接用静态图做的，如果方便的话可以看一下模型吗

**Comment by SunYF-0729** [comment]
> > 没有，我只做了量化。其他的硬件部分我不清楚，你也在做这个模型的剪裁吗
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "PaddlePaddle/PaddleSlim" _**@**_._**>; 发送时间: 2022年7月19日(星期二) 下午3:16 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [PaddlePaddle/PaddleSlim] paddleslim对ssd_mobilenet_v1进行剪裁出现的推理速度等相关问题 (Issue #1305) 请问你们现在能做到多少ms，这个裁剪率已经很高了 只有量化的能到350，裁剪加量化没做出来呢 纯量化就能到300多，是模型导出时把卷积连续映射到加速器了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 是的，可能是你直接用静态图做的，如果方便的话可以看一下模型吗

我用的动态图做的量化，边训练边模拟量化然后用paddlelite部署，因为静态图有一系列的问题我不清楚，也做不出来，就没做了，这里不能发模型，方便的话邮件交流吧

**Comment by yu0802chao** [comment]
好的，我的邮箱是65091929@qq.com

**Comment by wangplin** [comment]
只做量化能达到350ms吗，有用了dorefa吗？

**Comment by SunYF-0729** [comment]
> 只做量化能达到350ms吗，有用了dorefa吗？

没有用，我这个裁剪搞不定，兄弟能指导一下不

**Comment by wangplin** [comment]
加下微信吧，NSwpl255598

**Comment by personqianduixue** [comment]
@SunYF-0729 请问你这个模型的mAP怎么到77%的，你是用VOC训练的吗？我最高73.6%

**Comment by liopos** [comment]
@SunYF-0729 请问用动态图怎么裁剪这种检测模型呢，我使用L1NormFilterPruner的时候inputs加载总出错，大佬能指导指导吗？
