### ISSUE TITLE
动态qat量化后用netron查看模型的 pdparams参数含义不明晰

### ISSUE THREAD

**Issue by fpjnice** [PaddlePaddle/PaddleSlim#1314]

**Comment by yghstill** [comment]
@fpjnice 
1. netron可视化动转静导出后的pdmodel文件，才能查看网络拓扑图。
2. 这个scale就是量化尺度因子，根据量化计算公式来进行量化与反量化。这些可以交给预测库处理，模型训练侧可以不用处理这些参数。

**Comment by fpjnice** [comment]
hh

**Comment by yghstill** [comment]
@fpjnice 可以，xxx.scale就是对应层的out scale属性
