### ISSUE TITLE
使用Inference模型恢复训练

### ISSUE THREAD

**Issue by moonlightian** [PaddlePaddle/PaddleSlim#1318]
在paddleslim中的recover_inference_program貌似提供了推理模型转训练模型的功能，但是没有找到具体的应用实例，可以给一个简单的demo演示一下该功能如何使用并进行训练吗？

**Comment by ceci3** [comment]
https://github.com/PaddlePaddle/PaddleSlim/blob/cfec7b341f290762a5d1bf4589ad88128ac9c72a/paddleslim/auto_compression/create_compressed_program.py#L217 
直接调用 recover_inference_program ，传入inference program就可以了
