### ISSUE TITLE
Please check the py_verion variable

### ISSUE THREAD

**Issue by colorjam** [PaddlePaddle/PaddleSlim#1323]
https://github.com/PaddlePaddle/PaddleSlim/blob/8b156124638caf851e728f49cf46afb9ebf7ed4e/paddleslim/analysis/latency_predictor.py#L98

**Comment by zzjjay** [comment]
Thanks! We have submitted pr(https://github.com/PaddlePaddle/PaddleSlim/pull/1324) to fix the issue
