### ISSUE TITLE
量化模型转TensorRT

### ISSUE THREAD

**Issue by xingyueye** [PaddlePaddle/PaddleSlim#1325]
请问如何把链接中yolov6的量化模型转成对应的TensorRT模型
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/pytorch_yolov6

**Comment by xingyueye** [comment]
我想用paddle2onnx先转onnx再转TRT，但是paddle2onnx无法识别量化算子：
```
NotImplementedError:
There's 2 ops are not supported yet
=========== fake_quantize_moving_average_abs_max ===========
=========== fake_channel_wise_dequantize_max_abs ===========
```

**Comment by yghstill** [comment]
@xingyueye 马上支持，文档和demo正在补充中，下周就可以使用了。

**Comment by yghstill** [comment]
@xingyueye Already supported in #1327.

**Comment by xingyueye** [comment]
👍非常感谢
“pip install paddle2onnx==1.0.0rc3”，不过我现在pip安装的时候还检索不到 1.0.0rc3 的版本。可以提供下 wheel包吗

**Comment by yghstill** [comment]
@xingyueye 更新下pip呢？python -m pip install --upgrade pip

**Comment by xingyueye** [comment]
更新了paddle2onnx之后还是报算子支持问题，如下
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/40205112/183576413-df863617-1d33-4b2d-b17f-637df8e562e6.png">
是不是链接中的 `model.pdmodel`和`model.pdiparams` 也需要更新一下？

**Comment by yghstill** [comment]
@xingyueye 嗯嗯，需要更新，链接中的模型权重我更新下

**Comment by yghstill** [comment]
@xingyueye 已更新文档。

**Comment by xingyueye** [comment]
感谢👍模型已经跑通了
