### ISSUE TITLE
是否支出训练自己的数据集

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleSlim#133]
paddleslim是否支持训练自己的数据集，yolov3_mobilenet_v1_voc_prune下载的一堆权重文件怎么使用？是否有教程或者视频等

**Comment by wanghaoshuang** [comment]
PaddleSlim支持训练自己的数据，如果你计划对PaddleDetection检测库里的模型压缩的话，请参考PaddleDetection的自定义数据教程：https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/advanced_tutorials/READER.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90

**Comment by wanghaoshuang** [comment]
>yolov3_mobilenet_v1_voc_prune下载的一堆权重文件怎么使用

你应该说的是这里设置的预训练模型吧：https://github.com/PaddlePaddle/PaddleDetection/blob/master/configs/yolov3_mobilenet_v1_voc.yml#L9
这个权重是检测模型的backbone网络的预训练模型，用于加速训练。

**Comment by jaffe-fly** [comment]
数据集整理好之后，怎么开始训练自己的数据呢？总得把权重文件导入模型吧怎么操作  没找到教程

**Comment by wanghaoshuang** [comment]
@jaffe-fly 

>数据集整理好之后，怎么开始训练自己的数据呢？

数据整理好后，请参考这个教程配置自定义的数据源：
https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/advanced_tutorials/READER.md#%E8%AE%AD%E7%BB%83%E9%85%8D%E7%BD%AE

>总得把权重文件导入模型吧怎么操作 没找到教程

你这里说的权重文件是指？

**Comment by wanghaoshuang** [comment]
参考这个配置文件配置数据集：https://github.com/PaddlePaddle/PaddleDetection/blob/master/configs/yolov3_mobilenet_v1_voc.yml#L65-L71

**Comment by jaffe-fly** [comment]
> @jaffe-fly
> 
> > 数据集整理好之后，怎么开始训练自己的数据呢？
> 
> 数据整理好后，请参考这个教程配置自定义的数据源：
> https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/advanced_tutorials/READER.md#%E8%AE%AD%E7%BB%83%E9%85%8D%E7%BD%AE
> 
> > 总得把权重文件导入模型吧怎么操作 没找到教程
> 
> 你这里说的权重文件是指？

paddleslim的模型库下载的yolov3_mobilenet_v1_voc_prune的权重文件

**Comment by wanghaoshuang** [comment]
>paddleslim的模型库下载的yolov3_mobilenet_v1_voc_prune的权重文件

如果是用自己的数据，这些权重文件就不需要了。这些权重文件是在voc数据上训练得到的。

**Comment by jaffe-fly** [comment]
好的，明白了
