### ISSUE TITLE
不支持windows https://pypi.org/simple/paddleslim-opt-tools/

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleSlim#1346]
不支持windows ，也找不到windows的包：  

Adding paddleslim 2.3.0 to easy-install.pth file

Installed c:\programdata\anaconda3\envs\paddlegpu\lib\site-packages\paddleslim-2.3.0-py3.7.egg
Processing dependencies for paddleslim==2.3.0
Searching for paddleslim-opt-tools
Reading https://pypi.org/simple/paddleslim-opt-tools/
No local packages or working download links found for paddleslim-opt-tools
error: Could not find suitable distribution for Requirement.parse('paddleslim-opt-tools')

![微信图片_20220816165838](https://user-images.githubusercontent.com/6648329/184841649-792525ed-1325-49de-a5eb-664fd5c2f690.png)

**Comment by yghstill** [comment]
@gg22mm 这个包在Windows下不支持，直接安装paddleslim==2.3.2试下吧

**Comment by gg22mm** [comment]
> @gg22mm 这个包在Windows下不支持，直接安装paddleslim==2.3.2试下吧

这个不行，Windows只能用 paddleslim==1.1.1

**Comment by yghstill** [comment]
@gg22mm 是什么原因只能用paddleslim 1.1.1？

**Comment by gg22mm** [comment]
> 能用paddleslim 1

就因为是windos 吧

**Comment by yghstill** [comment]
windows支持安装paddleslim 2.3.2的

**Comment by gg22mm** [comment]
> paddleslim 2.3.2

嗯嗯，谢谢~~  我看了，是安装上去了，但是过程有报错，不知道会不会影响. 

![微信图片_20220817114513](https://user-images.githubusercontent.com/6648329/185031076-b5917cc4-f9c7-4499-b9d4-96543bd6aa3b.png)
![微信图片_20220817114443](https://user-images.githubusercontent.com/6648329/185031084-6a6feeec-74cd-4663-b33e-a4abd8221b09.png)
![微信图片_20220817114546](https://user-images.githubusercontent.com/6648329/185031089-18e58c59-e51d-4a01-9ebd-7edc16f55ae2.png)

**Comment by iamWHTWD** [comment]
1）可以通过安装swig 解决，安装方式可参考： https://blog.csdn.net/qq_40088639/article/details/116980025
2）paddleslim截至到8.22最新版本为V2.3.3，升级：pip install -U paddleslim
