### ISSUE TITLE
离线KL量化 使用 Paddle2ONNX转换模型

### ISSUE THREAD

**Issue by Linaom1214** [PaddlePaddle/PaddleSlim#1350]
[Paddle2ONNX] Oops, there are some operators not supported yet, including linspace

**Comment by yghstill** [comment]
@Linaom1214 是哪个模型？更详细报错信息可以发下吗？

**Comment by Linaom1214** [comment]
> @Linaom1214 是哪个模型？更详细报错信息可以发下吗？

自己搭建的模型， 就这一个报错无法转换， 我正在尝试去掉模型中的inplane操作

**Comment by Linaom1214** [comment]
> @Linaom1214 是哪个模型？更详细报错信息可以发下吗？

自己搭建的模型

```
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [Info] The Paddle model is a quantized model. 
[Paddle2ONNX] Oops, there are some operators not supported yet, including linspace,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)
```

**Comment by yghstill** [comment]
@Linaom1214 paddle2onnx是1.0.0.rc3吗？

**Comment by Linaom1214** [comment]
> @Linaom1214 paddle2onnx是1.0.0.rc3吗？

是的，已经和Paddle2ONNX确认过了，目前不支持linspace 这个OP

**Comment by yghstill** [comment]
@Linaom1214 嗯嗯，可以等paddle2onnx支持后再进行尝试
