### ISSUE TITLE
图片分割例子不能运行

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleSlim#1351]
cd PaddleSlim/example/auto_compression/semantic_segmentation/
python run.py

run.py 如下：
`

def parse_args():
    parser = argparse.ArgumentParser(description='Model training')
    parser.add_argument(
        '--model_dir',
        type=str,
        default='./models/ppseg_lite_portrait_398x224_with_softmax',  #模型目录
        help="inference model directory.")
    parser.add_argument(
        '--model_filename',
        type=str,
        default='model.pdmodel',                                       #模型名
        help="inference model filename.")
    parser.add_argument(
        '--params_filename',
        type=str,
        default='model.pdiparams',                                     #模型参数
        help="inference params filename.")
    parser.add_argument(
        '--save_dir',
        type=str,
        default='./save_compressed_model',                             #自动压缩后的模型保存目录
        help="directory to save compressed model.")
    parser.add_argument(
        '--strategy_config',
        type=str,
        default=None,
        help="path of compression strategy config.")
    parser.add_argument(
        '--dataset_config',
        type=str,
        default='./configs/dataset/humanseg_dataset.yaml',              #数据集配置 
        help="path of dataset config.")
    parser.add_argument(
        '--deploy_hardware',
        type=str,
        default='deploy_hardware',                                      #传入 deploy_hardware 字段时，将自动搜索压缩策略进行压缩
        help="The hardware you want to deploy.")
    return parser.parse_args()

`

![11](https://user-images.githubusercontent.com/6648329/185053456-0776984d-0d32-4c9b-9407-7f77691b89e8.png)
![33](https://user-images.githubusercontent.com/6648329/185053530-810b68d7-ec64-4b31-80b8-e0b8abc3065b.png)

报错：

(paddleGpu) D:\dzkj\PaddleSlim\example\auto_compression\semantic_segmentation>python run.py
2022-08-17 14:46:42,134-WARNING: post-quant-hpo is not support in system other than linux
C:\ProgramData\Anaconda3\envs\paddleGpu\lib\site-packages\paddle\fluid\reader.py:485: UserWarning: DataLoader with multi-process mode is not supported on MacOs and Windows currently. Please use signle-process mode with num_workers = 0 instead
Wed Aug 17 14:46:42-WARNING: The old way to load inference model is deprecated. model path: D:\dzkj\PaddleSlim\example\auto_compression\semantic_segmentation\models\ppseg_lite_portrait_398x224_with_softmax\model.pdmodel, params path: D:\dzkj\PaddleSlim\example\auto_compression\semantic_segmentation\models\ppseg_lite_portrait_398x224_with_softmax\model.pdiparams
W0817 14:46:42.415777  2076 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 3.7, Driver API Version: 10.2, Runtime API Version: 10.2
W0817 14:46:42.431401  2076 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "run.py", line 181, in <module>
    deploy_hardware=args.deploy_hardware)
  File "C:\ProgramData\Anaconda3\envs\paddleGpu\lib\site-packages\paddleslim-2.3.0-py3.7.egg\paddleslim\auto_compression\compressor.py", line 152, in __init__
  File "C:\ProgramData\Anaconda3\envs\paddleGpu\lib\site-packages\paddleslim-2.3.0-py3.7.egg\paddleslim\auto_compression\utils\dataloader.py", line 37, in wrap_dataloader
  File "run.py", line 138, in gen
    imgs = np.array(data[0])
KeyError: 0
![55](https://user-images.githubusercontent.com/6648329/185053814-0cc3466f-f8b6-4bce-abb7-d89e04c6c3fc.png)

我138行打印：print(data) 返回的是这样的：
{'trans_info': [[['padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding', 'padding'], [<paddle.fluid.core_avx.Tensor object at 0x00000182DF1AFAB0>, <paddle.fluid.core_avx.Tensor object at 0x00000182DF05CE30>]], [['resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize', 'resize'], [<paddle.fluid.core_avx.Tensor object at 0x00000182DEE8AF30>, <paddle.fluid.core_avx.Tensor object at 0x00000182F9843430>]]], 'img': <paddle.fluid.core_avx.Tensor object at 0x00000182DF069B30>, 'label': <paddle.fluid.core_avx.Tensor object at 0x00000182DF2AF2B0>, 'gt_fields': [['label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label', 'label']]}

------------------------

还有另一个问题，不知道是不是这个问题导致一连串问题，就是：--config_path 没有这个参数，
所以并不能用： python run.py --config_path='./configs/pp_humanseg/pp_humanseg_auto.yaml'  ，只能： python run.py
![6666](https://user-images.githubusercontent.com/6648329/185057607-c9c34de6-c8b6-4852-a458-e1b789fcc751.jpg)

**Comment by zzjjay** [comment]
@gg22mm  你是修改了run.py吗？贴出的代码中没有config path参数，所以指令执行错误，请拉取最新代码试试。

**Comment by gg22mm** [comment]
> @gg22mm 你是修改了run.py吗？贴出的代码中没有config path参数，所以指令执行错误，请拉取最新代码试试。

哦哦。我之前用的是正试版：v2.3.0 测试的。 我现在用：develop 版报的是另一个错：

ImportError: cannot import name 'load_config' from 'paddleslim.common'

**Comment by zzjjay** [comment]
@gg22mm  这个错误应该是slim安装版本的问题，之前更新过一些文件路径，麻烦重装下paddleslim~
在develop版代码里执行：python setup.py install

**Comment by gg22mm** [comment]
> @gg22mm 这个错误应该是slim安装版本的问题，之前更新过一些文件路径，麻烦重装下paddleslim~ 在develop版代码里执行：python setup.py install

嗯嗯，paddleslim 这个对windows实在不友好.. 我现在放到 aistudio 上也报错上面的错：
![微信图片_20220817163829](https://user-images.githubusercontent.com/6648329/185075747-d3a24ee0-cf48-494d-b2e9-d7483c129eba.jpg)

**Comment by zzjjay** [comment]
我没多久还测试过这个demo是能跑通的，我在你的代码上检查下 @gg22mm

**Comment by gg22mm** [comment]
> 我没多久还测试过这个demo是能跑通的，我在你的代码上检查下 @gg22mm

那是您没有使用这这个模型，我刚刚又测试了一遍，在aistudio上：  

代码够新的了：
![77777](https://user-images.githubusercontent.com/6648329/185082194-f183204a-9855-43f1-8fbf-3ad349a0e10b.png)



cd example/auto_compression/semantic_segmentation/
wget https://bj.bcebos.com/v1/paddlemodels/PaddleSlim/analysis/ppseg_lite_portrait_398x224_with_softmax.tar.gz
tar -xzf ppseg_lite_portrait_398x224_with_softmax.tar.gz
python ./data/download_data.py mini_humanseg
python run.py --config_path='./configs/pp_humanseg/pp_humanseg_auto.yaml' --save_dir='./save_compressed_model'

**Comment by zzjjay** [comment]
@gg22mm  要不你公开下你aistudio上的代码环境，我在你的环境里复现下这个问题，我在本机测试正常。

**Comment by gg22mm** [comment]
> 你公开下你aistudio上的代码环境，我在你的环境里复现下这个问题，我在

好的，谢谢： 
https://aistudio.baidu.com/aistudio/projectdetail/4439311?channelType=0&channel=0
GPU 方式运行
python setup.py install
pip install paddleseg  -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by zzjjay** [comment]
@gg22mm 问题出在paddleseg版本上，这是不同seg版本的dataloader返回数据格式有差异导致的。
请使用 pip install paddleseg==2.5.0 安装paddleseg2.5
pip install paddleseg -i https://pypi.tuna.tsinghua.edu.cn/simple 会安装v2.6
![image](https://user-images.githubusercontent.com/41366441/185086111-245ce790-9a92-4a84-a378-e1d27b56126f.png)
麻烦先卸载paddleseg，再重装下paddleseg2.5吧～

**Comment by gg22mm** [comment]
> -i https://pypi.tuna.tsinghua.edu.cn/simple

哦哦，您是对的，非常谢谢~~。。 终于出坑了~~。
