### ISSUE TITLE
ImportError: cannot import name 'load_config' from 'paddleslim.common'

### ISSUE THREAD

**Issue by jo-dean** [PaddlePaddle/PaddleSlim#1352]
![image](https://user-images.githubusercontent.com/38728358/185031220-32e068ec-68fa-4fd7-a4e7-58567236a384.png)

import 失败
安装了paddleslim 以及paddlepaddle 推理版本
![image](https://user-images.githubusercontent.com/38728358/185031315-b405cb25-d599-4e7f-8c68-a9a5b76e424f.png)

**Comment by yghstill** [comment]
这个报错是由于没有安装最新版paddleslim，本周paddleslim会发布2.3.3版本，所以你暂时可以用两种方式的任何一种，即可import 最新版paddslim版本：
1. 编译安装：
```
git clone https://github.com/PaddlePaddle/PaddleSlim.git & cd PaddleSlim
python setup.py install
```
2. 直接在环境变量中指定python路径：export PYTHONPATH=/你的路径/PaddleSlim/:$PYTHONPATH

**Comment by jo-dean** [comment]
第一种方法可以了，但是进行自动压缩训练时出现了问题
AttributeError: 'numpy.ndarray' object has no attribute 'numpy'
![image](https://user-images.githubusercontent.com/38728358/185058725-3fdb0930-d543-42e5-98df-066c1143b2b9.png)
这个update函数里的.numpy()都有问题。
我上周安装了就没有问题，可以直接训练，也没有出现:cannot import name 'load_config' from 'paddleslim.common'这个问题。

**Comment by yghstill** [comment]
@jo-dean 你是什么模型？.numpy()的这个问题在PaddleDetection已经修复过了，可以更新下develop的PaddleDetection试下

**Comment by jo-dean** [comment]
ppyolo_mbv3_samll
这是我的paddledet版本
![image](https://user-images.githubusercontent.com/38728358/185272761-ba745752-a006-481c-bb19-31eca781728a.png)

![image](https://user-images.githubusercontent.com/38728358/185272422-08eda696-e5f6-4e16-a71f-8a86d0f438bf.png)

**Comment by yghstill** [comment]
@jo-dean 你是voc数据集吗？或者你的ppyolo_mbv3_samll模型是不是不包含nms后处理？

**Comment by jo-dean** [comment]
自己的数据集，和VOC是一样格式的。
对的，没有nms

**Comment by jo-dean** [comment]
现在可以训练了，不过还是要在改了.numpy格式的情况下

**Comment by yghstill** [comment]
@jo-dean 嗯嗯，更新到PaddleDetection develop版本也可以，这个问题一个月前修复了，但ppdet还没发新版。

**Comment by jo-dean** [comment]
好的，谢谢
