### ISSUE TITLE
YOLOV7-tiny单卡和多卡训练，都按照默认的学习率么？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleSlim#1357]
![image](https://user-images.githubusercontent.com/78945582/185080532-936ccea2-8207-43f0-ac32-f6355dad583f.png)
YOLOV7-tiny单卡和多卡训练，都按照默认的学习率么？

**Comment by yghstill** [comment]
@lixiangMindSpore 是的，就按照这个设置即可。

**Comment by gutao0315** [comment]
请问 yolov7的配置文件在哪儿  PaddleDetection里只有yolo3的 你是在哪儿训练的

**Comment by yghstill** [comment]
@gutao0315 可以到https://github.com/nemonameless/PaddleDetection_YOLOSeries 找到yolov7的配置文件
