### ISSUE TITLE
做分割模型图像抠图压缩遇到的问题

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleSlim#1360]
图片抠图用的是： https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/Matting    生成的模型25MB， 但是有点慢大概4秒时间，想通过压缩加速好提升速度，于似呼开始爬坑......

1、看了语义分割模型自动压缩示例没找到关于“Matting ”的
	https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/semantic_segmentation
    打算自己添加一个：    
          cd PaddleSlim/example/auto_compression/semantic_segmentation
         
![8888](https://user-images.githubusercontent.com/6648329/185308004-a9962957-0ee8-4478-8187-bdf8a11b6f6e.png)
![99999](https://user-images.githubusercontent.com/6648329/185309187-f14b0b3a-66d5-4d2f-aaec-ef9f2a616292.png)

其中自己添加配置：
       configs/modnet/modnet-mobilenetv2_auto.yaml
模型来自：
            /models/modnet-mobilenetv2/    
            生成模型是通过Matting  生成如下：
                    cd PaddleSeg-release-2.6/Matting/
                    python train.py --config configs/modnet/modnet-mobilenetv2.yml --do_eval --use_vdl --save_interval 30 --num_workers 0 --save_dir output
                   python export.py --config configs/quick_start/modnet-mobilenetv2.yml --model_path ./weigth/modnet-mobilenetv2.pdparams  --save_dir ./inference_model
                    
2、模型压缩
    因为与现有例子的语义分割数据格式是： 
               图片： JPEGImages\1.png          蒙版：Annotations\1.png  是这样种格式
     而Matting只是这种格式： 
               图片data/tongue/val/fg/1.jpg     蒙版：没有在train.txt中，只需要把 fg 改成： alpha 就是蒙版图，所以下载：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/paddleseg  目录放到 example/auto_compression/semantic_segmentation 目录下，并修改example/auto_compression/semantic_segmentation/paddleseg/datasets/dataset.py
               修改如下图：

![777777](https://user-images.githubusercontent.com/6648329/185310370-87f15a99-0de6-47bc-9578-9e8fbed46cbe.png)

3、执行压缩
  python run.py --config_path='./configs/modnet/modnet-mobilenetv2_auto.yaml' --save_dir='./save_compressed_model'

报如下错：不知道怎么回事？ 
    
![666666](https://user-images.githubusercontent.com/6648329/185313573-69de644e-dbb3-4ce2-b6d9-282571e7f825.png)

建议官方用：Matting   做个例子 ，  太需要了....

**Comment by zzjjay** [comment]
@gg22mm 这个看起来是在dataloader部分读取数据集出了问题，参考paddleseg关于matting数据集的设置再看下吧~https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/Matting/README_CN.md
PaddleSeg也整理了可用于MODNet训练的PPM-100数据集：https://paddleseg.bj.bcebos.com/matting/datasets/PPM-100.zip

**Comment by gg22mm** [comment]
> @gg22mm 这个看起来是在dataloader部分读取数据集出了问题，参考paddleseg关于matting数据集的设置再看下吧~https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/Matting/README_CN.md PaddleSeg也整理了可用于MODNet训练的PPM-100数据集：https://paddleseg.bj.bcebos.com/matting/datasets/PPM-100.zip

这个看了一下，还是dataset问题， 对我来说可能有点难了。 先看一下有没有其它方式
