### ISSUE TITLE
./configs/pp_liteseg/pp_liteseg_auto.yaml 模型配置没有运行成功

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleSlim#1363]
测试了下：有没模型配置没有运行成功

#这个可以成功
python run.py --config_path='./configs/pp_humanseg/pp_humanseg_auto.yaml' --save_dir='./save_compressed_model'	  

#这个没有成功 - NameError: name 'post_quant_hpo' is not defined
python run.py --config_path='./configs/pp_liteseg/pp_liteseg_auto.yaml' --save_dir='./save_compressed_model'	

   
![11111](https://user-images.githubusercontent.com/6648329/185360098-bd0bbfdf-6e3c-414c-8837-ef3764fb1e45.jpg)

**Comment by wanghaoshuang** [comment]
请问，您的环境是linux操作系统么？
配置文件“pp_liteseg_auto.yaml”触发了超参搜索功能，但是非linux操作系统不支持超参搜索功能。

后续的修复：
1. 在首页文档给出功能支持情况对照表
2. 捕获当前error，在log中给出解释 https://github.com/PaddlePaddle/PaddleSlim/commit/1bea8e18a549dc00f7704d42db506defee9ec6f6

**Comment by gg22mm** [comment]
> 触发了超参搜索功能

是linux , 用的是aistudioi

**Comment by wanghaoshuang** [comment]
>是linux , 用的是aistudioi

好的，我再排查下这个问题

**Comment by gg22mm** [comment]
我以后还是用这个方式： https://github.com/PaddlePaddle/PaddleSlim/issues/1366
