### ISSUE TITLE
关于直接修改源码获得train_loader 并自动压缩问题

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleSlim#1366]
1、通过文档：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression 我们知道 只要传入相应该的train_loader 即可"运行自动化压缩" 如图：
![1](https://user-images.githubusercontent.com/6648329/185398649-66a6cadd-5087-49b6-8c82-fc23736fd339.png)

2、实战：
     下载：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/Matting
      修改：  PaddleSeg/Matting/core/train.py  ， 可以直接下载：[PaddleSeg/Matting/core/tarin.py](http://ztg.diyyq.com/train.txt)
      
      顶部引入：
            # 快速压缩模型 - 运行自动化压缩
            from paddleslim.auto_compression import AutoCompression
           # paddle.enable_static()

     添加如下图：
![2](https://user-images.githubusercontent.com/6648329/185399639-18520241-4ff8-4471-91ef-6b7234fc7e97.png)

3、运行
python train.py --config configs/modnet/modnet-mobilenetv2.yml --do_eval --use_vdl --save_interval 30 --num_workers 0 --save_dir output

报如下错是怎么回事？：

![3](https://user-images.githubusercontent.com/6648329/185400278-cbb64da6-b5fd-46d4-93bf-b9e2c174d594.png)

AutoCompression   是不是要传固定样式的 dataloader  ?

**Comment by wanghaoshuang** [comment]
你好，这个报错和dataloader无关。
应该是模型结构的问题。在插入模拟量化节点时，某个op找不到输出。
可以分享一下model.pdmodel文件么？我需要根据这个文件排查下。

**Comment by gg22mm** [comment]
> 你好，这个报错和dataloader无关。 应该是模型结构的问题。在插入模拟量化节点时，某个op找不到输出。 可以分享一下model.pdmodel文件么？我需要根据这个文件排查下。

您好，可以的，这就是模型的下载地址：[点击这里模型测试下载](#)
非常感谢！


附模型是这样训练出来的：
cd PaddleSeg/Matting
python train.py --config configs/modnet/modnet-mobilenetv2.yml --do_eval --use_vdl --save_interval 30 --num_workers 0 --save_dir output

**Comment by wanghaoshuang** [comment]
## 解决办法
临时解决办法如下：
在Paddle安装目录下，找到文件“paddle/fluid/contrib/slim/quantization/utils.py”。
修改[代码](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/quantization/utils.py#L195)，将`Out`替换为`Y`.

后续会在PaddlePaddle2.3.3正式解决该问题。

## 原因
与DataLoader无关，是量化功能没有正确处理instance_norm。详情如下：
在量化模块，定义了每个OP的输入和输出名称。
其中，instance_norm的输出被定义为了“out”，详见[代码](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/quantization/utils.py#L195)。
但是，instance_norm OP输出的名称实际为“Y”，详见[代码](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/instance_norm_op.cc#L78)

**Comment by gg22mm** [comment]
> ## 解决办法
> 
> 临时解决办法如下： 在Paddle安装目录下，找到文件“paddle/fluid/contrib/slim/quantization/utils.py”。 修改[代码](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/quantization/utils.py#L195)，将`Out`替换为`Y`.
> 
> 后续会在PaddlePaddle2.3.3正式解决该问题。
> ## 原因
> 
> 与DataLoader无关，是量化功能没有正确处理instance_norm。详情如下： 在量化模块，定义了每个OP的输入和输出名称。 其中，instance_norm的输出被定义为了“out”，详见[代码](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/quantization/utils.py#L195)。 但是，instance_norm OP输出的名称实际为“Y”，详见[代码](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/instance_norm_op.cc#L78)

非常感谢 ！~~
    我直接 vi /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/utils.py 进行修改了成了： "instance_norm": [["X"], ["Y"]],   然后utils的问题解决了，但是还报其它的错如下：

![444444](https://user-images.githubusercontent.com/6648329/185549173-f28e9e2e-aa72-4f7f-92f9-639a7a22d835.png)

------------------------------------------------


# 打印train_loader
print( list( loader() ) )
exit()

我看格式train_loader中有img_name 如图：
![555](https://user-images.githubusercontent.com/6648329/185553134-09f68107-d5f9-478e-968f-d71711d4488c.png)


[=============点击下载格式===========](http://ztg.diyyq.com/dataload_format.txt)

**Comment by wanghaoshuang** [comment]
>然后utils的问题解决了，但是还报其它的错如下：

关于”image_name“的问题，模型输入的Tensor的名称和DataLoader给的名称不一致。

- 模型输入Tensor名称为img，如下图所示：（使用netron可视化model.pdmodel文件）
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/7534971/185558072-5178b309-e556-4b68-b637-cecc14b17a51.png">

- DataLoader给的名称是“image_name”

综上，需要您修改`train_dataset`，将“image_name”修改为“img”。根据你以上提供的信息，无法看到train_dataset的定义，所以暂时无法判断应该具体在哪里修改。

**Comment by gg22mm** [comment]
> > 然后utils的问题解决了，但是还报其它的错如下：
> 综上，需要您修改`train_dataset`，将“image_name”修改为“img”。根据你以上提供的信息，无法看到train_dataset的定义，所以暂时无法判断应该具体在哪里修改。



我改了image_name 为 img 只解决了这个字段key

但是又报其它字段key： ValueError: var alpha not in this block
![22](https://user-images.githubusercontent.com/6648329/185562049-fe46fc00-4392-4b02-8573-e3f28743ed04.png)

要改的文件（里面还有很多，不知道怎么替换其它的）：
![111](https://user-images.githubusercontent.com/6648329/185561508-02b6bf0a-a1fd-4cf8-90e6-ffc2d4fbd563.png)

  我看了一下里面有很多data[key]，都要改吗，不知道要改成什么？

**Comment by wanghaoshuang** [comment]
>我看了一下里面有很多data[key]，都要改吗，不知道要改成什么？

从你的推理模型的可视化结果来看，输入只有一个“img”，所以dataset中不能有其它keys.
你可以在[这一行](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/Matting/ppmatting/datasets/matting_dataset.py#L190)前添加一行：
```
data = ["img": data['img']]
```

**Comment by gg22mm** [comment]
直接添加 ：  data = {"img": data['img']}  #这个是模型压缩时添加的，平时都要禁用，之前的 image_name 为 img 不用修改。

完美，没有问题了，  非常感谢大佬。  跪拜啊..   模型压缩这个搞了我好久终于出坑了~~   太激动了。    
非常nice ,  看到这个页面应该没有什么问题了。感谢~~
![1](https://user-images.githubusercontent.com/6648329/185575547-4753d42d-3f66-49ad-b3c9-9625406a1fcc.png)
