### ISSUE TITLE
在windows上安装PaddleSlim失败，报swig error

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleSlim#1367]
Attempting uninstall: tornado
    Found existing installation: tornado 6.2
    Uninstalling tornado-6.2:
      Successfully uninstalled tornado-6.2
  Running setup.py install for pyrfr ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyrfr did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      [<setuptools.extension.Extension('pyrfr._regression') at 0x2854db53400>, <setuptools.extension.Extension('pyrfr._util') at 0x2854dcf2220>]
      running install
      C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build_ext
      building 'pyrfr._regression' extension
      swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
      swig.exe -python -c++ -modern -py3 -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
      error: command 'swig.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyrfr

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

使用pip install PaddleSlim安装,结果报错,上面是错误提示.使用PaddleSlim官方的安装教程安装,依然报错,也是同样的报错提示.
paddlegpu是2.3.2,cuda10.2版本,970显卡,windows11系统,64位.

**Comment by wanghaoshuang** [comment]
可以参考这个教程单独安装下swig， https://github.com/PaddlePaddle/PaddleSlim/issues/1258

**Comment by yuwoyizhan** [comment]
@wanghaoshuang 
1.我刚才使用pip install swig,安装完swig后,使用pip install PaddleSlim,安装就不会报错了.我也按照#1258提示,打开swig的网站,里面的英文介绍很清楚,windows系统需要安装swigwin.但我没有安装swigwin.目前安装PaddleSlim没有报错了.
你可以考虑改成先使用pip install swig安装完再安装PaddleSlim,或许就好了.
2.有没有代码让我测试PaddleSlim是否成功安装了呢?安装paddlepaddle和paddledet后,他们的安装教程都有告诉我如何测试,是否安装成功,安装PaddleSlim好像没有测试是否安装成功这个步骤,建议添加,谢谢.

**Comment by wanghaoshuang** [comment]
>你可以考虑改成先使用pip install swig安装完再安装PaddleSlim,或许就好了.

>安装PaddleSlim好像没有测试是否安装成功这个步骤,建议添加,谢谢.

非常感谢您的建议，我们后续会完善这两点。

**Comment by wanghaoshuang** [comment]
已解决
