### ISSUE TITLE
使用 paddledetection train出来的yolox auto_compression 发现有问题

### ISSUE THREAD

**Issue by JackYang825** [PaddlePaddle/PaddleSlim#1382]
<img width="989" alt="截屏2022-08-22 17 44 11" src="https://user-images.githubusercontent.com/15171817/185891820-4a9fcc99-d31f-4074-b13b-d2c48b26d8f7.png">
命令: usr/bin/python -u /PaddleSlim/example/auto_compression/pytorch_yolo_series/run.py --config_path=./configs/yolov5s_qat_dis.yaml --save_dir='./output/'
<img width="774" alt="截屏2022-08-22 17 45 39" src="https://user-images.githubusercontent.com/15171817/185892104-316542a8-2ee9-413a-9054-9598552576d5.png">

**Comment by yghstill** [comment]
@AlfredTheBest 如果是PaddleDetection产出的模型，可以使用https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/auto_compression 的demo进行测试

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/113ff463291e4df0c0ac3358a87ff1c399081892/deploy/auto_compression/configs/yolox_s_qat_dis.yaml 参考这个试一下
