### ISSUE TITLE
如何用自己训练的模型进行量化。

### ISSUE THREAD

**Issue by Genlk** [PaddlePaddle/PaddleSlim#1386]
我用的是芯原的产品，在学习PaddleSlim-quant-demo.tar.gz  这个demo 时，model里的模型跟paddledection 里训练好的模型(如pdmodel 和pdiparams) 格式似乎不一样，去运行自己训练好的模型作量化时就报错了，运行demo里的mobilenet_v1 和 resnet50时是正确的，用自己的训练 好的模型做静态量化时还需要注意什么？  谢谢

**Comment by Genlk** [comment]
与一个网友遇到同样的问题，就把他的问题copy过来，在此提问了

**Comment by yghstill** [comment]
@Genlk 请问你是什么模型，模型格式是什么样的？

**Comment by Genlk** [comment]
> 

自己定义的一个简单的模型，


------------------------
1.模型文件如下
import torch
from torch import nn
from x2paddle.convert import pytorch2paddle,onnx2paddle

class Net1(torch.nn.Module):
    def __init__(self):
        super(Net1, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=3,out_channels=16,stride=4,kernel_size=3,device="cuda")
        self.pool1 = nn.MaxPool2d(kernel_size=2,stride=2)
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=1, stride=4, kernel_size=3,device="cuda")
        self.pool2 = nn.MaxPool2d(kernel_size=4, stride=2)

    def forward(self, x):
        x = self.conv1(x)
        x = self.pool1(x)
        x = self.conv2(x)
        y = self.pool2(x)
        return y

def trans():
    save_path  = './paddle_model/1/mini.onnx'
    model = Net1()
    print(model)
    x = torch.randn(1,3,1024, 512, requires_grad=False,device="cuda")
    model.eval()
    print(model(x))
    torch.onnx.export(model, x, save_path, export_params=True, opset_version=9, do_constant_folding=True)
    print("onnx export successfully!")
 
if __name__=="__main__":

    trans()



------------------------
2.生成mini.onnx 之后，调用x2paddle 生成paddle模型
 x2paddle --framework=onnx --model=mini.onnx --save_dir=paddle_out


------------------------
3.在paddle 当中的文件如下从
![image](https://user-images.githubusercontent.com/24912927/186054444-523f0e2d-97be-4c6f-ab2c-e3cc3a11cdf9.png)

------------------------
4.PaddleSlim-quant-demo.tar.gz  demo 里面的模型如下
![image](https://user-images.githubusercontent.com/24912927/186054639-9f9acc9f-53b5-4230-88ac-6a4ff389b093.png)


------------------------
5.两者不一致，调用quant_post_rockchip_npu.sh*，会提示找不到 __model__文件

**Comment by Genlk** [comment]
@yghstill  FYI

**Comment by yghstill** [comment]
@Genlk 你想要做离线量化吗？你的PaddleSlim-quant-demo.tar.gz 的代码可能有些老了？你可以直接参考这个离线量化的demo进行离线量化：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant_post

**Comment by yghstill** [comment]
> 5.两者不一致，调用quant_post_rockchip_npu.sh*，会提示找不到 __model__文件

是由于模型文件没有加载进去，最新的paddle预测模型文件是model.pdmodel这样命名的，__model__的命名格式是旧的形式，可以：
mv model.pdmodel __model__ 

但是还是建议你使用比较新的demo进行实验

**Comment by Genlk** [comment]
> > 5.两者不一致，调用quant_post_rockchip_npu.sh*，会提示找不到 __model__文件
> 
> 是由于模型文件没有加载进去，最新的paddle预测模型文件是model.pdmodel这样命名的，__model__的命名格式是旧的形式，可以： mv model.pdmodel **model**
> 
> 但是还是建议你使用比较新的demo进行实验

问题已经解决了，新的版本当中使用quant_post_static 替代了 quant_post

__model__ 是 non combine 格式的模型，使用combine格式的模型文件如下
![image](https://user-images.githubusercontent.com/24912927/186308933-2980492d-cffb-488c-9d79-861c5346cb7d.png)


在quant_post_static当中有参数，设置模型文件和参数文件，设置之后就可以进行量化了
![image](https://user-images.githubusercontent.com/24912927/186309297-6c456bd1-0380-463e-96f6-a6506027fbbc.png)
