### ISSUE TITLE
Does paddleslim support generating task models? 

### ISSUE THREAD

**Issue by AIikai** [PaddlePaddle/PaddleSlim#1395]
Does paddleslim support generating task models?  Prepare to compress the translation model trained by fairseq, such as distillation and pruning. Can you give me some advice?
Thank U.

**Comment by wanghaoshuang** [comment]
>Does paddleslim support generating task models?

Yes. `distillation`, `QAT` and `PTQ` can be used in generation task. 
And structure pruning just support convolution operator.
