### ISSUE TITLE
auto_compression/pytorch_yolo_series 无法run成功

### ISSUE THREAD

**Issue by shituo123456** [PaddlePaddle/PaddleSlim#1406]
按照官方教程配置好环境后，报如下错：

Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 12, automatically treated as op_set: 9.
Total nodes: 248
Nodes converting ...
Converting node 327 ...     2022-09-02 10:36:26,643-WARNING: convert failed node:onnx__Concat_271, op_type is Resize
2022-09-02 10:36:26,643-ERROR: x2paddle threw an exception, you can ask for help 

按照 https://github.com/PaddlePaddle/X2Paddle/issues/494 的方法重新配置x2paddle后，又报如下错：

2022-09-02 10:39:31,795-INFO: Now translating model from onnx to paddle.
2022-09-02 10:39:31,795-WARNING: __init__() missing 1 required positional argument: 'enable_onnx_checker'
2022-09-02 10:39:31,795-ERROR: x2paddle threw an exception, you can ask for help at: https://github.com/PaddlePaddle/X2Paddle/issues

目前这个问题找不到解决方法。麻烦看一下 谢谢

**Comment by leiqing1** [comment]
看log信息是X2Paddle问题造成的，我们复现下这个问题@yghstill～

**Comment by yghstill** [comment]
@shituo123456 可以确认下x2paddle版本，需要x2paddle >=1.3.6，如果还有问题，我们检查下example
```shell
pip list|grep x2paddle
```

**Comment by shituo123456** [comment]
> @shituo123456 可以确认下x2paddle版本，需要x2paddle >=1.3.6，如果还有问题，我们检查下example
> 
> ```shell
> pip list|grep x2paddle
> ```

![image](https://user-images.githubusercontent.com/64970397/189011890-15ba7358-cb26-44e7-97ab-1e4d48016662.png)
版本满足要求的。但是还是run不起来

**Comment by ginalee828** [comment]
Hi @shituo123456 
 I've encountered the same issue with x2paddle==1.3.9
 Did you solve the problem?

**Comment by zzjjay** [comment]
> 2022-09-02 10:39:31,795-INFO: Now translating model from onnx to paddle.
>2022-09-02 10:39:31,795-WARNING: init() missing 1 required positional argument: 'enable_onnx_checker'

该问题是x2paddle和paddleslim版本不一致导致的；
如果使用的是paddleslim develop版，请安装x2paddle1.3.9；
如果使用的是paddleslim2.3版，则安装x2paddle1.3.8

**Comment by hhxdestiny** [comment]
> paddleslim
```bash
paddlepaddle       2.4.0rc0
x2paddle              1.3.9
paddleslim            2.3.3
```
以上环境仍然会复现该问题
