### ISSUE TITLE
paddlelite 支持int8预测吗？

### ISSUE THREAD

**Issue by wchuan163** [PaddlePaddle/PaddleSlim#1418]
paddlelite 支持int8预测吗？

**Comment by yghstill** [comment]
支持的

**Comment by wchuan163** [comment]
就是支持arm cpu int8预测？

**Comment by yghstill** [comment]
> 就是支持arm cpu int8预测？

支持arm cpu，npu的int8预测

**Comment by leiqing1** [comment]
@wchuan163 你好，如果使用lite部署全量化模型有问题，也欢迎部署群详细交流。（微信号：18813190139）
