### ISSUE TITLE
自动化压缩处理完之后 可以部署到tf serving中使用吗

### ISSUE THREAD

**Issue by qiu-pinggaizi** [PaddlePaddle/PaddleSlim#1429]

**Comment by leiqing1** [comment]
@qiu-pinggaizi 转成onnx模型，只要tf serving支持onnx量化模型格式就行。

**Comment by qiu-pinggaizi** [comment]
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/pytorch_yolo_series#yolo%E7%B3%BB%E5%88%97%E6%A8%A1%E5%9E%8B%E8%87%AA%E5%8A%A8%E5%8E%8B%E7%BC%A9%E7%A4%BA%E4%BE%8B
![image](https://user-images.githubusercontent.com/52409244/194988142-115f556c-42ad-48ea-9ac6-c1c67b0befde.png)

图像中量化后的onnx格式模型能单独使用么，必须需要和.cache配合使用吗？可直接将onnx转换为saved_model？
