### ISSUE TITLE
PaddleX训练的模型使用paddleslim量化报错

### ISSUE THREAD

**Issue by Hyperpepe** [PaddlePaddle/PaddleSlim#1434]
我在使用paddlex训练完成我自己的mobilenetv1模型后，参考https://paddle-lite.readthedocs.io/zh/develop/demo_guides/verisilicon_timvx.html
这个文档进行模型量化，是基于npu的模型量化，遇到了如下问题
![image](https://user-images.githubusercontent.com/74920047/192414646-d0886a52-78a9-48d9-81b6-d67e90ab6115.png)
看了原先其他人的讲法是paddleslim的版本过旧，那基于这个paddlelite npusoc的paddleslim量化方式建议同步改进，或者能否告诉我如何使用现有的模型进行转化

**Comment by yghstill** [comment]
根据报错，是由于model路径找不到，检查下输入的模型路径是否正确吧，还有model_filename是否指定的正确。

**Comment by Hyperpepe** [comment]
能够确定的是paddleslim的模型版本问题，主要是模型文件里面没有这个_model_这个文件，paddlex 1.0支持，但是目前还没有成功
