### ISSUE TITLE
采用paddleslim静态离线量化api ，quant_post_static(), 量化之后，送入paddlelite进行推理，出现op_info->Hasinputscale（） check failed

### ISSUE THREAD

**Issue by tomtcy** [PaddlePaddle/PaddleSlim#1442]
具体问题如图所示

<img width="796" alt="截屏2022-09-28 下午9 33 15" src="https://user-images.githubusercontent.com/55530624/192961586-71f615aa-6470-41ab-ae5d-ca59ea3bf75c.png">

**Comment by wanghaoshuang** [comment]
https://paddle-lite.readthedocs.io/zh/develop/user_guides/quant/quant_post_static.html
有参考这个教程么？
需要用opt工具转换slim产出的模型到nb格式：

3.1 模型转换
参考[模型转换](https://paddle-lite.readthedocs.io/zh/develop/user_guides/model_optimize_tool.html)准备模型转换工具，建议从 Release 页面下载。

参考[模型转换](https://paddle-lite.readthedocs.io/zh/develop/user_guides/model_optimize_tool.html)使用模型转换工具，参数按照实际情况设置。比如在安卓手机 ARM 端进行预测，模型转换的命令为：

./OPT --model_dir=./mobilenet_v1_quant \
      --optimize_out_type=naive_buffer \
      --optimize_out=mobilenet_v1_quant_opt \
      --valid_targets=arm

**Comment by tomtcy** [comment]
> 
嗯嗯，我的模型有两个输入，我参考了这个网页下面的demo文档，将相应的静态离线量化脚本进行了修改，进行了量化。因为是在x86 寒武纪平台进行适配，因此没有采用opt 工具将其转化为 naive_buffer 类型。

**Comment by wanghaoshuang** [comment]
@tomtcy 给我发了量化模型结构文件，为旧格式，使用PaddleLite推理，出现以下错误：
<img width="936" alt="d4b588f7288116d16340d1515a4bbcd5" src="https://user-images.githubusercontent.com/7534971/192978157-4f793d79-e790-448e-a288-8836f5f9e841.png">

量化模型结构中，并没有对fill_any_like op做量化。
有两个问题：
1. Paddle Lite有对x86寒武纪平台适配过量化推理么？ 
2. Paddle Slim当前量化新格式，已经或能适配x86寒武纪平台么？ @jiangjiajun 

更新：
>2. Paddle Slim当前量化新格式，已经或能适配x86寒武纪平台么？ @jiangjiajun

PaddleInference通过onednn支持Slim量化新格式的模型在X86平台推理部署，但是咱不确定onednn对X86寒武纪支持的情况如何。

**Comment by jiangjiajun** [comment]
@yeliang2258

**Comment by wanghaoshuang** [comment]
模型结构文件：
[__model__.zip](https://github.com/PaddlePaddle/PaddleSlim/files/9672640/__model__.zip)

**Comment by yeliang2258** [comment]
用户你好，支持avx的机器上可以使用inference mkldnn部署量化模型，你可以先看看你的机器是否支持avx2或者avx512等指令，如果支持的话，可以用inference mkldnn来部署。

**Comment by hong19860320** [comment]
@tomtcy PaddleLite+MLU370 是支持 int8 + fp32/fp16 混合精度的，从模型上看是内部业务，建议在内部群讨论。
