### ISSUE TITLE
示例代码运行错误及修改

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleSlim#1448]
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression
快速开始
* 3

CUDA_VISIBLE_DEVICES=0 python ./image_classification/eval.py
中使用了Global传参，但是eval.yaml中没有该参数，会直接报错。建议修改。

还有这里并没有git clone仓库 切换目录的过程，按照该流程无法直接运行得到eval结果。建议添加。

**Comment by leiqing1** [comment]
感谢反馈问题。@ceci3 @yghstill  修正下这个产品易用性问题
