### ISSUE TITLE
[question]RuntimeError: Can't load tokenizer for './afqmc'.

### ISSUE THREAD

**Issue by buhanyunfei** [PaddlePaddle/PaddleSlim#1465]
![b8c25b40fe9bade47aa736b38b5b3fc](https://user-images.githubusercontent.com/75259281/195900771-25ac2dda-11aa-4bae-a8f5-cf5ba709a13e.png)

**Comment by buhanyunfei** [comment]
我把路径删完了但还是会报一个错误
![image](https://user-images.githubusercontent.com/75259281/195901190-a1647c46-e4c9-4e95-92b8-db09977f3625.png)

**Comment by ceci3** [comment]
> 我把路径删完了但还是会报一个错误 ![image](https://user-images.githubusercontent.com/75259281/195901190-a1647c46-e4c9-4e95-92b8-db09977f3625.png)

看起来paddle安装的是有问题的，可以按照提示重新安装一下paddle试试
