### ISSUE TITLE
请问支持什么权重和激活函数的量化类型 and 什么类型的预处理方法

### ISSUE THREAD

**Issue by Yamabukiss** [PaddlePaddle/PaddleSlim#1471]
我好像只在QAT源码中看到了有type 但是config中没有说明 还有请问在paddlelite上进行推理支持什么量化类型进行量化产生的量化模型呢

**Comment by yghstill** [comment]
权重量化支持abs_max或者channel_wise_abs_max，激活支持abs_max。预处理方法目前支持PACT。PaddleLite上都支持

**Comment by Yamabukiss** [comment]
> 权重量化支持abs_max或者channel_wise_abs_max，激活支持abs_max。预处理方法目前支持PACT。PaddleLite上都支持

请问意思是paddlelite上支持您这句回答里的方法还是说paddlelite支持所有类型的量化方法？

**Comment by yghstill** [comment]
目前PaddleSlim中量化算法产出的模型，在paddlelite上基本都支持
