### ISSUE TITLE
tinypose qat demo missing！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleSlim#1488]
hi，
      https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/detection 请问下啥时候会有tinypose的qat全量化的demo呢？ 目前看来，用不起来，训练的时候loss都是nan，ru如下图所示:
![image](https://user-images.githubusercontent.com/8407513/199145264-04520186-34a1-40d4-8bc6-7ef7c72fe845.png)

BR

**Comment by wanghaoshuang** [comment]
请问，是用的这个配置文件吗？
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/detection/configs/tinypose_qat_dis.yaml
