### ISSUE TITLE
picodet 全量化版本bug！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleSlim#1492]
hi，
  按照下述的链接，复现后结果跟文档不符
https://github.com/PaddlePaddle/PaddleSlim/tree/v2.4rc/example/full_quantization/picodet
 具体如下图所示:
![image](https://user-images.githubusercontent.com/8407513/199220355-8c34bc31-c852-4cb4-80d8-fdf5673baa23.png)
也就是说量化训练过程是有bug的，我的版本完全按照该文档所示的都是最新release版本具体如下
![image](https://user-images.githubusercontent.com/8407513/199220499-e2d08ab1-727c-40c6-b589-9affa1e3ab83.png)
期待pp大佬的支持，多谢
BR

**Comment by leiqing1** [comment]
如果在自己数据上训练，需要适当调整超参数哈。譬如learning rate等参数。
可以按照Paddle Detection里面的来，先在自己数据上训练全精度的网络，随后在用全量化能力完成全量化操作。这个过程已经集成到PaddleDetection里面了：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/picodet/FULL_QUANTIZATION.md

**Comment by 2050airobert** [comment]
补充:
1 相关pp repo如下
![image](https://user-images.githubusercontent.com/8407513/199388463-5913e5e0-b419-4d56-8ff1-8857b265dc56.png)
2 如果采用之前你们专门为专题issue定制的验证模型tinypose_act.tar.gz
[tinypose_act.tar.gz](https://github.com/PaddlePaddle/PaddleSlim/files/9915740/tinypose_act.tar.gz)
 ，采用如下配置
![image](https://user-images.githubusercontent.com/8407513/199389657-3d09ff92-bf4c-42e5-8ddb-def24840ae49.png)
命令如下 
![image](https://user-images.githubusercontent.com/8407513/199391885-a4dee2cd-2629-4cb3-9cf6-2389052db1a1.png)
PaddleSlim代码分支为: release/2.3
训练过程和结果都是正常的！
![image](https://user-images.githubusercontent.com/8407513/199391949-0cf30eed-6c44-48ee-8f8c-110847800ac7.png)
除此之外，其他版本组合和其他任何你们开源repo官网发布的模型(比如官网模型 
[tinypose_128x96.zip](https://github.com/PaddlePaddle/PaddleSlim/files/9916708/tinypose_128x96.zip)
，训练过程中loss都会有很多nan，结果异常
期待您的答复 多谢
3  除了上述唯一一次验证正常的 tinypose_act.tar.gz PaddleSlim代码分支为: release/2.3 之外，其他所有验证picodet NPU qat量化以及auto compress 我采用的代码 repo 如下:
    我使用的paddle slim  代码是develop分支 和 tag版本: v2.4rc ,
    PaddleDetection git clone下来的代码版本是 release/2.5
BR
