### ISSUE TITLE
ImportError: cannot import name '_legacy_C_ops' from 'paddle' (/home/ubuntu/anaconda3/envs/xl_paddleslim/lib/python3.8/site-packages/paddle/__init__.py)

### ISSUE THREAD

**Issue by Dora1483** [PaddlePaddle/PaddleSlim#1500]
环境问题。 找不到对应的包。

**Comment by wanghaoshuang** [comment]
请问您用的PaddlePaddle版本是？

**Comment by wanghaoshuang** [comment]
建议使用PaddleSlim2.4.0RC + PaddlePaddle2.4.0RC 
或 PaddleSlim2.3.4 + PaddlePaddle2.3.2

**Comment by Richard-mei** [comment]
> 建议使用PaddleSlim2.4.0RC + PaddlePaddle2.4.0RC 或 PaddleSlim2.3.4 + PaddlePaddle2.3.2

你好，我也遇到此问题，尝试过2.3.4+2.3.2和2.3.0+2.3.0，都是同样错误  
```[11-08 09:08:18 MainThread @utils.py:73] paddlepaddle version: 2.3.0.
WARNING:root:cannot import name 'layers' from 'parl' (/home/dl/anaconda3/envs/pds/lib/python3.8/site-packages/parl/__init__.py)
/home/dl/anaconda3/envs/pds/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "test_quant_training.py", line 2, in <module>
    import paddleslim as slim
  File "/home/dl/Projects/PaddleSlim/paddleslim/__init__.py", line 18, in <module>
    from paddleslim import nas
  File "/home/dl/Projects/PaddleSlim/paddleslim/nas/__init__.py", line 22, in <module>
    from .ofa import *
  File "/home/dl/Projects/PaddleSlim/paddleslim/nas/ofa/__init__.py", line 15, in <module>
    from .ofa import OFA, RunConfig, DistillConfig
  File "/home/dl/Projects/PaddleSlim/paddleslim/nas/ofa/ofa.py", line 27, in <module>
    from .layers import SuperConv2D, SuperLinear
  File "/home/dl/Projects/PaddleSlim/paddleslim/nas/ofa/layers.py", line 23, in <module>
    from paddle import _C_ops, _legacy_C_ops
ImportError: cannot import name '_legacy_C_ops' from 'paddle' (/home/dl/anaconda3/envs/pds/lib/python3.8/site-packages/paddle/__init__.py)
```  

```
Package              Version
-------------------- ---------------
absl-py              1.3.0
astor                0.8.1
certifi              2022.9.24
charset-normalizer   2.1.1
click                8.1.3
cloudpickle          1.6.0
ConfigSpace          0.6.0
contourpy            1.0.6
cycler               0.11.0
Cython               0.29.32
dask                 2022.10.2
decorator            5.1.1
distributed          2022.10.2
emcee                3.1.3
Flask                2.2.2
Flask-Cors           3.0.10
fonttools            4.38.0
fsspec               2022.10.0
grpcio               1.50.0
HeapDict             1.0.1
idna                 3.4
importlib-metadata   5.0.0
itsdangerous         2.1.2
Jinja2               3.1.2
joblib               1.2.0
kiwisolver           1.4.4
locket               1.0.0
Markdown             3.4.1
MarkupSafe           2.1.1
matplotlib           3.6.2
msgpack              1.0.4
numpy                1.23.4
opt-einsum           3.3.0
packaging            21.3
paddle-bfloat        0.1.2
paddlepaddle-gpu     2.3.0
paddleslim           2.3.0
paddleslim-opt-tools 2.11.2
parl                 2.0.5
partd                1.3.0
Pillow               9.3.0
pip                  22.2.2
protobuf             3.20.0
psutil               5.9.3
pynisher             0.6.4
pyparsing            3.0.9
pyrfr                0.8.3
python-dateutil      2.8.2
PyYAML               6.0
pyzmq                18.1.1
regex                2022.10.31
requests             2.28.1
scikit-learn         1.1.3
scipy                1.9.3
setuptools           65.5.0
six                  1.16.0
smac                 1.4.0
sortedcontainers     2.4.0
swig                 4.1.0
tb-nightly           1.15.0a20190801
tblib                1.7.0
tensorboardX         1.8
termcolor            2.1.0
threadpoolctl        3.1.0
toolz                0.12.0
tornado              6.1
tqdm                 4.64.1
typing_extensions    4.4.0
urllib3              1.26.12
Werkzeug             2.2.2
wheel                0.37.1
zict                 2.2.0
zipp                 3.10.0
```

**Comment by Richard-mei** [comment]
> > 建议使用PaddleSlim2.4.0RC + PaddlePaddle2.4.0RC 或 PaddleSlim2.3.4 + PaddlePaddle2.3.2
> 
> 你好，我也遇到此问题，尝试过2.3.4+2.3.2和2.3.0+2.3.0，都是同样错误
> 
> ```
> WARNING:root:cannot import name 'layers' from 'parl' (/home/dl/anaconda3/envs/pds/lib/python3.8/site-packages/parl/__init__.py)
> /home/dl/anaconda3/envs/pds/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
>   warnings.warn("Setuptools is replacing distutils.")
> Traceback (most recent call last):
>   File "test_quant_training.py", line 2, in <module>
>     import paddleslim as slim
>   File "/home/dl/Projects/PaddleSlim/paddleslim/__init__.py", line 18, in <module>
>     from paddleslim import nas
>   File "/home/dl/Projects/PaddleSlim/paddleslim/nas/__init__.py", line 22, in <module>
>     from .ofa import *
>   File "/home/dl/Projects/PaddleSlim/paddleslim/nas/ofa/__init__.py", line 15, in <module>
>     from .ofa import OFA, RunConfig, DistillConfig
>   File "/home/dl/Projects/PaddleSlim/paddleslim/nas/ofa/ofa.py", line 27, in <module>
>     from .layers import SuperConv2D, SuperLinear
>   File "/home/dl/Projects/PaddleSlim/paddleslim/nas/ofa/layers.py", line 23, in <module>
>     from paddle import _C_ops, _legacy_C_ops
> ImportError: cannot import name '_legacy_C_ops' from 'paddle' (/home/dl/anaconda3/envs/pds/lib/python3.8/site-packages/paddle/__init__.py)
> ```
> 
> ```
> Package              Version
> -------------------- ---------------
> absl-py              1.3.0
> astor                0.8.1
> certifi              2022.9.24
> charset-normalizer   2.1.1
> click                8.1.3
> cloudpickle          1.6.0
> ConfigSpace          0.6.0
> contourpy            1.0.6
> cycler               0.11.0
> Cython               0.29.32
> dask                 2022.10.2
> decorator            5.1.1
> distributed          2022.10.2
> emcee                3.1.3
> Flask                2.2.2
> Flask-Cors           3.0.10
> fonttools            4.38.0
> fsspec               2022.10.0
> grpcio               1.50.0
> HeapDict             1.0.1
> idna                 3.4
> importlib-metadata   5.0.0
> itsdangerous         2.1.2
> Jinja2               3.1.2
> joblib               1.2.0
> kiwisolver           1.4.4
> locket               1.0.0
> Markdown             3.4.1
> MarkupSafe           2.1.1
> matplotlib           3.6.2
> msgpack              1.0.4
> numpy                1.23.4
> opt-einsum           3.3.0
> packaging            21.3
> paddle-bfloat        0.1.2
> paddlepaddle-gpu     2.3.0
> paddleslim           2.3.0
> paddleslim-opt-tools 2.11.2
> parl                 2.0.5
> partd                1.3.0
> Pillow               9.3.0
> pip                  22.2.2
> protobuf             3.20.0
> psutil               5.9.3
> pynisher             0.6.4
> pyparsing            3.0.9
> pyrfr                0.8.3
> python-dateutil      2.8.2
> PyYAML               6.0
> pyzmq                18.1.1
> regex                2022.10.31
> requests             2.28.1
> scikit-learn         1.1.3
> scipy                1.9.3
> setuptools           65.5.0
> six                  1.16.0
> smac                 1.4.0
> sortedcontainers     2.4.0
> swig                 4.1.0
> tb-nightly           1.15.0a20190801
> tblib                1.7.0
> tensorboardX         1.8
> termcolor            2.1.0
> threadpoolctl        3.1.0
> toolz                0.12.0
> tornado              6.1
> tqdm                 4.64.1
> typing_extensions    4.4.0
> urllib3              1.26.12
> Werkzeug             2.2.2
> wheel                0.37.1
> zict                 2.2.0
> zipp                 3.10.0
> ```

我发现可能是因为我的脚本放在了PaddleSlim工程目录下，此目录下有paddleslim，所以导致import paddleslim出错？
