### ISSUE TITLE
AttributeError: 'MAOutputScaleLayer' object has no attribute 'gold_score'

### ISSUE THREAD

**Issue by Fordacre** [PaddlePaddle/PaddleSlim#1507]
在使用QAT进行模型量化的过程中，训练报错，AttributeError: 'MAOutputScaleLayer' object has no attribute 'gold_score'。
![image](https://user-images.githubusercontent.com/12699033/200506533-3fdf3fdd-1ba9-4f69-962d-7ae284305b4d.png)
报错layer为自定义layer。可以麻烦帮忙看一下如何解决这个问题嘛。

**Comment by yghstill** [comment]
@Fordacre 如果是自定义layer，你将该类不继承自nn.Layer再试下。（跳过该类的量化）

**Comment by Fordacre** [comment]
尝试了一下，不继承的话很多nn.Layer的功能都用不了了，模型无法运行。这里有什么参数能够设置取消这一层不进行量化嘛。

**Comment by yghstill** [comment]
@Fordacre 
1. MAOutputScaleLayer这个只是收集每个op输出的量化scale信息，你可以gold_score这个属性通过self._layer.gold_score获取。
2.  也可以将还有gold_score属性的a设置a.skip_quant = True，然后修改Paddle安装路径下的 `python/paddle/fluid/contrib/slim/quantization/imperative/qat.py`的ImperativeQuantizeOutputs类里的446行：

```python
for cur_name, cur_layer in model.named_sublayers():
    if hasattr(cur_layer, "skip_quant") and cur_layer.skip_quant == True):
        continue
```

**Comment by Fordacre** [comment]
问题已解决，感谢。
另外请问一下，在使用QAT的时候，一般训练的epoch和学习率是如何设置的呢，和基础训练保持一致嘛，还是需要小一些的epoch和学习率呢。
