### ISSUE TITLE
name '_logger' is not defined

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/PaddleSlim#151]
使用在线量化训练模型，报错：
Traceback (most recent call last):
  File "train.py", line 734, in <module>
    main()
  File "train.py", line 730, in main
    train(args)
  File "train.py", line 339, in train
    test_prog, place, quant_config, scope=None, for_test=True)
  File "/home/vis/duyuting/anaconda3/lib/python3.7/site-packages/paddleslim-1.0.0-py3.7.egg/paddleslim/quant/quanter.py", line 132, in quant_aware
NameError: name '_logger' is not defined
环境是paddle1.6 paddleslim是上一个issue给的release版本 我去quanter.py去看了一下确实对_logger没有定义？是有bug？

**Comment by slf12** [comment]
https://github.com/PaddlePaddle/PaddleSlim/blob/release/1.0.0/paddleslim/quant/quanter.py#L30 _logger有定义，另外，使用量化功能需要paddle1.7

**Comment by Cristhine** [comment]
> https://github.com/PaddlePaddle/PaddleSlim/blob/release/1.0.0/paddleslim/quant/quanter.py#L30 _logger有定义，另外，使用量化功能需要paddle1.7

在线量化也必须是paddle1.7嘛？我看上一个issue给的paddleslim有现在量化aware功能

**Comment by slf12** [comment]
> > https://github.com/PaddlePaddle/PaddleSlim/blob/release/1.0.0/paddleslim/quant/quanter.py#L30 _logger有定义，另外，使用量化功能需要paddle1.7
> 
> 在线量化也必须是paddle1.7嘛？我看上一个issue给的paddleslim有现在量化aware功能
> 
> 在线量化功能是修改了一些输入参数，比如将量化的op设置为用户可设置的参数，paddle 1.7已可以使用.
> 
> 您用的应该是paddleslim 0.1.0，我看了下确实没有定义，可以将https://github.com/PaddlePaddle/PaddleSlim/blob/release/1.0.0/paddleslim/quant/quanter.py#L30 这个定义加在quanter.py里

不好意思，网络比较慢，点错按钮了

在线量化功能是修改了一些输入参数，比如将量化的op设置为用户可设置的参数，paddle 1.7已可以使用.

您用的应该是paddleslim 0.1.0，我看了下确实没有定义，可以将https://github.com/PaddlePaddle/PaddleSlim/blob/release/1.0.0/paddleslim/quant/quanter.py#L30 这个定义加在quanter.py里

**Comment by Cristhine** [comment]
> > > https://github.com/PaddlePaddle/PaddleSlim/blob/release/1.0.0/paddleslim/quant/quanter.py#L30 _logger有定义，另外，使用量化功能需要paddle1.7
> > 
> > 
> > 在线量化也必须是paddle1.7嘛？我看上一个issue给的paddleslim有现在量化aware功能
> > 在线量化功能是修改了一些输入参数，比如将量化的op设置为用户可设置的参数，paddle 1.7已可以使用.
> > 您用的应该是paddleslim 0.1.0，我看了下确实没有定义，可以将https://github.com/PaddlePaddle/PaddleSlim/blob/release/1.0.0/paddleslim/quant/quanter.py#L30 这个定义加在quanter.py里
> 
> 不好意思，网络比较慢，点错按钮了
> 
> 在线量化功能是修改了一些输入参数，比如将量化的op设置为用户可设置的参数，paddle 1.7已可以使用.
> 
> 您用的应该是paddleslim 0.1.0，我看了下确实没有定义，可以将https://github.com/PaddlePaddle/PaddleSlim/blob/release/1.0.0/paddleslim/quant/quanter.py#L30 这个定义加在quanter.py里

出现新的错误 Traceback (most recent call last):
  File "train.py", line 734, in <module>
    main()
  File "train.py", line 730, in main
    train(args)
  File "train.py", line 339, in train
    test_prog, place, quant_config, scope=None, for_test=True)
  File "/home/vis/duyuting/anaconda3/lib/python3.7/site-packages/paddleslim-1.0.0-py3.7.egg/paddleslim/quant/quanter.py", line 151, in quant_aware
TypeError: __init__() got an unexpected keyword argument 'quantizable_op_type'  

如果这个paddleslim无法使用量化 请问https://github.com/PaddlePaddle/models/tree/develop/PaddleSlim/quant_low_level_api目前是可以正常使用嘛？

**Comment by slf12** [comment]
https://github.com/PaddlePaddle/PaddleSlim/pull/152 使用apddle 1.6的话按照这个pr修改下吧

quantizable_op_type是paddle 1.7新增的功能，可以自定义量化的op，如果需要的化，建议将paddle升到1.7 https://pypi.org/project/paddlepaddle-gpu/ ，同时使用paddleslim 1.0.0

**Comment by Cristhine** [comment]
> #152 使用apddle 1.6的话按照这个pr修改下吧
> 
> quantizable_op_type是paddle 1.7新增的功能，可以自定义量化的op，如果需要的化，建议将paddle升到1.7 https://pypi.org/project/paddlepaddle-gpu/ ，同时使用paddleslim 1.0.0

官方paddleslim版本https://pypi.org/project/paddleslim/#files 好像有问题 用这个版本安装还是会报错quant_post不存在的问题

**Comment by slf12** [comment]
> > #152 使用apddle 1.6的话按照这个pr修改下吧
> > quantizable_op_type是paddle 1.7新增的功能，可以自定义量化的op，如果需要的化，建议将paddle升到1.7 https://pypi.org/project/paddlepaddle-gpu/ ，同时使用paddleslim 1.0.0
> 
> 官方paddleslim版本https://pypi.org/project/paddleslim/#files 好像有问题 用这个版本安装还是会报错quant_post不存在的问题

这个文件上传比较久了，今天的修改里面肯定是没有的，建议源码安装，clone paddleslim, 在release 0.1.0分支中运行python setup.py install安装

**Comment by Cristhine** [comment]
> > > #152 使用apddle 1.6的话按照这个pr修改下吧
> > > quantizable_op_type是paddle 1.7新增的功能，可以自定义量化的op，如果需要的化，建议将paddle升到1.7 https://pypi.org/project/paddlepaddle-gpu/ ，同时使用paddleslim 1.0.0
> > 
> > 
> > 官方paddleslim版本https://pypi.org/project/paddleslim/#files 好像有问题 用这个版本安装还是会报错quant_post不存在的问题
> 
> 这个文件上传比较久了，今天的修改里面肯定是没有的，建议源码安装，clone paddleslim, 在release 0.1.0分支中运行python setup.py install安装

询问一下paddleslim训练产生模型的问题：
代码如下：https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/quant_low_level_api/quantization_aware_training.py#L340
        save_checkpoint_path = os.path.join(model_save_dir,  model_name, str(pass_id))
        if not os.path.isdir(save_checkpoint_path):
            os.makedirs(save_checkpoint_path)
        save_persistable_nodes(exe, save_checkpoint_path, main_graph)

    model_path = os.path.join(model_save_dir, model_name, args.act_quant_type)
    float_path = os.path.join(model_path, 'float')
    int8_path = os.path.join(model_path, 'int8')
    mobile_path = os.path.join(model_path, 'mobile')
    if not os.path.isdir(model_path):
        os.makedirs(model_path)

    # 2. Freeze the graph after training by adjusting the quantize
    # operators' order for the inference.
    freeze_pass = QuantizationFreezePass(
        scope=fluid.global_scope(),
        place=place,
        weight_quantize_type=weight_quant_type)
    freeze_pass.apply(test_graph)
    server_program = test_graph.to_program()
    fluid.io.save_inference_model(
        dirname=float_path,
        feeded_var_names=[image.name],
        target_vars=[out], executor=exe,
        main_program=server_program)
slim模型会产生三种类型的模型，一个是正常训练过程中产生的例如 save_persistable_nodes，一个是最后一个epoch模型转化为float目录下模型 一个是转化为int8目录下模型，请问三者的区别，按照我的理解是save_persistable_nodes产生的正常不做量化的float32模型，float目录下是量化后flaoat存储格式的模型 int8是int8存储格式模型，请问这个理解正确嘛？

**Comment by slf12** [comment]
> > > > #152 使用apddle 1.6的话按照这个pr修改下吧
> > > > quantizable_op_type是paddle 1.7新增的功能，可以自定义量化的op，如果需要的化，建议将paddle升到1.7 https://pypi.org/project/paddlepaddle-gpu/ ，同时使用paddleslim 1.0.0
> > > 
> > > 
> > > 官方paddleslim版本https://pypi.org/project/paddleslim/#files 好像有问题 用这个版本安装还是会报错quant_post不存在的问题
> > 
> > 
> > 这个文件上传比较久了，今天的修改里面肯定是没有的，建议源码安装，clone paddleslim, 在release 0.1.0分支中运行python setup.py install安装
> 
> 询问一下paddleslim训练产生模型的问题：
> 代码如下：https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/quant_low_level_api/quantization_aware_training.py#L340
> save_checkpoint_path = os.path.join(model_save_dir, model_name, str(pass_id))
> if not os.path.isdir(save_checkpoint_path):
> os.makedirs(save_checkpoint_path)
> save_persistable_nodes(exe, save_checkpoint_path, main_graph)
> 
> ```
> model_path = os.path.join(model_save_dir, model_name, args.act_quant_type)
> float_path = os.path.join(model_path, 'float')
> int8_path = os.path.join(model_path, 'int8')
> mobile_path = os.path.join(model_path, 'mobile')
> if not os.path.isdir(model_path):
>     os.makedirs(model_path)
> 
> # 2. Freeze the graph after training by adjusting the quantize
> # operators' order for the inference.
> freeze_pass = QuantizationFreezePass(
>     scope=fluid.global_scope(),
>     place=place,
>     weight_quantize_type=weight_quant_type)
> freeze_pass.apply(test_graph)
> server_program = test_graph.to_program()
> fluid.io.save_inference_model(
>     dirname=float_path,
>     feeded_var_names=[image.name],
>     target_vars=[out], executor=exe,
>     main_program=server_program)
> ```
> 
> slim模型会产生三种类型的模型，一个是正常训练过程中产生的例如 save_persistable_nodes，一个是最后一个epoch模型转化为float目录下模型 一个是转化为int8目录下模型，请问三者的区别，按照我的理解是save_persistable_nodes产生的正常不做量化的float32模型，float目录下是量化后flaoat存储格式的模型 int8是int8存储格式模型，请问这个理解正确嘛？

https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/quant_low_level_api/quantization_aware_training.md#1-%E9%87%8F%E5%8C%96%E8%AE%AD%E7%BB%83low-level-apis%E4%BB%8B%E7%BB%8D . 麻烦看下低级api介绍吧，这里面解释了量化api做的事情

**Comment by Cristhine** [comment]
@slf12 在线量化产生的float模型进行离线量化报错如下：请问问题是？
Traceback (most recent call last):
  File "post_training_quantization.py", line 63, in <module>
    ptq.save_quantized_model(args.save_model_path)
  File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 216, in save_quantized_model
    params_filename="params")
  File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 1187, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 986, in prepend_feed_ops
    out = global_block.var(name)
  File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2283, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var read_file_0.tmp_0 not in this block

**Comment by slf12** [comment]
> @slf12 在线量化产生的float模型进行离线量化报错如下：请问问题是？
> Traceback (most recent call last):
> File "post_training_quantization.py", line 63, in
> ptq.save_quantized_model(args.save_model_path)
> File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 216, in save_quantized_model
> params_filename="params")
> File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 1187, in save_inference_model
> prepend_feed_ops(main_program, feeded_var_names)
> File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 986, in prepend_feed_ops
> out = global_block.var(name)
> File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2283, in var
> raise ValueError("var %s not in this block" % name)
> ValueError: var read_file_0.tmp_0 not in this block

在线量化产生的float模型已经是量化后的模型了，weight是int8范围，类型是float，不需要再离线量化了。。。。。

**Comment by Cristhine** [comment]
> > @slf12 在线量化产生的float模型进行离线量化报错如下：请问问题是？
> > Traceback (most recent call last):
> > File "post_training_quantization.py", line 63, in
> > ptq.save_quantized_model(args.save_model_path)
> > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 216, in save_quantized_model
> > params_filename="params")
> > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 1187, in save_inference_model
> > prepend_feed_ops(main_program, feeded_var_names)
> > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 986, in prepend_feed_ops
> > out = global_block.var(name)
> > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2283, in var
> > raise ValueError("var %s not in this block" % name)
> > ValueError: var read_file_0.tmp_0 not in this block
> 
> 在线量化产生的float模型已经是量化后的模型了，weight是int8范围，类型是float，不需要再离线量化了。。。。。

好吧我理解错误了 那在线量化产生的模型 可以再做trt int8量化嘛？trt int8量化是可以预测中加载的

**Comment by slf12** [comment]
> > > @slf12 在线量化产生的float模型进行离线量化报错如下：请问问题是？
> > > Traceback (most recent call last):
> > > File "post_training_quantization.py", line 63, in
> > > ptq.save_quantized_model(args.save_model_path)
> > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 216, in save_quantized_model
> > > params_filename="params")
> > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 1187, in save_inference_model
> > > prepend_feed_ops(main_program, feeded_var_names)
> > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 986, in prepend_feed_ops
> > > out = global_block.var(name)
> > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2283, in var
> > > raise ValueError("var %s not in this block" % name)
> > > ValueError: var read_file_0.tmp_0 not in this block
> > 
> > 
> > 在线量化产生的float模型已经是量化后的模型了，weight是int8范围，类型是float，不需要再离线量化了。。。。。
> 
> 好吧我理解错误了 那在线量化产生的模型 可以再做trt int8量化嘛？trt int8量化是可以预测中加载的

trt int8量化也是离线量化，本质都是把weight和激活值量化成int8

**Comment by Cristhine** [comment]
> > > > @slf12 在线量化产生的float模型进行离线量化报错如下：请问问题是？
> > > > Traceback (most recent call last):
> > > > File "post_training_quantization.py", line 63, in
> > > > ptq.save_quantized_model(args.save_model_path)
> > > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 216, in save_quantized_model
> > > > params_filename="params")
> > > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 1187, in save_inference_model
> > > > prepend_feed_ops(main_program, feeded_var_names)
> > > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 986, in prepend_feed_ops
> > > > out = global_block.var(name)
> > > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2283, in var
> > > > raise ValueError("var %s not in this block" % name)
> > > > ValueError: var read_file_0.tmp_0 not in this block
> > > 
> > > 
> > > 在线量化产生的float模型已经是量化后的模型了，weight是int8范围，类型是float，不需要再离线量化了。。。。。
> > 
> > 
> > 好吧我理解错误了 那在线量化产生的模型 可以再做trt int8量化嘛？trt int8量化是可以预测中加载的
> 
> trt int8量化也是离线量化，本质都是把weight和激活值量化成int8



> > > > @slf12 在线量化产生的float模型进行离线量化报错如下：请问问题是？
> > > > Traceback (most recent call last):
> > > > File "post_training_quantization.py", line 63, in
> > > > ptq.save_quantized_model(args.save_model_path)
> > > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 216, in save_quantized_model
> > > > params_filename="params")
> > > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 1187, in save_inference_model
> > > > prepend_feed_ops(main_program, feeded_var_names)
> > > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 986, in prepend_feed_ops
> > > > out = global_block.var(name)
> > > > File "/home/vis/yuanyuchen/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2283, in var
> > > > raise ValueError("var %s not in this block" % name)
> > > > ValueError: var read_file_0.tmp_0 not in this block
> > > 
> > > 
> > > 在线量化产生的float模型已经是量化后的模型了，weight是int8范围，类型是float，不需要再离线量化了。。。。。
> > 
> > 
> > 好吧我理解错误了 那在线量化产生的模型 可以再做trt int8量化嘛？trt int8量化是可以预测中加载的
> 
> trt int8量化也是离线量化，本质都是把weight和激活值量化成int8

是这个样子没错 但是正常的float32模型转trt int8模型会产生掉点 如果是在线量化后的flaot模型 本身就是int8值的范围 再经过trt int8模型激活成真正的int8模型 这个过程总归是不怎么掉点的吧

**Comment by slf12** [comment]
> 是这个样子没错 但是正常的float32模型转trt int8模型会产生掉点 如果是在线量化后的flaot模型 本身就是int8值的范围 再经过trt int8模型激活成真正的int8模型 这个过程总归是不怎么掉点的吧

你说的trt int8如果是这个
![image](https://user-images.githubusercontent.com/8036226/75412187-b367a980-595c-11ea-8da1-8f6d23d746e2.png)
那就是将量化后的数据再量化一次，如果想知道的是量化后的模型怎么使用trt加载预测来加速，可以咨询预测库的同学。
