### ISSUE TITLE
请问有没有针对语音识别的模型压缩方案或规划？？

### ISSUE THREAD

**Issue by lvchigo** [PaddlePaddle/PaddleSlim#1511]
- 如题；有没有针对语音识别的模型压缩方案、或规划？？
- 语音识别框架，例如wenet，kaldi等；

**Comment by ceci3** [comment]
有计划哈~ Q4会先针对PaddleSpeech的一两个模型去做压缩

**Comment by leiqing1** [comment]
@lvchigo 我们最近正在筹备Speech模型的压缩，如有需要可以加我微信详细沟通：18813190139
