### ISSUE TITLE
调用autocompress的非结构化剪枝工具后模型参数文件大小不发生变化

### ISSUE THREAD

**Issue by moonlightian** [PaddlePaddle/PaddleSlim#1521]
请问autocompress的非结构化剪枝是只对模型的参数做置零处理，其实并不改变模型结构吗？发现剪枝前后的模型参数文件model.pdiparams并未发生改变

**Comment by ceci3** [comment]
是的，模型结构没有改变，是参数里的部分参数置零，所以pdiparams大小不发生变化
