### ISSUE TITLE
yolov5s自动压缩后的pdparems权重能保存成动态的batch吗

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleSlim#1526]
我用ylov5s onnx自动压缩生成pdprarms文件，但是netron打开是1x3x640x640怎么保存成动态的batch -1x3x640x640

**Comment by ceci3** [comment]
在 https://github.com/PaddlePaddle/PaddleSlim/issues/1525 进行回复

**Comment by ceci3** [comment]
参考：https://github.com/PaddlePaddle/PaddleSlim/issues/1525
