### ISSUE TITLE
使用自动压缩工具prune_dis对模型进行减枝模型参数变大

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/PaddleSlim#1539]
padddleslim使用的develop版本
paddle版本是paddle2.4rc0
自动化压缩使用的是PaddleSlim-develop/example/auto_compression/image_classification/run.py
配置文件是PaddleSlim-develop/example/auto_compression/image_classification/configs/MobileNetV3_large_x1_0/prune_dis.yaml

对分类模型的减枝，执行命令python run.py后，**模型参数大小变大了**。

原始模型参数：
![image](https://user-images.githubusercontent.com/36955510/203250784-258fbfaf-1d50-4f7e-8624-21041cae5b77.png)
模型减枝后模型参数：
![image](https://user-images.githubusercontent.com/36955510/203250890-bb05fead-5def-446b-a5e7-1ce2bb01cbda.png)

**Comment by ceci3** [comment]
您好，可以把剪枝后的模型参数文件发我们看下嘛？

**Comment by LiquorPerfect** [comment]
> 

![image](https://user-images.githubusercontent.com/36955510/203456042-709ee080-0221-4d63-a4b3-928b05eae266.png)
模型没用减枝，同时好像把权重也再模型pdmodel中

**Comment by ceci3** [comment]
好的，我复现一下看看哈

**Comment by ceci3** [comment]
你好，这个配置是非结构化稀疏的配置，mask矩阵也保存下来了，所以参数增加了一倍，这个我们修复下

**Comment by ceci3** [comment]
修复pr：https://github.com/PaddlePaddle/PaddleSlim/pull/1548

**Comment by LiquorPerfect** [comment]
> 修复pr：#1548
还是没用修复好呀，一样的问题。
![image](https://user-images.githubusercontent.com/36955510/203932082-581033c2-e357-4296-863b-486ef81dfcd9.png)
上图左边是最新的develop，右边是我本地修改的。
![image](https://user-images.githubusercontent.com/36955510/203933210-f7b8b330-47e3-436a-bd91-a15cd9bab725.png)

**Comment by ceci3** [comment]
安装最新的paddleslim，或者2.4.0的slim试下
