### ISSUE TITLE
采用官方提供的量化后模型，精度很低

### ISSUE THREAD

**Issue by jiaerwang0328** [PaddlePaddle/PaddleSlim#1541]
从这里下载的模型
![选区_159](https://user-images.githubusercontent.com/38750407/203253602-0ea75165-e5b4-41d7-8733-d58cf0f05196.jpg)
在post_training_quantization/pytorcho_series目录下执行 python eval.py --config=./configs/yolov7_ptq.yaml命令
配置文件为：
![选区_161](https://user-images.githubusercontent.com/38750407/203254262-77e76b5f-d804-4251-bf30-0fc414cc482a.jpg)

得到精度如下
![选区_160](https://user-images.githubusercontent.com/38750407/203253803-0b9f95e9-868c-4a67-9b48-ee022ae05f4d.jpg)

**Comment by ceci3** [comment]
这个模型需要放到实际的推理环境下去测试精度，使用 暂时不支持直接使用eval.py去测试，可以使用https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/pytorch_yolo_series/paddle_inference_eval.py 这个脚本测试哈

**Comment by yghstill** [comment]
@jiaerwang0328 请直接使用https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/pytorch_yolo_series/paddle_inference_eval.py 脚本测试精度吧。
目前配置文件中onnx_format=True时默认导出的是全量化的模型，使用fake的测试脚本eval.py测试精度不准确，可以直接使用paddle Inference或者TRT脚本在真实预测库下测试精度。

**Comment by jiaerwang0328** [comment]
> 这个模型需要放到实际的推理环境下去测试精度，使用 暂时不支持直接使用eval.py去测试，可以使用https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/pytorch_yolo_series/paddle_inference_eval.py 这个脚本测试哈

感谢回复！！！，运行[这个](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/pytorch_yolo_series/paddle_inference_eval.py)脚本，python paddle_inference_eval.py --model_path=output --image_file=images/000000570688.jpg --use_trt=True --precision=int8  报错：
环境：paddlepaddle=2.3.2,paddleslim==2.3.2,cuda 11.1
![选区_162](https://user-images.githubusercontent.com/38750407/203265405-ab58c74e-67fa-4193-8012-8674268913cb.jpg)

**Comment by ceci3** [comment]
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/pytorch_yolo_series#4%E9%A2%84%E6%B5%8B%E9%83%A8%E7%BD%B2
可以根据预测部署流程来，这个报错是因为安装的不是带有trt的paddle 推理库
