### ISSUE TITLE
请问，语音合成声学模型，能否paddleslim进行量化呢？模型fastspeech2

### ISSUE THREAD

**Issue by liroda** [PaddlePaddle/PaddleSlim#1561]

**Comment by yghstill** [comment]
@liroda 理论上是支持的，但fastspeech2模型目前还没尝试过量化。

**Comment by liroda** [comment]
请问这块建议使用哪种量化方式比较好呢？

**Comment by leiqing1** [comment]
> 请问这块建议使用哪种量化方式比较好呢？

请问你压缩后是在GPU上部署还是其他什么端侧芯片上部署？

**Comment by yghstill** [comment]
@liroda 可以试下静态离线量化，fastspeech2的模型正在支持中，有最新demo会及时发布出来。

**Comment by liroda** [comment]
在GPU上部署，期待啊

**Comment by yt605155624** [comment]
@liroda 参考：https://github.com/PaddlePaddle/PaddleSpeech/pull/2729

**Comment by liroda** [comment]
厉害，请问paddleslim是2.4.0，搭配的paddle 是什么版本呢？

**Comment by yt605155624** [comment]
搭配的是个未合入的 develop
by the way，现在即使能压缩，但是推理会失败，所以等我们弄好再通知你吧




原湉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSlim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月12日(星期一) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSlim] 请问，语音合成声学模型，能否paddleslim进行量化呢？模型fastspeech2 (Issue #1561)





 
厉害，请问paddleslim是2.4.0，搭配的paddle 是什么版本呢？
