### ISSUE TITLE
自动压缩c++部署，trt_run不管用哪个run_mode速度都都一样？

### ISSUE THREAD

**Issue by alfheim1993** [PaddlePaddle/PaddleSlim#1562]

**Comment by alfheim1993** [comment]
./build/trt_run --arch YOLOv7 --model_file ../yolov7_tiny_quant/model.pdmodel --params_file ../yolov7_tiny_quant/model.pdiparams --run_mode=trt_int8 --trt_min_subgraph_size 100

I1128 08:41:12.912881  3316 trt_run.cc:101] [trt_int8 bs-1 ] run avg time is 15.4254 ms

./build/trt_run --arch YOLOv7 --model_file ../yolov7_tiny_quant/model.pdmodel --params_file ../yolov7_tiny_quant/model.pdiparams --run_mode=trt_fp32 --trt_min_subgraph_size 100

I1128 08:41:46.140003  3321 trt_run.cc:101] [trt_fp32 bs-1 ] run avg time is 15.2457 ms

**Comment by yghstill** [comment]
@alfheim1993 trt_min_subgraph_size设置的太大了，设置成3就可以，不然会导致速度慢特别多。并且trt_fp32模式下，需要加载非量化的模型，否则算子融合等会有问题。

**Comment by alfheim1993** [comment]
感谢回复，我之所以设置成100的原因是设成3的时候模型推理会报错，错误如下
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input [fill_constant_5.tmp_0] shape of trt subgraph is [1].it's not supported by trt so far
  [Hint: Expected shape.size() != 1UL, but received shape.size():1 == 1UL:1.] (at /paddle/paddle/fluid/inference/tensorrt/engine.h:141)


> @alfheim1993 trt_min_subgraph_size设置的太大了，设置成3就可以，不然会导致速度慢特别多。并且trt_fp32模式下，需要加载非量化的模型，否则算子融合等会有问题。
