### ISSUE TITLE
YOLOv5s量化后转换会onnx报错

### ISSUE THREAD

**Issue by litao-zhx** [PaddlePaddle/PaddleSlim#1565]
在用paddleslim对YOLOv5s进行ACT压缩后，转换回ONNX时报错如下：
![image](https://user-images.githubusercontent.com/76981650/204718870-fbb00552-1486-49bd-8579-3737bdbdcb1e.png)
报错上看，是paddle2onnx不支持量化后的模型，是这样吗？

**Comment by www7890** [comment]
我也遇到一樣的狀況，我用的是yolov7 我自己訓練的模型，轉回onnx時也遇到一樣的錯誤

**Comment by yghstill** [comment]
@www7890 @litao-zhx 使用的是自动压缩工具吗？将onnx_format设为True。https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/pytorch_yolo_series/configs/yolov5s_qat_dis.yaml#L16

**Comment by www7890** [comment]
> @www7890 @litao-zhx 使用的是自动压缩工具吗？将onnx_format设为True。https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/pytorch_yolo_series/configs/yolov5s_qat_dis.yaml#L16

我已經成功轉好模型了，正在嘗試各種不同的調參策略，謝謝
