### ISSUE TITLE
量化模型转onnx报错

### ISSUE THREAD

**Issue by backtime92** [PaddlePaddle/PaddleSlim#1568]
paddleslim 版本是2.4.0RC，paddlepaddle版本也是2.4.0RC，paddleslim版本是1.0.0RC，下图是export模型时配置的参数
![image](https://user-images.githubusercontent.com/29878249/205034219-ed4a8a3e-3fff-40de-a010-f10b26215d97.png)
设置了onnx_format=True，但是paddle2onnx时还是报错，如下图
![image](https://user-images.githubusercontent.com/29878249/205034438-fda4b2f0-2b58-4079-adff-83fcb6fc930e.png)

**Comment by yghstill** [comment]
@backtime92 将Paddleslim更新至2.4.0再试下
