### ISSUE TITLE
使用官方demo对yoloe模型进行离线量化失败

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleSlim#1569]
![image](https://user-images.githubusercontent.com/102579571/205203907-8d740a37-2de1-45d3-8626-1178dd81c47c.png)
![image](https://user-images.githubusercontent.com/102579571/205204002-e8d5b462-1167-44a1-bd39-e392fbfad74f.png)
命令如下
![image](https://user-images.githubusercontent.com/102579571/205204071-e604d565-22e6-4795-80d2-fc302a85d4af.png)

**Comment by yghstill** [comment]
@lilianjie111111 使用这个demo再试下吧：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/full_quantization/ppyoloe
或者直接推荐你使用自动化压缩工具产出PPYOLOE量化模型：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/detection
