### ISSUE TITLE
离线量化yoloe模型速度不增反降

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleSlim#1570]
量化前
![image](https://user-images.githubusercontent.com/102579571/205223420-64a2db8f-06f1-4b7d-87c3-89595eb76068.png)
量化后
![image](https://user-images.githubusercontent.com/102579571/205223455-9dedbf9a-06fd-4144-9607-872d2002f0e5.png)

使用的是这个demo
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/post_training_quantization/detection#%E7%A6%BB%E7%BA%BF%E9%87%8F%E5%8C%96%E6%B5%81%E7%A8%8B

**Comment by yghstill** [comment]
@lilianjie111111 PPYOLOE的模型包含nms吗，看Inference time是264vs260，但也不符预期，run_mode是TRT吗？可能是nms没进trt，这个修复过。Paddle Inference测试时的PaddlePaddle版本是多少？更新到2.4再试下呢

**Comment by laoda1112222** [comment]
> @lilianjie111111 PPYOLOE的模型包含nms吗，看Inference time是264vs260，但也不符预期，run_mode是TRT吗？可能是nms没进trt，这个修复过。Paddle Inference测试时的PaddlePaddle版本是多少？更新到2.4再试下呢
cpu推理，不带nms

**Comment by lilianjie111111** [comment]
> @lilianjie111111 PPYOLOE的模型包含nms吗，看Inference time是264vs260，但也不符预期，run_mode是TRT吗？可能是nms没进trt，这个修复过。Paddle Inference测试时的PaddlePaddle版本是多少？更新到2.4再试下呢

您好，感谢答复，没有nms，cpu不支持么，paddlepaddle2.4.0,paddleslim,2.4.0

**Comment by L-lei** [comment]
是否对量化训练后的模型使用过量化转换优化脚本?https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/performance_improving/quantization.html
