### ISSUE TITLE
yoloe静态离线量化问题，使用demo如下所示。

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleSlim#1572]
![image](https://user-images.githubusercontent.com/102579571/205232923-400c4310-df05-4722-9eaa-5cfbf4c7b37b.png)
配置文件如下所示
![image](https://user-images.githubusercontent.com/102579571/205233110-5204561c-89f7-4103-b97b-a909c9d616a5.png)

**Comment by yghstill** [comment]
@lilianjie111111  因为你是VOC数据集，所以需要在evalreader中加入collate_batch: false
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/detection/configs/ssd_reader.yml#L30
或者改为batch_size=1
