### ISSUE TITLE
paddleslim支持mbart模型量化吗？

### ISSUE THREAD

**Issue by Amy234543** [PaddlePaddle/PaddleSlim#1577]

**Comment by yghstill** [comment]
目前没有开放mbart模型的量化demo，可以基于现有的demo改造下进行量化，比如：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant_post
或者：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/nlp
