### ISSUE TITLE
带lstm的crnn模型是不支持int8量化吗

### ISSUE THREAD

**Issue by zuowanbushiwo** [PaddlePaddle/PaddleSlim#1583]
在语音增强方向上这个网络效果还可以，也有很多变种，但是基本结构如下：
![image](https://user-images.githubusercontent.com/3354428/206599922-29ef13ce-1576-49ac-8582-e572704b4f70.png)
![image](https://user-images.githubusercontent.com/3354428/206600323-8d0e51f6-a909-4475-9c4d-1dfba0d30019.png)

**Comment by ceci3** [comment]
可以量化，可以试下离线量化

**Comment by zuowanbushiwo** [comment]
@ceci3 感谢，请问有看到相关的例子吗？对这部分还不是很熟悉。

**Comment by ceci3** [comment]
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/quant/quant_post/quant_post.py
可以参考这个示例，语音的示例可以关注下PaddleSpeech，近期应该会提交相关示例

**Comment by zuowanbushiwo** [comment]
谢谢，我关注PaddleSpeech
