### ISSUE TITLE
ACT tools onnx output with different opset version

### ISSUE THREAD

**Issue by www7890** [PaddlePaddle/PaddleSlim#1584]
Hi, 
I did success to use ACT tools for model pruning and quantization. 
And I want to output  model with different opset version onnx model, because I need to deploy model on different platform
Is there anyway to do it? Thanks

**Comment by zzjjay** [comment]
you can use this api

**Comment by zzjjay** [comment]
You can use this api to transform the model with different opset version.
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/paddleslim/common/load_model.py#L212

**Comment by www7890** [comment]
> You can use this api to transform the model with different opset version. https://github.com/PaddlePaddle/PaddleSlim/blob/develop/paddleslim/common/load_model.py#L212

Thanks! it works!
