### ISSUE TITLE
压缩模型训练报错

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleSlim#1589]
使用这样的命令：
![image](https://user-images.githubusercontent.com/99952437/207415833-0e7a4396-09f3-4e28-8144-6463c53a585a.png)

会报这样的错误：
![image](https://user-images.githubusercontent.com/99952437/207415750-4c76a5ac-2ec2-4c38-9369-df4bb3a904c6.png)

如果install会：
![image](https://user-images.githubusercontent.com/99952437/207415709-d641ba18-0c75-4e10-af98-a162ba6abd5e.png)

请问该怎么解决？

**Comment by ceci3** [comment]
安装下最新的ppdet试下？
