### ISSUE TITLE
自动压缩工具报错

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleSlim#1593]
报错如下：
![image](https://user-images.githubusercontent.com/102579571/207583801-31225b68-47eb-44bb-82a0-99fde4b69fe2.png)

![image](https://user-images.githubusercontent.com/102579571/207583501-03cfbd45-09b8-48eb-bc6d-884b3f69c5ec.png)
数据集如下：
![image](https://user-images.githubusercontent.com/102579571/207583575-f15891d6-b293-489e-98c9-8207dde471da.png)
demo如下：
![image](https://user-images.githubusercontent.com/102579571/207583727-aa600b60-9e86-439e-9071-af06eb37cae4.png)

**Comment by ceci3** [comment]
看起来是数据格式不对，另外要压缩的ppyolo检测模型的话，dataloader需要用目标检测的dataloader，我看你代码里用的是分类的dataloader。检测dataloader可以用：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/detection/run.py#L139
