### ISSUE TITLE
X2Paddle转换ONNX模型使用paddleSlim中ACT一直报错

### ISSUE THREAD

**Issue by fengyanWang** [PaddlePaddle/PaddleSlim#1600]
paddleSlim:2.3.3
X2Paddle:2.3.1
模型：yolo5 lite

使用X2Paddle将pytorch导出的ONNX模型转换为paddle的inference模型，然后使用paddleSlim中的ACT进行量化，然后一直报如下错误：
KeyError: 'x2paddle_images'（通过netron工具查看模型的输入节点名称就是x2paddle_images）

注：
1.ACT配置项参考的是picodet_s_qat_dis.yaml文件
2.数据路径没有问题

![image](https://user-images.githubusercontent.com/36984088/208800253-d0253760-bf6f-45d4-80a2-d6d21c7d1179.png)

**Comment by zzjjay** [comment]
能发下完整的报错截图吗？
