### ISSUE TITLE
AutoCompression压缩后，推理变慢很多

### ISSUE THREAD

**Issue by cold-eye** [PaddlePaddle/PaddleSlim#1604]
做了ERNIE 3.0 的medium和xbase版本的压缩，速度都变慢很多(10倍以上那种)，paddle 2.3.1   paddleslim 2.3.0

**Comment by ceci3** [comment]
请问下部署环境是什么？

**Comment by cold-eye** [comment]
- 硬件：NVIDIA A100 单卡
- 软件：CUDA 11.2, cuDNN 8.1
- 测试配置：batch_size: 32, max_seq_len: 128

**Comment by ceci3** [comment]
是使用的是带TRT的Paddle Inference进行部署的嘛？https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/nlp#5-%E9%A2%84%E6%B5%8B%E9%83%A8%E7%BD%B2

**Comment by cold-eye** [comment]
没用TRT

这样的
!python paddle_inference_eval.py \
      --model_path=compressed \
      --model_filename=infer.pdmodel \
      --params_filename=infer.pdiparams \
      --metric='acc' \
      --test='test' \
      --precision=int8 \
      --use_mkldnn=True

**Comment by ceci3** [comment]
请问下是什么模型，有些模型在MKLDNN上的加速确实不行

**Comment by cold-eye** [comment]
> 请问下是什么模型，有些模型在MKLDNN上的加速确实不行

ERNIE 3.0 的medium做了文本分类，paddle 2.3.1 paddleslim 2.3.0

不使用MKLDNN，也无法加速。

剪枝和量化后，有些参数会使推理时间加倍，有些参数就是推理时间不变

**Comment by cold-eye** [comment]
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/nlp
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/48782821/215659098-fb168629-d24f-462b-9355-2c8383d421b7.png">

可以告知这个实验中 ERNIE 3.0-Medium 的剪枝+量化训练的参数设置吗？以及yaml文件。

我这边做的实验，最终都无法实现推理加速以及文件变小
