### ISSUE TITLE
报：could not load library libcudnn_cnn_train.so.8. 

### ISSUE THREAD

**Issue by Ledgero** [PaddlePaddle/PaddleSlim#1619]
版本：
cuda :11.3 cudnn:8.6.0 (对应cuda11.x)   python :3.8  paddlepaddle-gpu: 2.4.1.post112  paddleslim:2.4.1
系统：linux

**运行run.py过程中报如下错误：**
Could not load library libcudnn_cnn_train.so.8.     Error: /home/zjl/anaconda3/envs/paddle/bin/../lib/libcudnn_ops_train.so.8 :undefined symbol: _ZN5cudnn3ops26JoinInternalPriorityStreamEP12cudnnContexti , version libcudnn_ops_infer.so.8

t Error Message Summary:
FatalError:`Process abort signal' is detected by the operating system.
[TimeInfo: *** Aborted at 1672813800 (unix time)try "date -d @1672813000"  if you are using SNU date *][SignalInfo:*** SIGABRT (@Bx3e8000018c5)received by PID 6341 (TID 0x7f0f11fff780) from PID 6341 ***]
已放弃〔核心已转储）

**Comment by wanghaoshuang** [comment]
## 这个错误和PaddleSlim无关，应该是cudnn环境配置的问题。

根据log提示，应该是libcudnn_ops_train.so.8依赖的某个动态库的版本不对。

通过以下命令确认/libcudnn_ops_train.so.8的引用：
```
strings  /home/zjl/anaconda3/envs/paddle/bin/../lib/libcudnn_ops_train.so.8 | grep "JoinInternalPriorityStream"
```

您可以使用以下命令查看libcudnn_ops_train.so.8依赖的动态库：
```
ldd /home/zjl/anaconda3/envs/paddle/bin/../lib/libcudnn_ops_train.so.8

# 在我环境下，发现依赖libcudnn_ops_infer.so
# libcudnn_ops_infer.so.8 => /root/envs/cuda-10.2/lib64/libcudnn_ops_infer.so.8
```

然后看一下libcudnn_ops_infer.so.8中是否有报含关键字『JoinInternalPriorityStream』的符号定义：

```
strings  /root/envs/cuda-10.2/lib64/libcudnn_ops_infer.so.8 | grep "JoinInternalPriorityStream"
# 我这里输出 _ZN5cudnn3ops26JoinInternalPriorityStreamEP12cudnnContexti
```
如果libcudnn_ops_infer.so没有上述定义，那有可能是其版本不对。

在你的环境下，找到正确的libcudnn_ops_infer.so，并将其路径添加到LD_LIBRARY_PATH.
然后再check `ldd /home/zjl/anaconda3/envs/paddle/bin/../lib/libcudnn_ops_train.so.8`, 是否找到正确的libcudnn_ops_infer.so

**Comment by Ledgero** [comment]
> ldd /home/zjl/anaconda3/envs/paddle/bin/../lib/libcudnn_ops_train.so.8

> 输出：

>      linux-vdso.so.1 (0x00007ffcc79ba000)
	libcudnn_ops_infer.so.8 => /home/zjl/anaconda3/envs/paddle/bin/../lib/./libcudnn_ops_infer.so.8 (0x00007fcf81926000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fcf81905000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcf818e2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcf818dc000)
	libstdc++.so.6 => /home/zjl/anaconda3/envs/paddle/bin/../lib/./libstdc++.so.6 (0x00007fcf81728000)
	libgcc_s.so.1 => /home/zjl/anaconda3/envs/paddle/bin/../lib/./libgcc_s.so.1 (0x00007fcf8170d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcf8151b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcf96ead000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcf813cc000)
难以判断哪个是，我查询了libcudnn_ops_infer.so.8
> strings  /home/zjl/anaconda3/envs/paddle/bin/../lib/libcudnn_ops_infer.so.8 | grep "JoinInternalPriorityStream"

输出：
> ZN5cudnn3ops26JoinInternalPriorityStreamEP12cudnnContexti    
> #含有关键字。

**Comment by Beau-Chen** [comment]
麻烦问一下最后怎么解决的呀
