### ISSUE TITLE
目前有LSTM量化的demo吗？

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/PaddleSlim#1624]
在repo中没有找到lstm量化相关的demo，想问下目前paddleslim支持lstm量化吗？

**Comment by ceci3** [comment]
暂时没有，可以参考下分类的Demo：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/quant/quant_post/quant_post.py#L71
请问下同学是在什么场景下会用到LSTM的量化呢~

**Comment by littletomatodonkey** [comment]
好的，谢谢~主要是一些时序应用场景
