### ISSUE TITLE
量化训练以后导出int8模型，推理时报错：Operator (quantize) does not have kernel for {data_type[float]; data_layout[Undefined(AnyLayout)]; place[Place(gpu:0)]; library_type[PLAIN]}.

### ISSUE THREAD

**Issue by before31** [PaddlePaddle/PaddleSlim#1628]
# 环境：
- Tesla V100 [NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2]
- paddle: paddlepaddle-gpu               2.4.0.post112
- paddleslim: 2.4.0
- paddleocr:2.6.0

# 问题重现步骤
1. 采用ppocr提供的pgnet算法，使用自己的标注数据进行训练，训练脚本: [quant.py](https://github.com/PaddlePaddle/PaddleOCR/blob/303e81b0b44b092ee0d7c7765d46a0952a76d71c/deploy/slim/quantization/quant.py)
2. 训练完成后，导出成inference模型，导出用的脚本：[export_model.py](https://github.com/PaddlePaddle/PaddleOCR/blob/303e81b0b44b092ee0d7c7765d46a0952a76d71c/deploy/slim/quantization/export_model.py)，得到了inference.pdiparams、inference.pdiparams.info、inference.pdmodel 3个文件
3. 再转换成int8类型，转换用的脚本：[save_quant_model.py](https://github.com/PaddlePaddle/Paddle/blob/3fa7a736e32508e797616b6344d97814c37d3ff8/python/paddle/fluid/contrib/slim/tests/save_quant_model.py)，得到了inference.pdiparams、inference.pdmodel两个文件（指定了save_model_filename和save_params_filename参数，不然会是一堆分散的文件）
4. 推理时报错，推理代码：[predict_e2e.py](https://github.com/PaddlePaddle/PaddleOCR/blob/303e81b0b44b092ee0d7c7765d46a0952a76d71c/tools/infer/predict_e2e.py)

```
Traceback (most recent call last):
  File "tools/infer/predict_e2e.py", line 157, in <module>
    points, strs, elapse = text_detector(img)
  File "tools/infer/predict_e2e.py", line 120, in __call__
    self.predictor.run()
RuntimeError: (NotFound) Operator (quantize) does not have kernel for {data_type[float]; data_layout[Undefined(AnyLayout)]; place[Place(gpu:0)]; library_type[PLAIN]}.
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/framework/operator.cc:2019)
  [operator < quantize > error]
```

**Comment by minghaoBD** [comment]
第三步和第二步重复了。辛苦去掉第三步看下能跑通吗？

**Comment by before31** [comment]
不好意思，我没有描述清楚。
训练环境是Tesla V100，但最后的推理环境是intel CPU。
去掉第3步，在intel CPU上是可以正常运行，但是①模型大小相较于正常训练没有变小，②推理速度相较于正常训练、导出的inference模型没有变快。
我是看的[这里](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/mkldnn_quant/README.md)说的:
> 为了部署在CPU上，我们将保存的quant模型，通过一个转化脚本，移除fake_quantize/fake_dequantize op，进行算子融合和优化并且转化为INT8模型。
脚本在官网的位置为[save_quant_model.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/static/quantization/tests/save_quant_model.py)。

还有[这里](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/FAQ/quantization_FAQ.md)说的：
>如果量化模型在x86上线，需要使用[INT8 MKL-DNN](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/static/quantization/tests)
首先对模型进行转化，可以参考[脚本](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/static/quantization/tests/save_quant_model.py)
转化之后可使用预测部署API进行加载。比如[c++ API](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_guide/inference_deployment/inference/native_infer.html)

**Comment by dongyangli-del** [comment]
我也遇到同样的问题了，只不过我是在图像分类任务上，我是用的ACT模型自动压缩工具做的，得到quant模型，结果加载时报错
NotFoundError: Operator (dequantize_linear) is not registered.

**Comment by before31** [comment]
> 我也遇到同样的问题了，只不过我是在图像分类任务上，我是用的ACT模型自动压缩工具做的，得到quant模型，结果加载时报错 NotFoundError: Operator (dequantize_linear) is not registered.

我刚开始也是尝试自己用ACT工具去自动压缩来着，但是压缩的时候直接就报错了，paddle.static.load_inference_model函数返回的feed_target_names就只有一个'x'，跟数据对不上。我就没有再继续细究了，就准备自己做量化训练，结果到最后一步了还是失败了。

**Comment by dongyangli-del** [comment]
@minghaoBD  麻烦解释一下这是怎么回事啊？是不是因为paddlex没更新，需要用paddlepaddle训练？

**Comment by minghaoBD** [comment]
> 我也遇到同样的问题了，只不过我是在图像分类任务上，我是用的ACT模型自动压缩工具做的，得到quant模型，结果加载时报错 NotFoundError: Operator (dequantize_linear) is not registered.

建议新开一个issue吧，可以具体描述下吗？模型是什么，在哪里加载的。如果有复现的链接也辛苦提供下吧。

**Comment by minghaoBD** [comment]
> > 我也遇到同样的问题了，只不过我是在图像分类任务上，我是用的ACT模型自动压缩工具做的，得到quant模型，结果加载时报错 NotFoundError: Operator (dequantize_linear) is not registered.
> 
> 我刚开始也是尝试自己用ACT工具去自动压缩来着，但是压缩的时候直接就报错了，paddle.static.load_inference_model函数返回的feed_target_names就只有一个'x'，跟数据对不上。我就没有再继续细究了，就准备自己做量化训练，结果到最后一步了还是失败了。

这个可以看下保存推理模型的步骤，inputs是如何规定的，是不是少写了。添加进去应该就行。

**Comment by minghaoBD** [comment]
> 不好意思，我没有描述清楚。 训练环境是Tesla V100，但最后的推理环境是intel CPU。 去掉第3步，在intel CPU上是可以正常运行，但是①模型大小相较于正常训练没有变小，②推理速度相较于正常训练、导出的inference模型没有变快。 我是看的[这里](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/mkldnn_quant/README.md)说的:
> 
> > 为了部署在CPU上，我们将保存的quant模型，通过一个转化脚本，移除fake_quantize/fake_dequantize op，进行算子融合和优化并且转化为INT8模型。
> > 脚本在官网的位置为[save_quant_model.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/static/quantization/tests/save_quant_model.py)。
> 
> 还有[这里](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/FAQ/quantization_FAQ.md)说的：
> 
> > 如果量化模型在x86上线，需要使用[INT8 MKL-DNN](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/static/quantization/tests)
> > 首先对模型进行转化，可以参考[脚本](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/static/quantization/tests/save_quant_model.py)
> > 转化之后可使用预测部署API进行加载。比如[c++ API](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_guide/inference_deployment/inference/native_infer.html)

这个负责同学正在看。

**Comment by before31** [comment]
> > > 我也遇到同样的问题了，只不过我是在图像分类任务上，我是用的ACT模型自动压缩工具做的，得到quant模型，结果加载时报错 NotFoundError: Operator (dequantize_linear) is not registered.
> > 
> > 
> > 我刚开始也是尝试自己用ACT工具去自动压缩来着，但是压缩的时候直接就报错了，paddle.static.load_inference_model函数返回的feed_target_names就只有一个'x'，跟数据对不上。我就没有再继续细究了，就准备自己做量化训练，结果到最后一步了还是失败了。
> 
> 这个可以看下保存推理模型的步骤，inputs是如何规定的，是不是少写了。添加进去应该就行。

不太理解您说的这句话的意思，我是用的ppocr里面现成的代码进行导出的，我刚看了一下，导出逻辑是先根据训练所用的yml配置文件构建了model，然后调用paddle.jit.to_static生成新的model，再然后调用paddle.jit.save进行保存。这里面没有什么地方可以写'x'这样的inputs，只有to_static的时候传入了一个input_spec，值是[3, -1, -1]。

![image](https://user-images.githubusercontent.com/30918844/212831749-69d03e21-26aa-4d96-b7e9-fb127b6b2b9f.png)

**Comment by zzjjay** [comment]
@before31 使用自动压缩的报错问题建议重新提交一个issue，在新issue里具体描述下问题~

**Comment by before31** [comment]
@zzjjay 已新开issue， #1638

**Comment by before31** [comment]
> > 不好意思，我没有描述清楚。 训练环境是Tesla V100，但最后的推理环境是intel CPU。 去掉第3步，在intel CPU上是可以正常运行，但是①模型大小相较于正常训练没有变小，②推理速度相较于正常训练、导出的inference模型没有变快。 我是看的[这里](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/mkldnn_quant/README.md)说的:
> > > 为了部署在CPU上，我们将保存的quant模型，通过一个转化脚本，移除fake_quantize/fake_dequantize op，进行算子融合和优化并且转化为INT8模型。
> > > 脚本在官网的位置为[save_quant_model.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/static/quantization/tests/save_quant_model.py)。
> > 
> > 
> > 还有[这里](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/FAQ/quantization_FAQ.md)说的：
> > > 如果量化模型在x86上线，需要使用[INT8 MKL-DNN](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/static/quantization/tests)
> > > 首先对模型进行转化，可以参考[脚本](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/static/quantization/tests/save_quant_model.py)
> > > 转化之后可使用预测部署API进行加载。比如[c++ API](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_guide/inference_deployment/inference/native_infer.html)
> 
> 这个负责同学正在看。

麻烦问一下，这个问题是否有进展了？

**Comment by before31** [comment]
any update? @zzjjay @minghaoBD

**Comment by yghstill** [comment]
@before31 量化时设置onnx_format=True，保存量化新格式模型，然后无需使用[save_quant_model.py](https://github.com/PaddlePaddle/Paddle/blob/3fa7a736e32508e797616b6344d97814c37d3ff8/python/paddle/fluid/contrib/slim/tests/save_quant_model.py)进行模型转换了，直接使用Paddle 2.4以上版本mkldnn部署即可，预测代码可参考https://github.com/PaddlePaddle/PaddleTest/blob/develop/inference/python_api_test/test_int8_model/test_ocr_infer.py
