### ISSUE TITLE
AssertionError: distill_node_pair config wrong, the length needs to be an even number

### ISSUE THREAD

**Issue by dongyangli-del** [PaddlePaddle/PaddleSlim#1631]
# 一. Environment

OS: Ubuntu20.04
GPU: RTX 3090
RAM: 48GB
CPU: AMD 5800x
paddle-gpu 2.4.0
paddleslim 2.4.0
paddlex2.1.0
# 二. Problem
当执行ACT的压缩代码
`export CUDA_VISIBLE_DEVICES=0
python run.py --save_dir='/home/geek/Project/cloth_check/ACT/PPLCNet_quant' --config_path='/home/geek/Project/cloth_check/PaddleSlim/PaddleSlim-develop/example/auto_compression/image_classification/configs/PPLCNet_x1_0/qat_dis.yaml'`
时，出现如下报错：

![image](https://user-images.githubusercontent.com/62006079/212520529-23e0dbfe-50b2-468c-9921-4440b031c397.png)

`AssertionError: distill_node_pair config wrong, the length needs to be an even number`
请问这是怎么回事，该怎么解决？

**Comment by zzjjay** [comment]
该问题可能是蒸馏节点设置不正确导致的。解决方法如下：

1. 可以注释掉config文件中 Distillation 的node部分，程序将自动寻找最后一个带参数节点作为蒸馏节点；
2. 或者通过使用[Netron工具](https://netron.app/) 可视化model.pdmodel模型文件，选择模型中某些层输出Tensor名称，对蒸馏节点进行配置。参考[链接](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/hyperparameter_tutorial.md#1%E8%87%AA%E5%8A%A8%E8%92%B8%E9%A6%8F%E6%95%88%E6%9E%9C%E4%B8%8D%E7%90%86%E6%83%B3%E6%80%8E%E4%B9%88%E8%87%AA%E4%B8%BB%E9%80%89%E6%8B%A9%E8%92%B8%E9%A6%8F%E8%8A%82%E7%82%B9)自行设置蒸馏节点。

**Comment by dongyangli-del** [comment]
@zzjjay 给出的建议有效，谢谢！
