### ISSUE TITLE
predictor = create_predictor(config) 报错：RuntimeError: (NotFound) Cannot find  in scope. 

### ISSUE THREAD

**Issue by xiuxiuxius** [PaddlePaddle/PaddleSlim#1642]
运行的代码和报错信息如下
![image](https://user-images.githubusercontent.com/89114157/213338538-782e7c4f-dbce-4fff-a3c2-8257fcbc1235.png)
其中，model.pdmodel和model.pdiparams都存在的
![image](https://user-images.githubusercontent.com/89114157/213338957-bec33254-30f4-40b2-9985-79f35eba6c2d.png)

**Comment by xiuxiuxius** [comment]
补充信息：
cuda：11.1
cudnn：8.0.4
显卡：RTX 3070
tensorrt：8.5.2.2
paddleSlim：2.4.1
模型：yolov5_v6.2.pt
paddle：
     --  自动压缩并导出模型：paddlepaddle_gpu-2.4.1.post112-cp38-cp38-linux_x86_64.whl
     --  TensorRT Python部署：paddlepaddle_gpu-2.3.2.post112-cp38-cp38-linux_x86_64.whl（tr8）

**Comment by yghstill** [comment]
@xiuxiuxius 请使用PaddlePaddle 2.4以上版本进行TRT部署

**Comment by xiuxiuxius** [comment]
> @xiuxiuxius 请使用PaddlePaddle 2.4以上版本进行TRT部署
@yghstill 谢谢回复，详细如下：
1. 如下图，Readme中说明，TensorRT部署需要安装paddle包，我点进链接，发现linux下python38的whl都是paddle2.3.2的，安装paddlepaddle_gpu-2.3.2.post112-cp38-cp38-linux_x86_64.whl（tr8）后，运行出现本issues的错误
![1675099516585_DCF033F7-DA1D-4131-A82D-F49B6FDDFC72](https://user-images.githubusercontent.com/89114157/215552094-824d90c6-7af1-4e82-bf68-e687abffac36.png)
![1675099554994_6F52C555-F9E8-43e0-AE3A-94F759E83FFB](https://user-images.githubusercontent.com/89114157/215552608-c60f6e4e-23b3-401b-9d91-77c066ece178.png)
2. 如果使用paddlepaddle_gpu-2.4.1.post112-cp38-cp38-linux_x86_64.whl，运行后会出现段错误，如下图，我的conda环境中安装的tensorrt是8.5的
![13cadc52e864dde7ed41fbb779bb6d73](https://user-images.githubusercontent.com/89114157/215553645-eae72214-c4e9-4aa0-9db9-1162517a7dc7.png)
![f5fdc32f5b0178e749b0089736a1cd4e](https://user-images.githubusercontent.com/89114157/215553753-b097f4fd-d5ec-452a-8013-c1a2b010a300.png)

![image](https://user-images.githubusercontent.com/89114157/215554393-750ec294-0248-4492-8f2a-929e69ab01a4.png)
