### ISSUE TITLE
自动化压缩报错

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleSlim#1643]
![_6L}T~5WK(}$~WK%~ 6HG89](https://user-images.githubusercontent.com/99952437/215256453-1316b9e5-08b0-43ea-bf28-e8681e75bd83.png)
pppyoloe+自动化压缩到997轮报这个错误是什么原因？

**Comment by yghstill** [comment]
@NwTbbetter 你导出的PPYOLOE+模型带NMS吗？报错位置在单独的NMS后处理上。

**Comment by shuaigeeed** [comment]
> ![_6L}T~5WK(}$WK% 6HG89](https://user-images.githubusercontent.com/99952437/215256453-1316b9e5-08b0-43ea-bf28-e8681e75bd83.png) pppyoloe+自动化压缩到997轮报这个错误是什么原因？

请问你解决这个问题了吗

**Comment by shuaigeeed** [comment]
我也出现这样的问题但是不知道怎么解决，是需要修改原代码码，谢谢

**Comment by truthsun22** [comment]
这种问题是因为导出的ppyoloe模型有NMS，但是超参里面include_nms: 设置为了false，应该设置为true
