### ISSUE TITLE
yolov7压缩报错，in loadRes  if 'caption' in anns[0]: IndexError: list index out of range

### ISSUE THREAD

**Issue by Hongyao98** [PaddlePaddle/PaddleSlim#1655]
按照参考文档
![image](https://user-images.githubusercontent.com/124556509/217734377-ccefe29d-c42d-4ab9-b223-0296265535b3.png)
准备好自定义数据集，然后通过example/auto_compression/pytorch_yolo_series/run.py进行yolov7模型压缩。结果出现以下错误
![image](https://user-images.githubusercontent.com/124556509/217734604-15dfd94b-0c2e-4702-a798-f34d27eda4a8.png)
经过查询issues，得到类似问题的建议 ：
1.首先可以确认环境是否正确，直接跑官方demo看能否复现readme结果。
2.其次排查下你的模型、验证集是否有问题。直接用eval.py测试下量化前的模型精度。
3.还可以只设置image_path进行量化，不评估。 然后产出的模型直接预测图片看看符合预期吗？
由于coco数据集过大未进行步骤1，但使用eval.py同样出现类似问题
![image](https://user-images.githubusercontent.com/124556509/217735151-964fe376-7d47-4cc8-8576-7cc97a1c5b99.png)
只设置image_path，则run.py可以正常运行。求帮助，谢谢。

**Comment by yghstill** [comment]
请检查下COCO数据集，上述截图是annotation文件遍历报错，如果未使用coco数据集，只使用了image_path，那么无法进行评估。
