### ISSUE TITLE
自动化压缩报错

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleSlim#1656]
请问使用自动化压缩工具对ppyoloe+模型进行压缩时，这样的报错是什么原因？
![image](https://user-images.githubusercontent.com/99952437/218299379-68dbbb4d-611b-4752-958a-1506a7a1bdb3.png)
![image](https://user-images.githubusercontent.com/99952437/218299389-50472201-bfee-499e-b44e-1ea4bfd61c90.png)

**Comment by yghstill** [comment]
@NwTbbetter 数据预处理出错，请找到ppdet安装目录，注释掉try看下具体报错信息，并检查下数据：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/data/transform/operators.py#L125
