### ISSUE TITLE
怎么使用ACT自动压缩工具对pp-yoloe-s 只检测行人的模型进行压缩？

### ISSUE THREAD

**Issue by lw-2017** [PaddlePaddle/PaddleSlim#1657]

**Comment by yghstill** [comment]
和COCO上PP-YOLOE模型压缩流程一样，参考：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/detection

**Comment by lw-2017** [comment]
> 和COCO上PP-YOLOE模型压缩流程一样，参考：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/detection

感谢回复，那是否可以不准备训练数据集来执行ACT呢
