### ISSUE TITLE
RLNAS搜索后怎么拿到token？

### ISSUE THREAD

**Issue by Michael-Fuu** [PaddlePaddle/PaddleSlim#1663]
https://paddleslim.readthedocs.io/zh_CN/latest/api_cn/static/nas/nas_api.html#rlnas
SANAS 有save_checkpoint(str|None) - 保存checkpoint的文件目录 这个参数，能够从保存的json中拿到最优模型的token；RLNAS 没有save_checkpoint参数，取而代之的是save_controller(str|None|False) ，怎么获得最优模型的token呢

**Comment by wanghaoshuang** [comment]
https://github.com/PaddlePaddle/PaddleSlim/blob/65c776de2e0d7bdd4031e50f0a54670b706362cd/paddleslim/nas/rl_nas.py#L66
构造一个RLNAS实例，并通过选项load_controller指定搜索过程中保存的`save_controller`路径.
```
rlnas = RLNAS(load_controller="your_path")
```
然后调用rlnas.tokens获得最佳的一批tokens
