### ISSUE TITLE
linux环境下运行官方量化推理demo编译报错 OrtGetApiBase

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/PaddleSlim#1670]
你好，我在测试https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/mkldnn_quant中的Intel CPU量化部署，
在最后的编译环节中，我遇到了如下问题：（python版本会说卷积算子不支持int8量化，估计是没有mkldnn支持）

```bash
cd /PATH/TO/PaddleSlim
cd demo/mkldnn_quant/
mkdir build && cd build
cmake -DPADDLE_LIB=path/to/paddle_inference_install_dir ..
make -j
```

ld过程产生了onnxruntime相关的报错，
![image](https://user-images.githubusercontent.com/96160062/221822904-9514638f-13a7-486c-abfc-fe0009e2d481.png)
![image](https://user-images.githubusercontent.com/96160062/221822936-12534395-51a9-4bd9-b740-b41d39f28f01.png)

请问我该如何排查问题？我用的预编译推离库是：
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html

版本说明	预测库(2.3.2版本)
manylinux_cpu_avx_mkl_gcc8.2	[paddle_inference.tgz](https://paddle-inference-lib.bj.bcebos.com/2.3.2/cxx_c/Linux/CPU/gcc8.2_avx_mkl/paddle_inference.tgz)

谢谢你的回复。

**Comment by sanbuphy** [comment]
经过一番尝试，我用自己编译的推理库（关闭了onnx后端）编译成功，运行后发现pool算子没有注册：
![微信图片_20230301110046](https://user-images.githubusercontent.com/96160062/222034108-73e8d303-f528-4e7b-98f0-7d7d6dbcae4e.png)

**Comment by sanbuphy** [comment]
我尝试了各种构建方案（显式打开avx等编译出推理库，然后关闭图优化，都没有任何改善，一直是报告pool2d未注册error

**Comment by sanbuphy** [comment]
![image](https://user-images.githubusercontent.com/96160062/222072075-52d2d42d-060e-496c-b884-6285d4bc0630.png)

我尝试开了全部日志后，信息如上

**Comment by wanghaoshuang** [comment]
请问，您的模型是PaddleSlim提供的示例模型吗？如果不是，是否方便不量化pool op？
看log应该是CPU inference不支持pool op的int8推理。

**Comment by sanbuphy** [comment]
> 请问，您的模型是PaddleSlim提供的示例模型吗？如果不是，是否方便不量化pool op？ 看log应该是CPU inference不支持pool op的int8推理。

你好，是的，我参考的是
https://paddleslim.readthedocs.io/zh_CN/latest/deploy/deploy_cls_model_on_x86_cpu.html
的做法，然后直接下载的量化后模型
```text
可以跳过 2.1 和 2.2, 直接下载[mobilenetv2 post-training quant model](https://paddle-inference-dist.cdn.bcebos.com/quantizaiton/quant_post_models/mobilenetv2_quant_post.tgz)以及其对应的原始的FP32模型[mobilenetv2 fp32](https://paddle-inference-dist.cdn.bcebos.com/quantizaiton/fp32_models/mobilenetv2.tgz)
```

然后根据文档需求直接save转换去掉fake算子再用C++推理，（python版本的跑不了会直接说卷积不支持int8，会不会是因为官方paddle版本没有带对应的数学库支持编译）

而且我看到这里说：
```text
quantize_op_types: 目前CPU上量化支持的算子为 depthwise_conv2d, conv2d, mul, matmul, transpose2, reshape2, pool2d, scale, concat
```
里面有pool2d

我试一试把pool2d在save过程保存fp32好了~

**Comment by sanbuphy** [comment]
> 请问，您的模型是PaddleSlim提供的示例模型吗？如果不是，是否方便不量化pool op？ 看log应该是CPU inference不支持pool op的int8推理。

你好，我发现不量化还是有点问题：
我显式指定了不量化int8的pool layer的编号
![C5683284-31A2-4c76-ABEC-D18195E54E44](https://user-images.githubusercontent.com/96160062/222082736-d414716f-5438-45a8-900f-d181431d3ba4.png)

但在日志中还是能看到：
![02F6943F-9546-4238-9E8B-862F1FBFA36D](https://user-images.githubusercontent.com/96160062/222082843-5b54f260-092c-4c0a-ae92-86337d58654c.png)

而且在c++日志中也能看到还是寻求一个int8的输入

**Comment by sanbuphy** [comment]
@wanghaoshuang  @weishengying 
hi ,然后我发现还有个神奇的问题，develop版本的才可以使用from paddle.static.quantization import Quant2Int8MkldnnPass这个功能，否则会有模块报错找不到。 GPU和CPU的develop都可以，其他稳定版不可以

其他版本的对应模块位置移到了：from paddle.fluid.contrib.slim.quantization import Quant2Int8MkldnnPass

应该在版本修复上有问题？对于最新版2.4.*的paddle，运行这个旧版本的文件才是对的，新版本slim的脚本跑不了，一直提示需要pdmodel类似格式的模型：
https://github.com/PaddlePaddle/PaddleSlim/blob/release/2.2/ce_tests/dygraph/quant/src/save_quant_model.py

否则不能跑通demo要求的int8模型去除转换
