### ISSUE TITLE
cannot import name 'in_dygraph_mode' from 'paddle.framework' 

### ISSUE THREAD

**Issue by shuaigeeed** [PaddlePaddle/PaddleSlim#1671]
![image](https://user-images.githubusercontent.com/102586285/221823130-9c2e0acf-f207-49e8-9e35-45aed8422f05.png)这里怎么解决

**Comment by wanghaoshuang** [comment]
您用的是develop版本的PaddleSlim吗？PaddleSlim develop版本需要匹配develop版本的PaddlePaddle。
您可以参考这个页面安装develop版本的PaddlePaddle： https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by sunzhaohong** [comment]
> 您用的是develop版本的PaddleSlim吗？PaddleSlim develop版本需要匹配develop版本的PaddlePaddle。 您可以参考这个页面安装develop版本的PaddlePaddle： https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
