### ISSUE TITLE
intel cpu量化部署问题

### ISSUE THREAD

**Issue by luguanren** [PaddlePaddle/PaddleSlim#1672]
尝试如下这个demo的复现，但是出现了如下的错误。
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/mkldnn_quant/
![image](https://user-images.githubusercontent.com/126534866/221836012-4735838b-962b-4df3-88f4-8b70f890569c.png)
![image](https://user-images.githubusercontent.com/126534866/221836169-d175269b-4714-460a-95cc-907b547f057c.png)
![image](https://user-images.githubusercontent.com/126534866/221836393-5f57fe88-c8a2-4ec7-b761-86bb4dfcdac5.png)
这边尝试使用参数将对应id去除以及源码中的注释但没有什么用
还是如上错误，望大佬解答！谢谢！

**Comment by wanghaoshuang** [comment]
这个应该是安装的Paddle Inference版本不对，需要安装支持MKLDNN的版本，可以参考这个教程：

https://paddle-inference.readthedocs.io/en/master/guides/x86_cpu_infer/paddle_x86_cpu_int8.html

**Comment by luguanren** [comment]
> 

这个教程并没有描述您提到的这个问题“Paddle Inference版本不对，需要安装支持MKLDNN的版本”，请问如何安装支持mkldnn的版本？
