### ISSUE TITLE
ImportError: cannot import name duplicates_everseen

### ISSUE THREAD

**Issue by z5406** [PaddlePaddle/PaddleSlim#1673]
报错：ImportError: cannot import name duplicates_everseen，请问怎么解决呀？
![image](https://user-images.githubusercontent.com/109976361/221851411-c2b3f599-2fd8-4c44-b720-3d363d933594.png)
![image](https://user-images.githubusercontent.com/109976361/221851509-612500e4-d749-4ef5-8434-6f110d9c1f5e.png)

**Comment by wanghaoshuang** [comment]
请问您用的PaddlePaddle版本和PaddleSlim版本格式多少？

**Comment by z5406** [comment]
您好，使用的PaddlePaddle和PaddleSlim版本都是2.4.0




21065326张春杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSlim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月2日(星期四) 上午9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSlim] ImportError: cannot import name duplicates_everseen (Issue #1673)





 
请问您用的PaddlePaddle版本和PaddleSlim版本格式多少？

**Comment by railgun-zyy** [comment]
> 报错：ImportError: cannot import name duplicates_everseen，请问怎么解决呀？ ![image](https://user-images.githubusercontent.com/109976361/221851411-c2b3f599-2fd8-4c44-b720-3d363d933594.png) ![image](https://user-images.githubusercontent.com/109976361/221851509-612500e4-d749-4ef5-8434-6f110d9c1f5e.png)


我也遇到这个问题，请问您解决了吗

**Comment by Hooccee** [comment]
升级 more_itertools 库`pip install -U more_itertools
`
