### ISSUE TITLE
离线量化的quant_post_static如何使用自己的数据集？

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/PaddleSlim#1689]
如题，在quant_post_static函数的下面的例子中，sample_generator如何使用自己已标注好的数据集？VOC格式，目标检测。
```
slim.quant.quant_post_static(
        executor=exe,
        model_dir='./inference_model',
        quantize_model_path='./quant_post_static_model',
        sample_generator=paddle.dataset.mnist.test(),
        model_filename='fp32.pdmodel',
        params_filename='fp32.pdiparams',
        batch_nums=10)
```

**Comment by zzjjay** [comment]
可基于自己数据集初始化[paddle.io.dataloader](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#dataloader) 传入quant_post_static即可。
<img width="563" alt="image" src="https://user-images.githubusercontent.com/41366441/227187334-ea80f5bc-fe9a-4a14-8a71-f9450535d28f.png">
