### ISSUE TITLE
我遇到了问题： No module named 'paddle.quantization' 

### ISSUE THREAD

**Issue by yui330** [PaddlePaddle/PaddleSlim#1691]
这是我的版本：
paddlepaddle-gpu          2.3.2.post116
paddleslim                2.3.0

**Comment by junghyun-avikus** [comment]
so do I.

I followed the following steps.
`python -m pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`
for gpu version of paddlepaddle with cuda 11.2 and,
`pip install paddleslim`
for paddleslim.

After runnig setup.py,
I got the same error when I tried to import the paddleslim.

**Comment by zzjjay** [comment]
paddle量化相关api在paddle devlop分支中从旧的 paddle.fluid.contrib.slim.quantization 更新为 paddle.quantization 和 paddle.static.quantization

如果遇到 no module named 'paddle.quantization' 的问题，请安装 paddle develop版本和paddleslim develop版本使用。

如果代码中使用的是旧量化api，则需要安装paddle正式版和paddleslim正式版使用。

**Comment by Li-li-Zhen** [comment]
@zzjjay  paddle develop版本中并没有paddle.quantization啊

**Comment by zzjjay** [comment]
paddle dev版是有paddle.quantization 相关api的，请确认下安装的是否为paddle develop版，或者先使用 pip uninstall paddlepaddle-gpu 卸载干净 paddle，再重装 paddle dev版，有时候不经卸载直接重装可能会导致import失败。

paddle dev版的安装参考官网[文档](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html)

**Comment by Li-li-Zhen** [comment]
@zzjjay 我是用的aistudio，确实是develop版本。今天可以了，谢谢。
