### ISSUE TITLE
根据官方教程蒸馏训练的时候出错。

### ISSUE THREAD

**Issue by liang-bowen** [PaddlePaddle/PaddleSlim#1696]
使用yolov7导出的onnx模型，自定义coco数据集，在蒸馏训练的时候报错。
如下：
    InvalidArgumentError: The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [1, 27, 80, 80], X's size = 172800, 'shape' is [30, 3, 9, 40, 40], the capacity of 'shape' is 1296000.
      [Hint: Expected capacity == in_size, but received capacity:1296000 != in_size:172800.] (at /paddle/paddle/fluid/operators/reshape_op.cc:230)
      [operator < reshape2 > error]

**Comment by zzjjay** [comment]
该问题可能是batch size设置不对导致的。导出的onnx模型中可能限制了batch size大小，那么训练时dataloader的batch size则需要与onnx模型中batch size相同才行。
