### ISSUE TITLE
有两个问题想请教一下

### ISSUE THREAD

**Issue by railgun-zyy** [PaddlePaddle/PaddleSlim#1698]
1、根据自动化压缩的步骤，第一步测精度eval.py，结果报错TypeError: Require fetch_list[1] 's type shall be one of (Variable, str), but received NoneType.
2、运行自动化压缩，报错
![image](https://user-images.githubusercontent.com/63039098/227146819-0fdc686a-62c7-42bc-9a5a-f922e12fe7c6.png)

**Comment by railgun-zyy** [comment]
版本：
paddle gpu 2.3.2.post112
paddleslim 2.3.4

**Comment by railgun-zyy** [comment]
我安装了 paddle gpu 2.4.1.post112
paddleslim 2.4.1
报错 
ImportError: cannot import name duplicates_everseen

**Comment by railgun-zyy** [comment]
第一个问题已解决

**Comment by zzjjay** [comment]
第二个运行自动压缩的报错是因为没有选择到可用的压缩策略而产生的，需检查下config文件中的超参设置，其中策略选择设置可参考：[ACT超参文档](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/hyperparameter_tutorial.md)
如果使用的是paddlelsim devlop中的示例config，则需要配合安装paddleslim2.4版本进行实验。

**Comment by ZihaoZhao** [comment]
> TypeError: Require fetch_list[1] 's type shall be one of (Variable, str), but received NoneType.

我也遇到了同样的问题，请问您是怎么解决的

**Comment by wanghaoshuang** [comment]
> 根据自动化压缩的步骤，第一步测精度eval.py，结果报错TypeError: Require fetch_list[1] 's type shall be one of (Variable, str), but received NoneType.

注释以下行：
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/image_classification/eval.py#L69-L76
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/image_classification/eval.py#L93-L94

以上代码用作 debug ，被误提交了。
