### ISSUE TITLE
请问自动压缩能只保留QAT环节吗

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/PaddleSlim#1704]
你好，我在使用过程中发现蒸馏可能会造成最后结果的比较大偏差，不方便控制变量；我想只针对模型进行QAT而不蒸馏，但我发现直接注释蒸馏相关内容发现这个不能取消，是一个强制的内容；然后我想通过只蒸馏少数node来变相解决这个问题，但是我发现修改了少数node后还是会直接报错（我写的node是按照自动蒸馏的出现的node然后抄上去的，但还是出现问题）

请问有什么方法可实现单纯的QAT吗，谢谢（我尝试在ppdet下面的qat但是反而速度更慢了，只有ppslim重新封装后的可以得到正确预期的模型。

**Comment by zzjjay** [comment]
自动压缩是通过蒸馏loss驱动量化训练的，所以无法取消蒸馏。
对于自动压缩下量化训练效果不佳的情况，可以通过调节学习率，替换蒸馏loss来改进，参考[文档](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/hyperparameter_tutorial.md#114-%E7%9F%A5%E8%AF%86%E8%92%B8%E9%A6%8Fknowledge-distillation)
蒸馏节点设置问题，参考[文档](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/hyperparameter_tutorial.md#1%E8%87%AA%E5%8A%A8%E8%92%B8%E9%A6%8F%E6%95%88%E6%9E%9C%E4%B8%8D%E7%90%86%E6%83%B3%E6%80%8E%E4%B9%88%E8%87%AA%E4%B8%BB%E9%80%89%E6%8B%A9%E8%92%B8%E9%A6%8F%E8%8A%82%E7%82%B9)进行设置。

如果要使用『单纯的量化训练』，需要配置原始的有标签loss，再调用paddleslim的量化训练api进行实验。
如果是检测模型，建议还是通过paddledetection下面的qat配置进行实验。

**Comment by sanbuphy** [comment]
> 自动压缩是通过蒸馏loss驱动量化训练的，所以无法取消蒸馏。 对于自动压缩下量化训练效果不佳的情况，可以通过调节学习率，替换蒸馏loss来改进，参考[文档](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/hyperparameter_tutorial.md#114-%E7%9F%A5%E8%AF%86%E8%92%B8%E9%A6%8Fknowledge-distillation) 蒸馏节点设置问题，参考[文档](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/hyperparameter_tutorial.md#1%E8%87%AA%E5%8A%A8%E8%92%B8%E9%A6%8F%E6%95%88%E6%9E%9C%E4%B8%8D%E7%90%86%E6%83%B3%E6%80%8E%E4%B9%88%E8%87%AA%E4%B8%BB%E9%80%89%E6%8B%A9%E8%92%B8%E9%A6%8F%E8%8A%82%E7%82%B9)进行设置。
> 
> 如果要使用『单纯的量化训练』，需要配置原始的有标签loss，再调用paddleslim的量化训练api进行实验。 如果是检测模型，建议还是通过paddledetection下面的qat配置进行实验。

你好，我使用了paddledetection下面的qat配置，但是结果变得更慢了（在onnxruntime下），只有paddleslim的是有效的。

对于蒸馏的问题，我再去试试看，谢谢

**Comment by zzjjay** [comment]
> 我使用了paddledetection下面的qat配置，但是结果变得更慢了（在onnxruntime下），只有paddleslim的是有效的。

可以对比下两者的qat配置是否对齐，或通过netron.app可视化下两者导出的推理模型是否有差异。
按道理应该是一样的，paddledetction调用的也是slim的api进行压缩的。

**Comment by sanbuphy** [comment]
> > 我使用了paddledetection下面的qat配置，但是结果变得更慢了（在onnxruntime下），只有paddleslim的是有效的。
> 
> 可以对比下两者的qat配置是否对齐，或通过netron.app可视化下两者导出的推理模型是否有差异。 按道理应该是一样的，paddledetction调用的也是slim的api进行压缩的。

我发现他们的api是底层不同的，详见：https://github.com/PaddlePaddle/Paddle/issues/51915

**Comment by zzjjay** [comment]
这些差别只是动静态图api的差别，路径中包含imperative的是动态图qat api。

paddledetection是使用的动态图qat，paddleslim自动压缩使用的是静态图qat。调用两者api时，配置一致时结果是一致的。可以重点检查下onnx_format是否设置为True了。

**Comment by sanbuphy** [comment]
> 这些差别只是动静态图api的差别，路径中包含imperative的是动态图qat api。
> 
> paddledetection是使用的动态图qat，paddleslim自动压缩使用的是静态图qat。调用两者api时，配置一致时结果是一致的。可以重点检查下onnx_format是否设置为True了。

好的谢谢，不过我测试发现他们支持的量化op也是不同的，那这个可能是动态图静态图的支持范围不同所导致的。 
onnx_format是确定为True的，因为量化后还观察了对应量化算子，确实是q和dq，而不是paddle的特有格式fake_q_dq
