### ISSUE TITLE
关于零基础在半个月内用PaddleSlim实现手动压缩模型的可行性

### ISSUE THREAD

**Issue by rainy-london** [PaddlePaddle/PaddleSlim#1719]
求问一下懂轻量化的大佬们。
我的本科毕设，模型用的是PP-YOLOE+_SOD-l，我没有任何模型轻量化的基础，导师开会说不让用自动压缩说让我手动压缩，目标是半个月把这个事做完，半个月时间学轻量化并且做到手动压缩这件事可行吗？

**Comment by zzjjay** [comment]
paddleslim中提供了量化、结构化剪枝、非结构化稀疏的api进行压缩。通过调用相关api来实现模型轻量化，半个月内足矣。

如果完全要自己逐行开发轻量化代码，半个月的时间则太仓促了，那么可以尝试知识蒸馏去进行轻量化，开发经典的知识蒸馏算法不会太复杂，且也有许多开源代码（比如paddleslim内实现的蒸馏算法）作参考。

以下为PaddleSlim相关压缩实践文档：
[量化训练流程](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/quant_aware_tutorial.md)
[离线量化流程](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/quant_post_static_tutorial.md)
[结构化剪枝流程](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/pruning_tutorial.md)

**Comment by rainy-london** [comment]
> paddleslim中提供了量化、结构化剪枝、非结构化稀疏的api进行压缩。通过调用相关api来实现模型轻量化，半个月内足矣。
> 
> 如果完全要自己逐行开发轻量化代码，半个月的时间则太仓促了，那么可以尝试知识蒸馏去进行轻量化，开发经典的知识蒸馏算法不会太复杂，且也有许多开源代码（比如paddleslim内实现的蒸馏算法）作参考。
> 
> 以下为PaddleSlim相关压缩实践文档： [量化训练流程](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/quant_aware_tutorial.md) [离线量化流程](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/quant_post_static_tutorial.md) [结构化剪枝流程](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/pruning_tutorial.md)

感谢大佬指点，太感谢了！
