### ISSUE TITLE
指定某一层不进行量化

### ISSUE THREAD

**Issue by Mobu59** [PaddlePaddle/PaddleSlim#1734]
您好，想了解一下能否在量化时指定某一层不进行量化或者指定该层量化的bits为16？如果可以的话具体怎么操作呢

**Comment by ceci3** [comment]
可以的，可以指定对应参数：skip_tensor_list。https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/api_cn/static/quant/quantization_api.rst#quant_post_static
