### ISSUE TITLE
在使用静态量化的过程中如何指定融合算子

### ISSUE THREAD

**Issue by JPChen2000** [PaddlePaddle/PaddleSlim#1736]
请问在训练后使用静态量化的过程中如何指定融合算子？
在使用Paddle-Lite在TIMVX平台上部署PPOCRv3_det模型时发现，在模型量化时倒数第2层Conv2d_transpose层会将后面的relu层融合在一起，此时推理模型报错 nntp not  support this format。
将relu层去掉之后经过同样量化操作，则可以正常执行。

**Comment by ceci3** [comment]
这应该是Paddle-Lite端自动做的融合，可以在Paddle-Lite咨询下
