### ISSUE TITLE
save_quant_model.py  需要更新

### ISSUE THREAD

**Issue by mysteriousHerb** [PaddlePaddle/PaddleSlim#1742]
代码从import开始就有点问题，paddle.static.load_inference_model(
                 original_path, exe, model_filename=model_filename, params_filename=params_filename)

然后
            paddle.static.save_inference_model(
                path_prefix = save_path,
                feed_vars = [image],
                fetch_vars = fetch_targets,
                executor = exe,
                program=inference_program)

也需要更新，

**Comment by ceci3** [comment]
已经更新成static下的save和load了
