### ISSUE TITLE
剪枝例子报错

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/PaddleSlim#175]
![image](https://user-images.githubusercontent.com/50724968/76413196-f6e7fc00-63cf-11ea-8abe-a0eba7982a88.png)

**Comment by wanghaoshuang** [comment]
请将[这一行](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/slim/prune/eval_prune.py#L46)改为
```
from paddleslim.prune import load_model
```

**Comment by wanghaoshuang** [comment]
如有问题，请重新打开该issue.
