### ISSUE TITLE
动态图QAT如何指定部分层不量化？

### ISSUE THREAD

**Issue by WeixiangXu** [PaddlePaddle/PaddleSlim#1767]
paddleslim.QAT()
我注意到
[paddle/quantization/imperative/qat.py](https://github.com/PaddlePaddle/Paddle/blob/1b8a1a982845ffef44679f79da363a8e7f3b20ba/python/paddle/quantization/imperative/qat.py#LL181C1-L182C1)中有`self.linear_0.skip_quant = True`，
Q1：在模型定义时在某一层（如self.conv1）设定了 `self.conv1.skip_quant=True`，如何检查该层确实没有被量化？
Q2：有办法不在模型定义中，而是通过config接口指定哪些层不量化吗？

**Comment by minghaoBD** [comment]
Q1: 可以print(model)，可以通过是否在这一个layer前后插入了scale统计层来判断
Q2: Q1中的方法最直接，建议按照Q1来
