### ISSUE TITLE
quant_post量化yolov3报错 KeyError: 'stage.3.7.0.conv.weights'

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/PaddleSlim#177]
CPU 8
RAM 32GB
GPU v100
显存 16GB
磁盘 100GB
环境配置
Python版本 python3.7
框架版本  PaddlePaddle 1.7.0
@slf12 
aistudio@jupyter-115786-193843:~/post_training_quantization_withdata$ sh run_post_training_quanzation.sh 
-------------------args----------------------
algo: KL
batch_nums: 20
batch_size: 3000
is_full_quantize: False
model_dir: ../work/PaddleDetection_1/yolov3_dark_freeze/mj_yolov3_darknet
model_filename: None
params_filename: None
save_model_path: yolov3_int8_model
use_gpu: True
---------------------------------------------
W0314 12:14:31.721148   637 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0314 12:14:31.725704   637 device_context.cc:245] device: 0, cuDNN Version: 7.3.
2020-03-14 12:14:34,203-INFO: all run batch: 0
2020-03-14 12:14:34,203-INFO: all run batch: 0
2020-03-14 12:14:34,203-INFO: calculate scale factor ...
2020-03-14 12:14:34,203-INFO: calculate scale factor ...
Traceback (most recent call last):
  File "post_training_quantization.py", line 66, in <module>
    batch_nums=10)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/quant/quanter.py", line 306, in quant_post
    post_training_quantization.quantize()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 231, in quantize
    self._calculate_scale_factor()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 353, in _calculate_scale_factor
    data = self._sampling_data[var_name]
KeyError: 'stage.3.7.0.conv.weights'

**Comment by slf12** [comment]
可以检查下reader，一般是Reader没写对，一个batch都没跑会出现这种情况

**Comment by aixier** [comment]
reader就是训练的时候的reader:

def custom_reader(images_lists, data_dir, input_size, mode):
    def reader():
        np.random.shuffle(images_lists)
        for line in images_lists:
            if mode == 'train' or mode == 'eval':
                ######################  以下可能是需要自定义修改的部分   ############################
                parts = line.split()
                image_path = parts[0]
                try:
                    img = Image.open(os.path.join(data_dir, image_path))
                except ZeroDivisionError as e:
                    print("image_path==\n",ata_dir, image_path)
                    continue
                if img.mode != 'RGB':
                    img = img.convert('RGB')
                im_width, im_height = img.size
                # bbox 的列表，每一个元素为这样
                # layout: label | x-center | y-cneter | width | height | difficult
                bbox_labels = []
                for object_str in parts[1:]:
                    bbox_sample = []
                    object = json.loads(object_str)
                    bbox_sample.append(float(train_parameters['label_dict'][object['value']]))
                    bbox = object['coordinate']
                    box = [bbox[0][0], bbox[0][1], bbox[1][0] - bbox[0][0], bbox[1][1] - bbox[0][1]]
                    bbox = box_to_center_relative(box, im_height, im_width)
                    bbox_sample.append(float(bbox[0]))
                    bbox_sample.append(float(bbox[1]))
                    bbox_sample.append(float(bbox[2]))
                    bbox_sample.append(float(bbox[3]))
                    difficult = float(0)
                    bbox_sample.append(difficult)
                    bbox_labels.append(bbox_sample)
                ######################  可能需要自定义修改部分结束   ############################
                if len(bbox_labels) == 0: continue
                img, sample_labels = preprocess(img, bbox_labels, input_size, mode)
                # sample_labels = np.array(sample_labels)
                if len(sample_labels) == 0: continue
                boxes = sample_labels[:, 1:5]
                lbls = sample_labels[:, 0].astype('int32')
                difficults = sample_labels[:, -1].astype('int32')
                max_box_num = train_parameters['max_box_num']
                cope_size = max_box_num if len(boxes) >= max_box_num else len(boxes)
                ret_boxes = np.zeros((max_box_num, 4), dtype=np.float32)
                ret_lbls = np.zeros((max_box_num), dtype=np.int32)
                ret_difficults = np.zeros((max_box_num), dtype=np.int32)
                ret_boxes[0: cope_size] = boxes[0: cope_size]
                ret_lbls[0: cope_size] = lbls[0: cope_size]
                ret_difficults[0: cope_size] = difficults[0: cope_size]
                #print("shape===",img.shape)
                yield img, ret_boxes, ret_lbls, ret_difficults
   
    return reader

**Comment by aixier** [comment]
**reader就是训练用的reader** @slf12 
```
def custom_reader(images_lists, data_dir, input_size, mode):
    def reader():
        np.random.shuffle(images_lists)
        for line in images_lists:
            if mode == 'train' or mode == 'eval':
                ######################  以下可能是需要自定义修改的部分   ############################
                parts = line.split()
                image_path = parts[0]
                try:
                    img = Image.open(os.path.join(data_dir, image_path))
                except ZeroDivisionError as e:
                    print("image_path==\n",ata_dir, image_path)
                    continue
                if img.mode != 'RGB':
                    img = img.convert('RGB')
                im_width, im_height = img.size
                # bbox 的列表，每一个元素为这样
                # layout: label | x-center | y-cneter | width | height | difficult
                bbox_labels = []
                for object_str in parts[1:]:
                    bbox_sample = []
                    object = json.loads(object_str)
                    bbox_sample.append(float(train_parameters['label_dict'][object['value']]))
                    bbox = object['coordinate']
                    box = [bbox[0][0], bbox[0][1], bbox[1][0] - bbox[0][0], bbox[1][1] - bbox[0][1]]
                    bbox = box_to_center_relative(box, im_height, im_width)
                    bbox_sample.append(float(bbox[0]))
                    bbox_sample.append(float(bbox[1]))
                    bbox_sample.append(float(bbox[2]))
                    bbox_sample.append(float(bbox[3]))
                    difficult = float(0)
                    bbox_sample.append(difficult)
                    bbox_labels.append(bbox_sample)
                ######################  可能需要自定义修改部分结束   ############################
                if len(bbox_labels) == 0: continue
                img, sample_labels = preprocess(img, bbox_labels, input_size, mode)
                # sample_labels = np.array(sample_labels)
                if len(sample_labels) == 0: continue
                boxes = sample_labels[:, 1:5]
                lbls = sample_labels[:, 0].astype('int32')
                difficults = sample_labels[:, -1].astype('int32')
                max_box_num = train_parameters['max_box_num']
                cope_size = max_box_num if len(boxes) >= max_box_num else len(boxes)
                ret_boxes = np.zeros((max_box_num, 4), dtype=np.float32)
                ret_lbls = np.zeros((max_box_num), dtype=np.int32)
                ret_difficults = np.zeros((max_box_num), dtype=np.int32)
                ret_boxes[0: cope_size] = boxes[0: cope_size]
                ret_lbls[0: cope_size] = lbls[0: cope_size]
                ret_difficults[0: cope_size] = difficults[0: cope_size]
                #print("shape===",img.shape)
                yield img, ret_boxes, ret_lbls, ret_difficults
   
    return reader
```

**Comment by slf12** [comment]
> **reader就是训练用的reader** @slf12

最简单的验证方法是加载你要量化的模型，然后用这个Reader 定义dataloader, 然后run program，离线量化里做的事情也是拿数据跑前向收集中间的feature map来计算量化scale, 这个错误显示没有收集到中间的feature map

**Comment by aixier** [comment]
改好了，谢谢
