### ISSUE TITLE
自动量化报错[operator < elementwise_sub > error]

### ISSUE THREAD

**Issue by kongdebug** [PaddlePaddle/PaddleSlim#1798]
在PaddlePaddle2.5 PaddleSlim dev版本进行自动量化训练，启动的时候报错：NotFoundError: The kernel (elementwise_sub) with key (GPU, Undefined(AnyLayout), uint8) is not found and GPU kernel cannot fallback to CPU one. (at ../paddle/fluid/framework/phi_utils.cc:144)

**Comment by ceci3** [comment]
是对 elementwise_sub 算子进行了量化嘛？看起来是进行了不适当位置的量化操作

**Comment by kongdebug** [comment]
已解决
