### ISSUE TITLE
No default configuration file found at repository's root

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleSlim#1807]
https://readthedocs.org/projects/paddleslim/builds/22572627/

No default configuration file found at repository's root

![image](https://github.com/PaddlePaddle/PaddleSlim/assets/4617245/360ed3ea-c703-4301-9dfa-49e39d226f20)

**Comment by ceci3** [comment]
收到，应该是我们的文档构建有问题，我们排查下
