### ISSUE TITLE
自动压缩中的蒸馏损失为多个时，配置文件要怎么设置？

### ISSUE THREAD

**Issue by Wst-sd** [PaddlePaddle/PaddleSlim#1827]
![提问](https://github.com/PaddlePaddle/PaddleSlim/assets/125892081/f2733284-bc28-479a-ae5e-681f2105edf0)
我想在蒸馏中同时使用soft_label,和l2loss ，节点添加了4个（两组），但是尝试了修改配置文件用loss: [soft_label,l2] 和loss: soft_label, l2 均报错，请问正确的格式是怎么样的？

**Comment by ceci3** [comment]
同一个node不支持多个loss，不同的node的话，需要node个数和loss个数相同，都是list格式

**Comment by Wst-sd** [comment]
好的，谢谢
