### ISSUE TITLE
有考虑过新增人脸检测模型的压缩例程嘛？

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/PaddleSlim#1857]
如题，翻了一下仓库没看到有对人脸检测模型做量化的

**Comment by ceci3** [comment]
暂时没有这个计划~ 请问下是有什么场景吗

**Comment by Zheng-Bicheng** [comment]
> 暂时没有这个计划~ 请问下是有什么场景吗

YOLO这一类目标检测算法用来做人脸检测的话是没有关键点的，而类似SCRFD这一类的模型可以得到具体的坐标和人脸关键点信息，可以在人脸识别前做一些人脸对齐的操作。类似SCRFD这种在InsightFace仓库中的模型在人脸识别领域是非常热门的，而且很适合用来做量化。

**Comment by wanghaoshuang** [comment]
抱歉，PaddleSlim 没有直接提供 SCRFD 相关示例。
在 [PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection) 中集成了 PaddleSlim 压缩功能，理论上 PaddleDetection 支持的模型均可进行模型压缩。可以关注下 PaddleDetection 是否支持或是否计划支持 SCRFD。
感谢您的关注。
