### ISSUE TITLE
请问出现这种情况的原因会是什么？# 自动压缩 autoCompression

### ISSUE THREAD

**Issue by drakitLiu** [PaddlePaddle/PaddleSlim#1858]
代码如下：
![微信图片_20240228164204](https://github.com/PaddlePaddle/PaddleSlim/assets/143715628/9e0b6a58-ccfb-4c87-978d-61036453b646)

错误如下：
![微信图片_20240228163918](https://github.com/PaddlePaddle/PaddleSlim/assets/143715628/5527a4a7-d2e2-42f2-b8c3-81fe4953396b)
（接上图）
![微信图片_202402281639181](https://github.com/PaddlePaddle/PaddleSlim/assets/143715628/4667facd-e66f-41b9-9523-af3f428e4375)

**Comment by lizexu123** [comment]
config没设置具体的量化策略，默认是超参数搜索，导致递归过大，需要指定一下量化策略

**Comment by zzjjay** [comment]
建议使用PTQ（离线量化）策略快速尝试量化效果，图中使用的是超参搜索策略，容易因模型结构导致过多的递归次数而报错。
PTQ 设置参考文档：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/hyperparameter_tutorial.md#112-%E7%A6%BB%E7%BA%BF%E9%87%8F%E5%8C%96post-traing-quantization

**Comment by wanghaoshuang** [comment]
ConfigSpace 版本问题，最新的 ConfigSpace 有bug，会导致上述错误。
建议回退ConfigSpace 版本到[0.5.0](https://pypi.org/project/ConfigSpace/0.5.0/)：

```
pip uninstall ConigSpace
pip install ConfigSpace==0.5.0 
```

https://pypi.org/project/ConfigSpace/0.5.0/
相关 issue: https://github.com/automl/ConfigSpace/issues/343

**Comment by wanghaoshuang** [comment]
如有需要，可以重新打开该 issue，多谢。
