### ISSUE TITLE
PaddleSlim支持transformer模型吗？今后会支持吗

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/PaddleSlim#187]
谢谢！

**Comment by wanghaoshuang** [comment]
PaddleSlim中的量化和蒸馏理论上是支持的transformer模型的，但是我们没有验证过效果。
PaddleSlim中的剪裁暂时不支持transformer， 后续会尝试探索并支持。
感谢您的关注，希望后续能进一步交流和提建议。

**Comment by syyxtl** [comment]
> PaddleSlim中的量化和蒸馏理论上是支持的transformer模型的，但是我们没有验证过效果。 PaddleSlim中的剪裁暂时不支持transformer， 后续会尝试探索并支持。 感谢您的关注，希望后续能进一步交流和提建议。

现在呢

**Comment by XGZhang11** [comment]
> > PaddleSlim中的量化和蒸馏理论上是支持的transformer模型的，但是我们没有验证过效果。 PaddleSlim中的剪裁暂时不支持transformer， 后续会尝试探索并支持。 感谢您的关注，希望后续能进一步交流和提建议。
> 
> 现在呢

你好，现在已经支持transformer模型，具体使用可以参考文档
