### ISSUE TITLE
 from paddleslim.dygraph.dist中没有import AdaptorBase

### ISSUE THREAD

**Issue by wangfeiyun** [PaddlePaddle/PaddleSlim#1871]
from paddleslim.dygraph.dist import AdaptorBase出现错误，显示没有AdaptorBase，打开文件位置，发现的确没有，但是安装paddleslim好像是没啥问题

**Comment by zzjjay** [comment]
请问是在哪看到调用这个api呢？ 代码文件中显示没有该api

**Comment by wangfeiyun** [comment]
> 请问是在哪看到调用这个api呢？ 代码文件中显示没有该api

我采用的是paddlpaddle2.6，并且对应的paddleslim也下载了2,6.调用蒸馏的接口deploy/slim/distill/distill_train.py

**Comment by wangfeiyun** [comment]
> > 请问是在哪看到调用这个api呢？ 代码文件中显示没有该api
> 
> 我采用的是paddlpaddle2.6，并且对应的paddleslim也下载了2,6.调用蒸馏的接口deploy/slim/distill/distill_train.py



> 请问是在哪看到调用这个api呢？ 代码文件中显示没有该api

在distill_train.py的同级distill_config.py中from paddleslim.dygraph.dist import AdaptorBase

**Comment by zzjjay** [comment]
> deploy/slim/distill/distill_train.py

这是哪个页面的代码？似乎不是PaddleSlim 里的

**Comment by wangfeiyun** [comment]
> 请问是在哪看到调用这个api呢？ 代码文件中显示没有该api

![Uploading 1.JPG…]()

**Comment by wangfeiyun** [comment]
> > deploy/slim/distill/distill_train.py
> 
> 这是哪个页面的代码？似乎不是PaddleS我上传了图片
代码地址https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/deploy/slim/distill/distill_config.py

**Comment by wangfeiyun** [comment]
> > > deploy/slim/distill/distill_train.py
> > 
> > 
> > 这是哪个页面的代码？似乎不是PaddleS我上传了图片 代码地址 https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/deploy/slim/distill/distill_config.py

我是将paddleseg2.9下载到本地进行运行的

**Comment by zzjjay** [comment]
paddleslim版本不对吧

请按照文档示例将 PaddleSlim 切换到制定commit
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/docs/deployment/slim/distill/distill_cn.md#21-%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87
![image](https://github.com/PaddlePaddle/PaddleSlim/assets/41366441/2a000030-cd7e-4a25-9c31-ab4d9a621060)

**Comment by wangfeiyun** [comment]
> paddleslim版本不对吧
> 
> 请按照文档示例将 PaddleSlim 切换到制定commit https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/docs/deployment/slim/distill/distill_cn.md#21-%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87 ![image](https://private-user-images.githubusercontent.com/41366441/325834557-2a000030-cd7e-4a25-9c31-ab4d9a621060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDA1NTEsIm5iZiI6MTcxNDEwMDI1MSwicGF0aCI6Ii80MTM2NjQ0MS8zMjU4MzQ1NTctMmEwMDAwMzAtY2Q3ZS00YTI1LTljMzEtYWI0ZDlhNjIxMDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAyNTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYzhiYmFjMTQ5NGE1ZDM0M2U2YzRjZWMxMThjZmY5MjI1ZGIyOWVkZjA0ZGFhMmViNDZlNWI4MDM3N2M4YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kDn_krNB8MiMB3dJKumJQcf8n9jeD0v-Rdj413PZyWk)

好的，那我paddlepaddle2.6应该安装那个版本的paddleslim

**Comment by wangfeiyun** [comment]
这个问题还是没有解决

**Comment by wangfeiyun** [comment]
我又重新配置了一个虚拟环境，结果出现同样的问题

**Comment by zzjjay** [comment]
按照文档说明切换指定commit后，在PaddleSlim的目录下 paddleslim/dygraph/dist/distill.py  中 是能找到AdaptorBase的。

请先将之前的PaddleSlim卸载干净，再重新安装指定commit下的PaddleSlim
