### ISSUE TITLE
蒸馏时将teacher的变量加入student的program，那保存训练断点时模型参数会否变大？

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/PaddleSlim#195]
如题。模型是transformer模型

**Comment by wanghaoshuang** [comment]
保存训练断电时模型参数会变大。

如果不想保存teacher的变量的话：
在将teacher合并到student之前，可以先clone备份一下student program:
```
student_bak = student_program.clone()
```
在保存断点时，指定save_params或save_persistables接口的main_porgram为student_bak即可。
