### ISSUE TITLE
是否能支持设置某些层不量化？

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/PaddleSlim#199]
实测发现某些层量化后对精度的影响明显大于其他层，是否可以设置将这些层不量化只量化其他层？

**Comment by slf12** [comment]
![image](https://user-images.githubusercontent.com/8036226/77979250-b1678080-7336-11ea-8c6d-f977a7d215fd.png)
https://paddlepaddle.github.io/PaddleSlim/api_cn/quantization_api.html

**Comment by HaoLiuHust** [comment]
这是设置不量化的层类型，我是指用层名 @slf12

**Comment by HaoLiuHust** [comment]
比如有个卷积层测试下来不量化这层精度几乎不损失，而如果量化就掉几个点，能否设置这一层不量化

**Comment by slf12** [comment]
> 比如有个卷积层测试下来不量化这层精度几乎不损失，而如果量化就掉几个点，能否设置这一层不量化

![image](https://user-images.githubusercontent.com/8036226/77994250-3ca73d00-735c-11ea-9aec-4e9bdbe2295c.png)

**Comment by HaoLiuHust** [comment]
3q, 我试试看

**Comment by HaoLiuHust** [comment]
有个问题，这个参数在post_quant里能设置吗？

**Comment by HaoLiuHust** [comment]
@slf12
