### ISSUE TITLE
transformer distilling出错

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/PaddleSlim#202]
我试了transformer的distill,train了两个batch之后提示如下错误：
Error: Tensor holds no memory. Call Tensor::mutable_data first.
  [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.cc:23)
  [operator < elementwise_div > error]

是内存原因吗？

**Comment by wanghaoshuang** [comment]
不是内存的问题，是某个变量没有初始化，看着像是训练数据有问题。
麻烦您把所有log都贴出来？

**Comment by dlkht** [comment]
好的，如下：

I0403 10:39:23.727172 11525 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 3 cards are used, so 3 programs are executed in parallel.
W0403 10:39:26.841464 11525 fuse_optimizer_op_pass.cc:191] Find adam operators : 67, and 67 for dense gradients. To make the speed faster, those optimization are fused during training.
W0403 10:39:26.888103 11525 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 67. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 47.
I0403 10:39:26.893105 11525 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0403 10:39:26.995769 11525 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0403 10:39:27.052343 11525 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
2020-04-03 10:39:27,204-INFO: step_idx: 0, epoch: 0, batch: 0, avg loss: 8.852875, normalized loss: 7.619518, ppl: 6994.467285
2020-04-03 10:39:39,145-INFO: step_idx: 100, epoch: 0, batch: 100, avg loss: 8.515923, normalized loss: 7.282566, ppl: 4993.650879, speed: 8.37 step/s
2020-04-03 10:39:50,972-INFO: step_idx: 200, epoch: 0, batch: 200, avg loss: 8.965258, normalized loss: 7.731901, ppl: 7826.397949, speed: 8.46 step/s
2020-04-03 10:40:02,918-INFO: step_idx: 300, epoch: 0, batch: 300, avg loss: 9.121069, normalized loss: 7.887713, ppl: 9145.972656, speed: 8.37 step/s
2020-04-03 10:40:14,858-INFO: step_idx: 400, epoch: 0, batch: 400, avg loss: 9.527080, normalized loss: 8.293723, ppl: 13726.445312, speed: 8.38 step/s
2020-04-03 10:40:26,771-INFO: step_idx: 500, epoch: 0, batch: 500, avg loss: 9.279501, normalized loss: 8.046145, ppl: 10716.083008, speed: 8.39 step/s
/home/qzy3/.local/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "/home/qzy3/pycharm1/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/qzy3/pycharm1/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/qzy3/pycharm1/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/qzy3/pycharm1/pycharm-community-2018.1.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/qzy3/transformer/ver7-len80/transf-pal1.52.distill/train.py", line 667, in <module>
    train(args)
  File "/home/qzy3/transformer/ver7-len80/transf-pal1.52.distill/train.py", line 589, in train
    token_num, pyreader)
  File "/home/qzy3/transformer/ver7-len80/transf-pal1.52.distill/train.py", line 362, in train_loop
    feed=feed_dict_list)
  File "/home/qzy3/.local/lib/python3.7/site-packages/paddle/fluid/parallel_executor.py", line 311, in run
    return_numpy=return_numpy)
  File "/home/qzy3/.local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/home/qzy3/.local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/home/qzy3/.local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "/home/qzy3/.local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::Tensor::check_memory_size() const
3   float const* paddle::framework::Tensor::data<float>() const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseDivKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseDivKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16>, paddle::operators::ElementwiseDivKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseDivKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseDivKernel<paddle::platform::CUDADeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::details::ComputationOpHandle::RunImpl()
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
11  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
12  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
13  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/qzy3/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/qzy3/.local/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/qzy3/transformer/ver7-len80/transf-pal1.52.distill/model.py", line 612, in transformer
    avg_cost = sum_cost / token_num
  File "/home/qzy3/transformer/ver7-len80/transf-pal1.52.distill/train.py", line 523, in train
    is_test=False)
  File "/home/qzy3/transformer/ver7-len80/transf-pal1.52.distill/train.py", line 667, in <module>
    train(args)
  File "/home/qzy3/pycharm1/pycharm-community-2018.1.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/qzy3/pycharm1/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/qzy3/pycharm1/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/qzy3/pycharm1/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Tensor holds no memory. Call Tensor::mutable_data first.
  [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.cc:23)
  [operator < elementwise_div > error]

**Comment by dlkht** [comment]
distill 部分代码是这样：

def train(args):
    # priority: ENV > args > config
    is_local = os.getenv("PADDLE_IS_LOCAL", "1")
    if is_local == '0':
        args.local = False
    logging.info(args)

    if args.device == 'CPU':
        TrainTaskConfig.use_gpu = False

    training_role = os.getenv("TRAINING_ROLE", "TRAINER")

    if training_role == "PSERVER" or (not TrainTaskConfig.use_gpu):
        place = fluid.CPUPlace()
        dev_count = int(os.environ.get('CPU_NUM', multiprocessing.cpu_count()))
    else:
        gpu_id = int(os.environ.get('FLAGS_selected_gpus', 0))
        place = fluid.CUDAPlace(gpu_id)
        dev_count = get_device_num()

    exe = fluid.Executor(place)

#----------------
    teacher_train_prog = fluid.Program()
    teacher_startup_prog = fluid.Program()

    if args.enable_ce:
        teacher_train_prog.random_seed = 1000
        teacher_startup_prog.random_seed = 1000

    with fluid.program_guard(teacher_train_prog, teacher_startup_prog):
        with fluid.unique_name.guard():
            _, _, predict_t, _, _ = transformer(
                ModelHyperParams.src_vocab_size,
                ModelHyperParams.trg_vocab_size,
                ModelHyperParams.max_length + 1,
                ModelHyperParams.n_layer,
                ModelHyperParams.n_head,
                ModelHyperParams.d_key,
                ModelHyperParams.d_value,
                ModelHyperParams.d_model,
                ModelHyperParams.d_inner_hid,
                ModelHyperParams.prepostprocess_dropout,
                ModelHyperParams.attention_dropout,
                ModelHyperParams.relu_dropout,
                ModelHyperParams.preprocess_cmd,
                ModelHyperParams.postprocess_cmd,
                ModelHyperParams.weight_sharing,
                TrainTaskConfig.label_smooth_eps,
                ModelHyperParams.bos_idx,
                use_py_reader=args.use_py_reader,
                is_test=False)
    #exe = fluid.Executor(place)
    exe.run(teacher_startup_prog)
    fluid.io.load_persistables(
        exe, TrainTaskConfig.ckpt_path, main_program=teacher_train_prog)

#----------------

    train_prog = fluid.Program()
    startup_prog = fluid.Program()

    if args.enable_ce:
        train_prog.random_seed = 1000
        startup_prog.random_seed = 1000

    with fluid.program_guard(train_prog, startup_prog):
        with fluid.unique_name.guard():
            sum_cost, avg_cost, predict, token_num, pyreader = transformer(
                ModelHyperParams.src_vocab_size,
                ModelHyperParams.trg_vocab_size,
                ModelHyperParams.max_length + 1,
                2,                              #ModelHyperParams.n_layer,
                ModelHyperParams.n_head,
                ModelHyperParams.d_key,
                ModelHyperParams.d_value,
                ModelHyperParams.d_model,
                ModelHyperParams.d_inner_hid,
                ModelHyperParams.prepostprocess_dropout,
                ModelHyperParams.attention_dropout,
                ModelHyperParams.relu_dropout,
                ModelHyperParams.preprocess_cmd,
                ModelHyperParams.postprocess_cmd,
                ModelHyperParams.weight_sharing,
                TrainTaskConfig.label_smooth_eps,
                ModelHyperParams.bos_idx,
                use_py_reader=args.use_py_reader,
                is_test=False)
            #exe.run(startup_prog)


            if args.sync:
                lr_decay = fluid.layers.learning_rate_scheduler.noam_decay(
                    ModelHyperParams.d_model, TrainTaskConfig.warmup_steps)
                logging.info("before adam")

                #with fluid.default_main_program()._lr_schedule_guard():
                with train_prog._lr_schedule_guard():
                    learning_rate = lr_decay * TrainTaskConfig.learning_rate

                optimizer = fluid.optimizer.Adam(
                    learning_rate=learning_rate,
                    beta1=TrainTaskConfig.beta1,
                    beta2=TrainTaskConfig.beta2,
                    epsilon=TrainTaskConfig.eps)
            else:
                optimizer = fluid.optimizer.SGD(0.003)
            #optimizer.minimize(avg_cost)
    #fluid.io.load_persistables(
    #    exe, TrainTaskConfig.st_ckpt_path, main_program=train_prog)
    data_name_map = {

                     'src_word': 'src_word',
                     'src_pos': 'src_pos',
                     'src_slf_attn_bias': 'src_slf_attn_bias',
                     'trg_word': 'trg_word',
                     'trg_pos': 'trg_pos',
                     'trg_slf_attn_bias': 'trg_slf_attn_bias',
                     'trg_src_attn_bias': 'trg_src_attn_bias',
                     #'enc_output': 'enc_output', #
                     'lbl_word': 'lbl_word',
                     'lbl_weight': 'lbl_weight',
                     'init_score': 'init_score', #
                     'init_idx': 'init_idx',     #
                     #"src_pos_enc_table":"src_pos_enc_table",
                     #"trg_pos_enc_table":"trg_pos_enc_table"
                                          
                     }

    dist.merge(teacher_train_prog, train_prog, data_name_map, place)

    with fluid.program_guard(train_prog,startup_prog):
        #with fluid.unique_name.guard():
            student_var = train_prog.global_block().var(predict.name) #("fc_32.tmp_0")
            teacher_var = train_prog.global_block().var("teacher_"+predict_t.name) #("teacher_fc_32.tmp_0")

            #student_var = fluid.layers.softmax(student_var / 1.0)
            # teacher_var = fluid.layers.softmax(teacher_var / 1.0)
            teacher_var.stop_gradient = True

            #_loss = fluid.layers.reduce_mean(
            #    fluid.layers.cross_entropy(
            #        teacher_var,
            #        student_var, soft_label=True))
            _loss = layers.softmax_with_cross_entropy(
                logits=teacher_var,
                label=student_var,
                soft_label=True)
            _loss = fluid.layers.reduce_mean(_loss)
            avg_cost = avg_cost + _loss #fluid.layers.mean(avg_cost,_loss) #
            #optimizer = fluid.optimizer.Momentum(0.01, 0.9)
            optimizer.minimize(avg_cost)

    if args.local:
        logging.info("local start_up:")
        print(dev_count)
        train_loop(exe, train_prog, startup_prog, dev_count, sum_cost, avg_cost,
                   token_num, pyreader)

**Comment by baiyfbupt** [comment]
看起来是定义好train_prog后没有对startup_prog做初始化，在定义蒸馏loss和optimizer后加一下exe.run(startup_prog)呢？

**Comment by dlkht** [comment]
> 看起来是定义好train_prog后没有对startup_prog做初始化，在定义蒸馏loss和optimizer后加一下exe.run(startup_prog)呢？

在train_loop()里面加了exe.run(startup_prog)的。

如果不用dist.merge()合并变量，有什么办法可以实现蒸馏？比如先运行teacher_program,得输出logits作为student_program的输入参数呢？可行吗？
