### ISSUE TITLE
mobilenetv2 deeplabv3+ pruning问题

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/PaddleSlim#203]
在最新的paddleslim库和paddleseg库上进行mobilenetv2 deeplabv3+的pruning，配置裁剪参数后报以下错误，请问是什么原因。
![image](https://user-images.githubusercontent.com/7035538/78204782-1a80fc80-74cd-11ea-8d02-cd7084c188c8.png)

Parameter[decoder/separable_conv1/pointwise/BatchNorm/beta] loaded sucessfully!
Parameter[decoder/separable_conv1/pointwise/BatchNorm/moving_mean] loaded sucessfully!
Parameter[decoder/separable_conv1/pointwise/BatchNorm/moving_variance] loaded sucessfully!
Parameter[decoder/separable_conv2/depthwise/weights] loaded sucessfully!
Parameter[decoder/separable_conv2/depthwise/BatchNorm/gamma] loaded sucessfully!
Parameter[decoder/separable_conv2/depthwise/BatchNorm/beta] loaded sucessfully!
Parameter[decoder/separable_conv2/depthwise/BatchNorm/moving_mean] loaded sucessfully!
Parameter[decoder/separable_conv2/depthwise/BatchNorm/moving_variance] loaded sucessfully!
Parameter[decoder/separable_conv2/pointwise/weights] loaded sucessfully!
Parameter[decoder/separable_conv2/pointwise/BatchNorm/gamma] loaded sucessfully!
Parameter[decoder/separable_conv2/pointwise/BatchNorm/beta] loaded sucessfully!
Parameter[decoder/separable_conv2/pointwise/BatchNorm/moving_mean] loaded sucessfully!
Parameter[decoder/separable_conv2/pointwise/BatchNorm/moving_variance] loaded sucessfully!
Parameter[logit/weights] loaded sucessfully!
Parameter[logit/biases] loaded sucessfully!
332/332 pretrained parameters loaded successfully!
Traceback (most recent call last):
  File "./slim/prune/train_prune.py", line 504, in <module>
    main(args)
  File "./slim/prune/train_prune.py", line 491, in main
    train(cfg)
  File "./slim/prune/train_prune.py", line 347, in train
    only_graph=False)[0]
  File "/home/hpc/ccx/paddle1.7/PaddleSlim/paddleslim/prune/pruner.py", line 82, in prune
    param_t = np.array(scope.find_var(param).get_tensor())
AttributeError: 'NoneType' object has no attribute 'get_tensor'

@wanghaoshuang

**Comment by wanghaoshuang** [comment]
log提示在scope中没找到要待裁剪的变量，有可能：
1. 带裁剪的参数的名称写错了;请参考这里确认下参数名称：https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.2/slim/prune#3-%E7%A1%AE%E5%AE%9A%E5%BE%85%E5%88%86%E6%9E%90%E5%8F%82%E6%95%B0
2. scope设置的有问题

把您的脚本贴出来？

**Comment by A1exy** [comment]
python -u ./slim/prune/train_prune.py --log_steps 10 --cfg configs/deeplabv3p_mobilenet-1-0_pet.yaml --use_gpu --use_mpio \
SLIM.PRUNE_PARAMS 'conv2_1_linear_weights, conv3_1_linear_weights, conv3_2_linear_weights, conv4_1_linear_weights, conv4_2_linear_weights, conv4_3_linear_weights, conv5_1_linear_weights, conv5_2_linear_weights, conv5_3_linear_weights, conv5_4_linear_weights, conv6_1_linear_weights, conv6_2_linear_weights, conv6_3_linear_weights, conv7_1_linear_weights, conv7_2_linear_weights, conv7_3_linear_weights, conv8_1_linear_weights, conv2_1_expand_weights, conv3_1_expand_weights, conv3_2_expand_weights, conv4_1_expand_weights, conv4_2_expand_weights, conv4_3_expand_weights, conv5_1_expand_weights, conv5_2_expand_weights, conv5_3_expand_weights, conv5_4_expand_weights, conv6_1_expand_weights, conv6_2_expand_weights, conv6_3_expand_weights, conv7_1_expand_weights, conv7_2_expand_weights, conv7_3_expand_weights, conv8_1_expand_weights' \
SLIM.PRUNE_RATIOS '[0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]'

**Comment by A1exy** [comment]
裁剪的参数名称应该没什么问题。@wanghaoshuang
![image](https://user-images.githubusercontent.com/7035538/78235912-dfea8480-750b-11ea-99d9-2a1a5f586009.png)

**Comment by A1exy** [comment]
@wanghaoshuang 能回复下不，是现在deeplab v3+的裁剪还不支持吗？

**Comment by wanghaoshuang** [comment]
把train_prune.py 的内容贴一下？看着是scope设置错了。是支持deeplabv3的。

**Comment by A1exy** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/slim/prune/train_prune.py

@wanghaoshuang  用的就是你们paddleslim库的文件，就执行的命令修改了下。

执行命令见3L

**Comment by wanghaoshuang** [comment]
```
python -u ./slim/prune/train_prune.py --log_steps 10 --cfg configs/deeplabv3p_mobilenet-1-0_pet.yaml --use_gpu --use_mpio
SLIM.PRUNE_PARAMS 'conv2_1_linear_weights, conv3_1_linear_weights, conv3_2_linear_weights, conv4_1_linear_weights, conv4_2_linear_weights, conv4_3_linear_weights, conv5_1_linear_weights, conv5_2_linear_weights, conv5_3_linear_weights, conv5_4_linear_weights, conv6_1_linear_weights, conv6_2_linear_weights, conv6_3_linear_weights, conv7_1_linear_weights, conv7_2_linear_weights, conv7_3_linear_weights, conv8_1_linear_weights, conv2_1_expand_weights, conv3_1_expand_weights, conv3_2_expand_weights, conv4_1_expand_weights, conv4_2_expand_weights, conv4_3_expand_weights, conv5_1_expand_weights, conv5_2_expand_weights, conv5_3_expand_weights, conv5_4_expand_weights, conv6_1_expand_weights, conv6_2_expand_weights, conv6_3_expand_weights, conv7_1_expand_weights, conv7_2_expand_weights, conv7_3_expand_weights, conv8_1_expand_weights'
SLIM.PRUNE_RATIOS '[0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]'
```

SLIM.PRUNE_PARAMS中参数间以逗号分割，不能有空格。你去掉空格试试？

**Comment by A1exy** [comment]
好的，多谢

**Comment by JensenHJS** [comment]
同样的问题，原因在于剪裁参数太多，可能复制的时候就多加了空格
