### ISSUE TITLE
用quant_post量化了一个yolov3_darknet的的模型，推理加载出错

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/PaddleSlim#204]
环境：
paddle1.7
出错信息：
PaddleCheckError: OP(LoadCombine) fail to open file ..\yolov3_darknet_quant_924\__params__, please check whether the mod
el file is complete or damaged. at [D:\1.6.1\paddle\paddle/fluid/operators/load_combine_op.h:46]

量化代码
`def quantize():
    val_reader = mjreader.custom_reader(images_lists, data_dir, input_size,mode)
    place = fluid.CUDAPlace(0) 
    exe = fluid.Executor(place)
    quant_post(
        executor=exe,
        model_dir='../work/PaddleDetection/yolov3_freeze/yolov3_darknet',
        quantize_model_path='./yolov3_darknet_quant_924/',
        sample_generator=val_reader,
        model_filename='__model__',
        params_filename='__params__',
        batch_size=16,
        batch_nums=20)       
def main():
    quantize()`
用quant_post量化了一个yolov3_darknet的的模型，得到的模型如何进行加载推理

**Comment by aixier** [comment]
量化前模型：链接: https://pan.baidu.com/s/1Fursj2ui6uxjL2fNlcoseg 提取码: xxsf
量化后模型：链接: https://pan.baidu.com/s/1zGtHT-v-BJNcBosU22HAMw 提取码: t437 
模型加载方式：
` path = "../yolov3_darknet_quant_924/"
    [inference_program, feed_target_names, fetch_targets] = (fluid.io.load_inference_model(
        dirname=path, executor=exe, model_filename='__model__', params_filename='__params__'))`

**Comment by itminner** [comment]
量化后的模型，保存的是散装的参数，加载时只需要指定dirname就可以了，不需要指定model_filename和params_filename。示例如下：
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model( dirname=path, executor=exe)

如果指定了params_filename，程序会从dirname文件夹下找名字为params_filename的文件

**Comment by A1exy** [comment]
@itminner 我在xavier和2080ti下测试离线量化的MobileNet模型并没有什么加速效果啊，请问是什么原因

**Comment by A1exy** [comment]
@itminner 请问你测试的离线量化后的模型有加速效果吗？

**Comment by slf12** [comment]
> @itminner 请问你测试的离线量化后的模型有加速效果吗？

可以看下这个文档
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/FAQ/quantization_FAQ.md

![image](https://user-images.githubusercontent.com/8036226/78632463-a5993280-78d1-11ea-84c4-7976ba6e0ffd.png)

**Comment by A1exy** [comment]
@slf12  你们的文档我有一点问题，我是在GPU下使用，请问我现在用paddleslim离线量化的模型，可以直接开启TensorRT int8量化就可以加速吗？应该不可以吧，是不是还需要我走一遍TensorRT int8量化校准的流程，然后才能在GPU上用tensorRT int8加速？

**Comment by slf12** [comment]
> @slf12 你们的文档我有一点问题，我是在GPU下使用，请问我现在用paddleslim离线量化的模型，可以直接开启TensorRT int8量化就可以加速吗？应该不可以吧，是不是还需要我走一遍TensorRT int8量化校准的流程，然后才能在GPU上用tensorRT int8加速？

不需要走一遍Tensorrt int8校准的流程，paddleslim离线量化和tensorrt int8校准原理是一样的。直接使用tensorrt预测即可

**Comment by A1exy** [comment]
@slf12 好的，多谢
