### ISSUE TITLE
模型量化后运行预测速度会提高吗？

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/PaddleSlim#211]
如题

**Comment by slf12** [comment]
可以加速。

可以看下这个文档
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/FAQ/quantization_FAQ.md

![image](https://user-images.githubusercontent.com/8036226/78632463-a5993280-78d1-11ea-84c4-7976ba6e0ffd.png)

**Comment by JensenHJS** [comment]
如果想要量化后加速，在tx2这类嵌入式GPU上使用(CPU是arm的，带GPU），推荐哪种方式呢？paddle-lite还是paddle-tensorrt？
