### ISSUE TITLE
我在用slim剪枝时优化器报错怎么解决

### ISSUE THREAD

**Issue by JLei67** [PaddlePaddle/PaddleSlim#217]
pruned_program, _, _ = pruner.prune(train_program, fluid.global_scope(),
        params=ratios.keys(),ratios=ratios.values(), place=place)

报错为：Error: Param and Velocity of MomentumOp should have the same dimension.
  [Hint: Expected param_dim == ctx->GetInputDim("Velocity"), but received param_dim:12544, 4096 != ctx->GetInputDim("Velocity"):24832, 4096.] at (/paddle/paddle/fluid/operators/optimizers/momentum_op.h:79)
  [operator < momentum > error]
应该是说参数数量不匹？但我剪枝的话参数数量肯定会减少吧

**Comment by JLei67** [comment]
InvalidArgumentError: Param and Moment1 input of AdamOp should have same dimension. But received Param dims: [12544, 4096], Moment1 dims: [24832, 4096].
  [Hint: Expected param_dims == ctx->GetInputDim("Moment1"), but received param_dims:12544, 4096 != ctx->GetInputDim("Moment1"):24832, 4096.] at (/paddle/paddle/fluid/operators/optimizers/adam_op.cc:113)
  [operator < adam > error]
我把momentum优化器改成adam也一样报错

**Comment by wanghaoshuang** [comment]
请问Paddle版本和PaddleSlim版本分别是？剪裁的什么模型？

**Comment by JLei67** [comment]
> 请问Paddle版本和PaddleSlim版本分别是？剪裁的什么模型？

paddle是1.7.0 Slim是1.0.1   裁剪的VGG16

**Comment by wanghaoshuang** [comment]
您好，您是不是对全连接层也剪裁了，目前PaddleSlim仅支持对卷积层进行剪裁。
我尝试了对以下参数剪裁：
```
conv1_1_weights
conv1_2_weights
conv2_1_weights
conv2_2_weights
conv3_1_weights
conv3_2_weights
conv3_3_weights
conv4_1_weights
conv4_2_weights
conv4_3_weights
conv5_1_weights
conv5_2_weights
conv5_3_weights
```
结果没问题：
```
2020-04-10 09:50:21,052-INFO: FLOPs before pruning: 224035840.0
2020-04-10 09:50:22,939-INFO: FLOPs after pruning: 116490088.0
```

**Comment by wanghaoshuang** [comment]
请试下只指定剪裁卷积层？如果还不行，把您的脚本内容贴出来我看下？

**Comment by JLei67** [comment]
[](url)

> 请试下只指定剪裁卷积层？如果还不行，把您的脚本内容贴出来我看下？

https://aistudio.baidu.com/aistudio/projectdetail/329668
这是我的项目，您看下能看到吗？

**Comment by JLei67** [comment]
> 请试下只指定剪裁卷积层？如果还不行，把您的脚本内容贴出来我看下？

我选取参数的时候限定了名字要带 covn和 weight，应该是只裁剪了卷积层

**Comment by wanghaoshuang** [comment]
我将您项目中的剪裁调用代码改为如下，可以正确执行，应该是不能剪裁最后一层的卷积，因为会对FC层造成影响。请您先别剪裁最后一层卷积？我们继续优化下这个问题。
```
pruned_program, _, _ = pruner.prune(
        train_program,
        fluid.global_scope(),
#        params=ratios.keys(),
        params=['conv1_1_weights', 'conv1_2_weights', 'conv2_1_weights', 'conv2_2_weights', 'conv3_1_weights', 'conv3_2_weights', 'conv3_3_weights', 'conv4_1_weights', 'conv4_2_weights', 'conv4_3_weights', 'conv5_1_weights', 'conv5_2_weights'],
#        ratios=ratios.values(),
        ratios=[0.5]*12,
        place=place)
```

**Comment by JLei67** [comment]
> 我将您项目中的剪裁调用代码改为如下，可以正确执行，应该是不能剪裁最后一层的卷积，因为会对FC层造成影响。请您先别剪裁最后一层卷积？我们继续优化下这个问题。
> 
> ```
> pruned_program, _, _ = pruner.prune(
>         train_program,
>         fluid.global_scope(),
> #        params=ratios.keys(),
>         params=['conv1_1_weights', 'conv1_2_weights', 'conv2_1_weights', 'conv2_2_weights', 'conv3_1_weights', 'conv3_2_weights', 'conv3_3_weights', 'conv4_1_weights', 'conv4_2_weights', 'conv4_3_weights', 'conv5_1_weights', 'conv5_2_weights'],
> #        ratios=ratios.values(),
>         ratios=[0.5]*12,
>         place=place)
> ```

好的，谢谢您
