### ISSUE TITLE
关于量化的问题

### ISSUE THREAD

**Issue by hp-cuiwb** [PaddlePaddle/PaddleSlim#218]
文档中关于量化的配置：
weight_bits(int) - 参数量化bit数，默认8, 可选1-8，推荐设为8，因为量化后的数据类型是 int8 。
activation_bits(int) - 激活量化bit数，默认8，可选1-8，推荐设为8，因为量化后的数据类型是 int8 。
dtype(int8) - 量化后的参数类型，默认 int8 , 目前仅支持 int8 。
请问我如果把weight_bits(int) 设为7，把activation_bits(int)设为7，然后训练，模型的结果相当于7bit量化吗？

**Comment by slf12** [comment]
> 文档中关于量化的配置：
> weight_bits(int) - 参数量化bit数，默认8, 可选1-8，推荐设为8，因为量化后的数据类型是 int8 。
> activation_bits(int) - 激活量化bit数，默认8，可选1-8，推荐设为8，因为量化后的数据类型是 int8 。
> dtype(int8) - 量化后的参数类型，默认 int8 , 目前仅支持 int8 。
> 请问我如果把weight_bits(int) 设为7，把activation_bits(int)设为7，然后训练，模型的结果相当于7bit量化吗？

是的， 在量化时最大值是std::pow(2, bit_length - 1) - 1; 
但是需要注意的是，weight_bits(int) 设为7，把activation_bits(int)设为7，只能测试低比特量化在精度损失上的效果，转化成预测库能加载的模型时，目前是仍会按照int8处理，所以在预测时和int8是一样的

**Comment by hp-cuiwb** [comment]
您的思思是，数据前向推断是8bit的范围表示，实际值还是7bit的范围是吗？

**Comment by slf12** [comment]
> 您的思思是，数据前向推断是8bit的范围表示，实际值还是7bit的范围是吗？

数值范围是7bit，数据类型仍然是int8

**Comment by hp-cuiwb** [comment]
好的，明白，感谢
