### ISSUE TITLE
请问一下，对于COCO数据集任务的蒸馏是对模型整体进行蒸馏吗？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleSlim#221]
尊敬的开发者：
你好！
请问一下，对于COCO数据集的任务来说，模型蒸馏是对模型整体都进行蒸馏吗，还是只对主干网络部分进行蒸馏？
我在飞桨的课程中看到了这样的训练结果，
![图片](https://user-images.githubusercontent.com/27288110/79204572-5c1b8b00-7e6f-11ea-8612-49b111d35e18.png)

期待你的回复！

**Comment by baiyfbupt** [comment]
你好，COCO的蒸馏是对模型整体进行蒸馏的，也就是说同时对backbone和detection head进行蒸馏训练~

**Comment by songyuc** [comment]
@baiyfbupt ，好的，谢谢你的回复！

**Comment by songyuc** [comment]
@baiyfbupt ，还想请教你一下，这里这个COCO的任务，使用FSP蒸馏策略了吗？

**Comment by baiyfbupt** [comment]
没有用FSP策略
