### ISSUE TITLE
请问一下，如果针对COCO数据集的目标检测任务，使用强化学习策略进行NAS搜索有什么推荐的配置吗？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleSlim#222]
尊敬的开发者：
你好！
想请教一下，对于COCO数据集的目标检测任务，使用强化学习策略进行NAS搜索，有什么推荐的GPU配置吗？
我想知道我们现在的GPU服务器的配置是否适合这个任务，
期待你的回复！

**Comment by ceci3** [comment]
您好，对GPU配置没有什么要求，只要显存足够运行您搜索空间中的子模型就可以了。

**Comment by wanghaoshuang** [comment]
@songyuc 不建议使用强化学习对检测任务进行搜索，因为COCO检测任务训练比较慢，而且强化学习又是比较好资源的算法，所以实际的可行性并不高。

建议有限考虑蒸馏，如果有模型压缩需求可以试一下剪裁和量化。

如果确实需要使用NAS提升模型精度，可以参考PaddleSlim中DARTS的示例，自己设计一个搜索空间，尝试搜索下。目前我们还没来得及在检测任务上尝试DARTS策略，后续我们会进行该实验。

期待您的持续关注。

**Comment by songyuc** [comment]
谢谢各位老师的解答！
