### ISSUE TITLE
请问一下，硬件延时表，PaddleSlim是会自动测量吗，还是需要我们给出呀？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleSlim#223]
尊敬的开发者：
你好！
关于硬件延时表的话，PaddleSlim是会自动测量吗，还是需要我们给出呀？
期待你的回复！

**Comment by ceci3** [comment]
您好，paddleslim有提供读取硬件延时表的操作，不会自动测量。目前硬件延时表还是需要通过paddlelite在自己想要的硬件上测试得到。

**Comment by songyuc** [comment]
@ceci3 ，好的，谢谢您的回复！
