### ISSUE TITLE
slim裁剪，如何获取卷积层名字？

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleSlim#225]
问题一：
官网提供的很多教程都是 基于命令行形式的
但是slim中很多API参数都需要program的概念，我要如何获取这个参数？
比如使用 裁剪的时候，需要先获取卷积层的名字，应该什么方式获取？
模型训练完保存是这样的
![image](https://user-images.githubusercontent.com/49515380/79316896-92bcd880-7f37-11ea-9cc8-1513d5aa5c88.png)

问题二：
slim的API很多都是基于静态图的方法（根据参数来做的判断），在动态图上使用是否有连接教程？

**Comment by wanghaoshuang** [comment]
>官网提供的很多教程都是 基于命令行形式的

您这里说的教程是指？

>但是slim中很多API参数都需要program的概念，我要如何获取这个参数？

如果组网脚本中没有显式的生命program，则可以用fluid.default_main_program()获取默认的program

>比如使用 裁剪的时候，需要先获取卷积层的名字，应该什么方式获取？

可以参考这个链接查看program中parameter的名称，根据命名确定卷积层的参数名称：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html#all_parameters

**Comment by wanghaoshuang** [comment]
>问题二：
slim的API很多都是基于静态图的方法（根据参数来做的判断），在动态图上使用是否有连接教程？

动态图的支持正在规划中，暂时还不支持。

**Comment by jaffe-fly** [comment]
比如我运行训练都是通过这一条命令来做的
!python PaddleSeg/pdseg/train.py  --cfg PaddleSeg/configs/hrnet_optic.yaml --use_gpu  --use_mpio --do_eval

最后自动保存的save_model下面的文件 怎么获取卷积名称来做slim裁剪
![image](https://user-images.githubusercontent.com/49515380/79322859-006d0280-7f40-11ea-8346-9ebab7bde68e.png)
训练完想做裁剪，这儿衔接不起来，不知道怎么操作

**Comment by jaffe-fly** [comment]
可以参考这个回复[https://github.com/PaddlePaddle/PaddleSeg/issues/221](url)
