### ISSUE TITLE
在使用蒸馏时，若teacher program里有包含BIGRU会报错

### ISSUE THREAD

**Issue by dflmingle** [PaddlePaddle/PaddleSlim#233]
在teacher program里
定义
    encoder_fwd_cell =  fluid.layers.GRUCell(hidden_size=128)
    encoder_fwd_output, fwd_state =  fluid.layers.rnn(
        cell=encoder_fwd_cell,
        inputs=emb_out,
        sequence_length=None,
        time_major=False,
        is_reverse=False)
    # 使用GRUCell构建反向RNN
    encoder_bwd_cell =  fluid.layers.GRUCell(hidden_size=128)
    encoder_bwd_output, bwd_state =  fluid.layers.rnn(
        cell=encoder_bwd_cell,
        inputs=emb_out,
        sequence_length=None,
        time_major=False,
        is_reverse=True)
    # 拼接前向与反向GRU的编码结果得到h
    encoder_output =  fluid.layers.concat(
        input=[encoder_fwd_output, encoder_bwd_output], axis=2)
    encoder_output=fluid.layers.elementwise_mul(encoder_output,input_mask,axis=-1)
这个结构的话，就会报错，去掉就可以，估计源码中未考虑到某种情况导致出错

**Comment by baiyfbupt** [comment]
您好，感谢反馈。能否提供一段可完整复现问题的代码，帮助我们持续进行优化，谢谢

**Comment by dflmingle** [comment]
代码较长，一些内容暂不方便公开，是否可以发邮箱

**Comment by baiyfbupt** [comment]
> 代码较长，一些内容暂不方便公开，是否可以发邮箱

可以，请发送到baiyifan02@baidu.com

**Comment by baiyfbupt** [comment]
> 代码较长，一些内容暂不方便公开，是否可以发邮箱

hi，仔细看了您的代码，带GRUCell结构的teacher蒸馏是PaddleSlim目前不支持的
原因是这样的，Paddle程序定义Program类似于一个Python函数，有block的概念，类似于Python作用域

在一般的Paddle程序里只有一个block作用域，也就是program.global_block()，但是在GRU这种Cell结构中，Cell部分作为一个单独的作用域，它的变量都不在global_block()内，导致merge过程从global_block取变量出错，如下这几行。
https://github.com/PaddlePaddle/PaddleSlim/blob/2dc89a6b46d7b18e4f310e98196e97559d67c0fb/paddleslim/dist/single_distiller.py#L65
https://github.com/PaddlePaddle/PaddleSlim/blob/2dc89a6b46d7b18e4f310e98196e97559d67c0fb/paddleslim/dist/single_distiller.py#L71
https://github.com/PaddlePaddle/PaddleSlim/blob/2dc89a6b46d7b18e4f310e98196e97559d67c0fb/paddleslim/dist/single_distiller.py#L94
您可以尝试自行修改一下这段程序，也可以teacher暂时先不用这种Cell结构的网络，等待我们来修复

**Comment by dflmingle** [comment]
好的，我经debug发现了，grucell里有三个作用域，global block只涉及到第一个，但我尝试在这方面调了调，在其他方面又会报新的错，对paddlepaddle的底层还是没有你们那么了解，只是希望你们在以后的版本中有进一步的优化



---原始邮件---
发件人: "Bai Yifan"<notifications@github.com&gt;
发送时间: 2020年4月26日(星期日) 上午10:11
收件人: "PaddlePaddle/PaddleSlim"<PaddleSlim@noreply.github.com&gt;;
抄送: "dflmingle"<583025216@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleSlim] 在使用蒸馏时，若teacher program里有包含BIGRU会报错 (#233)




  
代码较长，一些内容暂不方便公开，是否可以发邮箱
  
hi，仔细看了您的代码，带GRUCell结构的蒸馏是PaddleSlim目前不支持的
 原因是这样的，Paddle程序定义Program类似于一个Python函数，有block的概念，类似于Python作用域
 
在一般的Paddle程序里只有一个block作用域，也就是program.global_block()，但是在GRU这种Cell结构中，Cell部分作为一个单独的作用域，它的变量都不在global_block()内，导致merge过程从global_block取变量出错，如下这几行。
 https://github.com/PaddlePaddle/PaddleSlim/blob/2dc89a6b46d7b18e4f310e98196e97559d67c0fb/paddleslim/dist/single_distiller.py#L65
 https://github.com/PaddlePaddle/PaddleSlim/blob/2dc89a6b46d7b18e4f310e98196e97559d67c0fb/paddleslim/dist/single_distiller.py#L71
 https://github.com/PaddlePaddle/PaddleSlim/blob/2dc89a6b46d7b18e4f310e98196e97559d67c0fb/paddleslim/dist/single_distiller.py#L94
 您可以尝试自行修改一下这段程序，也可以暂时先不用这种Cell结构的网络，等待我们来修复
