### ISSUE TITLE
为什么PaddleSlim模型量化时不量化卷积层的偏置？

### ISSUE THREAD

**Issue by zhizunbao-y** [PaddlePaddle/PaddleSlim#241]
另外，对于激活值得量化，为什么一般采用滑动窗口平均得办法，而不是最简单得abs_max，有什么依据吗？

**Comment by slf12** [comment]
> 另外，对于激活值得量化，为什么一般采用滑动窗口平均得办法，而不是最简单得abs_max，有什么依据吗？

关于量化偏置，量化偏置对精度或者速度没有明显帮助。

abs_max在预测部署时很慢，每次都需要找绝对值最大值，严重影响了预测速度，所以不推荐使用。

**Comment by zhizunbao-y** [comment]
@slf12 模型在预测部署阶段，权值保持不变的，仅需计算一次；输入只有一个，且是不确定的，每次前向推测需要计算一次；而激活值有多个，且作为下一层结构的输入也是不断变化的，每次迭代需要计算多次，所以为了节省运算时间和计算资源，对于模型输入和权重，采用动态计算比例系数；而对于激活值采用静态策略计算。请问这样理解对吗？

**Comment by slf12** [comment]
> @slf12 模型在预测部署阶段，权值保持不变的，仅需计算一次；输入只有一个，且是不确定的，每次前向推测需要计算一次；而激活值有多个，且作为下一层结构的输入也是不断变化的，每次迭代需要计算多次，所以为了节省运算时间和计算资源，对于模型输入和权重，采用动态计算比例系数；而对于激活值采用静态策略计算。请问这样理解对吗？

是的，你理解的是对的。有一点是预测部署时，weight已经是int8了，不需要计算比例系数。

**Comment by zhizunbao-y** [comment]
感谢解答！
