### ISSUE TITLE
官方文档的图片很多都加载不出来呀

### ISSUE THREAD

**Issue by 312shan** [PaddlePaddle/PaddleSlim#245]
[参考这个页面](https://paddlepaddle.github.io/PaddleSlim/algo/algo.html)

![image](https://user-images.githubusercontent.com/12961274/80474887-a0804e00-897a-11ea-9549-e6b8f2be69f9.png)

**Comment by wanghaoshuang** [comment]
github提供的托管服务不太稳定，我们现在已经将文档迁移到了readthedocs:
https://paddleslim.readthedocs.io/zh_CN/latest/
