### ISSUE TITLE
报错cannot import name 'quant_aware'

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleSlim#305]
from paddleslim.quant import quant_aware, convert
ImportError: cannot import name 'quant_aware'
安装了paddleslim也报这个错，paddle是1.7版本slim是1.1.1。请问怎么解决

**Comment by thunder95** [comment]
遇到了同样的问题

**Comment by thunder95** [comment]
我把版本降低到了paddleslim-1.0.1就可以了

**Comment by slf12** [comment]
![image](https://user-images.githubusercontent.com/8036226/82974069-9ef28600-a00b-11ea-9340-a7209b60bed1.png)
请参考这个版本对应
