### ISSUE TITLE
使用手册里的步骤进行量化训练出错

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleSlim#316]
paddle1.7.1
slim1.0.1
使用https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/slim/quantization里面的命令行进行量化训练出错。命令如下
python slim/quantization/train.py --not_quant_pattern yolo_output \
    --eval \
    -c ./configs/yolov3_mobilenet_v1.yml \
    -o max_iters=30000 \
    save_dir=./output/yolov3_mobilenet_v1_coco_quantization \
    LearningRate.base_lr=0.0001 \
    LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]" \
    pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1.tar

发现在if FLAGS.eval: 里进入eval_results函数，返回值box_ap_stats是空的list
改为voc上训练，也会出错

**Comment by slf12** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/811 已解决，麻烦关闭issue
