### ISSUE TITLE
在GPU上量化后加速的问题

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleSlim#317]
文档里说在GPU上量化后加速,要使用paddle-tensorrt这个方式，但是paddle-tensorrt例子里面似乎只有一个moblinet的例子程序？

**Comment by JensenHJS** [comment]
sample链接
https://paddle-inference-dist.bj.bcebos.com/tensorrt_test/paddle_inference_sample_v1.7.tar.gz

**Comment by slf12** [comment]
是的，更多的benckmark和教程文档正在整理中，预计这个月底上线。
