### ISSUE TITLE
paddleslim 知识蒸馏demo的问题

### ISSUE THREAD

**Issue by lastrei** [PaddlePaddle/PaddleSlim#318]
在进行到查看Variables这一步后，进行合并蒸馏loss，这时候报错
: var depthwise_conv2d_11.tmp_0 not in this block
查看Variables发现 student的Variables里并没有depthwise_conv2d_11.tmp_0

通过观察发现 student模型中的depthwise_conv2d_24.tmp_0与teacher中的teacher_bn5c_branch2b.output.1.tmp_3的尺寸一致都是(-1, 512, 1, 1)

所以把demo中的合并蒸馏loss改成了
```python
data_name_map = {'image': 'image'}
main = slim.dist.merge(teacher_program, student_program, data_name_map, fluid.CPUPlace())
with fluid.program_guard(student_program, student_startup):
    l2_loss = slim.dist.l2_loss('teacher_bn5c_branch2b.output.1.tmp_3', 'depthwise_conv2d_24.tmp_0', student_program)
    loss = l2_loss + avg_cost
    opt = fluid.optimizer.Momentum(0.01, 0.9)
    opt.minimize(loss)
exe.run(student_startup)
```

但是最后一步训练的时候又报这个错误
```bash
InvalidArgumentError: ShapeError: the shape of scale must equal to [32]But received: the shape of scale is [64]
  [Hint: Expected scale_dim[0] == C, but received scale_dim[0]:64 != C:32.] at (/paddle/paddle/fluid/operators/batch_norm_op.cc:116)
  [operator < batch_norm > error]
```

麻烦请看一下，执行是在aistudio平台,麻烦看一下谢谢

**Comment by baiyfbupt** [comment]
>在进行到查看Variables这一步后，进行合并蒸馏loss，这时候报错
: var depthwise_conv2d_11.tmp_0 not in this block
查看Variables发现 student的Variables里并没有depthwise_conv2d_11.tmp_0

你好，我这里测试aistudio demo是可以正常运行的，是否改动了代码呢？

**Comment by lastrei** [comment]
改本地运行后没有出现这个问题.还有个问题请教一下，是否只要教师模型中的和student模型中的某一对Variables维度一致就可以直接组成l2_loss ？还需要考虑其他的问题么？谢谢！

**Comment by baiyfbupt** [comment]
> 改本地运行后没有出现这个问题.还有个问题请教一下，是否只要教师模型中的和student模型中的某一对Variables维度一致就可以直接组成l2_loss ？还需要考虑其他的问题么？谢谢！

没有其他限制，只要shape一致就可以加蒸馏loss，但是效果如何得看实验情况

**Comment by lastrei** [comment]
> > 改本地运行后没有出现这个问题.还有个问题请教一下，是否只要教师模型中的和student模型中的某一对Variables维度一致就可以直接组成l2_loss ？还需要考虑其他的问题么？谢谢！
> 
> 没有其他限制，只要shape一致就可以加蒸馏loss，但是效果如何得看实验情况

感谢！是否考虑加入方放直接提取出shape一致的Variable，目前看demo中的示例都是直接观察，有点麻烦：），此外选取的时候是否有经验可以分享一下！谢谢！

**Comment by baiyfbupt** [comment]
@lastrei 感谢建议，我们会考虑增加:)

经验是`l2_loss和soft_label_loss`可以选择最后fc输出得到logits，`fsp_loss`尽量选择CNN网络中间层的feature_map，这样在多数任务上往往是效果比较好的

**Comment by Sejudyblues** [comment]
> 在进行到查看Variables这一步后，进行合并蒸馏loss，这时候报错
> : var depthwise_conv2d_11.tmp_0 not in this block
> 查看Variables发现 student的Variables里并没有depthwise_conv2d_11.tmp_0
> 
> 通过观察发现 student模型中的depthwise_conv2d_24.tmp_0与teacher中的teacher_bn5c_branch2b.output.1.tmp_3的尺寸一致都是(-1, 512, 1, 1)
> 
> 所以把demo中的合并蒸馏loss改成了
> 
> ```python
> data_name_map = {'image': 'image'}
> main = slim.dist.merge(teacher_program, student_program, data_name_map, fluid.CPUPlace())
> with fluid.program_guard(student_program, student_startup):
>     l2_loss = slim.dist.l2_loss('teacher_bn5c_branch2b.output.1.tmp_3', 'depthwise_conv2d_24.tmp_0', student_program)
>     loss = l2_loss + avg_cost
>     opt = fluid.optimizer.Momentum(0.01, 0.9)
>     opt.minimize(loss)
> exe.run(student_startup)
> ```
> 
> 但是最后一步训练的时候又报这个错误
> 
> ```shell
> InvalidArgumentError: ShapeError: the shape of scale must equal to [32]But received: the shape of scale is [64]
>   [Hint: Expected scale_dim[0] == C, but received scale_dim[0]:64 != C:32.] at (/paddle/paddle/fluid/operators/batch_norm_op.cc:116)
>   [operator < batch_norm > error]
> ```
> 
> 麻烦请看一下，执行是在aistudio平台,麻烦看一下谢谢

麻烦问下 我运行这个demo到 model = models.__dict__['mobilenet']() 这句的时候 就提醒错误了  说没有models没有定义。
