### ISSUE TITLE
关于量化的一些使用问题

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/PaddleSlim#321]
1. 量化训练完成后保存的模型是否保存了量化参数？如果有，怎么提取量化参数（每层输入输出和权重）？
2. 量化的type 包含mul ,bn 中的mul 也会被量化吗？
3. model有多种save 方式，包括检查点中的best_model，__model__，对应的除了检查点中包含训练的tmp梯度，还有什么区别吗？
4. 修改默认量化位宽为7bit，进行 量化训练，对训练后的模型convert 成量化模型（包括float和int）,int模型的权重范围还是【-128,127】，这个要怎么修改？
5. 量化推断模型实际的数据流是量化后的int7数据还是float32的模型？
6. 量化模型在做推断时，是怎么处理add,concat，等这些没有参数的层的？ 」

**Comment by wanghaoshuang** [comment]
>1. 量化训练完成后保存的模型是否保存了量化参数？如果有，怎么提取量化参数（每层输入输出和权重）？

在调用[quant-aware](https://paddleslim.readthedocs.io/zh_CN/latest/api_cn/quantization_api.html#quant-aware)时，需要传入一个program，可以通过这个还没有量化的program拿到模型参数名称，量化前后模型参数名不会变。通过参数名再从scope中拿到参数的数值。方式如下：

```
for param program.all_parameters():
    param_n = numpy.array(fluid.global_scope().find_var(param.name).get_tensor())
    print("name: {}; shape: {}".format(param.name, param_n.shape))
```

另外，量化后的模型还有scale参数，scale参数的命名方式为参数名或激活变量名称加后缀‘.scale’，比如卷积参数“conv_1.weights”对应的scale变量名称就是‘conv_1.weights.scale’

**Comment by wanghaoshuang** [comment]
> 2. 量化的type 包含mul ,bn 中的mul 也会被量化吗？

不会，因为bn中的乘scale的操作是在batch norm operator内部实现的

**Comment by wanghaoshuang** [comment]
> 3. model有多种save 方式，包括检查点中的best_model，model，对应的除了检查点中包含训练的tmp梯度，还有什么区别吗？

检查点中包含恢复训练所用的所有信息，但是不包含网络。
save_infrence_model保存的模型会对网络进行剪裁，得到用于预测的最小子网络，并会同时保存网络结构和参数。

**Comment by wanghaoshuang** [comment]
>4. 修改默认量化位宽为7bit，进行 量化训练，对训练后的模型convert 成量化模型（包括float和int）,int模型的权重范围还是【-128,127】，这个要怎么修改？

因为Paddle的预测库不支持int7的计算，所以最终的存储数值还是用int8存储的，如果一定要存成int7, 可以直接转成int7

**Comment by wanghaoshuang** [comment]
> 5. 量化推断模型实际的数据流是量化后的int7数据还是float32的模型？

Paddle的预测库PaddleLite只支持量化成int8的模型，在实际推断过程中，是使用int8计算的，部分没有量化的operator还是用float32数值阶段。

**Comment by wanghaoshuang** [comment]
> 6. 量化模型在做推断时，是怎么处理add,concat，等这些没有参数的层的？

会将前续operator的输出转成float32，然后再经过add计算，concat就是对前续operator的结果直接concat

**Comment by zyxcambridge** [comment]
> > 1. 量化训练完成后保存的模型是否保存了量化参数？如果有，怎么提取量化参数（每层输入输出和权重）？
> 
> 在调用[quant-aware](https://paddleslim.readthedocs.io/zh_CN/latest/api_cn/quantization_api.html#quant-aware)时，需要传入一个program，可以通过这个还没有量化的program拿到模型参数名称，量化前后模型参数名不会变。通过参数名再从scope中拿到参数的数值。方式如下：
> 
> ```
> for param program.all_parameters():
>     param_n = numpy.array(fluid.global_scope().find_var(param).get_tensor())
>     print(param_n)
> ```
> 
> 另外，量化后的模型还有scale参数，scale参数的命名方式为参数名或激活变量名称加后缀‘.scale’，比如卷积参数“conv_1.weights”对应的scale变量名称就是‘conv_1.weights.scale’

    # insert quantize op in train_prog, return type is CompiledProgram
    print("==========================================================")
    for param in train_prog.all_parameters():
        param_n = np.array(fluid.global_scope().find_var(param).get_tensor())
        print(param_n)
    train_prog_quant = quant_aware(train_prog, place, config, for_test=False)


    param_n = np.array(fluid.global_scope().find_var(param).get_tensor())
TypeError: find_var(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx._Scope, name: str) -> paddle.fluid.core_avx.Variable

Invoked with: <paddle.fluid.core_avx._Scope object at 0x7f82f6af5618>, name: "yolo_input.conv.weights"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: 32
      dims: 3
      dims: 3
      dims: 3
    }
  }
}

**Comment by wanghaoshuang** [comment]
@zyxcambridge 
Updated code in question 1:
```
for param program.all_parameters():
    param_n = numpy.array(fluid.global_scope().find_var(param.name).get_tensor())
    print("name: {}; shape: {}".format(param.name, param_n.shape))
```

**Comment by aboutmei** [comment]
question4：因为Paddle的预测库不支持int7的计算，所以最终的存储数值还是用int8存储的
paddle的预测库不支持int7推断是paddlelite使用的量化公式是默认int8的原因吗？

如果一定要存成int7, 可以直接转成int7
是在convert的时候转吗？具体要怎么修改呢？

**Comment by aboutmei** [comment]
1 . quantization下的infer.py中，load 的weight 是int8的model 和dequan的scale跑的推断对吧？
2 . 对于一个卷积块来说我可不可以这样理解数据流向：输入 int8  weight int8 做conv2d，然后对conv2d的输出dequant成float，做bn和lrelu，再对输出做int8的量化作为下层的输入？
3 . 我在训练的时候train_aware 的config 为       
'weight_quantize_type': 'channel_wise_abs_max',
        'activation_quantize_type': 'moving_average_abs_max',
        'quantize_op_types': ['depthwise_conv2d', 'mul', 'conv2d'],
        'not_quant_pattern': not_quant_pattern,
        'weight_bits': 7,
        'activation_bits': 7
权重的scale 没有保存，只有Lrelu的量化scale，shape为1 没有按照逐通道量化？
还是我的配置有问题?

**Comment by qingqing01** [comment]
> 如果一定要存成int7, 可以直接转成int7
>  是在convert的时候转吗？具体要怎么修改呢？

int7当前只能用int8或float32的类型表示吧，值的范围可以是int7。  但int7的类型不支持，Python，Paddle都没有此类型。  能问下您为什么需要int7吗？

**Comment by qingqing01** [comment]
>  1 . quantization下的infer.py中，load 的weight 是int8的model 和dequan的scale跑的推断对吧？

这个调用Paddle的预测，非PaddleLite或TensorRT时，只能加载fp32的weight和dequant的scale跑推断看下精度值。whl包安装的Paddle预测不支持加载INT8的模型。

> 2 . 对于一个卷积块来说我可不可以这样理解数据流向：输入 int8 weight int8 做conv2d，然后对conv2d的输出dequant成float，做bn和lrelu，再对输出做int8的量化作为下层的输入？

推理过程你理解的没错，是这样。


> 权重的scale 没有保存

训练得到的权重，之后会固定不变，这里直接保存成了目标bit的范围，没有保存scale，但weight的scale已经放到了反量化op的属性里了。

**Comment by aboutmei** [comment]
slim/quantization/train.py  权重7bit  激活8bit 量化训练
2020-06-04 19:23:59,367-WARNING: recv endsignal from outq with errmsg[consumer[consumer-807-6] failed to map with error:[]]
请问这个是什么原因？

**Comment by aboutmei** [comment]
yolov3_darknet_voc  量化训练时候的  window size 10000代表什么含义？
在量化训练的时候可以添加权重阶段吗？把浮点权重约束在自定义的范围内。leaky_relu_0.tmp_0.scale
elementwise_add_12.scale  concat_0.tmp_0.scale 就是训练后反量化的scale吗？

**Comment by qingqing01** [comment]
@justinmeibi  上面错误一般是reader出现了啥问题，不确定是不是多进程reader中一个进程挂了。 得详细的信息更好排查。

window size的含义：是在训练中统计激活的scale时，可以选取一个窗口大小(step大小)内数据，采用滑动平均等方式进行统计scale。

> 在量化训练的时候可以添加权重阶段吗？把浮点权重约束在自定义的范围内

是权重采用自己定义的量化方式吗？


> leaky_relu_0.tmp_0.scale
elementwise_add_12.scale concat_0.tmp_0.scale 就是训练后反量化的scale吗？

是量化需要的scale， 反量化也会用到此scale。
