### ISSUE TITLE
保存量化模型时出现奇怪问题

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/PaddleSlim#333]
你好！我在paddle-1.7.2或1.8.1下用paddleslim压缩模型（transformer)，在保存量化模型时，有时可以通过，但经常退出并提示：
Aborted at 1591265021 (unix time) try "date -d @1591265021" if you are using GNU date
查百度发现这个问题叫普遍，其它框架下也有，到底什么原因呢？

**Comment by dlkht** [comment]
详细一点：

2020-06-04 10:03:41,861-INFO: convert config {'quantize_op_types': ['conv2d', 'depthwise_conv2d', 'mul'], 'for_tensorrt': False, 'is_full_quantize': False, 'weight_bits': 8, 'dtype': 'int8', 'not_quant_pattern': ['skip_quant'], 'moving_rate': 0.9, 'activation_bits': 8, 'window_size': 10000, 'weight_quantize_type': 'abs_max', 'activation_quantize_type': 'moving_average_abs_max'}
W0604 10:03:41.863718   401 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0604 10:03:41.863734   401 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0604 10:03:41.863752   401 init.cc:214] The detail failure signal is:

W0604 10:03:41.863757   401 init.cc:217] *** Aborted at 1591265021 (unix time) try "date -d @1591265021" if you are using GNU date ***
W0604 10:03:41.864516   401 init.cc:217] PC: @                0x0 (unknown)
W0604 10:03:41.864639   401 init.cc:217] *** SIGSEGV (@0xfffffffcf0372c60) received by PID 401 (TID 0x7f9d14250700) from PID 18446744073444732000; stack trace: ***
W0604 10:03:41.865288   401 init.cc:217]     @     0x7f9d13e2f390 (unknown)
W0604 10:03:41.870870   401 init.cc:217]     @     0x7f9caa112069 paddle::framework::ProgramDesc::ProgramDesc()
W0604 10:03:41.874686   401 init.cc:217]     @     0x7f9caca5ef10 paddle::framework::ir::Graph::Graph()
W0604 10:03:41.876364   401 init.cc:217]     @     0x7f9caa07b5d3 _ZZN8pybind1112cpp_function10initializeIZNS_6detail8initimpl11constructorIJRKN6paddle9framework11ProgramDescEEE7executeINS_6class_INS6_2ir5GraphEJSt10shared_ptrISE_EEEEJELi0EEEvRT_DpRKT0_EUlRNS2_16value_and_holderES9_E_vJSP_S9_EJNS_4nameENS_9is_methodENS_7siblingENS2_24is_new_style_constructorEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES17_
W0604 10:03:41.878095   401 init.cc:217]     @     0x7f9ca9de9c31 pybind11::cpp_function::dispatcher()
W0604 10:03:41.878233   401 init.cc:217]     @           0x4e1307 PyCFunction_Call
W0604 10:03:41.878350   401 init.cc:217]     @           0x5c3bd7 PyObject_Call
W0604 10:03:41.878482   401 init.cc:217]     @           0x4f08be (unknown)
W0604 10:03:41.878589   401 init.cc:217]     @           0x5c3bd7 PyObject_Call
W0604 10:03:41.878726   401 init.cc:217]     @           0x55fa59 (unknown)
W0604 10:03:41.878859   401 init.cc:217]     @           0x579f4c (unknown)
W0604 10:03:41.878962   401 init.cc:217]     @           0x5c3bd7 PyObject_Call
W0604 10:03:41.879094   401 init.cc:217]     @           0x5354af PyEval_EvalFrameEx
W0604 10:03:41.879226   401 init.cc:217]     @           0x539a13 (unknown)
W0604 10:03:41.879354   401 init.cc:217]     @           0x5356a2 PyEval_EvalFrameEx
W0604 10:03:41.879485   401 init.cc:217]     @           0x539a13 (unknown)
W0604 10:03:41.879565   401 init.cc:217]     @           0x53a6cf PyEval_EvalCode
W0604 10:03:41.879700   401 init.cc:217]     @           0x6292c2 (unknown)
W0604 10:03:41.879817   401 init.cc:217]     @           0x62b76a PyRun_FileExFlags
W0604 10:03:41.879889   401 init.cc:217]     @           0x62bf5c PyRun_SimpleFileExFlags
W0604 10:03:41.880007   401 init.cc:217]     @           0x63d506 Py_Main
W0604 10:03:41.880118   401 init.cc:217]     @           0x4cfd11 main
W0604 10:03:41.880800   401 init.cc:217]     @     0x7f9d13a74830 __libc_start_main
W0604 10:03:41.880897   401 init.cc:217]     @           0x5d36e9 _start
W0604 10:03:41.881467   401 init.cc:217]     @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by slf12** [comment]
应该是量化后的模型结构有问题，可以给下压缩配置，slim版本，具体再看看

**Comment by qingqing01** [comment]
> 在保存量化模型时，有时可以通过，但经常退出并提示：
Aborted at 1591265021 (unix time) try "date -d @1591265021" if you are using GNU date


@dlkht  退出时模型是否已经保存了？

**Comment by dlkht** [comment]
> > 在保存量化模型时，有时可以通过，但经常退出并提示：
> > Aborted at 1591265021 (unix time) try "date -d @1591265021" if you are using GNU date
> 
> @dlkht 退出时模型是否已经保存了？

闪退时还不到保存那步，死在执行这句时：
val_program = quant.quant_aware(eval_program1, place, quant_config, scope=None, for_test=True)
到达framework.py如下得地方：
def _construct_from_desc(desc):
                p = Program()
        p.desc = desc      #<=======到这句就死掉
        p.blocks = [Block(p, i) for i in six.moves.range(p.desc.num_blocks())]
        p._sync_with_cpp()
        return p

原因好像是指向非法内存空间

**Comment by slf12** [comment]
> > > 在保存量化模型时，有时可以通过，但经常退出并提示：
> > > Aborted at 1591265021 (unix time) try "date -d @1591265021" if you are using GNU date
> > 
> > 
> > @dlkht 退出时模型是否已经保存了？
> 
> 闪退时还不到保存那步，死在执行这句时：
> val_program = quant.quant_aware(eval_program1, place, quant_config, scope=None, for_test=True)
> 到达framework.py如下得地方：
> def _construct_from_desc(desc):
> p = Program()
> p.desc = desc #<=======到这句就死掉
> p.blocks = [Block(p, i) for i in six.moves.range(p.desc.num_blocks())]
> p._sync_with_cpp()
> return p
> 
> 原因好像是指向非法内存空间

看起来像是graph转到program有问题，麻烦再给下压缩配置，slim版本，paddle版本等详细信息

**Comment by dlkht** [comment]
> > > > 在保存量化模型时，有时可以通过，但经常退出并提示：
> > > > Aborted at 1591265021 (unix time) try "date -d @1591265021" if you are using GNU date
> > > 
> > > 
> > > @dlkht 退出时模型是否已经保存了？
> > 
> > 
> > 闪退时还不到保存那步，死在执行这句时：
> > val_program = quant.quant_aware(eval_program1, place, quant_config, scope=None, for_test=True)
> > 到达framework.py如下得地方：
> > def _construct_from_desc(desc):
> > p = Program()
> > p.desc = desc #<=======到这句就死掉
> > p.blocks = [Block(p, i) for i in six.moves.range(p.desc.num_blocks())]
> > p._sync_with_cpp()
> > return p
> > 原因好像是指向非法内存空间
> 
> 看起来像是graph转到program有问题，麻烦再给下压缩配置，slim版本，paddle版本等详细信息

压缩配置：
quant_config = {
                # weight quantize type, default is 'channel_wise_abs_max'
                'weight_quantize_type': 'abs_max',
                # activation quantize type, default is 'moving_average_abs_max'
                'activation_quantize_type': 'moving_average_abs_max',
                # weight quantize bit num, default is 8
                'weight_bits': 8,
                # activation quantize bit num, default is 8
                'activation_bits': 8,
                # ops of name_scope in not_quant_pattern list, will not be quantized
                'not_quant_pattern': ['skip_quant'],
                # ops of type in quantize_op_types, will be quantized
                'quantize_op_types':['conv2d', 'depthwise_conv2d', 'mul'],
                
                # data type after quantization, such as 'uint8', 'int8', etc. default is 'int8'
                'dtype': 'int8',
                # window size for 'range_abs_max' quantization. defaulf is 10000
                'window_size': 10000,
                # The decay coefficient of moving average, default is 0.9
                'moving_rate': 0.9,
            }

paddle版本：paddlepaddle-gpu-1.7.2.post107或paddlepaddle-gpu-1.8.1.post107
                     或paddlepaddle-gpu-1.8.2.post107

paddleslim版本：1.1.1
