### ISSUE TITLE
模型剪枝是否能够提高模型的速度？

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/PaddleSlim#334]
最近试验了模型剪枝，大小减低了20%，但是发现速度几乎没有变化，是合理的吗

**Comment by JensenHJS** [comment]
剪枝肯定是可以加速的，量化才是不一定能加速。可能是你剪的层太少或者比例太低。我最近在实验剪枝中

**Comment by wanghaoshuang** [comment]
>最近试验了模型剪枝，大小减低了20%，但是发现速度几乎没有变化，是合理的吗

是合理的，这和硬件对卷积计算的优化有关。
根据我们的经验：
- 在GPU上加速不明显，应该是CUDNN对特殊通道数量的卷积进行了优化，剪裁产出的通道数不一定是CUDNN需要的最优通道数。
- 在CPU上加速明显，应该是对卷积通道并行计算相关的优化较少
- 某些特殊的卷积对剪裁不敏感，比如MobileNetV2里的卷积

建议：
- 在剪裁的时候，可以控制下剩余的通道数，使其是4的倍数

**Comment by wanghaoshuang** [comment]
这里有一些推理加速数据供您参考：https://paddleslim.readthedocs.io/zh_CN/latest/model_zoo.html#id4
