### ISSUE TITLE
为什么文档里的图挂掉了，你们也是吗

### ISSUE THREAD

**Issue by eucommiaulmoides** [PaddlePaddle/PaddleSlim#337]
求助

**Comment by wanghaoshuang** [comment]
请问是哪个文档，贴个链接？

**Comment by eucommiaulmoides** [comment]
是paddleslim的文档

https://paddlepaddle.github.io/PaddleSlim/algo/algo.html










在 2020-06-09 11:18:02，"whs" <notifications@github.com> 写道：

请问是哪个文档，贴个链接？
