### ISSUE TITLE
从经过训练量化的模型产生预测模型（int8)出错

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/PaddleSlim#341]
想从经过训练量化的模型产生预测模型（int8),
实现程序是quant__freezy.py,我这边出错提示
Aborted at 1591755157 (unix time) try "date -d @1591755157" if you are using GNU date

**Comment by itminner** [comment]
这个错误应该不影响量化模型产出，可以看看有没有infer model保存下来，测下精度确认下

**Comment by dlkht** [comment]
只有两次保存模型成功，其余都在保存之前出错了

**Comment by dlkht** [comment]
用opt对生成的infer model优化，产生错误：
[I  6/10 17:46:28.205 ...ease_2.3/Paddle-Lite/lite/api/cxx_api.cc:245 Build] Load model from file.
terminate called after throwing an instance of 'std::invalid_argument'
  what():  unmatched type, store as -746832279, but want to get N6paddle4lite10TensorLiteE

**Comment by slf12** [comment]
> 用opt对生成的infer model优化，产生错误：
> [I 6/10 17:46:28.205 ...ease_2.3/Paddle-Lite/lite/api/cxx_api.cc:245 Build] Load model from file.
> terminate called after throwing an instance of 'std::invalid_argument'
> what(): unmatched type, store as -746832279, but want to get N6paddle4lite10TensorLiteE

@juncaipeng 能否看下这个量化模型转化到paddle-lite出错的问题？

**Comment by juncaipeng** [comment]
@AIpioneer  这个模型有多个block，目前通用量化功能没法支持量化多个block的模型。

**Comment by dlkht** [comment]
> @AIpioneer 这个模型有多个block，目前通用量化功能没法支持量化多个block的模型。

请问现在支持多个block的量化了吗
