### ISSUE TITLE
opt在protobuf格式下生成的model和params能用protobuf库里的接口解析吗？和caffe是否相同？

### ISSUE THREAD

**Issue by ArtyZe** [PaddlePaddle/PaddleSlim#347]
麻烦问下opt生成的和caffe的模型有啥区别，都能用protobuf工具解析吗？

**Comment by juncaipeng** [comment]
opt产出的protobuf格式模型，应该是可以使用protobuf库解析的。如果转换过程中有问题，可以到lite的qq群（696965088）咨询。

**Comment by ArtyZe** [comment]
@juncaipeng 好的，感谢。但是我使用protobuf解析后发现如下问题：
![image](https://user-images.githubusercontent.com/32027268/84638166-32431b00-af29-11ea-9783-18aeed76cd3e.png)
我是参考lite里api_cc写的，先解析program，使用的是framework.proto生成的cc和头文件

--------------------------------------------------------------------------------------------------
今天下午我又试了一下，
1. 首先我使用paddleslim里的eval.py去测试是ok的，
![image](https://user-images.githubusercontent.com/32027268/84638411-88b05980-af29-11ea-9312-1571398987a5.png)
之后我使用paddlelite测试一下，按照文档，先进行opt，我选择的如下，
![image](https://user-images.githubusercontent.com/32027268/84638493-a978af00-af29-11ea-985b-889cacad0421.png)
以及
![image](https://user-images.githubusercontent.com/32027268/84638539-b72e3480-af29-11ea-9ade-2aa0d6fb3dd6.png)

之后使用paddlelite测试，结果报错如下：
![image](https://user-images.githubusercontent.com/32027268/84638635-d4fb9980-af29-11ea-830f-821d80e112ce.png)

所以我想还是先在paddlelite上把他跑起来，可以帮忙看下是什么原因吗？目前只有paddleslim量化后的会有这个问题，float的模型lite是ok的

**Comment by juncaipeng** [comment]
paddlelite只有arm cpu支持量化模型，opt转换中的valid_targets设置为arm。
