### ISSUE TITLE
关于paddleslim量化原理的问题

### ISSUE THREAD

**Issue by taoja12** [PaddlePaddle/PaddleSlim#354]
在模型量化文档中(https://paddlepaddle.github.io/PaddleSlim/algo/algo.html)，训练后量化：
对于权重Tensor的量化操作采用非饱和量化方法(No Saturation)，对于输入采用饱和量化方法(Saturation)。
1、那权重和输入进行矩阵相乘后，反量化成float32的操作原理是什么？比如反量化的计算公式，反量化的尺度怎么计算的（因为权重和输入采用两种量化方式，所以反量化如何计算不太清楚）？

**Comment by itminner** [comment]
量化原理请参考 https://paddlepaddle.github.io/PaddleSlim/algo/algo.html#quantization-aware-training

**Comment by itminner** [comment]
离线量化 原理可以参考 https://zdaiot.com/MLFrameworks/TensorRT/TensorRT%20INT8%E9%87%8F%E5%8C%96%E5%8E%9F%E7%90%86/
