### ISSUE TITLE
训练后量化如何指定某些层不量化

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/PaddleSlim#359]
![image](https://user-images.githubusercontent.com/7233091/85114146-156d5700-b24b-11ea-9440-0a2bb1abd5bf.png)
API文档中有一个字典配置量化参数，里面有not_quant_pattern来指定一些pattern可以不量化，可是在quant_post中却并不是通过字典来配置量化参数的，请问quant_post中能指定哪些层不量化么

**Comment by juncaipeng** [comment]
离线量化没有输入参数支持跳过op量化。

但是，如果在构建网络结构的时候，将不需要量化的op定义在name_scope("skip_quant")中，然后正常训练保存。对这个预测模型使用离线量化，还是可以支持跳过量化的。

**Comment by HaoLiuHust** [comment]
多谢，可以在保存后修改网络结构将不需要定义的op放在name_scope("skip_quant")再重新保存不

**Comment by juncaipeng** [comment]
嗯，好像是可以的，你修改模型结果，然后从新load权重，进行保存。你量化前先测试一下这个模型精度是否正确。

**Comment by HaoLiuHust** [comment]
好的，多谢
