### ISSUE TITLE
量化后精度下降非常大

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/PaddleSlim#364]
量化了一个识别模型，精度下降了几十个点，如何调试问题出在哪一层？

**Comment by qingqing01** [comment]
@HaoLiuHust  请问具体是什么模型？ 使用的是量化训练吗？ 如果是量化训练，可以适当调整下超参数(lr, epoch)等。

**Comment by HaoLiuHust** [comment]
是一个人脸识别模型，结构类似mobilenet, 是直接用quant_post量化的

**Comment by juncaipeng** [comment]
识别模型精度一般下降不多的，主要可以采用：
* 增大校准数据集，校准数据集需要具有代表性，可以表示预测数据的分布
* 调整离线量化中量化的op，比如减少量化op类型
* 改用量化训练方法

**Comment by HaoLiuHust** [comment]
好的，我先试试量化训练

**Comment by HaoLiuHust** [comment]
另外有没有工具可以逐层比对量化前后的每一层呢

**Comment by HaoLiuHust** [comment]
用了量化重训练，精度拉回去挺多了，可能这个模型对参数比较敏感

**Comment by HaoLiuHust** [comment]
弄错了。。精度没有拉回去，训练的时候没开量化。我以前用其他家的量化工具量化这个模型也出现过量化精度损失很多的情况，最后发现是只量化权重（不插入量化和反量化OP)时，损失很小，最后是他们修复了这个bug

**Comment by HaoLiuHust** [comment]
有没有办法确定是否也是同样的原因

**Comment by qingqing01** [comment]
@HaoLiuHust  

1.  PaddleSlim也支持只量化权重，参考接口： https://paddleslim.readthedocs.io/zh_CN/latest/api_cn/quantization_api.html#quant-post-dynamic 

2. 人脸识别模型，量化训练损失"几十个点"，觉得不正常，评价指标是啥？ 能否详细描述下 量化训练的一些参数设置？

**Comment by itminner** [comment]
可能是feature值离群点导致的，可以试下加大权重衰减。只量化权重的话，就掩盖了feature值离群点问题，而且只量化权重恐怕不能在预测 速度上取得收益

**Comment by HaoLiuHust** [comment]
@itminner 他们是修复了量化OP里面的bug, 最后使用的时候还是量化了Op的

**Comment by HaoLiuHust** [comment]
> @HaoLiuHust
> 
> 1. PaddleSlim也支持只量化权重，参考接口： https://paddleslim.readthedocs.io/zh_CN/latest/api_cn/quantization_api.html#quant-post-dynamic
> 2. 人脸识别模型，量化训练损失"几十个点"，觉得不正常，评价指标是啥？ 能否详细描述下 量化训练的一些参数设置？

1、 嗯，我也看到了这个接口，我想在PC上测试性能，这个接口保存的文件是不是只能在paddle-lite里跑？
2、评价指标是tpr-fpr。loss使用的是arc loss, 实现使用的是PaddleCV里的实现，量化训练参数基本使用的默认的config

**Comment by xiteng1988** [comment]
@HaoLiuHust 可以参考人脸识别模型的量化，在lfw上离线量化损失很小的，对于大的数据集，刚开始飞掉正常的很快就可以训回来，基于pact量化会好一些

**Comment by HaoLiuHust** [comment]
@xiteng1988 pact量化是啥

**Comment by HaoLiuHust** [comment]
有人脸识别模型的量化demo么 @xiteng1988

**Comment by qingqing01** [comment]
@HaoLiuHust 

1. 只量化weight，在PC上测试是没有加速的，只能减少模型体积。
2.  quant_post(也就是校准量化)掉几十个点，量化训练掉多少点？

一些量化的可参考的信息：

<img width="1027" alt="图片" src="https://user-images.githubusercontent.com/7845005/86022107-7cb1b500-ba5c-11ea-86d4-da86b36cf54c.png">

这个图是Nvidia的资料，离线量化的一些在一些任务上没有这么大的损失(看entropy那栏，采用KL散度的方式)，你所采用的quant_post也是KL散度的方式。

量化训练，我们尝试过的模型，大部分损失0.x% - 2%(可以看Slim提供的benchmark)，但MobileNetv3训练就不稳定，使用abs-max(也就是默认的量化训练)量化，SE-block得跳过不量化，不然不稳定。

量化训练可提供的建议:

a.  看下调整训练的epoch数、学习率超参数超参数搜，看下精度是否能提升。如果还不能:
b.  看下是否对一些敏感的层不量化，比如对最后的预测层不量化(或如果有SE-Block不量化，其他的需要依据网络结构分析下)
  
       如何对一些层不做量化:

      先对不量化的层通过`fluid.name_scope`设置表示:

           with fluid.name_scope('skip_quant'):  # 可以任意字符串表示
                block_out = fluid.layers.conv2d(
                    input=tip,
                    num_filters=num_filters,
                    filter_size=1,
                    stride=1,
                    padding=0,
                    act=None)

      量化配置中，设置`not_quant_pattern`字段
            https://paddleslim.readthedocs.io/zh_CN/latest/api_cn/quantization_api.html#id12 
   
c.  可以考虑PACT，参考MobileNetv3+PACT的例子： https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/pact_quant_aware  PACT较好解决了离群点问题，在 MobileNetV3上表现不错。

**Comment by HaoLiuHust** [comment]
> @HaoLiuHust
> 
> 1. 只量化weight，在PC上测试是没有加速的，只能减少模型体积。
> 2. quant_post(也就是校准量化)掉几十个点，量化训练掉多少点？
> 
> 一些量化的可参考的信息：
> 
> <img alt="图片" width="1027" src="https://user-images.githubusercontent.com/7845005/86022107-7cb1b500-ba5c-11ea-86d4-da86b36cf54c.png">
> 
> 这个图是Nvidia的资料，离线量化的一些在一些任务上没有这么大的损失(看entropy那栏，采用KL散度的方式)，你所采用的quant_post也是KL散度的方式。
> 
> 量化训练，我们尝试过的模型，大部分损失0.x% - 2%(可以看Slim提供的benchmark)，但MobileNetv3训练就不稳定，使用abs-max(也就是默认的量化训练)量化，SE-block得跳过不量化，不然不稳定。
> 
> 量化训练可提供的建议:
> 
> a. 看下调整训练的epoch数、学习率超参数超参数搜，看下精度是否能提升。如果还不能:
> b. 看下是否对一些敏感的层不量化，比如对最后的预测层不量化(或如果有SE-Block不量化，其他的需要依据网络结构分析下)
> 
> ```
>    如何对一些层不做量化:
> 
>   先对不量化的层通过`fluid.name_scope`设置表示:
> 
>        with fluid.name_scope('skip_quant'):  # 可以任意字符串表示
>             block_out = fluid.layers.conv2d(
>                 input=tip,
>                 num_filters=num_filters,
>                 filter_size=1,
>                 stride=1,
>                 padding=0,
>                 act=None)
> 
>   量化配置中，设置`not_quant_pattern`字段
>         https://paddleslim.readthedocs.io/zh_CN/latest/api_cn/quantization_api.html#id12 
> ```
> 
> c. 可以考虑PACT，参考MobileNetv3+PACT的例子： https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/pact_quant_aware PACT较好解决了离群点问题，在 MobileNetV3上表现不错。

嗯，多谢回复，我试试不量化一些层。“ 只量化weight，在PC上测试是没有加速的，只能减少模型体积。”，我只是测一下准确率，看看是不是只量化权重损失会正常些，这样就确认是量化OP引起的问题

**Comment by HaoLiuHust** [comment]
应该是这个模型结构或者参数分布导致的，我训练后量化了一个Resnet50模型（没有重训练），与issue中的模型训练数据是一样的，量化数据是一样的，Resnet50降得很少，1%以内。估计还是这个模型某些层的损失很大

**Comment by HaoLiuHust** [comment]
@qingqing01 这个pact要在那个paddle版本用，我试了1.8.1和2.0.0.alpha，都不行，QuantizationTransformPass没有act_quantize_func这个参数

**Comment by HaoLiuHust** [comment]
试了下MNN，rknn的量化，都出现了同样的现象，Resnet50（或通道砍半）都几乎没有损失，但这个mobilenetv2的改版却下降了非常多

**Comment by HaoLiuHust** [comment]
![image](https://user-images.githubusercontent.com/7233091/86986168-99b95700-c1c5-11ea-88be-681e2ff86717.png)

**Comment by wanghaoshuang** [comment]
>这个pact要在那个paddle版本用，我试了1.8.1和2.0.0.alpha，都不行，QuantizationTransformPass没有act_quantize_func这个参数

目前只有develop分支支持，您可以从这里下载最新的Paddle安装包：
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/install/Tables.html#whl-dev
