### ISSUE TITLE
请问一下是版本不对吗

### ISSUE THREAD

**Issue by chengxurensheng666** [PaddlePaddle/PaddleSlim#366]
![image](https://user-images.githubusercontent.com/48110081/85413335-47f5b780-b59d-11ea-811a-8234f8931343.png)
![image](https://user-images.githubusercontent.com/48110081/85413368-52b04c80-b59d-11ea-92e4-1bc7d88dd0f3.png)
问题1：我不管用什么slim的命令都要提示这个，padddlepaddle用的1.8版本，slim1.1.1 请问一下是版本不对吗
问题2：paddledetection里面内置了slim，请问还需要在pip install paddleslim吗
![image](https://user-images.githubusercontent.com/48110081/85413607-999e4200-b59d-11ea-9e68-f67774420608.png)

**Comment by wanghaoshuang** [comment]
您好，这个错误应该使和paddleslim无关的，应该是你环境里的pandas和numpy版本不兼容导致的。
我在aistudio里把pandas卸载了就可以了。

类似的问题可以参考：https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility

**Comment by chengxurensheng666** [comment]
我将pandas卸载后可以运行了，但是我发现裁剪部分参数会出现报错如：bn_conv1_scale
![image](https://user-images.githubusercontent.com/48110081/85522778-ad4ab680-b638-11ea-93e3-6b877265c3fa.png)
![image](https://user-images.githubusercontent.com/48110081/85522837-bd629600-b638-11ea-98d8-999c93e57d56.png)
有些能够正常运行如conv1_weights
所有参数名是通过python prune.py -c ../../configs/faster_rcnn_r50_1x.yml --print_params命令得到的

**Comment by wanghaoshuang** [comment]
PaddleSlim目前只能**直接**指定剪裁卷积层的参数。
在对卷积层进行剪裁时，会通过前向搜索或回溯对关联到的batch norm等层进行剪裁。
bn_conv1_scale应该是conv1 layer之后的batch norm， 在对conv1_weights进行剪裁时，会自动剪裁到bn_conv1_scale.

**Comment by chengxurensheng666** [comment]
懂了非常感谢 终于可以正常运行了
