### ISSUE TITLE
PaddleSlim/docs/zh_cn/quick_start/nas_tutorial.md里写的代码有问题

### ISSUE THREAD

**Issue by skyliuhc** [PaddlePaddle/PaddleSlim#367]
for step in range(3):
    archs = sanas.next_archs()[0]
    exe, train_program, eval_progarm, inputs, avg_cost, acc_top1, acc_top5 = build_program(archs)

test_program错写成了test_progarm
需要更正为exe, train_program, test_program, inputs, avg_cost, acc_top1, acc_top5 = build_program(archs)

**Comment by ceci3** [comment]
在 https://github.com/PaddlePaddle/PaddleSlim/pull/377 中进行修复，感谢反馈~
