### ISSUE TITLE
关于剪枝的咨询

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/PaddleSlim#375]
你们这里有个例子https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/api_cn/prune_api.rst，我不太明白，Pruner就是用于重训，减少权重中不重要的通道权值么？但是我还没有训练，我怎么知道哪个权重重不重要呢，这里要填个ratios剪切率，这样的我要怎么填呢？sensitivity
是重训后，计算每个卷积层敏感度，按说重训后不是去掉对应卷积层的一些通道的参数么，对比对应有些通道参数不重要的去掉么，这个计算每层的敏感度，作用是是什么？是说哪个敏感点，后面就裁剪多点？还有就是计算敏感度这里还有个pruned_ratios比例要填，不是应该是哪个不重要就去掉，这个我不去看权值，我怎么知道裁剪的比例呢？merge_sensitive
还有这个合并的时候，value 为剪裁比例， value 为精度损失的比例是我们自己要修改什么么，还是就上面的敏感度直接使用。剪裁的网络是哪个，我感觉我理解的不太对。所以不太明白。怎么感觉跟我平常用的剪枝不太一样，所以没有理解

**Comment by wanghaoshuang** [comment]
剪裁的一般流程是：
1. 在目标任务上训练好原始模型
2. 调用敏感度接口分析各层敏感度
3. 根据敏感度确定各层剪裁比例
4. 调用Pruner.prune，根据第3步确定的剪裁比例，对目标网络进行剪裁
5. 对剪裁后的网络进行重新训练


https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/api_cn/prune_api.rst
关于这个例子的一些问题：

-  剪裁前需要重训练么？ 
   - Pruner是用于重训剪裁后的模型么？ ** 答：Pruner不关心模型是否是训好的模型，Pruner.prune接口返回的模型不是重训的模型，用户需要手动对剪裁后的模型进行重训练。**
   - 在没有训练模型的前提下，怎么根据重要性填写ratios剪切率呢？ **答：需要使用敏感度（sensitivy）接口分析各层的重要性，并确定合适的剪裁率。而敏感度分析是需要模型提前训练好的。**

- sensitivity接口的作用是什么
   - sensitivity是重训后，计算每个卷积层敏感度？ **答：是对『剪裁前的且已训好的模型』进行敏感度分析。**
   - 重训后是裁掉相对不重要的通道参数么？ **答：剪掉不重要的通道，然后进行重训。**
   - 计算每层的敏感度，作用是是什么？ **答：作用是评估每层卷积的重要性，以便在后续剪裁过程中，确定每层卷积的剪裁率。**
   - 计算敏感度里的pruned_ratios怎么填写？不是应该是哪个不重要就去掉，这个我不去看权值，我怎么知道裁剪的比例呢？ **答：计算敏感度里的`pruned_ratios`和`Pruner`里的`pruned_ratios`概念不太一样。计算敏感度里的`pruned_ratios`一般是固定的，比如`[0.1, 0.2, 0.3, 0.5]`，意思是分别在剪掉0.1、0.2、0.3、0.5的情况下观察模型的精度损失。**

- merge_sensitive
key 为剪裁比例， value 为精度损失的比例是我们自己要修改什么么  **答：不需要修改**

- 还是就上面的敏感度直接使用,剪裁的网络是哪个  **答：在分析敏感度时用的哪个网络，后续剪裁时，就要用哪个网络。**
