### ISSUE TITLE
关于yolo 的量化训练问题

### ISSUE THREAD

**Issue by aboutmei** [PaddlePaddle/PaddleSlim#381]
1.yolov3_darknet.yml  coco 数据集加载与训练模型训练yolo_v3，map 一直非常低，4卡batch8迭代20000步,map大概0.14。请问预训练模型是否有问题，或者我这边哪里操作有问题?

2.yolov4_coco 数据集量化训练
CUDA_VISIBLE_DEVICES=2 python slim/quantization/train.py  --eval -c ./configs/yolov4/yolov4_cspdarknet_voc.yml  -o max_iters=1000      save_dir=./output_v4  LearningRate.base_lr=0.0001      LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]"      pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov4_cspdarknet.pdparams  
已将bn 改为：bn
报错 212-WARNING: recv endsignal from outq with errmsg[consumer[consumer-951-6] failed to map with error:[target0 not in samples]]

**Comment by heavengate** [comment]
1.  加载的预训练模型是全量的预训练还是backbone的预训练，如果没有修改默认配置的话是加载backbone预训练，yolov3训练收敛比较慢，coco数据集上全量训练完是50w iter，2w iter的时候精度应该还不高
2. 用的是哪个PaddleDetection分支和Paddle版本，我本地没有复现出这个问题

**Comment by heavengate** [comment]
yolov4训练精度对齐正在复现中，我们会在近期发布并支持slim进行模型压缩，目前直接压缩可能确实会有问题，我们跟进一下~
