### ISSUE TITLE
在paddleslim 图像分类模型知识蒸馏-快速开始 教程中 运行的问题？

### ISSUE THREAD

**Issue by Sejudyblues** [PaddlePaddle/PaddleSlim#383]
model = slim.models.__dict__['MobileNet']()
student_program = fluid.Program()
student_startup = fluid.Program()
with fluid.program_guard(student_program, student_startup):
    image = fluid.data(
        name='image', shape=[None] + [1, 28, 28], dtype='float32')
    label = fluid.data(name='label', shape=[None, 1], dtype='int64')
    out = model.net(input=image, class_dim=10)
    cost = fluid.layers.cross_entropy(input=out, label=label)
    avg_cost = fluid.layers.mean(x=cost)
    acc_top1 = fluid.layers.accuracy(input=out, label=label, k=1)
    acc_top5 = fluid.layers.accuracy(input=out, label=label, k=5)

当运行到这里时候 提示错误如下：
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<ipython-input-10-834c4c4f5932> in <module>
----> 1 model = models.__dict__['MobileNet']()
      2 student_program = fluid.Program()
      3 student_startup = fluid.Program()
      4 with fluid.program_guard(student_program, student_startup):
      5     image = fluid.data(
NameError: name 'models' is not defined

说model没有定义  我看这个教程最开始也只是导入
import paddle
import paddle.fluid as fluid
import paddleslim as slim
这三个锕  这是什么原因呢？望解答

**Comment by Sejudyblues** [comment]
> model = slim.models.**dict**'MobileNet'
> student_program = fluid.Program()
> student_startup = fluid.Program()
> with fluid.program_guard(student_program, student_startup):
> image = fluid.data(
> name='image', shape=[None] + [1, 28, 28], dtype='float32')
> label = fluid.data(name='label', shape=[None, 1], dtype='int64')
> out = model.net(input=image, class_dim=10)
> cost = fluid.layers.cross_entropy(input=out, label=label)
> avg_cost = fluid.layers.mean(x=cost)
> acc_top1 = fluid.layers.accuracy(input=out, label=label, k=1)
> acc_top5 = fluid.layers.accuracy(input=out, label=label, k=5)
> 
> 当运行到这里时候 提示错误如下：
> ---------------------------------------------------------------------------NameError Traceback (most recent call last) in
> ----> 1 model = models.**dict**'MobileNet'
> 2 student_program = fluid.Program()
> 3 student_startup = fluid.Program()
> 4 with fluid.program_guard(student_program, student_startup):
> 5 image = fluid.data(
> NameError: name 'models' is not defined
> 
> 说model没有定义 我看这个教程最开始也只是导入
> import paddle
> import paddle.fluid as fluid
> import paddleslim as slim
> 这三个锕 这是什么原因呢？望解答
 

> model = slim.models.**dict**'MobileNet'
> student_program = fluid.Program()
> student_startup = fluid.Program()
> with fluid.program_guard(student_program, student_startup):
> image = fluid.data(
> name='image', shape=[None] + [1, 28, 28], dtype='float32')
> label = fluid.data(name='label', shape=[None, 1], dtype='int64')
> out = model.net(input=image, class_dim=10)
> cost = fluid.layers.cross_entropy(input=out, label=label)
> avg_cost = fluid.layers.mean(x=cost)
> acc_top1 = fluid.layers.accuracy(input=out, label=label, k=1)
> acc_top5 = fluid.layers.accuracy(input=out, label=label, k=5)
> 
> 当运行到这里时候 提示错误如下：
> ---------------------------------------------------------------------------NameError Traceback (most recent call last) in
> ----> 1 model = models.**dict**'MobileNet'
> 2 student_program = fluid.Program()
> 3 student_startup = fluid.Program()
> 4 with fluid.program_guard(student_program, student_startup):
> 5 image = fluid.data(
> NameError: name 'models' is not defined
> 
> 说model没有定义 我看这个教程最开始也只是导入
> import paddle
> import paddle.fluid as fluid
> import paddleslim as slim
> 这三个锕 这是什么原因呢？望解答

自己已经解决了 查看了 paadleslim文件夹下的 models文件 发现他们模型都是分开的 并不是在models一个文件内
所以要将上述使用改为如下 model = slim.models.mobilenet.__dict__['MobileNet']() 即可。

**Comment by baiyfbupt** [comment]
您好，这里确实没有说清楚models的来源，感谢反馈。
这个教程仅供参考蒸馏的基本流程，如果想进一步了解可以参照https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/distillation 进行实验

**Comment by Sejudyblues** [comment]
> 您好，这里确实没有说清楚models的来源，感谢反馈。
> 这个教程仅供参考蒸馏的基本流程，如果想进一步了解可以参照https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/distillation 进行实验

好的，非常感谢！现在正在看学习这个demo在。
