### ISSUE TITLE
 支持Dataset方式的蒸馏训练

### ISSUE THREAD

**Issue by chenzaiping-dev** [PaddlePaddle/PaddleSlim#389]
RT。
目前的蒸馏使用的训练集和测试集reader，大部分是下载数据到本地后读取的，支持的训练集比较小；
如果可以支持Dataset方式训练蒸馏的话，对使用方可以自定义hdfs或afs等路径，不用关心数据拉取等细节，和普通的分布式训练更能保持一致；

**Comment by wanghaoshuang** [comment]
请问，可以详细说明下Dataset是什么？我们对这个需求不是很明确。
