### ISSUE TITLE
根据官方文档得到的量化模型，无法转化为“navie_buffer”格式

### ISSUE THREAD

**Issue by wuhang2016** [PaddlePaddle/PaddleSlim#410]
RT，根据 [https://paddlepaddle.github.io/PaddleSlim/quick_start/quant_aware_tutorial.html](url) 的快速开始教程，训练得到的量化模型为非combine类型，在将模型转化为“navie_buffer”格式时，报如下错：
    [I  8/ 6 17: 3:57.814 ...se_2.6/2.6.1/Paddle-Lite/lite/api/opt.cc:381 CheckIfModelSupported]  Erro: This model is not supported, because 2 ops are not supported on 'arm'. These unsupported ops are: 'accuracy, cross_entropy2'

    求问如何解决?

**Comment by wanghaoshuang** [comment]
多谢您的反馈。这个PR修复了文档中示例的问题：https://github.com/PaddlePaddle/PaddleSlim/pull/412

错误原因：
在保存PaddleLite所支持的预测模型时，是不能保存计算accuracy和loss的op的。在save_inference_model接口中，可以通过制定`target_vars`和`feeded_var_names`来剪裁得到一个没有`accuracy`,`loss`和`label`的子网络，正如上述PR中的修改。
