### ISSUE TITLE
急急急！！求问在循环生成模型的程序中，怎么在生成下一个模型的时候把上一个模型删除，避免显存爆炸。类似tensorflow中的clear_session()函数，以及matlab中的clear功能的函数

### ISSUE THREAD

**Issue by 1558513572** [PaddlePaddle/PaddleSlim#434]

**Comment by ceci3** [comment]
你好，请问下可以贴下可复现代码嘛？我们跑示例没有办法复现出来显存爆炸的问题。

**Comment by 1558513572** [comment]
非常感谢，现在这个问题已经解决了，谢谢！



---原始邮件---
发件人: "ceci3"<notifications@github.com&gt;
发送时间: 2020年9月2日(周三) 上午10:26
收件人: "PaddlePaddle/PaddleSlim"<PaddleSlim@noreply.github.com&gt;;
抄送: "1558513572"<1558513572@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleSlim] 急急急！！求问在循环生成模型的程序中，怎么在生成下一个模型的时候把上一个模型删除，避免显存爆炸。类似tensorflow中的clear_session()函数，以及matlab中的clear功能的函数 (#434)




 
你好，请问下可以贴下可复现代码嘛？我们跑示例没有办法复现出来显存爆炸的问题。
