### ISSUE TITLE
模型量化之后怎么加载int数据类型

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleSlim#437]
量化训练之后有float和int两种数类型的模型文件

float加载推理没有任何问题，但是int该怎么加载？
运行命令如下：
```bash
 python deploy/python/infer.py --model_dir=myfiles/quant_export/int --image_file=/d/hl_files/4_10_2_0003.jpg --use_gpu=True  --run_mode fluid --run_benchmark=True

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2933, in conv2d
    "data_format": data_format,
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/backbones/mobilenet.py", line 84, in _conv_norm
    bias_attr=False)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/backbones/mobilenet.py", line 159, in __call__
    input, 3, int(32 * scale), 2, 1, name=self.prefix_name + "conv1")
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 61, in build
    body_feats = self.backbone(im)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 162, in test
    return self.build(feed_vars, mode='test')
  File "export_model.py", line 77, in main
    test_fetches = model.test(feed_vars)
  File "export_model.py", line 122, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: input and filter data type should be consistent
  [Hint: Expected input_data_type == filter_data_type, but received input_data_type:5 != filter_data_type:21.] at (/d/hl_files/Paddle/paddle/fluid/operators/conv_op.cc:173)
  [operator < conv2d > error]
```

**Comment by baiyfbupt** [comment]
您好，量化后`convert()`接口导出的int模型不可用于paddle直接加载，因为paddle核心框架没有量化计算功能，如果需要使用量化模型部署可以结合您的场景选择Intel CPU、Nvidia TensorRT、PaddleLite进行Server CPU、Server GPU、端侧的预测部署，请参考文档 https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/FAQ/quantization_FAQ.md#2-%E9%87%8F%E5%8C%96%E8%AE%AD%E7%BB%83%E6%88%96%E8%80%85%E7%A6%BB%E7%BA%BF%E9%87%8F%E5%8C%96%E5%90%8E%E7%9A%84%E6%A8%A1%E5%9E%8B%E4%BD%BF%E7%94%A8fluid%E5%8A%A0%E8%BD%BD%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E5%8A%A0%E9%80%9F%E6%80%8E%E6%A0%B7%E6%89%8D%E8%83%BD%E5%8A%A0%E9%80%9F

部署也只需要用`convert()`导出的float模型，预测时会自动转为int类型。`convert()`导出int模型已经被废弃了，可以不用关注

**Comment by thunder95** [comment]
@baiyfbupt 你好，感谢回复，我是想用tensorrt部署(pc和xavier)，用的paddledetection， 按照文档里的方式，我改了下代码支持int8的方式，最终没有任何检测结果，用float时是有检测结果的。
```python
W0903 19:09:51.112918 11793 helper.h:72] No implementation obeys reformatting-free rules, at least 2 reformatting nodes are needed, now picking the fastest path instead.
W0903 19:09:51.138789 11793 helper.h:72] TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0903 19:09:51.147464 11793 graph_pattern_detector.cc:101] ---  detected 3 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0903 19:09:51.156589 11793 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0903 19:09:51.170382 11793 memory_optimize_pass.cc:223] Cluster name : im_size  size: 8
I0903 19:09:51.170397 11793 memory_optimize_pass.cc:223] Cluster name : yolo_box0.tmp_0  size: 17328
I0903 19:09:51.170400 11793 memory_optimize_pass.cc:223] Cluster name : transpose_0.tmp_0  size: 25992
I0903 19:09:51.170404 11793 memory_optimize_pass.cc:223] Cluster name : transpose_1.tmp_0  size: 103968
I0903 19:09:51.170408 11793 memory_optimize_pass.cc:223] Cluster name : yolo_box2.tmp_1  size: 415872
I0903 19:09:51.170411 11793 memory_optimize_pass.cc:223] Cluster name : yolo_box1.tmp_0  size: 69312
I0903 19:09:51.170414 11793 memory_optimize_pass.cc:223] Cluster name : yolo_box2.tmp_0  size: 277248
I0903 19:09:51.170418 11793 memory_optimize_pass.cc:223] Cluster name : multiclass_nms_0.tmp_0  size: 545832
I0903 19:09:51.170423 11793 memory_optimize_pass.cc:223] Cluster name : conv2d_36.tmp_1  size: 762432
--- Running analysis [ir_graph_to_program_pass]
I0903 19:09:51.195583 11793 analysis_predictor.cc:496] ======= optimize end =======
I0903 19:09:51.195719 11793 naive_executor.cc:95] ---  skip [feed], feed -> im_size
I0903 19:09:51.195725 11793 naive_executor.cc:95] ---  skip [feed], feed -> image
I0903 19:09:51.196902 11793 naive_executor.cc:95] ---  skip [conv2d_36.tmp_1], fetch -> fetch
W0903 19:09:51.434857 11793 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0903 19:09:51.512828 11793 device_context.cc:260] device: 0, cuDNN Version: 7.6.
W0903 19:09:55.806794 11793 helper.h:72] TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
W0903 19:09:56.070655 11793 helper.h:72] TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
W0903 19:09:56.287967 11793 helper.h:72] TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
[WARNING] No object detected.
[WARNING] No object detected.
[WARNING] No object detected.
```

**Comment by baiyfbupt** [comment]
>用float时是有检测结果的

这个是指原模型有结果？还是指量化后convert()导出的float32模型呢？

**Comment by thunder95** [comment]
> > 用float时是有检测结果的
> 
> 这个是指原模型有结果？还是指量化后convert()导出的float32模型呢？

@baiyfbupt  原模型和量化训练之后产生的float文件夹（也产生了int文件夹）， 都是有结果的

**Comment by baiyfbupt** [comment]
1. 原模型预测 （FP32模型验证）
2. 量化后的float模型以TRT float模式预测 （模拟量化效果验证）
3. 量化后的float模型以TRT int模式预测（注意是**使用量化得到的float模型**而非int模型）（真实int8量化模型效果验证）

量化可以按这三条逐一验证，我理解您现在是`1，2`都没问题了，但是`3`预测没有结果对吗，如果确认`3`没有用错模型，可以贴下TRT预测用的代码我们看下~

**Comment by thunder95** [comment]
嗯 你说的没错
预测用的代码我仍然用的是paddledetection， 在上面只是加了支持trt_int8的少量代码

[src.zip](https://github.com/PaddlePaddle/PaddleSlim/files/5172522/src.zip)

@baiyfbupt


> 1. 原模型预测 （FP32模型验证）
> 2. 量化后的float模型以TRT float模式预测 （模拟量化效果验证）
> 3. 量化后的float模型以TRT int模式预测（注意是**使用量化得到的float模型**而非int模型）（真实int8量化模型效果验证）
> 
> 量化可以按这三条逐一验证，我理解您现在是`1，2`都没问题了，但是`3`预测没有结果对吗，如果确认`3`没有用错模型，可以贴下TRT预测用的代码我们看下~

**Comment by cryoco** [comment]
您好，麻烦提供下完整的log，我们看下TensorRT的优化阶段是否出了问题

**Comment by thunder95** [comment]
> 您好，麻烦提供下完整的log，我们看下TensorRT的优化阶段是否出了问题

@cryoco 您好，我是使用aistudio进行量化的，没有发现哪里有log， 下面是我aistudio进行量化时的输出：

/home/aistudio/PaddleDetection/slim/quantization
env: CUDA_VISIBLE_DEVICES=0
WARNING: Do not have avx core. You may not build with AVX, but AVX is supported on local machine.
 You could build paddle WITH_AVX=ON to get better performance.
The original error is: No module named 'paddle.fluid.core_avx'
W0909 08:47:40.412988   181 init.cc:185] AVX is available, Please re-compile on local machine
[09-09 08:47:40 MainThread @logger.py:224] Argv: train.py --not_quant_pattern yolo_output -o use_fine_grained_loss=true --eval -c ../../myconfigs/my_ppyolo_quant.yml -o max_iters=20000 LearningRate.base_lr=0.0001 LearningRate.schedulers=[!PiecewiseDecay {gamma: 0.1, milestones: [8000]}] weights=/home/aistudio/PaddleDetection/output/my_ppyolo/model_final
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pandas/core/tools/datetimes.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py:153: UserWarning: PaddlePaddle version 1.8.0 or higher is required, but 0.0.0 installed, Maybe you are using a develop version, please make sure the version is good with your code.
  (min_version, fluid_version.full_version))
2020-09-09 08:47:45,610-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2020-09-09 08:47:46,972-INFO: places would be ommited when DataLoader is not iterable
W0909 08:47:47.122411   181 device_context.cc:268] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0909 08:47:47.126829   181 device_context.cc:276] device: 0, cuDNN Version: 7.3.
2020-09-09 08:47:52,612-INFO: quant_aware config {'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max', 'weight_bits': 8, 'activation_bits': 8, 'not_quant_pattern': ['yolo_output'], 'quantize_op_types': ['depthwise_conv2d', 'mul', 'conv2d'], 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9, 'for_tensorrt': False, 'is_full_quantize': False}
2020-09-09 08:48:26,479-INFO: quant_aware config {'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max', 'weight_bits': 8, 'activation_bits': 8, 'not_quant_pattern': ['yolo_output'], 'quantize_op_types': ['depthwise_conv2d', 'mul', 'conv2d'], 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9, 'for_tensorrt': False, 'is_full_quantize': False}
/home/aistudio/PaddleDetection/ppdet/data/source/voc.py:116: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  img_file))
2020-09-09 08:48:30,683-WARNING: Illegal image file: /home/aistudio/work/Six_Cate/JPEGImages/4_10_5_0147.jpg, and it will be ignored
2020-09-09 08:48:36,440-INFO: places would be ommited when DataLoader is not iterable
I0909 08:48:39.015946   181 graph_pattern_detector.cc:100] ---  detected 216 subgraphs
I0909 08:48:39.332103   181 graph_pattern_detector.cc:100] ---  detected 16 subgraphs
I0909 08:48:39.372484   181 graph_pattern_detector.cc:100] ---  detected 16 subgraphs
/home/aistudio/PaddleDetection/ppdet/data/parallel_map.py:243: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  .format(sample.errmsg))
2020-09-09 08:48:51,606-WARNING: recv endsignal from outq with errmsg[consumer[consumer-83c-5] failed to map with error:[target0 not in samples]]
^C

**Comment by thunder95** [comment]
> 您好，麻烦提供下完整的log，我们看下TensorRT的优化阶段是否出了问题

@cryoco
之前貌似没报这个错failed to map with error:[target0 not in samples]]， 但刚刚为了给您演示的时候却报了， 有点奇怪

**Comment by thunder95** [comment]
> > 您好，麻烦提供下完整的log，我们看下TensorRT的优化阶段是否出了问题
> 
> @cryoco
> 之前貌似没报这个错failed to map with error:[target0 not in samples]]， 但刚刚为了给您演示的时候却报了， 有点奇怪

@cryoco 
翻看其他issue， 这个错误已解决，但是量化时出现了新的问题：

Traceback (most recent call last):
  File "train.py", line 317, in <module>
    main()
  File "train.py", line 241, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1082, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1080, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1178, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 893, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_noavx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::ReadOp::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
3   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
4   paddle::framework::details::ComputationOpHandle::RunImpl()
5   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
6   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
7   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
8   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
9   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2798, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1081, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 979, in __init__
    self._init_non_iterable()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 621, in from_generator
    iterable, return_list, drop_last)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 155, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "train.py", line 110, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "train.py", line 317, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The fed Variable target0 should have dimensions = 5, shape = [-1, 3, 12, -1, -1], but received fed shape [32, 3, 86, 10, 10]
  [Hint: Expected DimensionIsCompatibleWith(shapes[i], in_dims) == true, but received DimensionIsCompatibleWith(shapes[i], in_dims):0 != true:1.] at (/paddle/paddle/fluid/operators/reader/read_op.cc:140)
  [operator < read > error]

**Comment by cryoco** [comment]
您好，您开始时是用TRT部署时结果不正确，所以想看下部署相关的log哈，就是您发的
```python
W0903 19:09:51.112918 11793 helper.h:72] No implementation obeys reformatting-free rules, at least 2 reformatting nodes are needed, now picking the fastest path instead.
W0903 19:09:51.138789 11793 helper.h:72] TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0903 19:09:51.147464 11793 graph_pattern_detector.cc:101] ---  detected 3 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
```
这部分log再往上的内容。

现在您是又遇到量化训练的问题了么？这个可能需要 @baiyfbupt 再帮忙看下

**Comment by thunder95** [comment]
@baiyfbupt 麻烦看下， 我运行的命令如下：!python train.py --not_quant_pattern yolo_output --eval -c ../../myconfigs/my_ppyolo_quant.yml -o max_iters=20000 LearningRate.base_lr=0.0001 LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [8000]}]" weights=/home/aistudio/PaddleDetection/output/my_ppyolo/model_final

使用的配置是这个：
[confg_quant.zip](https://github.com/PaddlePaddle/PaddleSlim/files/5215492/confg_quant.zip)
