### ISSUE TITLE
模型量化

### ISSUE THREAD

**Issue by ZhijunLStudio** [PaddlePaddle/PaddleSlim#438]
在模型量化最后保存的时候，这块的输入和输出应该是什么呢，试了好多都报错
![微信图片_20200903172158](https://user-images.githubusercontent.com/60954978/92097159-587ea580-ee0a-11ea-8e31-bd3c22c3bb5e.png)
![微信图片_20200903172204](https://user-images.githubusercontent.com/60954978/92097167-5a486900-ee0a-11ea-84f1-9e2b0f419ab6.png)
![微信图片_20200903172207](https://user-images.githubusercontent.com/60954978/92097173-5c122c80-ee0a-11ea-842d-79f7eb9a6cef.png)

**Comment by baiyfbupt** [comment]
1. `.var()`接口需要传入一个variable name，建议check一下pred[-1]的类型，确保是string类型，或许应该是pred[-1].name？
2. 量化模型保存inference_model和普通模型保存inference_model没有区别，可以参照save_inference_model API文档https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model ,你这里的写法应该没有问题

**Comment by itminner** [comment]
请参考save_inference_model api文档，https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model
量化模型导出和float模型导出没有区别。
如果pred本身是个变量，放到target_vars数组里即可
