### ISSUE TITLE
模型部署问题

### ISSUE THREAD

**Issue by ZhijunLStudio** [PaddlePaddle/PaddleSlim#439]
我在模型部署的时候，他说我这个expand_as不能用，有其他可以把c x 1 x 1扩展为c x n x n的api吗
![微信图片_20200906202746](https://user-images.githubusercontent.com/60954978/92325731-76a10b80-f07f-11ea-8412-1d652e86bfaa.png)

**Comment by baiyfbupt** [comment]
可以试下concat: https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/concat_cn.html#concat
另外paddlelite近期增加了expand_as op的支持，可以在lite咨询下是否可用 https://github.com/PaddlePaddle/Paddle-Lite/pull/4047
