### ISSUE TITLE
Slimfacenet的数据集及格式问题

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleSlim#445]
[casia的dataloader](https://github.com/PaddlePaddle/PaddleSlim/blob/release/1.1.1/demo/slimfacenet/dataloader/casia.py)中的数据集是否可以提供下？

是否是将原始数据集CASIA-WebFace做112X96的resize即可？

还有就是对于提供的预训练模型，inference的每张图片格式是什么样的呢？
是否按照如下操作？

```
img = imgreader.imread('./test.jpg')
img = (img - 127.5) / 128.0
img = img.transpose(2, 0, 1)
```

**Comment by nihuizhidao** [comment]
数据集是CASIA-WebFace中检测到的face crop algin成112X96大小，这个问题解决了。

inference的preprocess是不是就是上面提到的那样呢？

**Comment by xiteng1988** [comment]
数据集可以提供的，我近期加上下载链接提个PR哈
