### ISSUE TITLE
模型量化文件数变少问题

### ISSUE THREAD

**Issue by ZhijunLStudio** [PaddlePaddle/PaddleSlim#452]
量化前的权重文件数是300个，量化之后是220个，以致于用量化之后权重的来预测，什么都预测不出来，我按着官方文档来的，但是不知道哪里出了问题
![微信图片_20200914075341](https://user-images.githubusercontent.com/60954978/93031691-75fc0c80-f65f-11ea-810c-da0a9333dd5a.png)
![2](https://user-images.githubusercontent.com/60954978/93031695-78f6fd00-f65f-11ea-81b1-5d616e586b80.png)

**Comment by wanghaoshuang** [comment]
方便贴下网络定义代码么？在save_inference_model时，会根据target_vars对网络进行回溯剪枝，指定错误的target_vars有可能会导致您描述的现象。

**Comment by itcastlizhijun** [comment]
> 方便貼下網絡定義代碼麼？在save_inference_model時，會根據target_vars對網絡進行回溯剪枝，指定錯誤的target_vars有可能會導致您描述的現象。
主函数：
def train():
        logger.info("start train YOLOv3, train params:%s", str(train_parameters))
        logger.info("create place, use gpu:" + str(train_parameters['use_gpu']))
        logger.info("build network and program")

        scope = fluid.global_scope()
        train_program = fluid.Program()
        start_program = fluid.Program()
        test_program = fluid.Program()
        eval_program = fluid.Program()

        feeder, reader, loss, img = build_program_with_feeder(train_program, start_program, place)
        pred = build_program_with_feeder(test_program, start_program, istrain=False)
        cur_map, accum_map, eval_feeder = build_eval_program_with_feeder(eval_program, start_program)

        test_program = test_program.clone(for_test=True)
        eval_program = eval_program.clone(for_test=True)

        logger.info("build executor and init params")
        # exe = fluid.Executor(place)
        exe.run(start_program, scope=scope)

        train_fetch_list = [loss[0].name]

        #load_pretrained_params(exe, train_program)  #加载预训练模型

        # 配置
        config = {'weight_quantize_type': 'abs_max',
                  'activation_quantize_type': 'moving_average_abs_max'}
        build_strategy = fluid.BuildStrategy()
        exec_strategy = fluid.ExecutionStrategy()
        # 调用api
        quant_train_program = slim.quant.quant_aware(train_program, place, config, for_test=False)
        quant_eval_program = slim.quant.quant_aware(test_program, place, config, for_test=True)
        # 关闭策略
        build_strategy.fuse_all_reduce_ops = False
        build_strategy.sync_batch_norm = False
        quant_train_program = quant_train_program.with_data_parallel(
            loss_name=loss[0].name,
            build_strategy=build_strategy,
            exec_strategy=exec_strategy)

        for pass_id in range(train_parameters["num_epochs"]):
            logger.info("current pass: {}, start read image".format(pass_id))
            batch_id = 0
            total_loss = 0.0
            for batch_id, data in enumerate(reader()):

                t1 = time.time()
                loss = exe.run(quant_train_program, feed=feeder.feed(data), fetch_list=train_fetch_list)
                period = time.time() - t1
                loss = np.mean(np.array(loss))
                total_loss += loss
                batch_id += 1
                total_batch_count += 1

                if batch_id % 200 == 0:
                    logger.info("pass {}, trainbatch {}, loss {}, time {}".format(pass_id, batch_id, loss,
                                                                                  "%2.2f sec" % period))

            pass_mean_loss = total_loss / batch_id
            logger.info("pass {0} train result, current pass mean loss: {1}".format(pass_id, pass_mean_loss))

        logger.info("end training")

        inference_prog, int8_prog = slim.quant.convert(quant_eval_program, place, config, scope=None, save_int8=True)
        target_vars = [inference_prog.global_block().var(pred.name)]
        fluid.io.save_inference_model(dirname='./inference_model/float',
                                      feeded_var_names=[img.name],
                                      target_vars=target_vars,
                                      executor=exe,
                                      main_program=inference_prog)
        fluid.io.save_inference_model(dirname='./inference_model/int8',
                                      feeded_var_names=[img.name],
                                      target_vars=target_vars,
                                      executor=exe,
                                      main_program=int8_prog)


def build_program_with_feeder(main_prog, startup_prog, place=None, istrain=True):
    """
    build_program_with_feeder
    :param main_prog:
    :param startup_prog:
    :param place:
    :param istrain:
    :return:
    """
    max_box_num = train_parameters['max_box_num']
    ues_tiny = train_parameters['use_tiny']
    yolo_config = train_parameters['yolo_tiny_cfg'] if ues_tiny else train_parameters['yolo_cfg']
    with fluid.program_guard(main_prog, startup_prog):
        img = fluid.layers.data(name='img', shape=yolo_config['input_size'], dtype='float32')
        gt_box = fluid.layers.data(name='gt_box', shape=[max_box_num, 4], dtype='float32')
        gt_label = fluid.layers.data(name='gt_label', shape=[max_box_num], dtype='int32')
        difficult = fluid.layers.data(name='difficult', shape=[max_box_num], dtype='int32')
        with fluid.unique_name.guard():
            model = get_yolo(ues_tiny, train_parameters['class_dim'], yolo_config['anchors'],
                             yolo_config['anchor_mask'])

            outputs = model.net(img)
            if istrain:

                feeder = fluid.DataFeeder(feed_list=[img, gt_box, gt_label, difficult], place=place, program=main_prog)
                reader = single_custom_reader(train_parameters['train_list'],
                                              train_parameters['data_dir'],
                                              yolo_config['input_size'], 'train')
                return feeder, reader, get_loss(model, outputs, gt_box, gt_label, main_prog),img

            else:
                boxes = []
                scores = []
                image_shape = fluid.layers.data(name="image_shape", shape=[2], dtype='int32')
                downsample_ratio = model.get_downsample_ratio()
                # feeder = fluid.DataFeeder(feed_list=[img, image_shape, gt_label, gt_box, difficult], place=place, program=main_prog)
                # reader = create_eval_reader(train_parameters['eval_list'], train_parameters['data_dir'], yolo_config['input_size'], 'eval')
                for i, out in enumerate(outputs):
                    box, score = fluid.layers.yolo_box(
                        x=out,
                        img_size=image_shape,
                        anchors=model.get_yolo_anchors()[i],
                        class_num=model.get_class_num(),
                        conf_thresh=train_parameters['valid_thresh'],
                        downsample_ratio=downsample_ratio,
                        name="yolo_box_" + str(i))
                    boxes.append(box)
                    scores.append(fluid.layers.transpose(score, perm=[0, 2, 1]))
                    downsample_ratio //= 2

                pred = fluid.layers.multiclass_nms(
                    bboxes=fluid.layers.concat(boxes, axis=1),
                    scores=fluid.layers.concat(scores, axis=2),
                    score_threshold=0.005,
                    nms_top_k=train_parameters['nms_top_k'],
                    keep_top_k=train_parameters['nms_pos_k'],
                    nms_threshold=train_parameters['nms_thresh'],
                    background_label=-1,
                    name="multiclass_nms")

                return pred

**Comment by itcastlizhijun** [comment]
> 方便貼下網絡定義代碼麼？在save_inference_model時，會根據target_vars對網絡進行回溯剪枝，指定錯誤的target_vars有可能會導致您描述的現象。

def train():
        logger.info("start train YOLOv3, train params:%s", str(train_parameters))
        logger.info("create place, use gpu:" + str(train_parameters['use_gpu']))
        logger.info("build network and program")

        scope = fluid.global_scope()
        train_program = fluid.Program()
        start_program = fluid.Program()
        test_program = fluid.Program()
        eval_program = fluid.Program()

        feeder, reader, loss, img = build_program_with_feeder(train_program, start_program, place)
        pred = build_program_with_feeder(test_program, start_program, istrain=False)
        cur_map, accum_map, eval_feeder = build_eval_program_with_feeder(eval_program, start_program)

        test_program = test_program.clone(for_test=True)
        eval_program = eval_program.clone(for_test=True)

        logger.info("build executor and init params")
        # exe = fluid.Executor(place)
        exe.run(start_program, scope=scope)

        train_fetch_list = [loss[0].name]

        #load_pretrained_params(exe, train_program)  #加载预训练模型

        # 配置
        config = {'weight_quantize_type': 'abs_max',
                  'activation_quantize_type': 'moving_average_abs_max'}
        build_strategy = fluid.BuildStrategy()
        exec_strategy = fluid.ExecutionStrategy()
        # 调用api
        quant_train_program = slim.quant.quant_aware(train_program, place, config, for_test=False)
        quant_eval_program = slim.quant.quant_aware(test_program, place, config, for_test=True)
        # 关闭策略
        build_strategy.fuse_all_reduce_ops = False
        build_strategy.sync_batch_norm = False
        quant_train_program = quant_train_program.with_data_parallel(
            loss_name=loss[0].name,
            build_strategy=build_strategy,
            exec_strategy=exec_strategy)

        for pass_id in range(train_parameters["num_epochs"]):
            logger.info("current pass: {}, start read image".format(pass_id))
            batch_id = 0
            total_loss = 0.0
            for batch_id, data in enumerate(reader()):

                t1 = time.time()
                loss = exe.run(quant_train_program, feed=feeder.feed(data), fetch_list=train_fetch_list)
                period = time.time() - t1
                loss = np.mean(np.array(loss))
                total_loss += loss
                batch_id += 1
                total_batch_count += 1

                if batch_id % 200 == 0:
                    logger.info("pass {}, trainbatch {}, loss {}, time {}".format(pass_id, batch_id, loss,
                                                                                  "%2.2f sec" % period))

            pass_mean_loss = total_loss / batch_id
            logger.info("pass {0} train result, current pass mean loss: {1}".format(pass_id, pass_mean_loss))

        logger.info("end training")

        inference_prog, int8_prog = slim.quant.convert(quant_eval_program, place, config, scope=None, save_int8=True)
        target_vars = [inference_prog.global_block().var(pred.name)]
        fluid.io.save_inference_model(dirname='./inference_model/float',
                                      feeded_var_names=[img.name],
                                      target_vars=target_vars,
                                      executor=exe,
                                      main_program=inference_prog)
        fluid.io.save_inference_model(dirname='./inference_model/int8',
                                      feeded_var_names=[img.name],
                                      target_vars=target_vars,
                                      executor=exe,
                                      main_program=int8_prog)

**Comment by itcastlizhijun** [comment]
> 方便貼下網絡定義代碼麼？在save_inference_model時，會根據target_vars對網絡進行回溯剪枝，指定錯誤的target_vars有可能會導致您描述的現象。

def train():
        scope = fluid.global_scope()
        train_program = fluid.Program()
        start_program = fluid.Program()
        test_program = fluid.Program()
        eval_program = fluid.Program()

        feeder, reader, loss, img = build_program_with_feeder(train_program, start_program, place)
        pred = build_program_with_feeder(test_program, start_program, istrain=False)
        cur_map, accum_map, eval_feeder = build_eval_program_with_feeder(eval_program, start_program)

        test_program = test_program.clone(for_test=True)
        eval_program = eval_program.clone(for_test=True)

        logger.info("build executor and init params")
        # exe = fluid.Executor(place)
        exe.run(start_program, scope=scope)

        train_fetch_list = [loss[0].name]

        #load_pretrained_params(exe, train_program)  #加载预训练模型

        # 配置
        config = {'weight_quantize_type': 'abs_max',
                  'activation_quantize_type': 'moving_average_abs_max'}
        build_strategy = fluid.BuildStrategy()
        exec_strategy = fluid.ExecutionStrategy()
        # 调用api
        quant_train_program = slim.quant.quant_aware(train_program, place, config, for_test=False)
        quant_eval_program = slim.quant.quant_aware(test_program, place, config, for_test=True)
        # 关闭策略
        build_strategy.fuse_all_reduce_ops = False
        build_strategy.sync_batch_norm = False
        quant_train_program = quant_train_program.with_data_parallel(
            loss_name=loss[0].name,
            build_strategy=build_strategy,
            exec_strategy=exec_strategy)

        for pass_id in range(train_parameters["num_epochs"]):
            logger.info("current pass: {}, start read image".format(pass_id))
            batch_id = 0
            total_loss = 0.0
            for batch_id, data in enumerate(reader()):

                t1 = time.time()
                loss = exe.run(quant_train_program, feed=feeder.feed(data), fetch_list=train_fetch_list)
                period = time.time() - t1
                loss = np.mean(np.array(loss))
                total_loss += loss
                batch_id += 1
                total_batch_count += 1

                if batch_id % 200 == 0:
                    logger.info("pass {}, trainbatch {}, loss {}, time {}".format(pass_id, batch_id, loss,
                                                                                  "%2.2f sec" % period))

            pass_mean_loss = total_loss / batch_id
            logger.info("pass {0} train result, current pass mean loss: {1}".format(pass_id, pass_mean_loss))

        logger.info("end training")

        inference_prog, int8_prog = slim.quant.convert(quant_eval_program, place, config, scope=None, save_int8=True)
        target_vars = [inference_prog.global_block().var(pred.name)]
        fluid.io.save_inference_model(dirname='./inference_model/float',
                                      feeded_var_names=[img.name],
                                      target_vars=target_vars,
                                      executor=exe,
                                      main_program=inference_prog)
        fluid.io.save_inference_model(dirname='./inference_model/int8',
                                      feeded_var_names=[img.name],
                                      target_vars=target_vars,
                                      executor=exe,
                                      main_program=int8_prog)

**Comment by itcastlizhijun** [comment]
def train():
    logger.info("start train YOLOv3, train params:%s", str(train_parameters))
    logger.info("create place, use gpu:" + str(train_parameters['use_gpu']))
    logger.info("build network and program")

    scope = fluid.global_scope()
    train_program = fluid.Program()
    start_program = fluid.Program()
    test_program = fluid.Program()
    eval_program = fluid.Program()

    feeder, reader, loss, img = build_program_with_feeder(train_program, start_program, place)
    pred = build_program_with_feeder(test_program, start_program, istrain=False)
    cur_map, accum_map, eval_feeder = build_eval_program_with_feeder(eval_program, start_program)

    test_program = test_program.clone(for_test=True)
    eval_program = eval_program.clone(for_test=True)

    logger.info("build executor and init params")
    # exe = fluid.Executor(place)
    exe.run(start_program, scope=scope)

    train_fetch_list = [loss[0].name]

    #load_pretrained_params(exe, train_program)  #加载预训练模型

    # 配置
    config = {'weight_quantize_type': 'abs_max',
              'activation_quantize_type': 'moving_average_abs_max'}
    build_strategy = fluid.BuildStrategy()
    exec_strategy = fluid.ExecutionStrategy()
    # 调用api
    quant_train_program = slim.quant.quant_aware(train_program, place, config, for_test=False)
    quant_eval_program = slim.quant.quant_aware(test_program, place, config, for_test=True)
    # 关闭策略
    build_strategy.fuse_all_reduce_ops = False
    build_strategy.sync_batch_norm = False
    quant_train_program = quant_train_program.with_data_parallel(
        loss_name=loss[0].name,
        build_strategy=build_strategy,
        exec_strategy=exec_strategy)

    for pass_id in range(train_parameters["num_epochs"]):
        logger.info("current pass: {}, start read image".format(pass_id))
        batch_id = 0
        total_loss = 0.0
        for batch_id, data in enumerate(reader()):

            t1 = time.time()
            loss = exe.run(quant_train_program, feed=feeder.feed(data), fetch_list=train_fetch_list)
            period = time.time() - t1
            loss = np.mean(np.array(loss))
            total_loss += loss
            batch_id += 1
            total_batch_count += 1

            if batch_id % 200 == 0:
                logger.info("pass {}, trainbatch {}, loss {}, time {}".format(pass_id, batch_id, loss,
                                                                              "%2.2f sec" % period))

        pass_mean_loss = total_loss / batch_id
        logger.info("pass {0} train result, current pass mean loss: {1}".format(pass_id, pass_mean_loss))

    logger.info("end training")

    inference_prog, int8_prog = slim.quant.convert(quant_eval_program, place, config, scope=None, save_int8=True)
    target_vars = [inference_prog.global_block().var(pred.name)]
    fluid.io.save_inference_model(dirname='./inference_model/float',
                                  feeded_var_names=[img.name],
                                  target_vars=target_vars,
                                  executor=exe,
                                  main_program=inference_prog)
    fluid.io.save_inference_model(dirname='./inference_model/int8',
                                  feeded_var_names=[img.name],
                                  target_vars=target_vars,
                                  executor=exe,
                                  main_program=int8_prog)

**Comment by ZhijunLStudio** [comment]
> 方便贴下网络定义代码么？在save_inference_model时，会根据target_vars对网络进行回溯剪枝，指定错误的target_vars有可能会导致您描述的现象。



def build_program_with_feeder(main_prog, startup_prog, place=None, istrain=True):

    max_box_num = train_parameters['max_box_num']
    ues_tiny = train_parameters['use_tiny']
    yolo_config = train_parameters['yolo_tiny_cfg'] if ues_tiny else train_parameters['yolo_cfg']
    with fluid.program_guard(main_prog, startup_prog):
        img = fluid.layers.data(name='img', shape=yolo_config['input_size'], dtype='float32')
        gt_box = fluid.layers.data(name='gt_box', shape=[max_box_num, 4], dtype='float32')
        gt_label = fluid.layers.data(name='gt_label', shape=[max_box_num], dtype='int32')
        difficult = fluid.layers.data(name='difficult', shape=[max_box_num], dtype='int32')
        with fluid.unique_name.guard():
            model = get_yolo(ues_tiny, train_parameters['class_dim'], yolo_config['anchors'],
                             yolo_config['anchor_mask'])

            outputs = model.net(img)
            if istrain:

                feeder = fluid.DataFeeder(feed_list=[img, gt_box, gt_label, difficult], place=place, program=main_prog)
                reader = single_custom_reader(train_parameters['train_list'],
                                              train_parameters['data_dir'],
                                              yolo_config['input_size'], 'train')
                reader = multi_process_custom_reader(train_parameters['train_list'],
                                                     train_parameters['data_dir'],
                                                     4, 'train')
                return feeder, reader, get_loss(model, outputs, gt_box, gt_label, main_prog),img
            else:
                boxes = []
                scores = []
                image_shape = fluid.layers.data(name="image_shape", shape=[2], dtype='int32')
                downsample_ratio = model.get_downsample_ratio()
                # feeder = fluid.DataFeeder(feed_list=[img, image_shape, gt_label, gt_box, difficult], place=place, program=main_prog)
                # reader = create_eval_reader(train_parameters['eval_list'], train_parameters['data_dir'], yolo_config['input_size'], 'eval')
                for i, out in enumerate(outputs):
                    box, score = fluid.layers.yolo_box(
                        x=out,
                        img_size=image_shape,
                        anchors=model.get_yolo_anchors()[i],
                        class_num=model.get_class_num(),
                        conf_thresh=train_parameters['valid_thresh'],
                        downsample_ratio=downsample_ratio,
                        name="yolo_box_" + str(i))
                    boxes.append(box)
                    scores.append(fluid.layers.transpose(score, perm=[0, 2, 1]))
                    downsample_ratio //= 2

                pred = fluid.layers.multiclass_nms(
                    bboxes=fluid.layers.concat(boxes, axis=1),
                    scores=fluid.layers.concat(scores, axis=2),
                    score_threshold=0.005,
                    nms_top_k=train_parameters['nms_top_k'],
                    keep_top_k=train_parameters['nms_pos_k'],
                    nms_threshold=train_parameters['nms_thresh'],
                    background_label=-1,
                    name="multiclass_nms")

                return pred

**Comment by ZhijunLStudio** [comment]
> 方便贴下网络定义代码么？在save_inference_model时，会根据target_vars对网络进行回溯剪枝，指定错误的target_vars有可能会导致您描述的现象。

def train():

    logger.info("start train YOLOv3, train params:%s", str(train_parameters))
    logger.info("create place, use gpu:" + str(train_parameters['use_gpu']))
    logger.info("build network and program")

    scope = fluid.global_scope()
    train_program = fluid.Program()
    start_program = fluid.Program()
    test_program = fluid.Program()
    eval_program = fluid.Program()

    feeder, reader, loss, img = build_program_with_feeder(train_program, start_program, place)
    pred = build_program_with_feeder(test_program, start_program, istrain=False)
    cur_map, accum_map, eval_feeder = build_eval_program_with_feeder(eval_program, start_program)

    test_program = test_program.clone(for_test=True)
    eval_program = eval_program.clone(for_test=True)

    logger.info("build executor and init params")
    # exe = fluid.Executor(place)
    exe.run(start_program, scope=scope)

    train_fetch_list = [loss[0].name]

    #load_pretrained_params(exe, train_program)  #加载预训练模型

    # 配置
    config = {'weight_quantize_type': 'abs_max',
              'activation_quantize_type': 'moving_average_abs_max'}
    build_strategy = fluid.BuildStrategy()
    exec_strategy = fluid.ExecutionStrategy()
    # 调用api
    quant_train_program = slim.quant.quant_aware(train_program, place, config, for_test=False)
    quant_eval_program = slim.quant.quant_aware(test_program, place, config, for_test=True)
    # 关闭策略
    build_strategy.fuse_all_reduce_ops = False
    build_strategy.sync_batch_norm = False
    quant_train_program = quant_train_program.with_data_parallel(
        loss_name=loss[0].name,
        build_strategy=build_strategy,
        exec_strategy=exec_strategy)

    for pass_id in range(train_parameters["num_epochs"]):
        logger.info("current pass: {}, start read image".format(pass_id))
        batch_id = 0
        total_loss = 0.0
        for batch_id, data in enumerate(reader()):

            t1 = time.time()
            loss = exe.run(quant_train_program, feed=feeder.feed(data), fetch_list=train_fetch_list)
            period = time.time() - t1
            loss = np.mean(np.array(loss))
            total_loss += loss
            batch_id += 1
            total_batch_count += 1

            if batch_id % 200 == 0:
                logger.info("pass {}, trainbatch {}, loss {}, time {}".format(pass_id, batch_id, loss,
                                                                              "%2.2f sec" % period))

        pass_mean_loss = total_loss / batch_id
        logger.info("pass {0} train result, current pass mean loss: {1}".format(pass_id, pass_mean_loss))

    logger.info("end training")

    inference_prog, int8_prog = slim.quant.convert(quant_eval_program, place, config, scope=None, save_int8=True)
    target_vars = [inference_prog.global_block().var(pred.name)]
    fluid.io.save_inference_model(dirname='./inference_model/float',
                                  feeded_var_names=[img.name],
                                  target_vars=target_vars,
                                  executor=exe,
                                  main_program=inference_prog)
    fluid.io.save_inference_model(dirname='./inference_model/int8',
                                  feeded_var_names=[img.name],
                                  target_vars=target_vars,
                                  executor=exe,
                                  main_program=int8_prog)

**Comment by wanghaoshuang** [comment]
hi，我看你代码里调用`save_inference_model`时指定的target_vars没问题。

>量化前的权重文件数是300个

1. 这里指的权重文件确定全是weight和bias么？会不会包含了优化器相关的一些中间变量？
2. 你能统计观察出量化后少了哪些权重文件么？

**Comment by itcastlizhijun** [comment]
> hi，我看你代码里调用`save_inference_model`时指定的target_vars没问题。
> 
> > 量化前的权重文件数是300个
> 
> 1. 这里指的权重文件确定全是weight和bias么？会不会包含了优化器相关的一些中间变量？
> 2. 你能统计观察出量化后少了哪些权重文件么？

您好，第一张图是原本权重文件中有，但是量化之后没有；第二张图是量化之后有，原本权重文件没有
![1](https://user-images.githubusercontent.com/60954978/93335383-f46fce80-f858-11ea-94c4-b2be6df460b3.png)
![2](https://user-images.githubusercontent.com/60954978/93335402-fb96dc80-f858-11ea-9d05-1f0925696a60.png)

**Comment by ZhijunLStudio** [comment]
> hi，我看你代码里调用`save_inference_model`时指定的target_vars没问题。
> 
> > 量化前的权重文件数是300个
> 
> 1. 这里指的权重文件确定全是weight和bias么？会不会包含了优化器相关的一些中间变量？
> 2. 你能统计观察出量化后少了哪些权重文件么？

您好，第一张图片是原本权重文件有，但是量化之后没有；第二张图片是量化之后有，但是原本的权重文件没有，麻烦您看一下
![1](https://user-images.githubusercontent.com/60954978/93335961-ba52fc80-f859-11ea-8bd8-893609a579ff.png)
![2](https://user-images.githubusercontent.com/60954978/93336290-26cdfb80-f85a-11ea-8a26-8cd96ced5153.png)

**Comment by wanghaoshuang** [comment]
>您好，第一张图片是原本权重文件有，但是量化之后没有；第二张图片是量化之后有，但是原本的权重文件没有，麻烦您看一下

您好，这个现象是正常的。

1. 第一张图片里的权重是训练时优化器相关的变量，在预测时是不需要这些变量的。
2. 第二张图是做了量化之后引入的量化相关的变量，是正常的。
