### ISSUE TITLE
请问一下，在进行模型裁剪时，需要先进性的敏感度分析的原则是什么？也就是说敏感度是怎么算出来的？

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleSlim#468]

**Comment by yukavio** [comment]
在敏感度分析的过程中，会对网络模型中各个网络层独立的按照指定的稀疏比例进行裁剪，得出网络模型在各网络层不同的裁剪比例下精度损失的比例，损失的比例就是各网络层在不同稀疏度下的敏感度。
具体可以看一下：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/algo/algo.md 里关于敏感度分析的部分。
