### ISSUE TITLE
检测模型量化误差

### ISSUE THREAD

**Issue by Youngon** [PaddlePaddle/PaddleSlim#469]
我用的相同的数据集，相同的配置文件，分别训练了非量化版本以及量化版本，为什么测试mAP差别这么大？
（PaddleDetection/tools/train.py）非量化迭代30000次：
![image](https://user-images.githubusercontent.com/7603531/94383374-6eb22400-0172-11eb-8d39-e56c43706168.png)
（PaddleDetection/slin/quantization/train.py）量化迭代30000次：
![image](https://user-images.githubusercontent.com/7603531/94383384-783b8c00-0172-11eb-8bd5-2f3fa2a5f4a3.png)
差的不是一点半点

**Comment by wanghaoshuang** [comment]
请问您是不是贴错图了？这两个图看起来是一样的。

**Comment by Youngon** [comment]
> 请问您是不是贴错图了？这两个图看起来是一样的。

是我贴错了  非量化训练见下图
![image](https://user-images.githubusercontent.com/7603531/94400985-81415300-019c-11eb-966d-dc377b63fc83.png)

**Comment by baiyfbupt** [comment]
量化模型需要在训练好的FP32模型上进行finetune 训练，是这样训练的吗？
