### ISSUE TITLE
请问动态图怎么用paddleslim进行裁剪

### ISSUE THREAD

**Issue by doge-ac-cn** [PaddlePaddle/PaddleSlim#476]
现在是可以通过转换为静态图，保存为推断模型，但是不知道怎么进行模型通道裁剪。
` out_dygraph, static_layer = TracedLayer.trace(DeepSortNet, inputs=[image])
    static_layer.save_inference_model('infer_model')
`
因为 pruner.prune裁剪时需要传入program，但是动态图训练时并没有用programe

**Comment by wanghaoshuang** [comment]
您好，感谢反馈。

PaddleSlim暂时还不支持PaddlePaddle动态图, 当前我们正在高优开发支持动态图，预计11月底会完成相关开发。
