### ISSUE TITLE
量化模型每一层的细节参数

### ISSUE THREAD

**Issue by yhhu99** [PaddlePaddle/PaddleSlim#477]
在已经成功量化并得到了inference模型文件（\__model__与__params\__），请问如果想要得到网络中每一层的量化参数（细节），需要怎么做呢？谢谢！

**Comment by baiyfbupt** [comment]
您好，您可以安装[netron](https://github.com/lutzroeder/netron)后将__model__用其打开，可以看到模型的可视化结构和详细参数

**Comment by yhhu99** [comment]
> 您好，您可以安装[netron](https://github.com/lutzroeder/netron)后将__model__用其打开，可以看到模型的可视化结构和详细参数

好的，十分感谢回答！

**Comment by yhhu99** [comment]
> 您好，您可以安装[netron](https://github.com/lutzroeder/netron)后将__model__用其打开，可以看到模型的可视化结构和详细参数

您好，之前按照您的方法成功得到了模型结构信息，那有没有方法可以得到每一层的参数值呢？（比如权重参数，量化参数的具体数值）

**Comment by baiyfbupt** [comment]
可以在获取到各层参数的名称param_name之后通过以下代码这样获取：
```python
param = fluid.global_scope().find_var(param_name)
if param is not None:
    param_in_numpy = np.array(param.get_tensor())
```

**Comment by yhhu99** [comment]
> 可以在获取到各层参数的名称param_name之后通过以下代码这样获取：
> 
> ```python
> param = fluid.global_scope().find_var(param_name)
> if param is not None:
>     param_in_numpy = np.array(param.get_tensor())
> ```
感谢回答，这个API我在paddle的文档中有看到过，但是现在的问题在于要怎么从inference模型文件（model和params）获取各层的参数名呢？谢谢🙏

**Comment by yhhu99** [comment]
> 可以在获取到各层参数的名称param_name之后通过以下代码这样获取：
> 
> ```python
> param = fluid.global_scope().find_var(param_name)
> if param is not None:
>     param_in_numpy = np.array(param.get_tensor())
> ```

已经找到办法啦，感谢帮助！！
