### ISSUE TITLE
使用SlimFaceNet_C_x0_75()网络进行训练时出现错误InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [2, 3427] and the shape of Y = [4, 3427]. Received [2] in X is not equal to [4] in Y at i:0.

### ISSUE THREAD

**Issue by zhudibo** [PaddlePaddle/PaddleSlim#479]
求大佬指点，在使用SlimFaceNet_C_x0_75()模型训练时出现InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [2, 3427] and the shape of Y = [4, 3427]. Received [2] in X is not equal to [4] in Y at i:0.错误，感谢

**Comment by xiteng1988** [comment]
> 求大佬指点，在使用SlimFaceNet_C_x0_75()模型训练时出现InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [2, 3427] and the shape of Y = [4, 3427]. Received [2] in X is not equal to [4] in Y at i:0.错误，感谢

你使用的数据集是从slimfacenet demo提供的链接下载的吗？还是你自己下载的数据集？
