### ISSUE TITLE
直接贴的教程里的代码运行，结果报错InvalidArgumentError

### ISSUE THREAD

**Issue by doge-ac-cn** [PaddlePaddle/PaddleSlim#480]
代码
`import paddle
import paddle.fluid as fluid
import paddleslim as slim

exe, train_program, val_program, inputs, outputs = slim.models.image_classification("MobileNet", [1, 28, 28], 10,
                                                                                    use_gpu=True)
place = fluid.CUDAPlace(0)
import paddle.dataset.mnist as reader

train_reader = paddle.fluid.io.batch(
    reader.train(), batch_size=128, drop_last=True)
test_reader = paddle.fluid.io.batch(
    reader.test(), batch_size=128, drop_last=True)
data_feeder = fluid.DataFeeder(inputs, place)
import numpy as np

def test(program):
    acc_top1_ns = []
    acc_top5_ns = []
    for data in test_reader():
        acc_top1_n, acc_top5_n, _ = exe.run(
            program,
            feed=data_feeder.feed(data),
            fetch_list=outputs)
        acc_top1_ns.append(np.mean(acc_top1_n))
        acc_top5_ns.append(np.mean(acc_top5_n))
    print("Final eva - acc_top1: {}; acc_top5: {}".format(
        np.mean(np.array(acc_top1_ns)), np.mean(np.array(acc_top5_ns))))
    return np.mean(np.array(acc_top1_ns))

for data in train_reader():
    acc1, acc5, loss = exe.run(train_program, feed=data_feeder.feed(data), fetch_list=outputs)
print(np.mean(acc1), np.mean(acc5), np.mean(loss))

test(val_program)

params = []
for param in train_program.global_block().all_parameters():
    if "_sep_weights" in param.name:
        params.append(param.name)
print(params)
params = params[:5]

sens_0 = slim.prune.sensitivity(
    val_program,
    place,
    params,
    test,
    sensitivities_file="sensitivities_0.data",
    pruned_ratios=[0.1, 0.2])
print(sens_0)

sens_0 = slim.prune.sensitivity(
    val_program,
    place,
    params,
    test,
    sensitivities_file="sensitivities_0.data",
    pruned_ratios=[0.3])
print(sens_0)

sens_1 = slim.prune.sensitivity(
    val_program,
    place,
    params,
    test,
    sensitivities_file="sensitivities_1.data",
    pruned_ratios=[0.4])
print(sens_1)

s_0 = slim.prune.load_sensitivities("sensitivities_0.data")
s_1 = slim.prune.load_sensitivities("sensitivities_1.data")
print(s_0)
print(s_1)

s = slim.prune.merge_sensitive([s_0, s_1])
print(s)

loss = 0.01
ratios = slim.prune.get_ratios_by_loss(s_0, loss)
print(ratios)

pruner = slim.prune.Pruner()
print("FLOPs before pruning: {}".format(slim.analysis.flops(train_program)))
pruned_program, _, _ = pruner.prune(
    train_program,
    fluid.global_scope(),
    params=ratios.keys(),
    ratios=ratios.values(),
    place=place)
print("FLOPs after pruning: {}".format(slim.analysis.flops(pruned_program)))

pruner = slim.prune.Pruner()
print("FLOPs before pruning: {}".format(slim.analysis.flops(val_program)))
pruned_val_program, _, _ = pruner.prune(
    val_program,
    fluid.global_scope(),
    params=ratios.keys(),
    ratios=ratios.values(),
    place=place,
    only_graph=True)
print("FLOPs after pruning: {}".format(slim.analysis.flops(pruned_val_program)))

test(pruned_val_program)

for data in train_reader():
    acc1, acc5, loss = exe.run(pruned_program, feed=data_feeder.feed(data), fetch_list=outputs)
print(np.mean(acc1), np.mean(acc5), np.mean(loss))

test(pruned_val_program)
`

报错
`0.9921875 1.0 0.02577366
Final eva - acc_top1: 0.9693509340286255; acc_top5: 0.9984976053237915
['conv2_1_sep_weights', 'conv2_2_sep_weights', 'conv3_1_sep_weights', 'conv3_2_sep_weights', 'conv4_1_sep_weights', 'conv4_2_sep_weights', 'conv5_1_sep_weights', 'conv5_2_sep_weights', 'conv5_3_sep_weights', 'conv5_4_sep_weights', 'conv5_5_sep_weights', 'conv5_6_sep_weights', 'conv6_sep_weights']
2020-10-23 11:56:39,170-INFO: sensitive - param: conv2_1_sep_weights; ratios: 0.1
Final eva - acc_top1: 0.9693509340286255; acc_top5: 0.9984976053237915
2020-10-23 11:56:39,186-INFO: pruning: conv2_1_sep_weights
Traceback (most recent call last):
  File "C:/Users/83942/Desktop/github/paddleslim模型裁剪/main.py", line 46, in <module>
    pruned_ratios=[0.1, 0.2])
  File "C:\Users\83942\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleslim\prune\sensitive.py", line 99, in sensitivity
    param_backup=True)
  File "C:\Users\83942\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleslim\prune\pruner.py", line 165, in prune
    graph.infer_shape()
  File "C:\Users\83942\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleslim\core\graph_wrapper.py", line 362, in infer_shape
    op._op.desc.infer_shape(op._op.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\Users\83942\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\83942\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "C:\Users\83942\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layers\nn.py", line 2938, in conv2d
    "data_format": data_format,
  File "C:\Users\83942\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleslim\models\mobilenet.py", line 162, in conv_bn_layer
    bias_attr=False)
  File "C:\Users\83942\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleslim\models\mobilenet.py", line 188, in depthwise_separable
    name=name + "_dw")
  File "C:\Users\83942\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleslim\models\mobilenet.py", line 55, in net
    name="conv2_2")
  File "C:\Users\83942\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleslim\models\util.py", line 19, in image_classification
    out = model.net(input=image, class_dim=class_num)
  File "C:/Users/83942/Desktop/github/paddleslim模型裁剪/main.py", line 4, in <module>
    exe, train_program, val_program, inputs, outputs = slim.models.image_classification("MobileNet", [1, 28, 28], 10, use_gpu=True)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 64, the input's shape is [-1, 64, 14, 14]; the filter's channels is 1, the filter's shape is [64, 1, 3, 3]; the groups is 63, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:64 != filter_dims[1] * groups:63.] at (D:\1.8.5\paddle\paddle\fluid\operators\conv_op.cc:94)
  [operator < depthwise_conv2d > error]
W1023 11:56:00.958933  3628 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 11.1, Runtime API Version: 10.0
W1023 11:56:00.966912  3628 device_context.cc:260] device: 0, cuDNN Version: 7.6.`

**Comment by wanghaoshuang** [comment]
麻烦您贴一下PaddlePaddle的版本和PaddleSlim的版本？

**Comment by doge-ac-cn** [comment]
![image](https://user-images.githubusercontent.com/22387890/97252140-3ae71e80-1844-11eb-8076-2534c3436946.png)

**Comment by wanghaoshuang** [comment]
您的问题已在https://github.com/PaddlePaddle/PaddleSlim/commit/8ba34d787f21bab62716941492ffbf6e4238f669#diff-4325d04c12b19f2a133f8674953c32f4683cddd0af8e2708509d411ac7073a83 中修复，请您安装PaddleSlim develop试一下吧。

后续我们会尽快发布稳定的修复版本。
