### ISSUE TITLE
arc_margin_product（）函数中报错

### ISSUE THREAD

**Issue by zhudibo** [PaddlePaddle/PaddleSlim#481]
大佬我在运行SlimFaceNet_C_x0_75()网络时，在arc_margin_product（）中one_hot = fluid.one_hot(input=label, depth=out_dim)行报以下的错误
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/un/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/un/.local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/un/.local/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12212, in _elementwise_op
    'use_mkldnn': use_mkldnn})
  File "/home/un/.local/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12643, in elementwise_mul
    return _elementwise_op(LayerHelper('elementwise_mul', **locals()))
  File "/home/un/work/mobilenetv2/arcmarginloss.py", line 120, in arc_margin_product
    one_hot, phi) + fluid.layers.elementwise_mul(
  File "/home/un/work/mobilenetv2/arcmarginloss.py", line 29, in loss
    out = self.arc_margin_product(input, label, self.class_dim, self.margin, self.scale, self.easy_margin)
  File "/home/un/work/mobilenetv2/train.py", line 865, in train
    cost,out = metricloss.loss(out_featrue, label)
  File "/home/un/work/mobilenetv2/train.py", line 969, in <module>
    train()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [10, 3427] and the shape of Y = [20, 3427]. Received [10] in X is not equal to [20] in Y at i:0.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:157)
  [operator < elementwise_mul > error]

**Comment by xiteng1988** [comment]
> ## 大佬我在运行SlimFaceNet_C_x0_75()网络时，在arc_margin_product（）中one_hot = fluid.one_hot(input=label, depth=out_dim)行报以下的错误
> Python Call Stacks (More useful to users):
> File "/home/un/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
> attrs=kwargs.get("attrs", None))
> File "/home/un/.local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
> return self.main_program.current_block().append_op(*args, **kwargs)
> File "/home/un/.local/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12212, in _elementwise_op
> 'use_mkldnn': use_mkldnn})
> File "/home/un/.local/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12643, in elementwise_mul
> return _elementwise_op(LayerHelper('elementwise_mul', **locals()))
> File "/home/un/work/mobilenetv2/arcmarginloss.py", line 120, in arc_margin_product
> one_hot, phi) + fluid.layers.elementwise_mul(
> File "/home/un/work/mobilenetv2/arcmarginloss.py", line 29, in loss
> out = self.arc_margin_product(input, label, self.class_dim, self.margin, self.scale, self.easy_margin)
> File "/home/un/work/mobilenetv2/train.py", line 865, in train
> cost,out = metricloss.loss(out_featrue, label)
> File "/home/un/work/mobilenetv2/train.py", line 969, in
> train()
> 
> ## Error Message Summary:
> InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [10, 3427] and the shape of Y = [20, 3427]. Received [10] in X is not equal to [20] in Y at i:0.
> [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:157)
> [operator < elementwise_mul > error]


你使用的paddle和slim版本分别是哪个版本呢？

**Comment by zhudibo-unwulian** [comment]
问题我已经找到了，slimfacenet中使用的arc_margin_product函数在计算损失时也就是slimfacenet.py中第337行的one_hot = fluid.one_hot(input=label, depth=out_dim)存在bug，官网这部分有问题，应该改为one_hot = fluid.layers.one_hot(input=label, depth=out_dim)，

**Comment by yangy996** [comment]
> 问题我已经找到了，slimfacenet中使用的arc_margin_product函数在计算损失时也就是slimfacenet.py中第337行的one_hot = fluid.one_hot(input=label, depth=out_dim)存在bug，官网这部分有问题，应该改为one_hot = fluid.layers.one_hot(input=label, depth=out_dim)，

厉害了，尝试了下，完美解决
