### ISSUE TITLE
使用slimfacenet在训练模型遇到如下问题

### ISSUE THREAD

**Issue by zhudibo** [PaddlePaddle/PaddleSlim#482]
大佬我在使用slimfacenet训练模型时，网络的输出               x = fluid.layers.conv2d(
            x,
            num_filters=128,
            filter_size=1,
            stride=1,
            padding=0,
            groups=1,
            act=None,
            use_cudnn=True,
            param_attr=ParamAttr(
                name='linear_conv1x1_weights',
                initializer=MSRA(),
                regularizer=fluid.regularizer.L2Decay(4e-4)),
            bias_attr=False)
        bn_name = 'linear_conv1x1_bn'
        x = fluid.layers.batch_norm(
            x,
            param_attr=ParamAttr(name=bn_name + "_scale"),
            bias_attr=ParamAttr(name=bn_name + "_offset"),
            moving_mean_name=bn_name + '_mean',
            moving_variance_name=bn_name + '_variance')
        print(x.shape,x.shape[0],x.shape[1])
        x = fluid.layers.reshape(x, shape=[x.shape[0], x.shape[1]])
的卷积层的输出特征输入到损失网络时报一下的错误：
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [80, 3427] and the shape of Y = [160, 3427]. Received [80] in X is not equal to [160] in Y at i:0.恳请大佬给予指点啊

**Comment by xiteng1988** [comment]
> 大佬我在使用slimfacenet训练模型时，网络的输出 x = fluid.layers.conv2d(
> x,
> num_filters=128,
> filter_size=1,
> stride=1,
> padding=0,
> groups=1,
> act=None,
> use_cudnn=True,
> param_attr=ParamAttr(
> name='linear_conv1x1_weights',
> initializer=MSRA(),
> regularizer=fluid.regularizer.L2Decay(4e-4)),
> bias_attr=False)
> bn_name = 'linear_conv1x1_bn'
> x = fluid.layers.batch_norm(
> x,
> param_attr=ParamAttr(name=bn_name + "_scale"),
> bias_attr=ParamAttr(name=bn_name + "_offset"),
> moving_mean_name=bn_name + '_mean',
> moving_variance_name=bn_name + '_variance')
> print(x.shape,x.shape[0],x.shape[1])
> x = fluid.layers.reshape(x, shape=[x.shape[0], x.shape[1]])
> 的卷积层的输出特征输入到损失网络时报一下的错误：
> InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [80, 3427] and the shape of Y = [160, 3427]. Received [80] in X is not equal to [160] in Y at i:0.恳请大佬给予指点啊

请参见issue 479和481的回复
