### ISSUE TITLE
无法成功提交pr

### ISSUE THREAD

**Issue by zhudibo-unwulian** [PaddlePaddle/PaddleSlim#483]
在提交pr时遇到一下问题：
Username for 'https://github.com': zhudibo-unwulian
Password for 'https://zhudibo-unwulian@github.com': 
remote: Permission to PaddlePaddle/PaddleSlim.git denied to zhudibo-unwulian.
fatal: unable to access 'https://github.com/PaddlePaddle/PaddleSlim/': The requested URL returned error: 403

**Comment by baiyfbupt** [comment]
>fatal: unable to access 'https://github.com/PaddlePaddle/PaddleSlim/': The requested URL returned error: 403

看起来是网络连接问题，可以再试下`git clone https://github.com/PaddlePaddle/PaddleSlim `，如果还是一样的建议先解决本地的网络问题

**Comment by wanghaoshuang** [comment]
另附Paddle相关项目提交PR的流程，请参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.4/advanced_usage/development/contribute_to_paddle/index_cn.html
