### ISSUE TITLE
使用slimface训练好的模型在移动端部署进行预测，使用predictor=createpaddlepredictor<mobileconfig>(config)无法加载模型

### ISSUE THREAD

**Issue by zhudibo** [PaddlePaddle/PaddleSlim#491]
大佬，请求指导，使用slimface训练好模型，在移动端部署模型进行预测，函数如下：
mobileconfig config；
std::shared_ptr<paddlepredictor>predictor:
config.set_model_from_file(model_file);
predictor=createpaddlepredictor<mobileconfig>(config)无法加载slimface模型。

**Comment by qingqing01** [comment]
给下具体的错误信息吧。另外请问model_file是什么格式？

**Comment by zhudibo** [comment]
模型是.nb格式，按照paddle-site里面的c++api实例在进行部署slimfacenet网络的，之前部署mobileface的模型都已经成功，错误显示如下：
/work/inference_lite_lib.android.armv7/1$ adb shell 'cd /data/local/sm && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/data/local/sm &&  ./mobile_classify'
parameter:  model_file, image_path and label_file are necessary 
parameter:  topk, input_width,  input_height, are optional 
Segmentation fault

**Comment by zhudibo** [comment]
模型格式是. nb，按照paddle-site里面的c++api实例在移动端部署slimface net网络，之前部署mobileface的模型都已经成功，现在部署slimfacenet加载模型未成功，报的错误只有segmen tation fault，附件也有图片，谢大佬



---原始邮件---
发件人: "qingqing01"<notifications@github.com&gt;
发送时间: 2020年11月2日(周一) 中午12:23
收件人: "PaddlePaddle/PaddleSlim"<PaddleSlim@noreply.github.com&gt;;
抄送: "zhudibo"<1020286694@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleSlim] 使用slimface训练好的模型在移动端部署进行预测，使用predictor=createpaddlepredictor<mobileconfig&gt;(config)无法加载模型 (#491)




 
给下具体的错误信息吧。另外请问model_file是什么格式？

**Comment by zhudibo-unwulian** [comment]
模型是.nb格式，按照paddle-lite里面的c++api实例在进行部署slimfacenet网络的，之前部署mobileface的模型都已经成功，错误显示如下：
/work/inference_lite_lib.android.armv7/1$ adb shell 'cd /data/local/sm && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/data/local/sm && ./mobile_classify'
parameter: model_file, image_path and label_file are necessary
parameter: topk, input_width, input_height, are optional
Segmentation fault
加载模型的函数如下：
  config.set_model_from_file(model_file);
  predictor =CreatePaddlePredictor<MobileConfig>(config);

**Comment by AIpioneer** [comment]
根据用户反馈，后来将预测库改为with_extra之后，可以跑通。 这里需要paddle lite改进报错信息，给用户更好的提示。

**Comment by zhudibo** [comment]
这个问题就是我已经改的，感谢大佬



---原始邮件---
发件人: "AIpioneer"<notifications@github.com&gt;
发送时间: 2020年11月4日(周三) 下午5:14
收件人: "PaddlePaddle/PaddleSlim"<PaddleSlim@noreply.github.com&gt;;
抄送: "zhudibo"<1020286694@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleSlim] 使用slimface训练好的模型在移动端部署进行预测，使用predictor=createpaddlepredictor<mobileconfig&gt;(config)无法加载模型 (#491)




 
根据用户反馈，后来将预测库改为with_extra之后，可以跑通。 这里需要paddle lite改进报错信息，给用户更好的提示。
