### ISSUE TITLE
AttributeError: module 'paddleslim.quant' has no attribute 'quant_post_static'

### ISSUE THREAD

**Issue by zhuguiqian** [PaddlePaddle/PaddleSlim#495]
跑静态离线量化的实例代码：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/quant_post_static_tutorial.md
会报 module 'paddleslim.quant' has no attribute 'quant_post_static'的错误
paddle version:1.8.5
paddlesslim version:1.1.1

**Comment by qingqing01** [comment]
@zhuguiqian 感谢反馈，quant_post_static接口在>=1.1.2版本以上才有。

**Comment by zhuguiqian** [comment]
> @zhuguiqian 感谢反馈，quant_post_static接口在>=1.1.2版本以上才有。

好的，多谢回复

那 https://github.com/PaddlePaddle/PaddleSlim 这里的文档是不是要更新下，没有看到有支持1.1.2版本的paddle
![微信截图_20201102174430](https://user-images.githubusercontent.com/7693110/97853444-1652e100-1d33-11eb-9b38-362c6ff4c7b1.png)

**Comment by qingqing01** [comment]
@zhuguiqian 您可以安装 1.2.0 https://github.com/PaddlePaddle/PaddleSlim/releases 。文档我们更新下。

**Comment by zhuguiqian** [comment]
> @zhuguiqian 您可以安装 1.2.0 https://github.com/PaddlePaddle/PaddleSlim/releases 。文档我们更新下。

OK，多谢
