### ISSUE TITLE
PaddleSlim是否支持多标签网络的量化和以及逐层量化

### ISSUE THREAD

**Issue by zhuguiqian** [PaddlePaddle/PaddleSlim#499]
请教一下，PaddleSlim是否支持多标签网络的量化（例如人脸关键点网络），我这边试了一下报下图的错误，不确定是不支持多标签网络，还是其他错误。
环境：
paddlepaddle:1.8.5
paddleslim:1.1.1
![image](https://user-images.githubusercontent.com/7693110/97967619-6e075000-1df8-11eb-9c67-c5f124bbf972.png)
另外，aistudio上跑的slim例子，跑出来的量化结果是逐通道量化的（如下图），想问一下是否有选项可以选择逐层量化？
![image](https://user-images.githubusercontent.com/7693110/97968970-55983500-1dfa-11eb-8405-b1ab8e3d978f.png)

最后今天开始发现pip安装paddleslim一直报错，如果只是我这边问题请忽略
![image](https://user-images.githubusercontent.com/7693110/97968567-c68b1d00-1df9-11eb-892a-37fa82173a4b.png)

**Comment by baiyfbupt** [comment]
您好，您的问题看了一下：
1. PaddleSlim支持多标签网络量化，使用离线量化时注意传入的reader是否正确，可以先测试下迭代出来的数据对不对
2. 把量化的config，从`'weight_quantize_type': 'channel_wise_abs_max',`改为`'weight_quantize_type': 'abs_max'`就可以了
3. pip install建议使用清华源，参考首页文档：https://github.com/PaddlePaddle/PaddleSlim#%E5%AE%89%E8%A3%85

**Comment by zhuguiqian** [comment]
> 您好，您的问题看了一下：
> 
> 1. PaddleSlim支持多标签网络量化，使用离线量化时注意传入的reader是否正确，可以先测试下迭代出来的数据对不对
> 2. 把量化的config，从`'weight_quantize_type': 'channel_wise_abs_max',`改为`'weight_quantize_type': 'abs_max'`就可以了
> 3. pip install建议使用清华源，参考首页文档：https://github.com/PaddlePaddle/PaddleSlim#%E5%AE%89%E8%A3%85

多谢，试了一下是可以的。

另外有个问题，用slim量化后，一定要使用paddlelite来做推理吗？

**Comment by baiyfbupt** [comment]
根据设备决定预测引擎，您的推理硬件设备是？

**Comment by zhuguiqian** [comment]
> 根据设备决定预测引擎，您的推理硬件设备是？

现在在x86的linux的系统上跑，评估一下量化效果。后面会跑在arm linux上。

**Comment by baiyfbupt** [comment]
x86cpu可以参考这个教程https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/mkldnn_quant/
arm必须要用paddlelite

**Comment by zhuguiqian** [comment]
> x86cpu可以参考这个教程https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/mkldnn_quant/
> arm必须要用paddlelite

Ok,多谢,使用paddle-inference也可以推理slim量化后的.

请教另外一个问题:
通过读取模型的参数看到,float32模型和量化后的int8模型的参数
Float32:
Weight=-0.02324475
Bias=0.4343462
Int8:
Weight=-127
Bias=0.4343462
Scale=75.051513671875
请教一下这个Weight是如何从-0.02324475计算到-127的?
