### ISSUE TITLE
get_ratios_by_loss()函数怎么依据敏感度信息和损失阈值确定最佳的剪裁率？

### ISSUE THREAD

**Issue by junjun210** [PaddlePaddle/PaddleSlim#500]
get_ratios_by_loss()函数根据敏感度信息，在满足精度损失阈值的情况下，确定最大的剪裁率。怎么确定的呢？换句话说，不同层之间的精度损失是什么样的关系，累加吗，然后总和小于损失阈值？

**Comment by wanghaoshuang** [comment]
>不同层之间的精度损失是什么样的关系

我们在计算一组剪裁率时，假设不同层的精度损失是相互独立的，并不是累加，而是每一层的损失都是设置的损失阈值。
这里的损失阈值只是用来辅助寻找一组合适的满足FLOPs限制的剪裁率，和模型最终的精度损失无关。
