### ISSUE TITLE
module 'paddle' has no attribute 'static'

### ISSUE THREAD

**Issue by YukSing12** [PaddlePaddle/PaddleSlim#513]
按照[教程](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/tutorials/image_classification_sensitivity_analysis_tutorial.md)运行，报错：
```
Traceback (most recent call last):
  File "prune.py", line 73, in <module>
    if __name__ == '__main__':
  File "prune.py", line 68, in main
    sensitivities_file="sensitivities_0.data",
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim-1.0.0-py3.7.egg/paddleslim/prune/sensitive.py", line 70, in sensitivity
AttributeError: module 'paddle' has no attribute 'static'
```

**Comment by wanghaoshuang** [comment]
请问您使用的PaddlePaddle的版本是多少，PaddleSlim的版本是多少？
如果用的PaddleSlim develop分支，需要将PaddlePaddle升级到2.0 rc版本

**Comment by wanghaoshuang** [comment]
请问您用的PaddlePaddle版本是多少？

**Comment by YukSing12** [comment]
> 请问您用的PaddlePaddle版本是多少？

您好，我用的版本为paddlepaddle-gpu 1.8.4.post97

**Comment by wanghaoshuang** [comment]
建议您使用PaddleSlim v1.2.0分支下的教程：https://github.com/PaddlePaddle/PaddleSlim/blob/v1.2.0/docs/zh_cn/tutorials/image_classification_sensitivity_analysis_tutorial.md

develop分支下的教程正在适配paddle2.0 API

**Comment by YukSing12** [comment]
> 建议您使用PaddleSlim v1.2.0分支下的教程：https://github.com/PaddlePaddle/PaddleSlim/blob/v1.2.0/docs/zh_cn/tutorials/image_classification_sensitivity_analysis_tutorial.md
> 
> develop分支下的教程正在适配paddle2.0 API

v1.2.0会报错误(https://github.com/PaddlePaddle/PaddleSlim/issues/480)
