### ISSUE TITLE
PaddleSlim的使用

### ISSUE THREAD

**Issue by liuxi1007** [PaddlePaddle/PaddleSlim#519]
您好，请问有适用于paddle 2.0-rc版本程序的paddleslim包吗？正常pip install paddleslim 安装的包是否可以用于paddle 2.0-rc 编写的网络？

**Comment by zhouyuxixixi** [comment]
你得下载1.2.0版本的slim才能适用2.0.0rc

**Comment by liuxi1007** [comment]
谢谢
