### ISSUE TITLE
idx_selector 在通道较少时出错

### ISSUE THREAD

**Issue by YukSing12** [PaddlePaddle/PaddleSlim#525]
PaddleSlim/paddleslim/prune/idx_selector.py line 60:
```
pruned_num = int(round(len(sorted_idx) * ratio))
pruned_idx = sorted_idx[:pruned_num]
```

当网络某一层通道较少时，会出现pruned_num = 0，从而导致 pruned_idx = [] 而引发错误
是否需要增加一个判断，令pruned_idx 至少为1呢？

**Comment by wanghaoshuang** [comment]
>是否需要增加一个判断，令pruned_idx 至少为1呢？

感谢反馈，我们后续修复下这个问题。
