### ISSUE TITLE
请教两个剪枝的问题

### ISSUE THREAD

**Issue by Gaondong** [PaddlePaddle/PaddleSlim#534]
1、现在paddleslim开放了四种剪枝算法，是否有各个算法的对比，最好是目标检测模型的，现在最优的剪枝算法还是sensitive 这种吗？
2、pruner使用bn scaler 或者FPGM，是不是没有复现原文中稀疏化训练的过程？ 使用这两种算法后面是否还进行逐层尝试敏感度分析loss损失？

**Comment by Gaondong** [comment]
@yukavio @wanghaoshuang

**Comment by qingqing01** [comment]
@Gaondong 

在分类模型中对比过这些剪枝方法，最好的是FPGM。 在检测YOLOv3上，采用先进行敏感度分析、再进行FPGM裁剪有实际的例子，在COCO/VOC数据上验证过，加速还不错，可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/slim/prune/README.md

**Comment by Gaondong** [comment]
> @Gaondong
> 
> 在分类模型中对比过这些剪枝方法，最好的是FPGM。 在检测YOLOv3上，采用先进行敏感度分析、再进行FPGM裁剪有实际的例子，在COCO/VOC数据上验证过，加速还不错，可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/slim/prune/README.md

pruner使用bn scaler 或者FPGM，是不是没有复现原文中稀疏化训练的过程？(在论文中这两种算法都有关于稀疏化训练的描述)
在代码中没有找到这个部分。

**Comment by wanghaoshuang** [comment]
>是不是没有复现原文中稀疏化训练的过程？

是的，PaddleSlim暂时没有实现稀疏化训练。
