### ISSUE TITLE
PaddleOCR识别模型8.6ms是哪个模型

### ISSUE THREAD

**Issue by neptune4year** [PaddlePaddle/PaddleSlim#544]
看到PaddleOCR的评测时耗是8.6ms，想确定下是哪个模型？
然后用意见benchmark并不能跑通PaddleOCR发布的模型，请问有什么其他方法可以评测PaddleOCR模型的时耗么

**Comment by qingqing01** [comment]
@neptune4year 具体问题可以在PaddleOCR的repo 提issue再问下。
