### ISSUE TITLE
运行setup.py报错：“No module named 'paddle.jit”

### ISSUE THREAD

**Issue by stefan252423** [PaddlePaddle/PaddleSlim#557]
已安装paddlepaddle—gpu 2.0.0a0版本，控制台运行命令：python setup.py install，报错信息为“No module named 'paddle.jit”，是什么原因？
<img width="508" alt="微信截图_20201218104041" src="https://user-images.githubusercontent.com/68883664/102567955-82d84280-411d-11eb-8653-c5e7de5b8365.png">

**Comment by baiyfbupt** [comment]
您好，由于历史原因2.0.0a0版本的Paddle不能满足需要，请使用2.0rc版本的paddle重新安装试下

**Comment by Zhangwei1215** [comment]
2.2.2也出现这个问题啊
