### ISSUE TITLE
请问一下dygraph_flops(model, input_shape, only_conv=False, detail=False)中的model参数传入的是什么？

### ISSUE THREAD

**Issue by gyr-kdgc** [PaddlePaddle/PaddleSlim#569]
我现在有训练好的*.pdmodel,         *.pdopt,      *.pdparams三个文件，如何使用dygraph_flops计算模型的flops

**Comment by yukavio** [comment]
通过model参数传入在动态图下定义的网络模型，即继承paddle.nn.Layer的一个类。
