### ISSUE TITLE
图像分类模型知识蒸馏

### ISSUE THREAD

**Issue by musketeera** [PaddlePaddle/PaddleSlim#571]
在定义student_program和teacher_program的代码中，teacher_model没有定义，怎么解决

**Comment by baiyfbupt** [comment]
![image](https://user-images.githubusercontent.com/28884066/103271826-3d0d5b00-49f6-11eb-9379-561163f0b9da.png)
把这一行改成teacher_model就可以了，后续我们会修复下文档
