### ISSUE TITLE
在线量化后转换问题

### ISSUE THREAD

**Issue by sadknight0001** [PaddlePaddle/PaddleSlim#575]
您好，
使用paddleseg中deeplabv3+mobilenetv2模型，量化训练成功，模型保存成功，但进过转换工具后模型大小没有变化，速度也基本一致，看转换日志中大部分的卷积层量化都被跳过了。
现在支持mobilenetv2模型量化吗？

**Comment by baiyfbupt** [comment]
您使用的转换工具是哪个，是paddle-lite的工具吗？ https://paddle-lite.readthedocs.io/zh/latest/user_guides/model_quantization.html#paddle-lite

**Comment by sadknight0001** [comment]
> 您使用的转换工具是哪个，是paddle-lite的工具吗？ https://paddle-lite.readthedocs.io/zh/latest/user_guides/model_quantization.html#paddle-lite

转换工具用的是release版的2.6.3
不过这个不能压缩的情况好像是因为需要代码问题
但现在又有新问题了，运行lite的demo显示结果不一致，自己的模型在服务器和前端结果也有差别
