### ISSUE TITLE
humanseg模型量化问题

### ISSUE THREAD

**Issue by wsy1991** [PaddlePaddle/PaddleSlim#594]
Humanseg里的模型量化后(offline)，体积并未减小

**Comment by wanghaoshuang** [comment]
PaddleSlim量化产出的模型还是以float32格式存储的（数值范围再int8范围内），需要用PaddleLite或PaddleInference的工具进行转换。
https://paddle-lite.readthedocs.io/zh/latest/user_guides/quant_aware.html#paddle-lite
