### ISSUE TITLE
mkldnn_quant demo文档和编译问题

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/PaddleSlim#601]
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/mkldnn_quant/

![image](https://user-images.githubusercontent.com/52520497/104889645-760f6e80-59a9-11eb-81da-c4f48da449df.png)
run.sh 并没有接收输入参数

https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/mkldnn_quant/cmake/FindFluid.cmake#L131
![image](https://user-images.githubusercontent.com/52520497/104890355-6e9c9500-59aa-11eb-81f9-ecac2841dfd0.png)
此处编译产出了 libmkldnn.so.0 ，但是没有 libmkldnn.so 时，会cmake失败

https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/mkldnn_quant/cmake/FindFluid.cmake#L142
![image](https://user-images.githubusercontent.com/52520497/104890377-73f9df80-59aa-11eb-9d75-9333d2f3fbee.png)
新版本paddle中已经不依赖 zlib，snappy和snappystream了，会cmake失败

**Comment by lidanqing-vv** [comment]
我问一下是用mkldnn.so.0的包还是dnnl.so.1的包
