### ISSUE TITLE
paddleslim版本问题

### ISSUE THREAD

**Issue by zzchust** [PaddlePaddle/PaddleSlim#603]
最近在做ppyolo检测模型的训练量化， 遇到了一些问题，需要确认一下：

1. paddledetection master（https://github.com/PaddlePaddle/PaddleDetection/tree/master） 分支应该是paddle静态图最新的版本， 支持paddle1.8.5
2.paddle1.1.1和paddledetection master部分接口是冲突的
， paddledetection master 对应的paddleslim最新分支应该是1.3.0？ 
3. 是否有paddleslim 1.3.0的whl包呢
4. python2.7 paddle1.8.5通过python setup.py install 安装paddleslim-develop分支遇到以下问题
![image](https://user-images.githubusercontent.com/6135871/104928266-6447be80-59dd-11eb-9a9f-3f7ae3c51fc1.png)

**Comment by wanghaoshuang** [comment]
1. PaddleDetection master分支的静态图应该是和PaddleSlim1.2.0对应的
2. 1.2.0之后直接到2.0了，2.0预计在2月5日发布，主要内容是支持动态图。
3. 这个错误需要升级到python3.7或以上版本
