### ISSUE TITLE
ImportError: cannot import name 'dygraph_flops' from 'paddleslim.analysis'

### ISSUE THREAD

**Issue by Salary-only-17k** [PaddlePaddle/PaddleSlim#605]
你好，这是我的环境
paddlepaddle          2.0.0rc1
paddleslim               1.2.0
然后在执行PaddleSlim/demo/dygraph/pruning/train.py文件时候，报错：
ImportError: cannot import name 'dygraph_flops' from 'paddleslim.analysis'

请问是我上面装的两个大哥的版本问题吗？

**Comment by wanghaoshuang** [comment]
paddleslim2.0.0分支才开始支持动态图flops计算
