### ISSUE TITLE
opt转2.0识别模型失败

### ISSUE THREAD

**Issue by maoxiaoming86** [PaddlePaddle/PaddleSlim#609]
opt转en_number_mobile_v2.0_rec_infer会显示‘rnn'不支持
 Error: This model is not supported, because 1 ops are not supported on 'arm'. These unsupported ops are: 'rnn'.
如果转量化后的识别模型，会多报错一个op不支持
Error: This model is not supported, because 2 ops are not supported on 'arm'. These unsupported ops are: 'fake_channel_wise_quantize_dequantize_abs_max, rnn'

**Comment by maoxiaoming86** [comment]
发现最新的develop分支已支持，但是编译出错

In file included from /home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.cc:15:0:
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:89:17: 错误：‘is_trivially_copyable’不是‘std’的成员
                 std::is_trivially_copyable<T>::value>::type>
                 ^
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:89:17: 错误：‘is_trivially_copyable’不是‘std’的成员
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:89:45: 错误：模板第 1 个参数无效
                 std::is_trivially_copyable<T>::value>::type>
                                             ^
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:89:46: 错误：expected identifier before ‘::’ token
                 std::is_trivially_copyable<T>::value>::type>
                                              ^
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:89:46: 错误：expected ‘>’ before ‘::’ token
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:89:54: 错误：‘type’不是命名空间‘::’中的一个类型名
                 std::is_trivially_copyable<T>::value>::type>
                                                      ^
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:110:17: 错误：‘is_trivially_copyable’不是‘std’的成员
                 std::is_trivially_copyable<T>::value>::type>
                 ^
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:110:17: 错误：‘is_trivially_copyable’不是‘std’的成员
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:110:45: 错误：模板第 1 个参数无效
                 std::is_trivially_copyable<T>::value>::type>
                                             ^
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:110:46: 错误：expected identifier before ‘::’ token
                 std::is_trivially_copyable<T>::value>::type>
                                              ^
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:110:46: 错误：expected ‘>’ before ‘::’ token
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:110:54: 错误：‘type’不是命名空间‘::’中的一个类型名
                 std::is_trivially_copyable<T>::value>::type>
                                                      ^
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h: 在成员函数‘virtual size_t paddle::lite::model_parser::BinaryFileWriter::Align(size_t) const’中:
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:166:36: 错误：对‘paddle::lite::model_parser::BinaryFileWriter::Write(unsigned int) const’的调用没有匹配的函数
       ByteWriter::Write<uint8_t>(0U);
                                    ^
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:166:36: 附注：备选是：
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:116:8: 附注：template<class T, int N> void paddle::lite::model_parser::ByteWriter::Write(const T (&)[N]) const
   void Write(const T (&array)[N]) const {
        ^
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:116:8: 附注：  template argument deduction/substitution failed:
/home/maoxiaoming/code/Paddle-Lite/lite/model_parser/base/io.h:166:36: 附注：  mismatched types ‘const unsigned char [N]’ and ‘unsigned int’

**Comment by AIpioneer** [comment]
您好！Paddle Lite对Paddle2.0的支持会在2.8版本实现支持，预计在2.5发版，其中包括rnn op。敬请关注。 另外对于量化op的支持我们也会迭代开发，但是会晚一些时间。如果可以的话我们也可以私下再多沟通（v信：ifyoucare）

**Comment by wanghaoshuang** [comment]
>Error: This model is not supported, because 2 ops are not supported on 'arm'. These unsupported ops are: 'fake_channel_wise_quantize_dequantize_abs_max, rnn'

这个报错是因为：
PaddleLite暂时不支持channel wise 量化
