### ISSUE TITLE
paddleslim官方给的那个mobilenetv1剪枝的例子，敏感度计算那一部分运行报错

### ISSUE THREAD

**Issue by shenhao2954988368** [PaddlePaddle/PaddleSlim#619]
该链接中分析mobilenetv1的卷积通道敏感度的例子无法运行成功
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/tutorials/image_classification_sensitivity_analysis_tutorial.md

sens_0 = slim.prune.sensitivity(
        val_program,
        place,
        params,
        test,
        sensitivities_file="sensitivities_0.data",
        pruned_ratios=[0.1, 0.2])
print(sens_0)
上述代码段运行出错，报错如下：

ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 64, the input's shape is [-1, 64, 14, 14]; the filter's channels is 1, the filter's shape is [64, 1, 3, 3]; the groups is 63, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:64 != filter_dims[1] * groups:63.] (at /paddle/paddle/fluid/operators/conv_op.cc:96)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < depthwise_conv2d > error]

是否有人可以帮忙看一下，感谢

**Comment by wanghaoshuang** [comment]
请问您用的哪个版本的PaddleSlim?

**Comment by wanghaoshuang** [comment]
您好，已定位到您提出的问题。
最近PaddleSlim develop有个一个更新，develop分支的教程没有及时更新。
我们马上提PR修复这个问题。

**Comment by shenhao2954988368** [comment]
应该是最新版本的，1.2.0，我直接用pip安装的，然后我用的paddlepaddle是 20.0.0
















在 2021-01-27 09:30:27，"whs" <notifications@github.com> 写道：

请问您用的哪个版本的PaddleSlim?
