### ISSUE TITLE
执行A2C例子中出现的问题

### ISSUE THREAD

**Issue by WuLayman** [PaddlePaddle/PaddleSlim#690]
![2021-03-16 10-31-19 的屏幕截图](https://user-images.githubusercontent.com/38377756/111247489-07662e80-8643-11eb-8d5d-3cdc3f304b29.png)

**Comment by qingqing01** [comment]
@WuLayman 您在那里看到的这个A2C例子？

**Comment by WuLayman** [comment]
> @WuLayman您在那里看到的这个A2C例子？

我用的是例程，然后遇到了这个问题，跑不通。

**Comment by qingqing01** [comment]
@WuLayman 能发个例程的链接吗？

**Comment by WuLayman** [comment]
> @WuLayman 能发个例程的链接吗？

https://aistudio.baidu.com/aistudio/projectdetail/645039

**Comment by wanghaoshuang** [comment]
建议您升级下PARL的版本。
这个问题最好去 PARL repo 提个issue： https://github.com/PaddlePaddle/PARL/issues
PaddleSlim的同学对PARL不太熟悉。

**Comment by WuLayman** [comment]
> 建议您升级下PARL的版本。
> 这个问题最好去 PARL repo 提个issue： https://github.com/PaddlePaddle/PARL/issues
> PaddleSlim的同学对PARL不太熟悉。

好的，非常感谢
