### ISSUE TITLE
在aistudio上运行paddleslim中的demo/prune时出行错误ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by PQ-girl** [PaddlePaddle/PaddleSlim#706]
import models时出现下面错误
ModuleNotFoundError: No module named 'models'

**Comment by wanghaoshuang** [comment]
请问，您所用AIStudio教程的链接是？

**Comment by 18298405861** [comment]
https://aistudio.baidu.com/aistudio/projectoverview我在这里面创建运行的项目，在本地运行合适，上传到aistudio之后运行时出现上面错误

**Comment by PQ-girl** [comment]
我用的就是Aistudio平台上自己创建的项目，上传了paddleslim程序包，运行demo中的prune时出现错误
