### ISSUE TITLE
把ResNet里的网络层替换成Super系列后，精度低

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleSlim#707]
把conv和batchnorm替换成SuperConv2D，SuperBatchNorm2D。完整训练替换后网络，不改变任何参数，在相同训练配置的情况下，Top-1只能到 10%。替换前的网络训练几个epoch就能到达10%。

**Comment by zhengzhe97** [comment]
请问一下，这个可能是由什么原因导致的

**Comment by wanghaoshuang** [comment]
请问您用的是OFA功能么？PaddleSlim版本号是？

**Comment by ceci3** [comment]
@zhengzhe97 请问下是怎么用的这两个API？superconv superbn的通道数和kernelsize和之前的conv bn一样嘛？

**Comment by zhengzhe97** [comment]
@wanghaoshuang 是的，版本是2.0.0

**Comment by zhengzhe97** [comment]
@ceci3 superconv superbn的通道数和kernelsize和之前的conv bn是匹配的，下面是其中一个例子：
修改前：
```
        nn.Sequential(
            nn.Conv2D(in_channels=in_places, out_channels=places, kernel_size=kernel_size, stride=stride, padding=padding, bias_attr=False),
            nn.BatchNorm2D(places))
```
修改后：
```
        nn.Sequential(
            SuperConv2D(in_channels=in_places, out_channels=places, kernel_size=kernel_size, stride=stride, padding=padding, bias_attr=False)，
            SuperBatchNorm2D(places))
```

**Comment by zhengzhe97** [comment]
是直接把 conv和 bn直接修改成SuperConv2D 和 SuperBatchNorm2D

**Comment by zhengzhe97** [comment]
项目“Demo”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/1751525/1557c181c9e44c82895261842e3759ba

**Comment by ceci3** [comment]
> @ceci3 superconv superbn的通道数和kernelsize和之前的conv bn是匹配的，下面是其中一个例子：
> 修改前：
> 
> ```
>         nn.Sequential(
>             nn.Conv2D(in_channels=in_places, out_channels=places, kernel_size=kernel_size, stride=stride, padding=padding, bias_attr=False),
>             nn.BatchNorm2D(places))
> ```
> 
> 修改后：
> 
> ```
>         nn.Sequential(
>             SuperConv2D(in_channels=in_places, out_channels=places, kernel_size=kernel_size, stride=stride, padding=padding, bias_attr=False)，
>             SuperBatchNorm2D(places))
> ```

@zhengzhe97 你好，我简单验证了一下这个示例，如果super op不设置config的话，相同输入和参数的情况下superconv+superbn的输出和conv+bn 的输出是完全一致的，是不是用super op训练的时候设置了什么特殊的config？

**Comment by ceci3** [comment]
这是示例代码：

```python
import math
import paddle
import paddle.nn as nn
import numpy as np
import random
from paddle import callbacks
from paddleslim.nas.ofa.layers import SuperConv2D, SuperBatchNorm2D, SuperLinear

np_weight = np.random.random((6, 3, 3, 3)).astype('float32')
np_bias = np.random.random((6)).astype('float32')

class BaseConvBNLayer(nn.Layer):
    def __init__(self, in_places, places, kernel_size, stride, padding):
        super(BaseConvBNLayer, self).__init__()
        self.layer = nn.Sequential(
            nn.Conv2D(in_channels=in_places, out_channels=places, kernel_size=kernel_size, stride=stride, padding=padding, bias_attr=False),
            nn.BatchNorm2D(places))

    def forward(self, inputs):
        return self.layer(inputs)


class SuperConvBNLayer(nn.Layer):
    def __init__(self, in_places, places, kernel_size, stride, padding):
        super(SuperConvBNLayer, self).__init__()
        self.layer = nn.Sequential(
            SuperConv2D(in_channels=in_places, out_channels=places, kernel_size=kernel_size, stride=stride, padding=padding, bias_attr=False),
            SuperBatchNorm2D(places))

    def forward(self, inputs):
        return self.layer(inputs)

model1 = BaseConvBNLayer(3, 6, 3, 1, 0)
model2 = SuperConvBNLayer(3, 6, 3, 1, 0)

for name, m in model1.named_sublayers():
    if isinstance(m, nn.Conv2D):
        paddle.assign(paddle.to_tensor(np_weight), m.weight)
        paddle.assign(paddle.to_tensor(np_bias), m.bias)
    elif isinstance(m, nn.BatchNorm2D):
        paddle.assign(paddle.ones(m.weight.shape), m.weight)
        paddle.assign(paddle.zeros(m.bias.shape), m.bias)
for name, m in model2.named_sublayers():
    if isinstance(m, nn.Conv2D):
        paddle.assign(paddle.to_tensor(np_weight), m.weight)
        paddle.assign(paddle.to_tensor(np_bias), m.bias)
    elif isinstance(m, nn.BatchNorm2D):
        paddle.assign(paddle.ones(m.weight.shape), m.weight)
        paddle.assign(paddle.zeros(m.bias.shape), m.bias)

np_inp = np.random.random((3, 3, 112, 112)).astype('float32')
pinp = paddle.to_tensor(np_inp)
o1 = model1(pinp)
o2 = model2(pinp)
print(paddle.sum(paddle.abs(o1)))
print(paddle.sum(paddle.abs(o2)))
```

**Comment by zhengzhe97** [comment]
@ceci3 开始测试的时候用过config，精度比较差。后来把所有层的config都去掉了，精度还是低。感觉应该不是config的问题

**Comment by ceci3** [comment]
> @ceci3 开始测试的时候用过config，精度比较差。后来把所有层的config都去掉了，精度还是低。感觉应该不是config的问题

请问下是厂内用户嘛？方便发我一个可以复现训练精度差的demo吗？上面那个demo看起来不是能直接训练的

**Comment by zhengzhe97** [comment]
@ceci3 场外同学，重新生成了项目链接，里面有前后的精度差。可以直接训练https://aistudio.baidu.com/studio/project/partial/verify/1751525/b134c6a0b06f4bd6884e28f22acc4ccf
修改后：
<img width="770" alt="1" src="https://user-images.githubusercontent.com/26462054/114122902-d0bec380-9923-11eb-90b3-f890b6ca1e1f.png">
修改前：
<img width="771" alt="2" src="https://user-images.githubusercontent.com/26462054/114122914-d5837780-9923-11eb-9480-51e7bccafee5.png">

**Comment by zhengzhe97** [comment]
时间原因，我只训练了几轮，差距已经很大了

**Comment by ceci3** [comment]
好，我看一下

**Comment by zhengzhe97** [comment]
你好，请问一下，可能是什么原因导致的

**Comment by ceci3** [comment]
你模型定义的原因，layer需要用 nn.sequential包装一下，不然可能优化不到相应参数。你的demo里super layer是没有用nn.sequential包装的，普通conv是用了nn.sequential包装的

**Comment by zhengzhe97** [comment]
感谢，确实是这个问题。讲道理来说无论是否使用nn.sequential包装，参数都应该是可以优化才对。这个是paddle设计成这样的吗
