### ISSUE TITLE
RoBERTa模型压缩

### ISSUE THREAD

**Issue by AlinLaw** [PaddlePaddle/PaddleSlim#716]
请教一下，我用paddleslim中的bert模型dynabert方法压缩案例，改了一个roberta模型的压缩，导出了dynamic_model和static_model。

当把dynamic_model测试程序时，如果导出模型的width_mult 为1.0时，可以顺利测试，测试的结果正确率为0.9000左右。如下：
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for classifier.weight. classifier.weight receives a shape [768, 2], but the expected shape is [768, 217].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for classifier.bias. classifier.bias receives a shape [2], but the expected shape is [217].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
Loaded checkpoint from checkpoints/dstc2/sub

Test begin...
Total samples: 9896
Joint_acc: 0.9005

当width_mult为0.5时，显示roberta模型的某些层尺寸不对，测试的结果正确率为0.0001。如下：
#以上省略
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.10.linear2.weight. roberta.encoder.layers.10.linear2.weight receives a shape [1536, 768], but the expected shape is [3072, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.q_proj.weight. roberta.encoder.layers.11.self_attn.q_proj.weight receives a shape [768, 384], but the expected shape is [768, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.q_proj.bias. roberta.encoder.layers.11.self_attn.q_proj.bias receives a shape [384], but the expected shape is [768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.k_proj.weight. roberta.encoder.layers.11.self_attn.k_proj.weight receives a shape [768, 384], but the expected shape is [768, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.k_proj.bias. roberta.encoder.layers.11.self_attn.k_proj.bias receives a shape [384], but the expected shape is [768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.v_proj.weight. roberta.encoder.layers.11.self_attn.v_proj.weight receives a shape [768, 384], but the expected shape is [768, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.v_proj.bias. roberta.encoder.layers.11.self_attn.v_proj.bias receives a shape [384], but the expected shape is [768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.out_proj.weight. roberta.encoder.layers.11.self_attn.out_proj.weight receives a shape [384, 768], but the expected shape is [768, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.linear1.weight. roberta.encoder.layers.11.linear1.weight receives a shape [768, 1536], but the expected shape is [768, 3072].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.linear1.bias. roberta.encoder.layers.11.linear1.bias receives a shape [1536], but the expected shape is [3072].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.linear2.weight. roberta.encoder.layers.11.linear2.weight receives a shape [1536, 768], but the expected shape is [3072, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
Loaded checkpoint from checkpoints/dstc2/sub

Test begin...
Total samples: 9896
Joint_acc: 0.0001

把"intermediate_size": 由3072改为1536时，测试的结果正确率为大概0.4300左右，任然显示roberta模型的某些层尺寸不对，但比改之前少了一些错误。如下：
#以上省略
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.10.self_attn.out_proj.weight. roberta.encoder.layers.10.self_attn.out_proj.weight receives a shape [384, 768], but the expected shape is [768, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.q_proj.weight. roberta.encoder.layers.11.self_attn.q_proj.weight receives a shape [768, 384], but the expected shape is [768, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.q_proj.bias. roberta.encoder.layers.11.self_attn.q_proj.bias receives a shape [384], but the expected shape is [768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.k_proj.weight. roberta.encoder.layers.11.self_attn.k_proj.weight receives a shape [768, 384], but the expected shape is [768, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.k_proj.bias. roberta.encoder.layers.11.self_attn.k_proj.bias receives a shape [384], but the expected shape is [768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.v_proj.weight. roberta.encoder.layers.11.self_attn.v_proj.weight receives a shape [768, 384], but the expected shape is [768, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.v_proj.bias. roberta.encoder.layers.11.self_attn.v_proj.bias receives a shape [384], but the expected shape is [768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/richard/anaconda2/envs/paddlenlp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for roberta.encoder.layers.11.self_attn.out_proj.weight. roberta.encoder.layers.11.self_attn.out_proj.weight receives a shape [384, 768], but the expected shape is [768, 768].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
Loaded checkpoint from checkpoints/dstc2/sub

Test begin...
Total samples: 9896
Joint_acc: 0.4304

请问应该如何读取dynamic_model每一层的信息，还是有其他什么办法？

读取static_model时，也有同样的问题。

程序原模型保存的是pdparams，重写了一下读取模型的方法，可以读，但是测试总有问题。

**Comment by ceci3** [comment]
看起来是子网络的参数导出成功了，但是加载这个参数的模型还是原始大小的模型，导致参数加载失败，测试结果不正确。要加载动态图子网络的话需要改一下原始网络定义里每层的shape。加载static_model的话，直接用paddle.jit.load 这个接口加载这个模型直接进行预测。
