### ISSUE TITLE
BERT模型压缩

### ISSUE THREAD

**Issue by AlinLaw** [PaddlePaddle/PaddleSlim#717]
在BERT模型压缩的案例中，export_model.py有这样一段代码：
best_config = utils.dynabert_config(ofa_model, args.width_mult)
ofa_model.export(
        origin_model,
        best_config,
        input_shapes=[[1, args.max_seq_length], [1, args.max_seq_length]],
        input_dtypes=['int64', 'int64'])

在读取模型时，是不是要考虑读取best_config？

使用了ofa后，需要在读模型时加上OFA(model)吗？

在PaddleSlime源码ofa.py中的def _export_sub_model_config(self, origin_model, config, input_shapes, input_dtypes):方法是不是用来导出子模型参数的？

**Comment by ceci3** [comment]
嗯嗯，best_config其实是跟子网络搜索相关的一个返回，但是bert压缩里暂时没有用到子网络搜索，返回值就也没有添加best_config作为返回值。
def _export_sub_model_config(self, origin_model, config, input_shapes, input_dtypes):这个方法是用来导出子模型参数的
