### ISSUE TITLE
有没有关于如何使用paddle-rt，也就是在paddle中使用TensorRT的完整文档？？

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleSlim#736]
其实就是在jetson xavier nx上使用paddle-trt的文档，包括 需不需要量化，怎么量化，量化之后怎么评估的问题？？
我不是想部署，而是仅仅做评估，看看量化之后模型的帧率？？

**Comment by wanghaoshuang** [comment]
请参考：https://paddleinference.paddlepaddle.org.cn/optimize/paddle_trt.html#paddle-tensorrt

**Comment by dengxinlong** [comment]
> 请参考：https://paddleinference.paddlepaddle.org.cn/optimize/paddle_trt.html#paddle-tensorrt

问一下，安装了paddlepaddle，是不是还得安装paddle-inference
