### ISSUE TITLE
教程有问题

### ISSUE THREAD

**Issue by tt8000** [PaddlePaddle/PaddleSlim#773]
裁剪了模型，优化器不支持啊， 难道需要重新在定义优化器么，教程没说。

下面按照教程运行的报错结果，换了优化器一样，更新下教程吧！！！太难了。

![1](https://user-images.githubusercontent.com/73922533/118978332-c6272d80-b9a9-11eb-93af-8469366dd6e0.png)
![2](https://user-images.githubusercontent.com/73922533/118978345-c9bab480-b9a9-11eb-8714-7251756cdae5.png)

**Comment by tt8000** [comment]
而且不止这里，其他地方也有

**Comment by wanghaoshuang** [comment]
多谢反馈，理论上是支持Momentum的，我们排查下原因。

**Comment by minghaoBD** [comment]
你好，谢谢提出的问题。目前已经更新了教程，即需要在finetune之前重新初始化optimizer并调用model.prepare，
这么做是因为动态图的剪裁时，并没有遍历到optimizer中的velocity参数，导致velocity形状没有发生改变而报错。所以简单来说，可以直接初始化一个新的optimizer（也符合finetune的流程）；更加易用性的解决方案我们正在评估。

**Comment by minghaoBD** [comment]
我们已经在动态图的剪裁代码中，加入了剪裁optimizer相关参数的逻辑。具体pull request：https://github.com/PaddlePaddle/PaddleSlim/pull/784 。
详细使用请参照更新后的教程：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/dygraph/dygraph_pruning_tutorial.md 。
