### ISSUE TITLE
paddleslim训练得到的模型转onnx模型，出现问题。还是不允许这样转换呢？

### ISSUE THREAD

**Issue by swithmn1** [PaddlePaddle/PaddleSlim#790]
paddleslim :2.1.0
paddlepaddle-gpu :2.0.2
通过slim训练得到的模型，导出为inference model 
利用paddle2onnx 脚本转换报错如下：
![image](https://user-images.githubusercontent.com/32815600/121158132-b4d09300-c87c-11eb-9ae2-829e00dfc231.png)

**Comment by Zeref996** [comment]
你好，slim量化后的模型不支持paddle2onnx转换。slim裁剪后的模型是可以支持的。关于paddle2onnx详情可见repo：
https://github.com/PaddlePaddle/Paddle2ONNX

**Comment by swithmn1** [comment]
好的，多谢

**Comment by Lanme** [comment]
请问你用paddleslim 是采用的剪枝还是量化？训练后的模型有变小么？我感觉我剪枝训练之后模型小了参数大了总体没有改变。
