### ISSUE TITLE
quant_post可支持传dataloader吗

### ISSUE THREAD

**Issue by LiuChiachi** [PaddlePaddle/PaddleSlim#811]
`paddleslim.quant.quant_post`目前还不支持传入`paddle.io.DataLoader`，会支持吗，感谢！

**Comment by wanghaoshuang** [comment]
`quant_post`是Post training quantiztion, 在PaddleSlim中，动态图的`quant_post`是先将目标model转为静态图，然后再调用静态图的`quant_post`接口，而`paddle.io.DataLoader`是动态图API，所以不支持。

PaddleSlim正在开发动态图直接`quant_post`的接口，会支持传入`paddle.io.DataLoader`。会随Paddle2.2版本发布。

**Comment by LiuChiachi** [comment]
感谢回复:)
我先用静态图接口实验~
