### ISSUE TITLE
paddlehub输出的基于ernie自定义数据的序列标注模型支持压缩吗？

### ISSUE THREAD

**Issue by suntao2015005848** [PaddlePaddle/PaddleSlim#814]
paddlepaddle-gpu=1.8.5.post97
paddlehub=1.8.2
paddlehub的ernie=1.2.0

**Comment by wanghaoshuang** [comment]
支持，可以尝试使用离线量化。
Int8量化后的模型12层ERNIE模型使用PaddleInference部署，batch size=40, 在T4上加速约20%.
模型大小下降约75%

**Comment by suntao2015005848** [comment]
请问有相关的demo吗?离线量化对Paddle版本有具体要求吗？

**Comment by suntao2015005848** [comment]
如何可以的话请针对paddlehub的ernie的序列标注出一个demo,非常感谢。
