### ISSUE TITLE
slim裁剪 敏感度分析

### ISSUE THREAD

**Issue by jiamingming-004** [PaddlePaddle/PaddleSlim#829]
paddlepaddle 2.1版本
slim 2.0.0 版本
paddlex 
 yolov3在敏感度分析之后在裁剪使出现 如下问题;
<ipython-input-6-7cefec87ea6f> in <module>
      2 import paddlex as pdx
      3 model = pdx.load_model('output_dan_rats/yolov3_darknet53/best_model')
----> 4 pdx.slim.visualize(model, 'yolov3.sensi.data', save_dir='./')
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/slim/visualize.py in visualize(model, sensitivities_file, save_dir)
     46             sensitivities_file,
     47             eval_metric_loss=loss_thresh,
---> 48             scope=model.scope)
     49         x.append(prune_ratio)
     50         y.append(loss_thresh)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/slim/prune.py in cal_model_size(program, place, sensitivities_file, eval_metric_loss, scope)
    384                 prune_shape = prune_var.shape
    385                 break
--> 386         origin_size += reduce(lambda x, y: x * y, shape)
    387         new_size += reduce(lambda x, y: x * y, prune_shape)
    388     return (new_size * 1.0) / origin_size
TypeError: reduce() of empty sequence with no initial value
paddleX 版本不祥

**Comment by wanghaoshuang** [comment]
报错的代码是PaddleX中统计参数大小的代码，
辛苦 @jiangjiajun 帮忙看下这个问题？

**Comment by will-jl944** [comment]
Hi，你当前使用的PaddleX版本仅支持到paddle1.8和paddle2.0，paddleslim仅支持到1.2.0。降低paddle和paddleslim至相应的版本即可。

此外我们也发布了全面支持动态图的[PaddleX 2.0.0rc3](https://github.com/PaddlePaddle/PaddleX/tree/develop/dygraph)，支持最新版本的paddle和paddleslim，增加了更多的模型，简化了API接口。后续我们将主要开发和维护2.0版本的PaddleX。你可以通过`$ pip install paddlex==2.0.0rc3`安装体验。
