### ISSUE TITLE
您好，paddledetection的yolov3_darknet可以量化为8位共GPU调用的模型吗？我看给的例子都是基于mobileNet的量化？

### ISSUE THREAD

**Issue by zsffuture** [PaddlePaddle/PaddleSlim#831]
跪求解答啊，新手不知道怎么量化yolov3_darknet

**Comment by XGZhang11** [comment]
paddledetection的模型支持量化，文档如下：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/slim   。指定yolov3_darknet的配置文件即可。
