### ISSUE TITLE
请问 NAS-BERT 会集成吗？

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/PaddleSlim#854]
你好， 我看到了现在 paddleslim集承了 dynabert 和 OFA，那么 NAS-BERT 会集成进来吗？ https://arxiv.org/pdf/2105.14444.pdf

**Comment by wanghaoshuang** [comment]
感谢建议。
我们正在寻求更好的BERT压缩方案，但是还没评估NAS-BERT这个方法，后续我们会关注该方法，等有结论了再跟您同步计划。
另外，我们选择压缩策略时，还要考虑推理库的支持情况，有些优化方法可能会和TensorRT的优化（比如op fusion）有冲突。

再次感谢。

**Comment by luoqishuai** [comment]
@wanghaoshuang 
请问一般评价一个压缩方案,你们是依据什么呢?
论文中他们给出的指标?还是clue上的分数.
还是复现完,然后看看实际的分数.
