### ISSUE TITLE
网络搜索的current tokens的含义？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleSlim#860]
请教网络搜索的current tokens的含义？比如搜索**ResNetSpace**

**Comment by ceci3** [comment]
current tokens 对应的是 不同层的conv的通道数在当前层搜索空间里的index，具体每个idx对应的是哪个conv可以看这里：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/paddleslim/nas/search_space/resnet_block.py#L74
