### ISSUE TITLE
新版PaddleClas模型定义，使用pact量化报错

### ISSUE THREAD

**Issue by RainFrost1** [PaddlePaddle/PaddleSlim#861]
![图片](https://user-images.githubusercontent.com/11568925/126930810-cd1db56b-a48b-4bc5-b81a-b24757881890.png)
按照[这个教程](https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/dygraph/quant)将mobinetv3改成新版PaddleClas的[定义](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/ppcls/arch/backbone/legendary_models/mobilenet_v3.py)，就报如图所示错误

**Comment by XGZhang11** [comment]
paddle版本需要和paddleslim版本对应，均使用较新develop版本时没有报错
