### ISSUE TITLE
PaddleSlim使用model_size函数返回0

### ISSUE THREAD

**Issue by Disciple7** [PaddlePaddle/PaddleSlim#866]
您好！我正在使用paddleslim的analysis api完成一个对模型文件进行分析的任务，遇到了一些问题。
我目前手头没有数据集和模型，仅有以下保存好的模型文件：client_model_infer.pdiparams、client_model_infer.pdiparams.info、client_model_infer.pdmodel。经测试，它们可以用paddle.static.load_inference_model读取。

我使用了paddleslim.analysis下的flops和model_size函数进行返回，其中flops能够返回一个正常的值，但model_size返回了0。请问这是什么问题？

以下是我的代码：

```
import paddle
import paddleslim

checkpoint_name_2 = './client_model_infer'
paddle.enable_static()
paddle_executor = paddle.static.Executor(paddle.CPUPlace())
loaded_infer_model = paddle.static.load_inference_model(checkpoint_name_2, paddle_executor)
infer_program = loaded_infer_model[0]

flops = paddleslim.analysis.flops(infer_program)
print('FLOPs:', flops) # FLOPs: 7127040.0

model_size = paddleslim.analysis.model_size(infer_program)
print('Model Size:', model_size) # Model Size: 0
```

**Comment by Disciple7** [comment]
补充一下：源码中all_parameters()返回了一个空list，然后我看到用的应该是paddle.fluid.block的定义，其中all_parameters()调用了iter_parameters，后者判断一个item是否为Parameter类型来返回。但是新的Paddle版本貌似不再使用Parameter类型了，而且也即将抛弃paddle.fluid模块。

**Comment by wanghaoshuang** [comment]
感谢反馈。
这里的接口调用的paddle.fluid.block确实是比较旧的版本，但理论上还是向前兼容的。结果为0不确定是这个block的问题。
你可以用以下方法，看下是不是parameter的shape有异常。
```

for block in infer_program.blocks:
        for param in block.all_parameters():
            print(f"{param.name}\t{param.shape}")
            size += np.product(param.shape)
```

**Comment by wanghaoshuang** [comment]
使用load_inference_model加载的program中，Parameter全变成了Variables, 因此无法正确计算model size. 建议在save_inference_model之前计算model size.
