### ISSUE TITLE
静态离线量化，推理耗时不降反升。

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/PaddleSlim#867]
量化前模型推理速度：Avg Time: 0.03840347912000573
量化后模型推理速度：Avg Time: 0.06539143562316894
模型为paddleocr的det_r50_vd_db模型，每次测试数据集相同，500张。
为什么呢？

**Comment by XGZhang11** [comment]
您好，可以提供下环境以及测试代码吗

**Comment by wanghaoshuang** [comment]
@LiquorPerfect 
如果是GPU部署的话，需要打开TRT开关。如果是CPU的话，需要参考这个教程进行部署：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/mkldnn_quant/

**Comment by LiquorPerfect** [comment]
@XGZhang11 @wanghaoshuang 之前推理的时候没有使用trt加速，现在开了trt、fp16推理，速度略微提升。
目前还有一个问题：int8量化的模型，目前trt推理都是使用的fp16，能否设置为int8精度进行推理？我没有找到怎么设置。

**Comment by wanghaoshuang** [comment]
可以参考这个文档：https://paddleinference.paddlepaddle.org.cn/optimize/paddle_trt.html

通过设置```precision_mode```开启int8计算：
```
config.enable_tensorrt_engine(workspace_size = 1 << 30,
                              max_batch_size = 1,
                              min_subgraph_size = 3,
                              precision_mode=paddle_infer.PrecisionType.Int8,
                              use_static = False, use_calib_mode = False)
```

**Comment by LiquorPerfect** [comment]
使用trt int8推理，速度是不如fp16的。
