### ISSUE TITLE
有没有ssd_mobilenet_v1的全量化训练脚本demo可以参考一下？

### ISSUE THREAD

**Issue by mzxhzhp** [PaddlePaddle/PaddleSlim#883]
目标检测的 ssd_mobilenet_v1 模型，有没有全量化训练的脚本demo可以参考一下？
目前我在官方教程文档中，只看到有图像分类的PaddleSlim全量化训练demo，ssd_mobilenet_v1 的不知道应该怎么做。

**Comment by XGZhang11** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/configs/slim  可以参考这个demo

**Comment by mzxhzhp** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/configs/slim 可以参考这个demo

上面的链接我之前就试过了，不是全量化的，导致最终使用 opt 工具将 ssd_mobilenet_v1 转成PaddleLite格式 rknpu 的模型时报错。
