### ISSUE TITLE
量化模型时出错AttributeError: module 'paddle' has no attribute 'batch'

### ISSUE THREAD

**Issue by bueredgirll** [PaddlePaddle/PaddleSlim#890]
使用PaddleSlim量化模型，输出eval指令显示AttributeError: module 'paddle' has no attribute 'batch'，应该怎么修改，求指点

**Comment by bueredgirll** [comment]
paddle和paddleSlim都是2.1.2

**Comment by XGZhang11** [comment]
你好，请确认下paddle版本，可以将环境信息和具体报错粘贴在issue中。
