### ISSUE TITLE
对测试模型进行剪枝，剪枝完成之后将获得的program进行测试，报错

### ISSUE THREAD

**Issue by yezechen** [PaddlePaddle/PaddleSlim#900]
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 256, the input's shape is [32, 256, 125, 4]; the filter's channels is 1, the filter's shape is [256, 1, 3, 3]; the groups is 205, the data_format is NCHW. The error may come from wrong data_format setting.
      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:256 != filter_dims[1] * groups:205.] (at D:\v2.0.1\paddle\paddle\fluid\operators\conv_op.cc:96)
      [operator < depthwise_conv2d > error]

**Comment by Water2style** [comment]
同样， 输入的channel是256，他不等于 filter的channel*groups for OP，也是就 256 ！= 1*205
请问解决了吗？

**Comment by wanghaoshuang** [comment]
@yezechen 建议升级到最新的PaddleSlim.

看报错应该是剪裁的时候没有处理好grouped conv2d，在最新的PaddleSlim中做了修复。

**Comment by wanghaoshuang** [comment]
@Water2style 针对您的问题：

![image](https://user-images.githubusercontent.com/7534971/144068121-3049a21f-4b71-4339-bcf4-3e5df318b5ee.png)


>我发现PaddleSlim高阶教程-裁剪-静态图-敏感度分析的8.2小节有点问题呢[捂脸]会报一个通道不匹配的错误. 还有就是我有些不理解为何8.2要只剪网络结构,然后再测一下呢.

应该是您参考的教程和PaddleSlim版本不匹配导致的。

如果用PaddleSlim2.2.0，建议参考这个教程：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/tutorials/pruning/static/image_classification_sensitivity_analysis_tutorial.md#82-剪裁测试网络

其中，**只剪裁测试网络后，是不能进行测试的**，剪裁完训练网络后才能测试。因为Paddle的网络结构和tensor数值是分别存在program和scope两个数据结构的，而train_program和test_program共享一个scope，只有program和scope都被裁剪，才能正确执行。
上述截图中，剪裁test_program时，only_graph=True，意思是只剪裁存在program中的网络结构（groups数值会被改变），不会剪裁scope中的权重（计算过程中的feature map大小、channel number不会变），所以导致了groups不匹配。
您的另一个疑问『为何8.2要只剪网络结构？』，因为8.3节对训练网络剪裁时，需要用到原来的scope，所以不能在8.2剪裁scope.
我们正在提PR去除以上的约束：https://github.com/PaddlePaddle/PaddleSlim/pull/924

**Comment by Jiashuhao518** [comment]
> @yezechen 建议升级到最新的PaddleSlim.
> 
> 看报错应该是剪裁的时候没有处理好grouped conv2d，在最新的PaddleSlim中做了修复。

请问在paddleslim2.1.0中有没有解决
