### ISSUE TITLE
paddleslim如何压缩ernie-tiny

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleSlim#906]
![2D7AB4F321E58CD5D511589B23C6B0F4](https://user-images.githubusercontent.com/29837553/137061304-e47544db-140c-4b72-b95c-2bf1c0f99e94.jpg)
使用paddleslim对ernie-tiny压缩的，说可以达到1ms。这个有案例脚本？

**Comment by ceci3** [comment]
可以快速试下int8离线量化~ 参考：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant_post 这个文档~

**Comment by tianchiguaixia** [comment]
收到，谢谢大佬
