### ISSUE TITLE
RuntimeError: propeller 0.2 requires paddle 1.7+, got 2.1.0

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleSlim#907]
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/ofa/ernie#ofa%E5%8E%8B%E7%BC%A9ernie%E6%A8%A1%E5%9E%8B

环境：paddlepaddle==2.1

运行代码总是报错，难道2.1版本不是高于1.7？？？

**Comment by tianchiguaixia** [comment]
就是这个案例demo总是跑不通，升级paddle，paddleslim又会产生新的错误，按照文档给的环境也无法跑通。如果大佬跑通了，求告知下最新配置和环境。

**Comment by ceci3** [comment]
请问下具体是报什么错，paddlepaddle==2.1是可以的

**Comment by tianchiguaixia** [comment]
![image](https://user-images.githubusercontent.com/29837553/137103700-08caee7d-d939-45cb-abb7-e38f61381e5c.png)

**Comment by ceci3** [comment]
这一行改成 from ernie_supernet.optimization import LinearDecay试下~ 这里应该改了目录但是代码里没改~

**Comment by tianchiguaixia** [comment]
改了，还是不可以的
![image](https://user-images.githubusercontent.com/29837553/137106081-935fda79-bb1a-46e4-b928-7677afdc6a35.png)

**Comment by ceci3** [comment]
你好，demo的代码适配了一下最新的ernie 代码，可以先参考这个pr 修改~ https://github.com/PaddlePaddle/PaddleSlim/pull/908

**Comment by tianchiguaixia** [comment]
还是不行，可否告知下paddle-ernie,paddlepadle,paddleslim,propeller等的版本号。

**Comment by tianchiguaixia** [comment]
propeller 老是和flask冲突，全是环境问题。

**Comment by tianchiguaixia** [comment]
非常感谢啊，谢谢你啊，解决大问题了
