### ISSUE TITLE
离线量化问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleSlim#909]
paddleDetection导出模型离线量化报错：
![image](https://user-images.githubusercontent.com/63913709/137620820-7d5fb77c-998b-4230-b738-a754390aa1b1.png)
好像是加载校准数据时出错了，使用如下方式加载的：
import paddle.fluid as fluid
from paddleslim.quant import quant_post_static
from ppdet.core.workspace import load_config, merge_config, create
from ppdet.data.reader import create_reader
from ppdet.utils.cli import ArgsParser
from ppdet.utils.check import check_gpu, check_version, check_config, enable_static_mode
import logging
FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
logging.basicConfig(level=logging.INFO, format=FORMAT)
logger = logging.getLogger(__name__)

def main():
    env = os.environ
    cfg = load_config(FLAGS.config)
    main_arch = cfg.architecture
    model = create(main_arch)
    inputs_def = cfg['EvalReader']['inputs_def']
    feed_vars, eval_loader = model.build_inputs(**inputs_def)
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
    eval_dataset = eval_loader.set_sample_list_generator(eval_reader)
    place = fluid.CUDAPlace(0)
    exe = fluid.Executor(place)
    model_dir = r'E:\detection0.5bate\output\0910model\cascade_rcnn_dcn_r101_vd_fpn_tiles_0910'
    model_filename = '__model__'
    params_filename = '__params__'
    save_model_path = r'E:\detection0.5bate\output\qua_out'
    batch_generator = eval_dataset
    batch_size = 2
    batch_nums = None
    algo = "KL"
    quantizable_op_type = ["conv2d", "depthwise_conv2d", "mul"]
    quant_post_static(executor=exe,
                      model_dir=model_dir,
                      model_filename=model_filename,
                      params_filename=params_filename,
                      quantize_model_path=save_model_path,
                      batch_generator=batch_generator,
                      batch_size=batch_size,
                      batch_nums=batch_nums,
                      algo=algo,
                      quantizable_op_type=quantizable_op_type)

if __name__ == '__main__':
    enable_static_mode()
    parser = ArgsParser()
    FLAGS = parser.parse_args()
    main()
不知问题在哪里？另外有没有加载校准数据的DEMO供参考，谢谢！

**Comment by wanghaoshuang** [comment]
可以参考离线量化教程：https://paddleslim.readthedocs.io/zh_CN/latest/quick_start/dygraph/dygraph_quant_post_tutorial.html
