### ISSUE TITLE
Paddleseg 导出预测量化模型时报错。AttributeError: 'NoneType' object has no attribute 'state_dict'

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSlim#911]
paddlpaddle版本：paddlepaddle-gpu的nightly build版本
![image](https://user-images.githubusercontent.com/71338215/138858742-f264d451-4e88-4cd5-96b4-fa2c6bf83ac0.png)

报错：
![image](https://user-images.githubusercontent.com/71338215/138858770-4971b85f-db6f-4399-bdcf-8107dcc98abd.png)

**Comment by huangwan-jiayi** [comment]
另外   我测试量化模型的时候 python slim/quant/qat_val.py 报一样的错

**Comment by XGZhang11** [comment]
https://github.com/PaddlePaddle/Paddle/issues/36705
