### ISSUE TITLE
剪枝demo数据预处理未添加

### ISSUE THREAD

**Issue by BraveLii** [PaddlePaddle/PaddleSlim#912]
https://github.com/PaddlePaddle/PaddleSlim/blob/b9e5730bf3f35fee2b08102ff23db1dbafe0d2d0/demo/prune/eval.py#L37

对于mnist的数据，需要增加均值方差的预处理：
        transform = T.Compose([T.Transpose(), T.Normalize([127.5], [127.5])])
        val_dataset = paddle.vision.datasets.MNIST(mode='test', transform=transform)

**Comment by wanghaoshuang** [comment]
多谢反馈
