### ISSUE TITLE
在AIstudio多卡中，安装了Paddleslim在计算Flops的时候

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleSlim#923]
`os.system("cd PaddleDetection-release-2.3 && pip install paddleslim -i https://mirror.baidu.com/pypi/simple")`

训练时候在计算Flops的时候却显示：

`[11/21 10:15:40] ppdet.engine WARNING: Unable to calculate flops, please install paddleslim, for example: `pip install paddleslim``

**Comment by wanghaoshuang** [comment]
这种安装方式应该是不能及时将paddleslim module load到当前进程吧？你在当前脚本里设置一下PYTHONPATH?
