### ISSUE TITLE
非结构化训练加载GMPUnstructuredPruner报错，使用的2.2.1版本

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleSlim#945]
![image](https://user-images.githubusercontent.com/77316774/145350219-258d1b64-e4cb-4ea9-a720-cc3326aeb33c.png)

**Comment by minghaoBD** [comment]
您好，谢谢尝试非结构化稀疏功能～

我在本地运行：
`pip install paddleslim==2.2.1`
`python`
`from paddleslim import GMPUnstructuredPruner`
是没有问题的。
![image](https://user-images.githubusercontent.com/79566150/145535241-349deba3-3aa5-4e8f-8646-537052bbe78f.png)


请问您的paddleslim是否按照上述步骤安装成功呢？
