### ISSUE TITLE
希望尽快能把develop版本的发布一下，目前训练非结构化稀疏配路径太难了~~~

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleSlim#946]

**Comment by minghaoBD** [comment]
安装develop版本的paddleslim：
```bash
git clone https://github.com/PaddlePaddle/PaddleSlim.git
cd PaddleSlim
pip install -r requirements.txt
python setup.py install
```

但是，develop版本下非结构化稀疏功能与2.2.1无异，而且都不应该有【配置路径】的步骤。

**Comment by gaorui999** [comment]
2.2.1会出现报错，我的指令是这样的，他的报错在图上
`%cd paddle-detection1125/`
`!pip install -r requirements.txt -i https://mirror.baidu.com/pypi/simple  `
`!pip install paddleslim==2.2.1 -i https://pypi.tuna.tsinghua.edu.cn/simple  `
`!python3.7 -m paddle.distributed.launch --log_dir=log_test --gpus 0 tools/train.py -c configs/picodet/pruner/picodet_m_320_coco_pruner.yml --slim_config configs/slim/prune/picodet_m_unstructured_prune_75.yml --eval`


![微信截图_20211210155955](https://user-images.githubusercontent.com/77316774/145538386-8029a823-99ce-4ff7-9bd5-4660d57c3a87.png)

**Comment by minghaoBD** [comment]
多谢反馈～
这个小功能没有合入2.2.1，麻烦安装下develop版本 : )
我同步合入这个小功能到2.2分支，完成后我在这里回复。

**Comment by gaorui999** [comment]
感谢百度大大的回复，万分感谢，折磨了两天了

**Comment by gaorui999** [comment]
@minghaoBD 可以冒昧的问一下，大概什么时间能完成呢

**Comment by minghaoBD** [comment]
> @minghaoBD 可以冒昧的问一下，大概什么时间能完成呢

我和发版同学沟通了下，他们建议还是使用develop版本～

这么做是考虑到local_sparsity是一个新的【小功能】，不是对于之前功能的bug修复，不建议合入release/2.2分支。所以需要麻烦您按照上述指令，安装develop版本paddleslim了。

**Comment by gaorui999** [comment]
难过~~

**Comment by gaorui999** [comment]
请问下我有没有办法自己做一个发版呢？

**Comment by minghaoBD** [comment]
> 请问下我有没有办法自己做一个发版呢？

这个可能比较麻烦。我建议还是安装develop版本的paddleslim。
看你在使用jupyter运行命令，猜测你可能遇到了一些安装develop版本的问题，我大概搜了一些相关教程供参考：
1. 执行git clone 获取paddleslim：https://blog.csdn.net/weixin_43695915/article/details/86471264
2. 运行setup.py 文件：https://blog.csdn.net/DoReAGON/article/details/100122750
3. 如果你可以直接打开命令行终端，所有命令都可以在终端中按照这个教程执行：https://blog.csdn.net/Lianyudedouzi/article/details/109715011
