### ISSUE TITLE
可以对yolov5进行压缩和量化吗？

### ISSUE THREAD

**Issue by WEIZHIHONG720** [PaddlePaddle/PaddleSlim#948]
可以对yolov5进行压缩和量化吗？

**Comment by yghstill** [comment]
@weizh588 如果有yolov5的Paddle的组网训练代码，可以进行量化训练。如果只有Inference model，可以进行离线量化：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant_post

**Comment by Eric-Zhang1990** [comment]
> @weizh588 如果有yolov5的Paddle的组网训练代码，可以进行量化训练。如果只有Inference model，可以进行离线量化：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant_post

@yghstill  请问有检测模型的离线量化demo吗？给出的demo是分类的，检测模型的量化的数据怎么加载呢？谢谢

**Comment by dium6i** [comment]
> > @weizh588 如果有yolov5的Paddle的组网训练代码，可以进行量化训练。如果只有Inference model，可以进行离线量化：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant_post
> 
> @yghstill 请问有检测模型的离线量化demo吗？给出的demo是分类的，检测模型的量化的数据怎么加载呢？谢谢

同问，直接把demo套在检测模型上，提示could not convert string to float。
