### ISSUE TITLE
uniform剪枝要如何操作?

### ISSUE THREAD

**Issue by sc0ttms** [PaddlePaddle/PaddleSlim#949]
直接获取所有卷积操作的变量名称API应该参考哪个？
uniform 剪枝是步骤是指 获得了所有卷积变量名称后每个变量剪枝相同比例吗？

**Comment by wanghaoshuang** [comment]
>直接获取所有卷积操作的变量名称API应该参考哪个？

对于静态图：

```
for param in program.global_block().all_parameters():
    print(f"name: {param.name}; shape: {param.shape}")
```

对于动态图, 请参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Layer_cn.html#parameters

>uniform 剪枝是步骤是指 获得了所有卷积变量名称后每个变量剪枝相同比例吗？

是的
