### ISSUE TITLE
安装时错误

### ISSUE THREAD

**Issue by zhizunbao-y** [PaddlePaddle/PaddleSlim#95]
使用从clone代码安装会报错：
```
from paddle.fluid.contrib.slim.quantization import PostTrainingQuantization
ImportError: cannot import name 'PostTrainingQuantization'

```
使用pip安装不会报错，但运行代码会报上述错误

**Comment by slf12** [comment]
请安装最新版的paddle再试一下

**Comment by zhizunbao-y** [comment]
@slf12 在annaconda环境里使用最新的paddlepaddle-gpu-1.6.3仍是这个错误

**Comment by slf12** [comment]
> @slf12 在annaconda环境里使用最新的paddlepaddle-gpu-1.6.3仍是这个错误

确认了下，需要安装paddle latest版本，可在  https://www.paddlepaddle.org.cn/install/doc/tables 里找到，PostTrainingQuantization 会在1.7版本里加入

**Comment by wanghaoshuang** [comment]
我们在paddle1.7发布前，给paddleslim拉了个release/0.1.0分支，去掉了对依赖paddle1.7，但是损失了离线量化功能。
https://github.com/PaddlePaddle/PaddleSlim/issues/118#issuecomment-588151146

**Comment by CheungBH** [comment]
> 我们在paddle1.7发布前，给paddleslim拉了个release/0.1.0分支，去掉了对依赖paddle1.7，但是损失了离线量化功能。
> [#118 (comment)](https://github.com/PaddlePaddle/PaddleSlim/issues/118#issuecomment-588151146)

是不是现在的PaddlePaddle 1.7还没发布，最高只有1.6.3。只有等到1.7发布了才行？因为我无论是pip还是conda，安装的最终都是1.6.3

**Comment by slf12** [comment]
> > 我们在paddle1.7发布前，给paddleslim拉了个release/0.1.0分支，去掉了对依赖paddle1.7，但是损失了离线量化功能。
> > [#118 (comment)](https://github.com/PaddlePaddle/PaddleSlim/issues/118#issuecomment-588151146)
> 
> 是不是现在的PaddlePaddle 1.7还没发布，最高只有1.6.3。只有等到1.7发布了才行？因为我无论是pip还是conda，安装的最终都是1.6.3

https://www.paddlepaddle.org.cn/install/doc/tables#%E5%A4%9A%E7%89%88%E6%9C%ACwhl%E5%8C%85%E5%88%97%E8%A1%A8-dev-11 可以在这里找到我们更新的最新安装包，这个安装包会跟着develop更新
