### ISSUE TITLE
使用不同shape的校准数据量化模型，产生报错

### ISSUE THREAD

**Issue by weishengying** [PaddlePaddle/PaddleSlim#951]
假设一个由单个conv组成的简单模型，conv的输入是动态的【1，3，None，None】，使用quant_post_static量化，这个api的校准数据迭代器sample_generator产生不同shape的校准数据，量化过程中报错：
源码：

> 
     import paddle
     from paddle.nn import Conv2D
     from paddle.nn.initializer import Assign
     import paddleslim
     
     
     # 定义一个简单只有conv op的模型,其中weight_attr定义为全1数据
    class conv_model(paddle.nn.Layer):
        def __init__(self):
            super(conv_model, self).__init__()
            self.conv_2d = Conv2D(in_channels=3, 
                                out_channels=3, 
                                kernel_size=2, 
                                padding="SAME", 
                                weight_attr = paddle.ParamAttr(initializer=Assign(np.ones([3,3,2,2]).astype(np.float32))
                                ))

        def forward(self, inputs):
            y = self.conv_2d(inputs)
            return y

    from paddle.static import InputSpec
    import numpy as np

    paddle.disable_static()
    conv_2d_model = conv_model()

    # save
    path = "./example_conv_2d/conv2d"
    paddle.jit.save(
        layer=conv_2d_model,
        path=path,
        input_spec=[InputSpec(shape=[1,3,None,None], dtype='float32')])

    paddle.enable_static()
    place = paddle.CPUPlace()
    exe = paddle.static.Executor(place)

    def reader():
      for x in [5,6]:
        for _ in range(100):
            yield np.random.random([1,3,x,x]).astype(np.float32)

    paddleslim.quant.quant_post_static(
      executor=exe,
      weight_bits=8,
      model_dir="./example_conv_2d",
      quantize_model_path="./static_quantized_conv_2d",
      sample_generator=reader,
      model_filename="./example_conv_2d/conv2d.pdmodel",
      params_filename="./example_conv_2d/conv2d.pdiparams",
      )

假如使用相同shape的校准数据，便不产生报错
>
    def reader():
      for x in [5]:
        for _ in range(100):
            yield np.random.random([1,3,x,x]).astype(np.float32)

**Comment by yghstill** [comment]
需要看下exe.run执行fp32 model是否也支持动态宽高输入
