### ISSUE TITLE
QAT量化后执行eval()报错如下

### ISSUE THREAD

**Issue by sc0ttms** [PaddlePaddle/PaddleSlim#952]
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds ::paddle::platform::float16, but desires to be float.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at /paddle/paddle/fluid/framework/tensor_impl.h:33)
  [operator < fake_quantize_dequantize_moving_average_abs_max > error]

**Comment by yghstill** [comment]
@sc0ttms 量化训练哪个模型？PaddlePaddle版本是多少

**Comment by sc0ttms** [comment]
> @sc0ttms 量化训练哪个模型？PaddlePaddle版本是多少

@yghstill 
PaddlePaddle 2.2.1 设置未train()模式是正常的
模型是复现的DCCRN语音增强网络，encoder(CNN)+RNN(LSTM)+decoder(CNN)的结构

**Comment by yghstill** [comment]
@sc0ttms 这个问题在现有的模型中并未出现过，有代码链接吗？我复现并修复下这个问题。

**Comment by sc0ttms** [comment]
最近身体不适，后续恢复后整理一下复现代码
