### ISSUE TITLE
EC-DARTS: Inducing Equalized and Consistent Optimization into DARTS

### ISSUE THREAD

**Issue by fxwfzsxyq** [PaddlePaddle/PaddleSlim#959]
这篇文章啥时候开源

**Comment by wanghaoshuang** [comment]
多谢建议，我们会关注下该文章，但是近期应该不会复现。

**Comment by fxwfzsxyq** [comment]
> 多谢建议，我们会关注下该文章，但是近期应该不会复现。

这篇文章至少从论文贴出效果来说改进是很大的，所以想试试，因为论文中没给出搜索出来的架构，但是提到会在paddleslim开源，所以就问下，期待尽快开源
