### ISSUE TITLE
请问如何在动态图中离线量化

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleSlim#962]
动态图离线量化教程
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/dygraph/dygraph_quant_post_tutorial.md
中的代码似乎是静态图代码吧

paddle.enable_static()
place = paddle.CPUPlace()
exe = paddle.static.Executor(place)
paddleslim.quant.quant_post_static(
        executor=exe,
        model_dir='./',
        model_filename='fp32_inference_model.pdmodel',
        params_filename='fp32_inference_model.pdiparams',
        quantize_model_path='./quant_post_static_model',
        sample_generator=paddle.dataset.cifar.test10(),
        batch_nums=10)

**Comment by yghstill** [comment]
@huilin16 请参考：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/dygraph/post_quant
